### ISSUE TITLE
Cannot remove new_api from expiremental config section

### ISSUE THREAD

**Issue by royto** [zigbee2mqtt/hassio-zigbee2mqtt#102]
**Description of problem:**
zigbee2mqtt has remove the experimental config section in [1.17.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.17.0) 

I have warning in supervisor log

**Zigbee2mqtt add-on version (if edge, please report commit hash):** 1.18.1-1 
```
21-05-05 19:13:12 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
```

When I try to remove this configuration, this is automatically restored when saving.

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.4.6
Supervisor: supervisor-2021.04.3
Operating System: HassOS  5.13
```

**Your logs from Home Assistant Supervisor**
```
21-05-05 19:13:12 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
```

**Comment by wojciechczyz** [comment]
Same situation here, actually 1.18.1-1 is not updating to 1.18.3, likely this is related.
In my case HA is installed with supervisor on top of Raspbian, so not really supported...

**Comment by ciotlosm** [comment]
You should be able to remove the new_api config option and save the new config with no problem, unless you changed some permission rights and your addon can't save it's configuration. Also make sure you are using the latest (now 1.21.0) from the official repository (https://github.com/zigbee2mqtt/hassio-zigbee2mqtt)
