### ISSUE TITLE
How to re-install addon without loosing configuration.

### ISSUE THREAD

**Issue by jrhbcn** [zigbee2mqtt/hassio-zigbee2mqtt#103]
**Description of problem:**
I dont know how but my zigbee2mqtt addon has lost the link to the addon repository. As a consequence, addon works but I have no icon and no info if running in the supervisor page in home assistant. Furthermore, I don't get updates:

![image](https://user-images.githubusercontent.com/22198270/117293078-3d6ca580-ae71-11eb-9a7a-46795d08bdb0.png)

It seems the problem came as I lost the addon repository list on home assistant. Putting it back did not link the current zigbee2mqtt installed addon with the one in the repository resulting in the image above and the described problems.

I think re-installing the addon should be enough to solve the problem, however I would like to keep the configuration (friendly_name change etc.) of the 20+ devices I have already included. 

**Would there be enough by copying/paste the entire configuration options (including the network key)?** 

**Is there anything I can do to not loose the config of all my devices?**

Thanks

**Comment by jrhupc** [comment]
@dnedeltchev I have managed to fix my addon (restoring from a backup). However, I am in the exact same position as you. Addon with the old repo stuck in 1.18.1. I wish there was a way to make the addon point to the new repo.

**Comment by jrhbcn** [comment]
@dnedeltchev I have managed to fix my addon (restoring from a backup). However, I am in the exact same position as you. Addon with the old repo stuck in 1.18.1. I wish there was a way to make the addon point to the new repo.

**Comment by dnedeltchev** [comment]
> @dnedeltchev I have managed to fix my addon (restoring from a backup). However, I am in the exact same position as you. Addon with the old repo stuck in 1.18.1. I wish there was a way to make the addon point to the new repo.

I wonder if there is something really simple that only you and me have missed? Surely there must be a load of people in this situation?

**Comment by dnedeltchev** [comment]
Have a look at this post. Looks like exactly what we need.
https://community.home-assistant.io/t/updating-zigbee2mqtt-when-ive-installed-from-an-old-repo/287373

**Comment by dnedeltchev** [comment]
> Have a look at this post. Looks like exactly what we need.
> https://community.home-assistant.io/t/updating-zigbee2mqtt-when-ive-installed-from-an-old-repo/287373

I think... the correct approach is as follows, not done it yet though, just sharing to see if you or anyone else (doesn't look like anyone else is reading this) can spot any issues with this:

- shutdown z2m just to make sure it's all clean - may be a bit over the top but...
- make a backup copy of /share/zigbee2mqtt - I do not know if uninstalling the add-on will remove this folder so just in case
- make a backup copy of the config of the add-on
- uninstall old add-on
- remove old repo
- install new add-on
- restore your config making sure the default data_path remains pointing to /config/zigbee2mqtt (looks like this is now the default path on the new version)
- copy the zigbee2mqtt folder to /config
- start add-on and keep fingers crossed :)
- be prepared to reset all your devices just in case :)

**Comment by dnedeltchev** [comment]
> > > Have a look at this post. Looks like exactly what we need.
> > > https://community.home-assistant.io/t/updating-zigbee2mqtt-when-ive-installed-from-an-old-repo/287373
> > 
> > 
> > I think... the correct approach is as follows, not done it yet though, just sharing to see if you or anyone else (doesn't look like anyone else is reading this) can spot any issues with this:
> > 
> > * shutdown z2m just to make sure it's all clean - may be a bit over the top but...
> > * make a backup copy of /share/zigbee2mqtt - I do not know if uninstalling the add-on will remove this folder so just in case
> > * make a backup copy of the config of the add-on
> > * uninstall old add-on
> > * remove old repo
> > * install new add-on
> > * restore your config making sure the default data_path remains pointing to /config/zigbee2mqtt (looks like this is now the default path on the new version)
> > * copy the zigbee2mqtt folder to /config
> > * start add-on and keep fingers crossed :)
> > * be prepared to reset all your devices just in case :)
> 
> I had a look at all the files in the current /share/zigbee2mqtt folder and there is no reference to /share/zigbee2mqtt other than in the logs. So I think the above is safe to do, i.e. copying the current folder to the new location won't bring some obsolete config.

Oh, one last thing, I take full nightly backups so I have not included that step in the beginning, just in case things go really south! :) but as with anything before an upgrade, full backup is a must :)

**Comment by dnedeltchev** [comment]
Success!
Basically the above steps are what I followed.
One thing I noticed is that uninstalling the old add-on does not remove the /share/zigbee2mqtt folder but just in case, make a copy!

**Comment by jrhbcn** [comment]
congrats @dnedeltchev  and thanks for the info!! Do you use hassio?? I don't seem to find /share/zigbee2mqtt connecting to ssh on my machine... :?

**Comment by dnedeltchev** [comment]
> congrats @dnedeltchev and thanks for the info!! Do you use hassio?? I don't seem to find /share/zigbee2mqtt connecting to ssh on my machine... :?
> 
> EDIT: OK just as I sent the reply I found it. It is here: /mnt/data/supervisor/share/zigbee2mqtt
> 
> I am going to see if I can overwrite the files from ssh and then I'll follow your steps.

I got the home assistant blue when they first released it so I am running home assistant OS mode. I have the Samba add-on and this is how I manage the shares like config, etc. Good that you managed to find the old location. Good luck with the migration! Hope you manage to get on the new repo successfully too!

**Comment by jrhbcn** [comment]
Great! I will use the samba addon as well!

**Comment by jrhbcn** [comment]
and ... success!!!! Thank you again @dnedeltchev for the nice instructions.  :)

**Comment by dnedeltchev** [comment]
> and ... success!!!! Thank you again @dnedeltchev for the nice instructions. :)

👍

**Comment by ovizii** [comment]
I have no idea how you guys got it working but no matter what I do, every time I start this addon it overwrites the /config/zigbee2mqtt/configuration.yaml file with its default content. 

Btw. can someone elaborate on this please:
`restore your config making sure the default data_path remains pointing to /config/zigbee2mqtt (looks like this is now the default path on the new version)`

**Comment by dnedeltchev** [comment]
> I have no idea how you guys got it working but no matter what I do, every time I start this addon it overwrites the /config/zigbee2mqtt/configuration.yaml file with its default content.
> 
> Btw. can someone elaborate on this please:
> `restore your config making sure the default data_path remains pointing to /config/zigbee2mqtt (looks like this is now the default path on the new version)`

Hey there, 

Did you follow the steps exactly as above? The reason I did the restore the config (copy/paste over the existing config) after I installed z2m from the new repo and after I copied the zigbee2mqtt folder to /config is so that it can overwrite whatever the installation did. The point you ask to elaborate was mentioned because when I did copy old config and paste, the old config points to the old share. So I did paste the old config chahed the share to the new location /share/zigbee2mqtt, that undated the configuration.yaml and the add on started with all my devices available.

**Comment by m4dm4xi** [comment]
> > Have a look at this post. Looks like exactly what we need.
> > https://community.home-assistant.io/t/updating-zigbee2mqtt-when-ive-installed-from-an-old-repo/287373
> 
> I think... the correct approach is as follows, not done it yet though, just sharing to see if you or anyone else (doesn't look like anyone else is reading this) can spot any issues with this:
> 
> ....

Thank you very much. It worked like a charm!
