### ISSUE TITLE
What is the best way to test development of upstream converters?

### ISSUE THREAD

**Issue by afoeder** [zigbee2mqtt/hassio-zigbee2mqtt#106]
**Description of problem:**
I am [currently fiddling with converters](https://github.com/Koenkk/zigbee-herdsman-converters/pull/2563) in zigbee-herdsman-converters and would like to know the best approach on how to get those changes into HA's Z2M add-on environment?

----

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.18.3-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
_does not apply_

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.4.5
Supervisor: supervisor-2021.04.3
Operating System: Home Assistant OS 5.13
```

**Your logs from Home Assistant Supervisor**
_not relevant_

**Comment by avee87** [comment]
The way I tested changes is somewhat similar to this: https://github.com/zigpy/zha-device-handlers#testing-quirks-in-development-in-docker-based-install
Basically, connect to your addon with Portainer console, copy updated files into the installation:
```
cp /path/to/your_changed_file.js app/node_modules/zigbee-herdsman-converters/devices/
```
and restart the addon (via Portainer, not Supervisor or you'll lose your changes).
You probably want to use edge version of the addon because it's more current.

**Comment by afoeder** [comment]
Notes to myself and others:
* install the [Portainer addon](https://github.com/hassio-addons/addon-portainer) from the Add-on-store
* Make sure to disable `Protection mode`: 
    ![image](https://user-images.githubusercontent.com/1125168/118788032-aa316800-b893-11eb-8567-f2122159f64c.png)
* Start Portainer and "Open Web UI"
* in the left menu,
  * head to `Settings` > section *Hidden Containers* and remove `io.hass.type`: `addon`
  * go to "Containers", `addon_[…]_zigbee2mqtt`, `Console`, `Connect`
* ℹ️ the location of zigbee-herdsman-converters for example is `/app/node_modules/zigbee-herdsman-converters`  
* make your adjustments by copying or `vi`'ing
* Still in portainer, go back to the add on's container and `Restart`

After work is done, don't forget to reintroduce the security measures:
* re-add the filter `io.hass.type`: addon` for *Hidden Containers*
* re-activate the "Protection mode" of the Portainer
