### ISSUE TITLE
configuration.yaml file is in JSON format? Plugin not updating, cannot change configuration

### ISSUE THREAD

**Issue by wojciechczyz** [zigbee2mqtt/hassio-zigbee2mqtt#109]
**Description of problem:**

SInce 2018.1.1-1 I am getting strange behaviour:

1. Plugin works, 
2. Plugin stopped updating automatically, nor does detect newer version for manual update.
3. When HA starts it is complaining that :
```
21-05-12 12:28:37 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-12 12:28:37 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-12 12:28:37 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
```

I cannot remove them, once I save they always come back in the configuration.

4. I lookend into configuration.yaml and it is in ... json format. I tried to overwrite it with yaml as taken from configuration file, yet it is always coming back in json format. Why is that?

// Please do a short description of the problem
// Make sure your problem is related to the add-on, not to core Zigbee2mqtt functionality, like problems with specific devices - for such issues use https://github.com/Koenkk/zigbee2mqtt/issues

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
// Example:
// > zigbee2mqtt@1.17.0 start /app
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
// replace this line with your pasted configuration
```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.2.2
Supervisor: supervisor-2021.02.6
Operating System: HassOS 5.4
```

**Your logs from Home Assistant Supervisor**
```
// Your logs here
```

**Comment by ovizii** [comment]
I've got the exact same problem but didn't see your post so I also posted. => https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/115

**Comment by ovizii** [comment]
btw. I don't see a problem with the json format as the addon description explicitly states it:

`Home Assistant requires add-on configuration in JSON format, rather than YAML. If you don't understand the difference, you can use a YAML-to-JSON converter.`

I would simply love to be able to edit my config again :-)

**Comment by ovizii** [comment]
about the issue with the addon no longer updating: https://github.com/Koenkk/zigbee2mqtt/discussions/7478

**Comment by wojciechczyz** [comment]
> btw. I don't see a problem with the json format as the addon description explicitly states it:
> 
> `Home Assistant requires add-on configuration in JSON format, rather than YAML. If you don't understand the difference, you can use a YAML-to-JSON converter.`
> 
> I would simply love to be able to edit my config again :-)

Why not change file extension from .yaml to .json then? This would be much more intuitive and consistent.

**Comment by ciotlosm** [comment]
If you are using Home Assistant OS with Supervisor and the Add-On you should always manage your configuration using the add-on UI. 

If you are deleting config options and saving and they appear back it might be because you messed some permissions and Home Assistant Supervisor can't save the config for it.

**Comment by mslotema** [comment]
This is an excellent remark. I did not realize this (does not seem intuitive).

Was already puzzling why my changes kept converting back.. Thanks.

> If you are using Home Assistant OS with Supervisor and the Add-On you should always manage your configuration using the add-on UI.
> 
> If you are deleting config options and saving and they appear back it might be because you messed some permissions and Home Assistant Supervisor can't save the config for it.
