### ISSUE TITLE
zigbee-herdsman:deconz:driver no free slots

### ISSUE THREAD

**Issue by JochenKlenk** [zigbee2mqtt/hassio-zigbee2mqtt#112]
Addon not started anymore.

Issue : 

 zigbee-herdsman:deconz:driver no free slots. Delay sending of APS Request

Version : 1.18.3-1
```


core-2021.5.4
supervisor-2021.04.3
Operating System: HassOS 5.4
```

**Comment by ciotlosm** [comment]
Please move this issue to https://github.com/Koenkk/zigbee2mqtt/issues
