### ISSUE TITLE
TS0601_cover do not show correctly attribute "Running" when used arrow UP/DOWN

### ISSUE THREAD

**Issue by QbaF** [zigbee2mqtt/hassio-zigbee2mqtt#118]
**Description of problem:**
For TS0601_cover there is attribute "Running" which show value true (for running cover) or false (when cover is currently nit running).
Unfortunatelly this attribute is working ok when changing cover state via Position slider. 
![image](https://user-images.githubusercontent.com/57077178/118993438-cdd4db00-b985-11eb-984d-ba9a975f9fad.png)

When using UP/DOWN arrow, state "Running" is always false
![image](https://user-images.githubusercontent.com/57077178/118993107-86e6e580-b985-11eb-884b-2cbb601fba89.png)

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
checked @`1.18.1-1`, new `1.18.3-1` and `Edge`

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.5.5
Supervisor: supervisor-2021.04.3
Operating System: Debian GNU/Linux 10 (buster)
Docker version: 20.10.5
```

**Comment by ciotlosm** [comment]
Please move device specific issues here: https://github.com/Koenkk/zigbee2mqtt/issues
