### ISSUE TITLE
Option 'ota' does not exist in the schema

### ISSUE THREAD

**Issue by CodeFinder2** [zigbee2mqtt/hassio-zigbee2mqtt#120]
Hi,

I am getting a few warnings like:
```
21-05-23 11:42:13 WARNING (SyncWorker_1) [supervisor.addons.options] Option 'ota' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
```

in my supervisor's log. Any fix for this? :)

Using 1.18.3-1 on a RPi4.

Edit: still happening with v1.19.0-1.

**Comment by ciotlosm** [comment]
@CodeFinder2 can you please post your config and logs?

**Comment by CodeFinder2** [comment]
I just checked for such errors again and they seem to have disappeared. :-) But thanks for your feedback nonetheless!

I will close this and re-open if it happens again.

**Comment by firstnamegit** [comment]
Still getting it:
v 1.22.2-1

![image](https://user-images.githubusercontent.com/45424240/149004129-c8f34683-7b9a-4371-b267-9e80be463946.png)

![image](https://user-images.githubusercontent.com/45424240/149004052-961da459-c8c9-4f3e-85dc-9471271e57d0.png)

![image](https://user-images.githubusercontent.com/45424240/149004095-a8888c9a-2a1c-4a66-b1d7-877d69e0e282.png)
