### ISSUE TITLE
Homeassistant node is trying to reach zigbee2mqtt on port 9090

### ISSUE THREAD

**Issue by danielo515** [zigbee2mqtt/hassio-zigbee2mqtt#122]
**Description of problem:**
Hello.

I have my home assistant installation and my zigbee2mqtt running on different nodes.
I have configured zigbee to use home assistant as mqtt broker and everything works, a bit slow, but works.

On my zigbee server I have ufw activated, and this blocks access to all ports except for the normal ones: 443, 22, 80, etc.

If I check the log of my zigbee server I see blocked request coming from my hassio host on port 9090.
I am wondering what this port is for? And what is home assistant trying to achieve by contacting my zigbee server on that port?

**Running platform (details from Suypervisor > System)**

## System Health

version | core-2021.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.109
arch | x86_64
timezone | Europe/Madrid

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.12.3
Stage | running
Available Repositories | 890
Installed Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.3
docker_version | 19.03.15
disk_total | 24.9 GB
disk_used | 16.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.1), AppDaemon 4 (0.6.0), File editor (5.3.0), ESPHome (1.17.1), SSH & Web Terminal (8.2.1), WireGuard (0.5.1), UniFi Controller (0.22.0), Node-RED (9.0.1), Mosquitto broker (5.1.1), Visual Studio Code (3.3.1), Home Assistant Google Drive Backup (0.102.0), MariaDB (2.3.0), Portainer (1.5.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 11
views | 6
mode | storage

</details>

**Firewall logs**
```
[134866.124061] [UFW BLOCK] IN=eth0 OUT= MAC=xxxxxxx SRC=192.168.0.7 DST=192.168.0.47 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=65280 DF PROTO=TCP SPT=37286 DPT=9090 
[134947.276487] [UFW BLOCK] IN=eth0 OUT= MAC=xxxxxxx SRC=192.168.0.7 DST=192.168.0.47 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=56781 DF PROTO=TCP SPT=37446 DPT=9090 WINDOW=64240 RES=0x00 SYN URGP=0
```

**Comment by ciotlosm** [comment]
I think that is a question for the Home-Assistant repo. It might be something that the supervisor does to try and communicate with it's add-ons or so. I don't have much knowledge on this, but I assume you could dig in the supervisor code to understand it.
