### ISSUE TITLE
HA addon stop working after a few hours

### ISSUE THREAD

**Issue by andischweig** [zigbee2mqtt/hassio-zigbee2mqtt#125]
**Description of problem:**
// Please do a short description of the problem
// Make sure your problem is related to the add-on, not to core Zigbee2mqtt functionality, like problems with specific devices - for such issues use https://github.com/Koenkk/zigbee2mqtt/issues

I reinstalled HA and zigbee2mqtt 2 weeks ago and at the beginning it worked like a charm. After a few days later, some problems that i had before were repeating. 

After ~8 hours i cannot control my devices anymore. The only thing that works, is a zigbee2mqtt restart (Settings-> Tools - Restart zigbee2mqtt). At first i thought it is a MQTT (Mosquito broker) Problem with the "User credentials login". But switching to cert file authentication didn´t solved it. 

Is there anyone who had the same Problem?

** 

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
zigbee2mqtt@1.18.3-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
- xxxxxxxxxxxxxx
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.5.5
Supervisor: supervisor-2021.04.3
Operating System: HassOS 5.13
HW: 
Raspberry Pi 3B+
Electrolama zig-a-zig-ah! (zzh!) 
```

**Your logs from Home Assistant Supervisor**
```
Zigbee2MQTT:error 2021-05-25 23:11:46: Publish 'set' 'color_temp' to 'wohnzimmer_standlicht_ikea' failed: 'Error: Command 0xbc33acfffe216c5d/1 lightingColorCtrl.moveToColorTemp({"colortemp":426,"transtime":450}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'
Zigbee2MQTT:info  2021-05-25 23:11:46: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'color_temp' to 'wohnzimmer_standlicht_ikea' failed: 'Error: Command 0xbc33acfffe216c5d/1 lightingColorCtrl.moveToColorTemp({\"colortemp\":426,\"transtime\":450}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (SRSP - AF - dataRequest after 6000ms)'","meta":{"friendly_name":"wohnzimmer_standlicht_ikea"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:error 2021-05-25 23:11:52: Publish 'set' 'color_temp' to 'wohnzimmer_deckenlicht' failed: 'Error: Command 0x90fd9ffffed5a134/1 lightingColorCtrl.moveToColorTemp({"colortemp":426,"transtime":450}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'
Zigbee2MQTT:info  2021-05-25 23:11:52: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'color_temp' to 'wohnzimmer_deckenlicht' failed: 'Error: Command 0x90fd9ffffed5a134/1 lightingColorCtrl.moveToColorTemp({\"colortemp\":426,\"transtime\":450}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (SRSP - AF - dataRequest after 6000ms)'","meta":{"friendly_name":"wohnzimmer_deckenlicht"},"type":"zigbee_publish_error"}'
```

**Comment by gkyprios** [comment]
Did you sort this one out? I have similar problem over at: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/162

**Comment by andischweig** [comment]
> 
> 
> Did you sort this one out? I have similar problem over at: #162

**Comment by andischweig** [comment]
Hey, unfortunately no. I think the problem is that i use Ikea (bulbs) and Aqara (sensors) devices. It seems that the ikea bulbs can not route the aqara messages.

**Comment by ciotlosm** [comment]
For the authentication problem I would recommend you use the automated discovery for mqtt credentials
For the problem with the messages i can only make some suggestions:
- make sure your adapter has latest firmware
- make sure you are using a USB extender to move the stick away from any interference source (rpi wifi card, other router, anything emitting close to 2.4ghz range). 
- get a more powerful adapter if possible (see recommended adapters on z2m core docs)
