### ISSUE TITLE
Xiaomi WXKG11LM HA Logs 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'

### ISSUE THREAD

**Issue by shirou93** [zigbee2mqtt/hassio-zigbee2mqtt#126]
**Description of problem:**
// Please do a short description of the problem
// Make sure your problem is related to the add-on, not to core Zigbee2mqtt functionality, like problems with specific devices - for such issues use https://github.com/Koenkk/zigbee2mqtt/issues

**Zigbee2mqtt add-on version (if edge, please report commit hash):**

Zigbee2MQTT version 1.18.3 commit: 1.18.3
Coordinator type zStack3x0
Coordinator revision 20210120
Frontend version 0.4.0
```
`Logger: homeassistant.helpers.template
Source: helpers/template.py:1367
First occurred: 17:57:08 (1 occurrences)
Last logged: 17:57:08

Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'`
**Running platform (details from Suypervisor > System)**
```
Core: core-2021.5.5
Supervisor: core-2021.5.5
Operating System: Debian
```

**Comment by hqsone** [comment]
I have the same problem

**Comment by ciotlosm** [comment]
Can you try updating to 1.21.0 and see if the problem persists? This is a device related problem so the issue should go here: https://github.com/Koenkk/zigbee2mqtt/issues
