### ISSUE TITLE
Bad Gateway?

### ISSUE THREAD

**Issue by slurpey** [zigbee2mqtt/hassio-zigbee2mqtt#128]
**Description of problem:**

If I click on Open Web UI, I get "Bad Gateway" or a white screen timeout.  I have a ConbeeII plugged into my RPI which runs hassio.  I failed to figure out if I need to change anything in the config as I am not extremely technical savvy.
Ultimate goal is  to set sensitivity to a vibration sensor...

Zigbee2mqtt@1.19.0-1

```
// Example:
// > zigbee2mqtt@1.17.0 start /app
```

```
I didn't change anything (I don't know what I should change)
```

**Running platform (details from Suypervisor > System)**
```
core-2021.4.4
supervisor-2021.05.4
Home Assistant OS 5.13

```

**Your logs from Home Assistant Supervisor**
```
21-06-02 13:54:36 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-06-02 13:54:36 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-06-02 13:54:40 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt!
21-06-02 13:54:40 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt application
21-06-02 13:54:41 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.19.0-1
21-06-02 13:55:10 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-02 13:55:10 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-06-02 13:55:10 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-02 13:55:10 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-02 13:55:10 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-02 13:55:10 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-06-02 13:55:10 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-02 13:55:10 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-02 13:55:10 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-06-02 13:55:10 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-02 13:55:10 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-02 13:55:10 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-06-02 13:55:10 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
```

**Comment by BanditJackpot** [comment]
I'm getting the same bad gateway error.  In my supervisor logs, i'm also getting the following errors:
`21-06-04 19:55:40 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.19.1-1
21-06-04 19:55:49 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.6:8099 ssl:default [Connect call failed ('172.30.33.6', 8099)]`

**Comment by haade-administrator** [comment]
I have same problem

**Comment by ciotlosm** [comment]
You need to check the add-on logs to see why the add-on core is not starting up. Try to go to Supervisor > Dashboard > Zigbee2mqtt addon > Logs

**Comment by jimmymarbles** [comment]
I am also having the Bad Gateway error.  HA is installed on Debian 11 in Supervisor mode.

I am using the unsupported HUSBZB-1, but have managed to get Zigbee2mqtt to connect (I think per the Zigbee2mqtt Edge log below). 

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[05:18:38] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[05:18:38] INFO: MQTT available, fetching server detail ...
[05:18:38] INFO: MQTT server settings not configured, trying to auto-discovering ...
[05:18:39] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[05:18:39] INFO: Previous config file found, checking backup
[05:18:39] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[05:18:39] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[05:18:39] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.21.1-dev start
> node index.js

However, if I select Open in Web UI, I get the following System error under logs

> 21-09-29 05:19:01 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.4:8099 ssl:default [Connect call failed ('172.30.33.4', 8099)]

Now I don't have any SSL (Let's Encrypt) installed so I was poking around to see if SSL option can be removed.  So far I haven't located where I can modify it.  Also, I tried changing the port under the frontend section of the configuration, but it appears that is ignored and is hard coded to 8099.

Any suggestions?
