### ISSUE TITLE
Xiaomi MiJia Wireless Switch WXKG01LM "Template variable warning"

### ISSUE THREAD

**Issue by liamstears** [zigbee2mqtt/hassio-zigbee2mqtt#131]
I am getting a template variable warning in home assistant because of the Xiaomi MiJia Wireless Switch WXKG01LM

```
Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
```

This seems to be a common issue as there seems to be other threads with other devices which face the same issue, for example: https://github.com/Koenkk/zigbee2mqtt/issues/6987

I believe there is enough info there to be able to find a suitable solution?

If you need anything else please let me know

**Comment by xiaolei0125** [comment]
I also have same issue:   Home Assitant:2021.6.2,  zigbee2mqtt: 1.19.2

**Comment by ciotlosm** [comment]
Please move device specific issues here: https://github.com/Koenkk/zigbee2mqtt/issues
