### ISSUE TITLE
upgrade path/procedure 1.18.1-1 -> newer releases?

### ISSUE THREAD

**Issue by g3r0nim00** [zigbee2mqtt/hassio-zigbee2mqtt#134]
**Description of problem:**
What is the 'official' upgrade path/procedure for going from 1.18.1-1 to the newest version(s)?
When I add the new repository (https://github.com/zigbee2mqtt/hassio-zigbee2mqtt) in home-assistant, it gives me 2 more Zigbee2mqtt add-ons to install. It doesn't give the option to 'upgrade' my 1.18.1-1 add-on to the newer versions.
When I install the add-on from the new repository, it seems to add a new 'fresh' zigbee2mqtt installation (without copying the configuration etc)...

is there a way to go from 1.18.1-1 without any hassle (copying config files etc)?  

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
Current version: 1.18.1-1 (Changelog)
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
n/a, not config related
```

**Running platform (details from Suypervisor > System)**
```
Version: core-2021.5.5 (reverted back from 2021.6x because of other issues)
Supervisor: supervisor-2021.05.4
Operating System: Home Assistant OS 5.13
```

**Your logs from Home Assistant Supervisor**
```
n/a
```

**Comment by davidstosik** [comment]
(Note: I spent way too long trying to figure out why my old zigbee2mqtt add-on would not update before getting here... 😅 )

1. I followed the installation steps described in [the new repository's README](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt#installation), and now have two "Zigbee2MQTT" add-ons on my Home Assistant setup. One shows "current version: 1.18.1-1" and will never update further (that's the old one), and the other shows a more recent version (1.19.1-1 as of writing), that's the new one.
2. I stopped the old Zigbee2MQTT add-on.
3. I copy-pasted my configuration file from the old Zigbee2MQTT add-on to the new one.
4. I started the new Zigbee2MQTT add-on.

Everything seems to be working fine, so I disabled auto-start for the old add-on, enabled it for the new, and will consider uninstalling the old add-on in a few days, once I've confirmed it's all going well.

**Comment by g3r0nim00** [comment]
Thanks... I was also going to give that approach a try, but I'm wondering what will happen to the config which is not editable in the add-on configuration (eg: device names etc which have been assigned through the zigbee2mqtt web frontend).
I don't want to loose this configuration... or loose all devices ;-)

**Comment by davidstosik** [comment]
All my devices kept their name, everything kept working it seems.

**Comment by davidstosik** [comment]
I think it was more or less instant. You might want to check if you explicitly chose a channel in your configuration file. If you didn't, there might be a chance that the new instance chose a different one?

Here's an extract of my `configurations.yaml`:
```yml
advanced:
  log_level: debug
  channel: 11
  network_key:
    - ...
```

As you see I am explicitly telling zigbee2mqtt to use channel 11.

If no channel is set in your configuration file, you'll want to check first what your old instance is using.
On the Zigbee2MQTT screen, I think you can go to Settings > Settings > Advanced and scroll down to "ZigBee channel".

Note that I'm fairly unexperimented will Zigbee2MQTT myself too, so please don't take my advice as the absolute truth. 🙇🏻‍♂️

**Comment by g3r0nim00** [comment]
Hi David,

thanks. I've verified: both configurations are identical... (including the channel, I guess 11 is the default channel).
No worries, I'm also fairly unexperienced with zigbee. Your advise makes total sense, it's the same approach I was planning to follow without any 'official' advise.

However, it doesn't seem to work for me... I'll trial and error further unless a more 'official' approach is posted.
