### ISSUE TITLE
filtered_attributes: It didn't take effect

### ISSUE THREAD

**Issue by shgqynet2** [zigbee2mqtt/hassio-zigbee2mqtt#135]
Inside the devices.yaml
Add properties
'0x00124b00133fecc6':
  friendly_name: '0x00124b00133fecc6'
  filtered_attributes: ["l5", "l6", "l7", "l8", "l9", "l10", "l11", "l12", "l13", "l14", "l15", "l16"]
But theme publishing still has these attributes. What is the wrong setting?
Hope to reply, thank you.

**Comment by shgqynet2** [comment]
Complete theme：
Zigbee2MQTT:info  2021-06-05 12:47:24: MQTT publish: topic 'zigbee2mqtt/0x00124b00133fecc6', payload '{"action":null,"l1":null,"l10":null,"l11":null,"l12":null,"l13":null,"l14":null,"l15":null,"l16":null,"l2":null,"l3":null,"l4":null,"l5":null,"l6":null,"l7":null,"l8":null,"l9":null,"linkquality":96,"state_l1":"OFF","state_l10":null,"state_l11":null,"state_l12":null,"state_l13":null,"state_l14":null,"state_l15":null,"state_l16":null,"state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","state_l5":null,"state_l6":null,"state_l7":null,"state_l8":null,"state_l9":null}'

**Comment by ciotlosm** [comment]
Please report this under https://github.com/Koenkk/zigbee2mqtt/issues as this repo only handles configs set via add-on interface.
