### ISSUE TITLE
Can't save adapter type as ezsp on HA edge Add-On

### ISSUE THREAD

**Issue by nugget200** [zigbee2mqtt/hassio-zigbee2mqtt#144]
**Description of problem:**
When I try to setup Z2M Edge in HA as the Add-On using a wifi ZBbridge it wont let me save the configuration as it says "Failed to save add-on configuration, not a valid value." This error goes if I remove the adapter line from the config but of course doesn't therefore work.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
HA Z2M Edge
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:

```
{
  "external_converters": [],
  "devices": [
    "devices.yaml"
  ],
  "groups": [
    "groups.yaml"
  ],
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "user": "mqttuser",
    "password": "*******",
    "server": "mqtt://core-mosquitto:1883"
  },
  "serial": {
    "port": "tcp://192.168.7.20:8888",
    "adapter": "ezsp"
  },
  "advanced": {
    "log_level": "info",
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blocklist": [],
    "availability_passlist": []
  },
  "device_options": {},
  "blocklist": [],
  "passlist": [],
  "queue": {},
  "frontend": {
    "port": 8099
  },
  "experimental": {}
}

```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.6.5
Supervisor: supervisor-2021.06.0
Operating System: HassOS 6.0
```

**Comment by grego1981** [comment]
Same issue on latest HA with 
Zigbee2mqtt version: 1.18.1-1

**Comment by Blade0001** [comment]
Some issue on my site 
Version : 1.20.0

**Comment by ciotlosm** [comment]
Submitted a fix for edge, if you can test when builds are done and all works well, I will add it to stable as well.

**Comment by Blade0001** [comment]
> Submitted a fix for edge, if you can test when builds are done and all works well, I will add it to stable as well.

@ciotlosm thank you. I will test it when it's ready. Can you give a sign?

**Comment by ciotlosm** [comment]
Should be ready on edge

**Comment by ciotlosm** [comment]
@Blade0001 you can test now using edge 
cc: @nugget200 @grego1981

**Comment by Blade0001** [comment]
@ciotlosm, it just tested it. It works for me now. I am able to add adapter: ezsp to my config now.

**Comment by ciotlosm** [comment]
I will prepare a new release for stable then with the update I did in `edge`.

**Comment by MegoVaTx** [comment]
same issue on latest update

**Comment by MegoVaTx** [comment]
My config: 
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  user: ***********
  password: ***********
  server: mqtt://core-mosquitto
serial:
  port: /dev/ttyUSB1
  adapter: ezsp
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  baudrate: 57600
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
zigbee_herdsman_debug: true

**Comment by MegoVaTx** [comment]
`data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  user: mttq_user
  password: MTTQ_password2212
  server: mqtt://core-mosquitto
serial:
  port: /dev/ttyUSB1
  adapter: ezsp
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  baudrate: 57600
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
zigbee_herdsman_debug: true`
