### ISSUE TITLE
Hue tap fails after update to 1.19.1; also problem adding router

### ISSUE THREAD

**Issue by emdekext** [zigbee2mqtt/hassio-zigbee2mqtt#145]
After upgrading z2m to v1.19.1-1 my existing Hue Tap switch only functions when permit join is enabled. If join is disabled nothing appears in debug log if either of the 4 Tap buttons are pressed. Restarting z2m integration or restarting HA did not solve it. Rolled back to v1.19.0-1 and functionality of the Tap is instantly restored. Using Slae.sh CC2652RB stick on Hass OS 5.13.
Edit: update, I also was not able to add a CC2530+CC2591 router flashed with router-cc2530-cc2591-std.hex, after downgrading this worked instantly.

**Comment by ciotlosm** [comment]
Can you try with 1.20 and see if problems were solved? You need to open issues for device specific problems in https://github.com/Koenkk/zigbee2mqtt/issues to get them resolved as this is just add-on wrapper.
