### ISSUE TITLE
1.16.2  WARNING (MainThread) [supervisor.addons.validate] Unknown options restartdelay 

### ISSUE THREAD

**Issue by shirou93** [zigbee2mqtt/hassio-zigbee2mqtt#15]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
 1.16.2
**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

**Description of problem:**
Error in logs when start or restart addon

**Your logs from Home Assistant**

20-12-03 16:34:59 WARNING (MainThread) [supervisor.addons.validate] Unknown options restartdelay
20-12-03 16:34:59 WARNING (MainThread) [supervisor.addons.validate] Unknown options initialdelay

**Comment by shirou93** [comment]
Is thist error? I have (old config)

  restartdelay: 1
  initialdelay: 1

in config but when i check default config this positions will disaapear.

**Comment by ciotlosm** [comment]
You must remove those options. The add-on no longer relies on fork process hack and restarts, it now uses proper s6-overlay services structure.
