### ISSUE TITLE
Repository structure is not compliant

### ISSUE THREAD

**Issue by geidorei** [zigbee2mqtt/hassio-zigbee2mqtt#155]
Hi - I get the error message 'Repostitory structure for v1.20.0-1 is not compliant' when I try to add the Repo.

Any ideas? Many thanks.

**Comment by ciotlosm** [comment]
It works for me. How are you trying to add the repo? Are you using the documentation provided? Please use: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt as URL.

**Comment by ciotlosm** [comment]
I tested this and works on multiple installation. I will close the issue unless more details are provided.

**Comment by geidorei** [comment]
Me being thick- all ok- thanks folks.
