### ISSUE TITLE
Backup file coordinator_backup.json is not updated when the addon is restarted

### ISSUE THREAD

**Issue by Enzokot** [zigbee2mqtt/hassio-zigbee2mqtt#159]
**Description of problem:**
Backup file `coordinator_backup.json` is not updated when the addon is restarted or stoped.
Only UI restart button update the backup file.

**Running platform (details from Suypervisor > System)**
```
Add-on: 1.21.0-1
Core: core-2021.7.4
Supervisor: supervisor-2021.06.8
Operating System: Raspbian GNU/Linux 10 (buster)
```

**Comment by ciotlosm** [comment]
I can look to fix this if you can point me to how the UI is triggering the backup update.

**Comment by Enzokot** [comment]
In UI go to the Settings->Tools->Restart Zigbee2MQTT

![Screenshot_20210812-155024_Home Assistant](https://user-images.githubusercontent.com/43236573/129199906-8b4a84fa-c60e-4289-b8f9-24d78058aa38.png)

**Comment by Enzokot** [comment]
@ciotlosm did I misunderstand the question?

**Comment by ciotlosm** [comment]
Nope, but was curious of the code behind the restart backup, not the button. I will have to dig more in the code to see what I could add to the s6 container to perform the backup at restart

**Comment by Hacker-CB** [comment]
+1. 
Same behavior in 1.21.1 HA add-on.

**Comment by Enzokot** [comment]
@ciotlosm any news?

**Comment by Enzokot** [comment]
@Koenkk can you help us with fix?

**Comment by Enzokot** [comment]
Keep alive

**Comment by Enzokot** [comment]
Keep alive

**Comment by Enzokot** [comment]
Keep alive

**Comment by Koenkk** [comment]
Can you provide the herdsman debug log of this?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by Enzokot** [comment]
> Can you provide the herdsman debug log of this?
> 
> See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

Yes, I add `zigbee_herdsman_debug: true` and grab log file with command `docker logs CONTAINER_ID > log.txt 2>&1` 
After that restart addon twice, the last one log file in attachment
[log.txt](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/files/9283148/log.txt)

**Comment by Koenkk** [comment]
Just wanted to let you know that I found a possible solution, will update you probably later this week.

**Comment by Koenkk** [comment]
This should be partially fixed now (https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/commit/5fb69e744271487ed0bc333b8148d015b37ad643). However if the backup takes longer than 10 seconds docker will kill the container resulting in no backup. 

Can you check if this fixed the issue for you @Enzokot ? (use the edge addon)

**Comment by Enzokot** [comment]
@Koenkk Seems this fix work correctly with edge addon

**Comment by Koenkk** [comment]
Great! Then this can be closed now 😄

**Comment by Enzokot** [comment]
Thanks!
