### ISSUE TITLE
Stelpro Thermostat - Not see humidity sensor

### ISSUE THREAD

**Issue by gobol007** [zigbee2mqtt/hassio-zigbee2mqtt#161]
Hello,

Rpi 3 + usb dongle zigbee
Home assistant - Last release
MQTT and zigbee2MQTT installed

I'm paired 9 Stelpro Thermostat SMT402. All work great, but i'm not showing the hmidity sensor in Home Assistant.

state from zigbee2MQTT send : 
```
{
    "humidity": 45,
    "linkquality": 108,
    "local_temperature": 24,
    "occupied_heating_setpoint": 5,
    "operation": "idle",
    "pi_heating_demand": 0,
    "running_state": "idle",
    "system_mode": "heat"
}
```

I can't seeing sensor from humidity for all my Stelpro Device.

Try add this on my configuration and the sensor not have value : 
```
- platform: "mqtt"
    state_topic: "zigbee2mqtt/0xf8f005fffff961f4"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "humidity"
    value_template: "{{ value_json.humidity }}"
```

What is wrong ?

Thank you

**Comment by ciotlosm** [comment]
Why are you not using auto-discovery? It will save you the trouble of configuring it yourself by hand.

**Comment by ciotlosm** [comment]
Maybe there is a problem with the discovery message, not the state one. Can you check how your discovery messages look like when adding the integration?

**Comment by gobol007** [comment]
No, how i can check that ? I checked in logs... but i'm nothing...

**Comment by gobol007** [comment]
in Dashboard  for stelpro, i'm see that 
![stelpro](https://user-images.githubusercontent.com/8069819/129204964-7109cf30-4924-48e1-b265-c8d4bcf3d2df.JPG)

**Comment by ciotlosm** [comment]
By reading https://www.zigbee2mqtt.io/devices/SMT402.html it seems that the humidity is not exposed as a sensor for this. I don't think this issue is for the add-on repo. Maybe try opening an issue here: https://github.com/Koenkk/zigbee2mqtt/issues for more support.
