### ISSUE TITLE
After updating cc2652R firmware, no devices are connecting

### ISSUE THREAD

**Issue by pilonull** [zigbee2mqtt/hassio-zigbee2mqtt#162]
**Description of problem:**
Hello, I have a CC2652R from here https://www.tindie.com/products/electrolama/zzh-cc2652r-multiprotocol-rf-stick/
I have been using zigbee2mqtt with the CC2652R_coordinator_20210120 firmware. Well, I was checking the changelog today for zigbee2mqtt 1.21.0-1 and found out there was a firmware update for my stick.. Well, I did what the instructions said, stopping/starting the addon, unplugging the stick, taking it to my windows PC to uipdate the firmware to the new one, CC2652R_coordinator_20210708.. firmware updates sucessfully.. I plug the stick back in to my Hassio box, start zigbee2mqtt... anddd none of my devices are responding. I get a bunch of errors like:

021-08-05 03:11:08: Publish 'set' 'state' to 'Office Subwoofer' failed: 'Error: Command 0x00124b00226a7cf9/1 genOnOff.on({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'

I was able to flash the stick back to the older firmware and restore a backup from earlier when I updated to Hassio 8.0.. and zigbee2mqtt was working.. so i decided to try update the coordinator again.. only to have the same results. Devices still aren't connecting to the coordinator with the new firmware.

So, I try to flash back to 20210120 again, restore the backup again.. and now none of my devices are connecting with the old firmware.. soo now I think I'm stuck repairing all my devices again.. which is unfortunate because I have 26 of them and a lot of them are sonoff zbmini's behind wall plates.. 

SO. what was the correct/proper update procedure? Because what I did was not successful. 

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
Zigbee2mqtt
Current version: 1.21.0-1

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.8.0
supervisor-2021.06.8
Home Assistant OS 6.2
```

**Your logs from Home Assistant Supervisor**
```
not relevant at this time, no related log entries for zigbee2mqtt
```

**Comment by pilonull** [comment]
Here are some more logs from zigbee2mqtt after spamming some switches trying to get something to respond.

```
error Publish 'set' 'state' to 'Bathroom Fan' failed: 'Error: Command 0x804b50fffeb569e4/1 genOnOff.on({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":45336,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
error Publish 'set' 'state' to 'Guest Bathroom Fan' failed: 'Error: Command 0x0c4314fffe9e59af/1 genOnOff.on({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":5509,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
error Publish 'set' 'state' to 'Guest Bathroom Light' failed: 'Error: Command 0x0c4314fffea010f6/1 genOnOff.on({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 56355 - 1 - 15 - 6 - 11 after 10000ms)'
error Publish 'set' 'state' to 'OfficeLight4' failed: 'Error: Command 0x60a423fffeb884b4/1 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
error Publish 'set' 'state' to 'OfficeLight3' failed: 'Error: Command 0x60a423fffef82c36/1 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
error Publish 'set' 'state' to 'OfficeLight1' failed: 'Error: Command 0x60a423fffef73849/1 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
error Publish 'set' 'state' to 'OfficeLight2' failed: 'Error: Command 0x5c0272fffe53a478/1 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
error Publish 'set' 'state' to 'Bathroom Fan' failed: 'Error: Command 0x804b50fffeb569e4/1 genOnOff.on({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 45336 - 1 - 4 - 6 - 11 after 10000ms)'
```

**Comment by gkyprios** [comment]
I updated my firmware on my ZZH CC2652R to 20210708 and HASS Addon to 1.21.0-1. I did two restarts are per the doco and everything is working. However after about 24hrs of operation I get the same errors as above. I can get all devices working again if I pull the usb stick and restart the addon. I'll post some errors here when it happens again.

**Comment by gkyprios** [comment]
As promised here are some log errors. The issue seems to start 22-23hrs later. I suspect an issue with the stick itself or more accurately, the new firmware. It was working flawlessly before I updated it. I'll try flashing it again, although it reported success after flashing it last time.  I'll also try a new USB port on the Pi.

Zigbee2MQTT:error 2021-08-10 17:41:04: Publish 'set' 'state' to 'Ensuite George 1' failed: 'Error: Command 0x00178801035639c0/11 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'
Zigbee2MQTT:error 2021-08-10 17:41:10: Publish 'set' 'state' to 'Ensuite George 2' failed: 'Error: Command 0x00178801035624e4/11 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'

**Comment by ciotlosm** [comment]
Please move your issue to https://github.com/Koenkk/zigbee2mqtt/issues as that is the repo for z2m core. This is just for the add-on that makes it work with home assistant. This just packages the code that is found there. 

I will not close this issue atm, as it has already some conversation going, but I strongly recommend you close it yourself once the new issue is up and conversation is moved there.

**Comment by Jens-Wymeersch** [comment]
@pilonull I'm using the same stick as yours, but I didn't do an upgrade, but getting every other something similar. Were you able to find a solution ? 

@ciotlosm I guess I also need to go to  https://github.com/Koenkk/zigbee2mqtt/issues with my problem ?

`Zigbee2MQTT:error 2021-09-18 21:05:38: Publish 'set' 'state' to 'Lamp Colour L1 Master' failed: 'Error: Command 0x00158d0004774bd0/1 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)`

Once I restart the add-on, it works again, but after a couple of days drops again.
