### ISSUE TITLE
Need to repair SNZB-01 after every z2m update 

### ISSUE THREAD

**Issue by sneakythr0ws** [zigbee2mqtt/hassio-zigbee2mqtt#164]
very unpleasant thing 
Other SNZB(-02,03,04) work correctly.

**Comment by ciotlosm** [comment]
Please move your issue to https://github.com/Koenkk/zigbee2mqtt/issues as this is only for specific add-on settings, not core z2m functionality. I would recommend you put in more information on your issue when posting there to get more support, like steps to reproduce and your setup details, as there are so many ways to have z2m up and running.
