### ISSUE TITLE
AddonManager.install blocked from execution, system is not health

### ISSUE THREAD

**Issue by bruvv** [zigbee2mqtt/hassio-zigbee2mqtt#17]
I am trying to install the addon but I am unable to do so, I am receiving the following error:

```
20-12-04 22:41:37 WARNING (MainThread) [supervisor.jobs] 'AddonManager.install' blocked from execution, system is not healthy
```

**Comment by andriej** [comment]
Do you have supported Supervised installation? 
You can check it in Supervisor -> System menu.

**Comment by ciotlosm** [comment]
@bruvv Can you help with some reproducing steps?

**Comment by andriej** [comment]
It's error message from supervisor stopping installation, not addon fault I think.

**Comment by bruvv** [comment]
Amdreij is correct. IT was because I've been running it on an unsported setup. Closing this
