### ISSUE TITLE
YSRSAI YSR-MINI-01_rgbcct color temp range max 370 mireds on HA 500 on web panel z2m

### ISSUE THREAD

**Issue by shirou93** [zigbee2mqtt/hassio-zigbee2mqtt#170]
Zigbee2MQTT version: 1.21.0
Adapter hardware: CC2652RB
Adapter firmware version: 20210708

https://www.zigbee2mqtt.io/devices/YSR-MINI-01_rgbcct.html#ysrsai-ysr-mini-01_rgbcct

max on ha:
![image](https://user-images.githubusercontent.com/59237288/129763480-10ecb1c8-b9f5-4959-98e9-429165114dd7.png)

z2m panel:
![image](https://user-images.githubusercontent.com/59237288/129763737-277d0111-6419-459e-8b3a-4a0ad3ad3232.png)

**Comment by ciotlosm** [comment]
This is a core issue and should go under: https://github.com/Koenkk/zigbee2mqtt/issues

This repository is just for the add-on specific settings and functionality which just wraps the core.
