### ISSUE TITLE
Warning when using `device_options.retain` in HomeAsssistant plugin

### ISSUE THREAD

**Issue by marklagendijk** [zigbee2mqtt/hassio-zigbee2mqtt#176]
**Description of problem:**
I have the following section in my Zigbee2mqtt plugin config in HomeAssistant:
```yaml
device_options:
  retain: true
```
This causes the following warning in the Supervisor logs:
```
21-08-23 18:20:59 WARNING (MainThread) [supervisor.addons.options] Unknown option 'retain' for Zigbee2mqtt (45df7312_zigbee2mqtt)
```

**Zigbee2mqtt add-on version**
```
> zigbee2mqtt@1.21.0 start
```

**Running platform**
```
Core: core-2021.8.8
Supervisor: supervisor-2021.06.8
Operating System: Debian GNU/Linux 10 (buster)
```

**Your logs from Home Assistant Supervisor**
```
21-08-23 18:19:08 WARNING (MainThread) [supervisor.addons.options] Unknown option 'retain' for Zigbee2mqtt (45df7312_zigbee2mqtt)
```

**Comment by ciotlosm** [comment]
I've had a look at z2m [configuration docs](https://www.zigbee2mqtt.io/information/configuration.html) and I think this option does not exist under `device_options`. 

I've seen it referenced under `Device specific configuration` which would require you to configure it in the add-on using `devices.yaml` option.

**Comment by marklagendijk** [comment]
In [this section](https://www.zigbee2mqtt.io/information/configuration.html#changing-device-type-specific-defaults) it says:
> The default values used for the device specific configuration can be overriden via e.g.:

If I understand that correctly it means that you can override any defaults, meaning that you can set any property that you would use in the Device specific configuration.

**Comment by ciotlosm** [comment]
I've had a look again at historical issues and you are correct. The current problem is with a limitation on the add-on itself. 

`device_options` as it currently stands can get some options added (I will try to add `retain` on edge) however if the device options are more than 1 layer deep it will not work on the add-on due to how configuration options are restricted in home assistant add-on to maximum two levels. 

works: 

```
device_options: 
  retain: true
```

does not work:

```
device_options: 
  homeassistant:
    expire_after: 30

```
