### ISSUE TITLE
New availability option not available

### ISSUE THREAD

**Issue by andriej** [zigbee2mqtt/hassio-zigbee2mqtt#180]
**Description of problem:**
New Availability (even experimental) is not available in HA addon - it was integrated and mentioned in 1.21.1-1 changelog.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.21.1-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
n/a
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.9.0
Supervisor: supervisor-2021.8.1
Operating System: Debian 11 Supervised
```

**Your logs from Home Assistant Supervisor**
```
n/a
```

**Comment by vturekhanov** [comment]
It looks like there are some typos in the [config.json](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/master/zigbee2mqtt-edge/config.json) file.

<img width="287" alt="Screenshot 2021-09-02 at 09 30 14" src="https://user-images.githubusercontent.com/5890453/131777992-101212e1-89fa-4ac7-bbcd-a4cf652ee419.png">
<img width="304" alt="Screenshot 2021-09-02 at 09 33 05" src="https://user-images.githubusercontent.com/5890453/131777998-4bc87bde-12a0-40e7-a27d-5fc5bea72c39.png">

**Comment by ciotlosm** [comment]
This option was only added on edge and not on stable. There is still a problem with the option itself (can only set it to true) as it uses more than 2 layers deep which is not supported as configuration by home assistant add-ons in general. 

https://github.com/Koenkk/zigbee2mqtt.io/blob/availability/docs/information/availability.md#advanced-configuration
