### ISSUE TITLE
Zigbee2MQTT - cannot open Web UI - 502 Bad Gateway 

### ISSUE THREAD

**Issue by benalla** [zigbee2mqtt/hassio-zigbee2mqtt#197]
I have been using same config now for some months.
Nothing has been changed.

Since yesterday: I noticed that my lights where not available.
Restarted Z2MQTT, restarted the RPI4.
Nothing helps and I cannot use the Web UI: 502 Bad Gateway

Current version: 1.18.1-1
HA Core 9.7
RPI4

Log:
```
Zigbee2MQTT:info  2021-10-01 15:33:28: Starting Zigbee2MQTT version 1.18.1 (commit #1.18.1)
Zigbee2MQTT:info  2021-10-01 15:33:28: Starting zigbee-herdsman (0.13.71)
Zigbee2MQTT:debug 2021-10-01 15:33:28: Using zigbee-herdsman with settings: '{"adapter":

2021-10-01T13:33:28.395Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
Zigbee2MQTT:error 2021-10-01 15:33:47: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-10-01 15:33:47: Failed to start zigbee
Zigbee2MQTT:error 2021-10-01 15:33:47: Exiting...
Zigbee2MQTT:error 2021-10-01 15:33:47: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-01T13_33_48_021Z-debug.logbee2mqtt/hassio-zigbee2mqtt/issues
```

**Comment by MikeNovik** [comment]
Hi. I have the same problem.
Zigbee2mqtt
Current version: 1.22.0-2
Сore-2021.11.3

[15:47:38] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.0 start
> node index.js
Zigbee2MQTT:error 2021-11-15 15:48:11: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-11-15 15:48:11: Failed to start zigbee
Zigbee2MQTT:error 2021-11-15 15:48:11: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-11-15 15:48:11: Exiting...
Zigbee2MQTT:error 2021-11-15 15:48:12: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:97:5)
[15:48:13] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.0 start
> node index.js

**Comment by benalla** [comment]
I tried everything, reset, delete and reinstall devices, backup from HA. Nothing  helped.

Untill I ordered and installed a new adapter.
Everything worked fine after that.

**Comment by tortho** [comment]
+1 on the issue. 2 installations, bad gateway or connection refused on both installations.
This is also valid for other new installed addons as well. (Old addons working)
