### ISSUE TITLE
latest update is broken for me can save new config zigbee2mqtt edge

### ISSUE THREAD

**Issue by rchiileea** [zigbee2mqtt/hassio-zigbee2mqtt#199]
**Description of problem:**
Update to latest version then paste back up config and get 

Failed to save add-on configuration, expected boolean.  Got {'data_path': '/config/zigbee2mqtt', 'external_converters': [], 'devices': 'devices.yaml', 'groups': 'groups.yaml', 'homeassistant': True, 'permit_join': False, 'mqtt': {'base_topic': 'zigbee2mqtt'}, 'serial': {'port': '/dev/ttyACM0', 'adapter': 'deconz'}, 'advanced': {'log_level': 'info', 'pan_id': 6754, 'channel': 11, 'network_key': [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13], 'availability_blocklist': [], 'availability_passlist': []}, 'device_options': {}, 'blocklist': [], 'pass...

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
// Example:
// > zigbee2mqtt@1.17.2 start /app
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
// replace this line with your pasted configuration
```

**Running platform (details from Suypervisor > System)**
```
// Example
core-2021.9.7
supervisor-2021.09.6

Home Assistant OS 6.4
```

**Your logs from Home Assistant Supervisor**
21-10-04 07:07:40 INFO (SyncWorker_0) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/generic-x86-64-homeassistant
21-10-04 07:07:40 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:1000 is not str
21-10-04 07:07:40 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-10-04 07:07:59 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-10-04 07:08:09 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-10-04 07:08:10 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-10-04 07:08:17 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-10-04 07:08:49 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 45df7312_zigbee2mqtt_edge
21-10-04 07:08:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-10-04 07:08:59 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-10-04 07:08:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-10-04 07:09:00 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-10-04 07:09:05 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-10-04 07:09:07 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-10-04 07:09:07 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-10-04 07:09:07 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-10-04 07:12:21 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-10-04 07:12:21 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-10-04 07:12:21 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-10-04 07:13:23 INFO (SyncWorker_6) [supervisor.docker.interface] Removing image zigbee2mqtt/zigbee2mqtt-edge-amd64 with latest and edge
21-10-04 07:13:23 INFO (MainThread) [supervisor.addons.addon] Removing add-on data folder /data/addons/data/45df7312_zigbee2mqtt_edge
21-10-04 07:13:23 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 45df7312_zigbee2mqtt_edge
21-10-04 07:13:23 INFO (MainThread) [supervisor.addons] Add-on '45df7312_zigbee2mqtt_edge' successfully removed
21-10-04 07:13:25 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/45df7312_zigbee2mqtt_edge
21-10-04 07:13:25 INFO (SyncWorker_4) [supervisor.docker.interface] Downloading docker image zigbee2mqtt/zigbee2mqtt-edge-amd64 with tag edge.
21-10-04 07:13:26 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-10-04 07:13:27 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-10-04 07:13:31 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-10-04 07:13:31 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-10-04 07:13:31 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-10-04 07:13:31 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-10-04 07:13:32 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-10-04 07:13:32 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-10-04 07:13:50 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-10-04 07:13:51 INFO (MainThread) [supervisor.addons] Add-on '45df7312_zigbee2mqtt_edge' successfully installed
21-10-04 07:13:53 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-10-04 07:13:53 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-10-04 07:13:53 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-10-04 07:14:48 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 45df7312_zigbee2mqtt_edge
21-10-04 07:14:52 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-10-04 07:14:52 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-10-04 07:14:54 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-10-04 07:14:55 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-10-04 07:14:55 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-10-04 07:14:55 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-10-04 07:14:55 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-10-04 07:14:55 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-10-04 07:19:56 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
21-10-04 07:19:56 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
21-10-04 07:20:26 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-10-04 07:20:26 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-10-04 07:20:26 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-10-04 07:22:12 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-10-04 07:22:14 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-10-04 07:22:14 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-10-04 07:22:14 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-10-04 07:22:28 INFO (MainThread) [supervisor.host.info] Updating local host information
21-10-04 07:22:29 INFO (MainThread) [supervisor.host.services] Updating service information
21-10-04 07:22:29 INFO (MainThread) [supervisor.host.network] Updating local network information
21-10-04 07:22:30 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-10-04 07:22:30 INFO (MainThread) [supervisor.host.manager] Host information reload completed
21-10-04 07:26:46 INFO (MainThread) [supervisor.backups.manager] Found 0 backup files
21-10-04 07:26:46 INFO (MainThread) [supervisor.backups.manager] Found 0 backup files
21-10-04 07:27:00 INFO (MainThread) [supervisor.backups.manager] Found 0 backup files
21-10-04 07:27:00 INFO (MainThread) [supervisor.backups.manager] Found 0 backup files
21-10-04 07:27:06 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 45df7312_zigbee2mqtt
21-10-04 07:27:09 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.21.1-1
21-10-04 07:27:10 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-10-04 07:27:11 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-10-04 07:27:11 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-10-04 07:27:11 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-10-04 07:27:18 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug 169ef730
21-10-04 07:27:18 INFO (MainThread) [supervisor.backups.manager] Backing up 169ef730 store Add-ons
21-10-04 07:27:18 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on 45df7312_zigbee2mqtt
21-10-04 07:27:18 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon 45df7312_zigbee2mqtt
21-10-04 07:27:18 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 169ef730 completed
21-10-04 07:27:19 INFO (SyncWorker_2) [supervisor.docker.interface] Updating image zigbee2mqtt/zigbee2mqtt-amd64:1.21.1-1 to zigbee2mqtt/zigbee2mqtt-amd64:1.21.2-1
21-10-04 07:27:19 INFO (SyncWorker_2) [supervisor.docker.interface] Downloading docker image zigbee2mqtt/zigbee2mqtt-amd64 with tag 1.21.2-1.
21-10-04 07:27:23 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
21-10-04 07:27:23 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
21-10-04 07:27:23 INFO (MainThread) [supervisor.api.middleware.security] /backups/169ef730/info access from cebe7a76_hassio_google_drive_backup
21-10-04 07:27:25 INFO (MainThread) [supervisor.api.middleware.security] /backups/169ef730/download access from cebe7a76_hassio_google_drive_backup
21-10-04 07:27:25 INFO (MainThread) [supervisor.api.backups] Downloading backup 169ef730
21-10-04 07:27:27 INFO (MainThread) [supervisor.api.middleware.security] /backups/169ef730 access from cebe7a76_hassio_google_drive_backup
21-10-04 07:27:27 INFO (MainThread) [supervisor.backups.manager] Removed backup file 169ef730
21-10-04 07:27:28 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
21-10-04 07:27:28 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
21-10-04 07:27:33 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
21-10-04 07:27:33 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
21-10-04 07:27:50 INFO (SyncWorker_2) [supervisor.docker.interface] Stopping addon_45df7312_zigbee2mqtt application
21-10-04 07:27:51 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt application
21-10-04 07:27:51 INFO (MainThread) [supervisor.addons] Add-on '45df7312_zigbee2mqtt' successfully updated
21-10-04 07:27:51 INFO (SyncWorker_7) [supervisor.docker.interface] Cleanup images: ['zigbee2mqtt/zigbee2mqtt-amd64:1.21.1-1']
21-10-04 07:27:53 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.21.2-1
21-10-04 07:29:09 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed// Your logs here
```

**Comment by DavyRoswinkel** [comment]
I can confirm, I got the same error

**Comment by Theoreet** [comment]
Same error

**Comment by DavyRoswinkel** [comment]
Found the solution! 

In your config edit the following:
availability: bool?

change it to:
availability: true

save and start the addon..

it works for me

**Comment by rchiileea** [comment]
all fixed withy that for me too, thanks for the spot DavyRoswinkel
