### ISSUE TITLE
External converters are not picked up anymore

### ISSUE THREAD

**Issue by geoffreylagaisse** [zigbee2mqtt/hassio-zigbee2mqtt#201]
**Description of problem:**
// Please do a short description of the problem
// Make sure your problem is related to the add-on, not to core Zigbee2mqtt functionality, like problems with specific devices - for such issues use https://github.com/Koenkk/zigbee2mqtt/issues

Since the latest version external converters aren't picked up anymore.
The device that was working with my external converter becomes unsupported.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.21.2
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters:
  - TRV_quirk.js
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: secret
  password: secret
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_22_98_87_F1-if00-port0
advanced:
  log_level: warn
  pan_id: 6754
  channel: 25
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  availability_timeout: 300
  timestamp_format: DD-MM-YYYY HH:mm:ss
  ikea_ota_use_test_url: true
  homeassistant_legacy_triggers: true
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.9.7
Supervisor: supervisor-2021.09.6
Operating System: Home Assistant OS 6.4
```

**Your logs from Home Assistant Supervisor**
```
// Your logs here
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[23:28:26] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[23:28:26] INFO: MQTT available, fetching server detail ...
[23:28:26] INFO: Previous config file found, checking backup
[23:28:26] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[23:28:26] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:28:26] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.21.2 start
> node index.js
```

**Comment by dollop80** [comment]
I experience the same problem with all my external converters

**Comment by geoffreylagaisse** [comment]
I'm glad that I'm not the only one! I reverted to the backup of the container to make them work again.

**Comment by kaweksl** [comment]
I'm having similar issue. I have created external converter for device but looks like it's not loaded when starting/restarting via Home assistant addon-s page, i have to go into zigbee2mqtt webui -> settings -> tools and restart zigbee2mqtt, after that converter is loaded and device becomes supported

I have set external converter in HA addon configuration tab.

**Comment by sipossz** [comment]
Same issue... It's forgetting external converters after zigbee2mqtt resterted from the HA add-on pages. Additional restart must be triggered from the zigbee2mqtt Settings/Tools page itself and the unsopported devices become supported again.

**Comment by M-Dobr** [comment]
Happens also for me...

**Comment by Nesvet** [comment]
Same here

Home Assistant Supervisor version 2022.01.1
Home Assistant Core version 2022.2.0
Zigbee2MQTT version 1.23.0

**Comment by DmitryMyadzelets** [comment]
Same issue
