### ISSUE TITLE
502 - Bad Gateway =>TypeError: Cannot read property 'payload' of undefined

### ISSUE THREAD

**Issue by mobilandi** [zigbee2mqtt/hassio-zigbee2mqtt#203]
After updating and restarting my HomeAssistant, zigbee2mqtt won't start anymore. The interface shows a "502 - Bad Gateway" error. The log shows following issue:

> Zigbee2MQTT:error 2021-10-06 22:58:07: Error while starting zigbee-herdsman
> Zigbee2MQTT:error 2021-10-06 22:58:07: Failed to start zigbee
> Zigbee2MQTT:error 2021-10-06 22:58:07: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
> Zigbee2MQTT:error 2021-10-06 22:58:07: Exiting...
> Zigbee2MQTT:error 2021-10-06 22:58:07: TypeError: Cannot read property 'payload' of undefined
>     at AdapterNvMemory.writeItem (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/adapter-nv-memory.ts:111:31)
>     at ZnpAdapterManager.clearAdapter (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:473:9)
>     at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:331:9)
>     at ZnpAdapterManager.beginRestore (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:296:9)
>     at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:80:17)
>     at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
>     at Zigbee.start (/app/lib/zigbee.ts:63:27)
>     at Controller.start (/app/lib/controller.js:116:27)
>     at start (/app/index.js:95:5)
> [22:58:07] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.21.2 start
> node index.js

I'm using following releases:
zigbee2mqtt; 1.21.2-1
Core: core-2021.10.0
Host OS: Home Assistant OS 6.4
Supervisor: supervisor-2021.09.6

Is this any compability issue between these new releases?

**Comment by MPowerData** [comment]
Were you be able to resolve this?

I am having similar log entries.

Thnx.

**Comment by Skovens** [comment]
I have this exact problem. It is my first time using HA and zigbee2mqtt and figured i was doing something wrong? I have followed countless tutorials with this exact same result everytime. Does anyone have any progress?

**Comment by MPowerData** [comment]
Same here, did not find a solution yet unfortunately...

**Comment by MPowerData** [comment]
@Koenkk  , any idea what is going wrong here?

**Comment by Koenkk** [comment]
Probably something wrong on the adapter side, try reflashingit.

**Comment by tieppm** [comment]
I have the same error
i use sonoff zigbee 3.0 usb dongle plus
flashed CC1352P2_CC2652P_launchpad_coordinator_20210708
zigbee2mqtt; 1.22.1-1
Core: core-2021.11.5
Host OS: Home Assistant OS 64

**Comment by mobilandi** [comment]
> Probably something wrong on the adapter side, try reflashing it.

Yes I think there is something wrong with my adapter. I did reflash it several times. At some point the message disappeared and zigbee2mqtt started working again. So I don't have a 100% answer, but reflashing could help.

**Comment by Oddiwahn** [comment]
Hi I also have the sonoff zigbee 3.0 usb dongle.
For me reflashing didn't help.
Also, the adapter works fine when I use the ZHA addon but not with zigbee2mqtt, so shouldn't be an adapter issue
I get the following errors, after each z2m tries restarting itself:

Zigbee2MQTT:error 2021-12-10 22:45:42: TypeError: Cannot read property 'payload' of undefined
Zigbee2MQTT:error 2021-12-10 22:46:09: TypeError: Cannot read property 'payload' of undefined
Zigbee2MQTT:error 2021-12-10 22:46:36: Error: SRSP - SYS - getExtAddr after 6000ms
Zigbee2MQTT:error 2021-12-10 22:47:55: Error: SRSP - ZDO - startupFromApp after 40000ms
Zigbee2MQTT:error 2021-12-10 22:48:23: Error: SRSP - SYS - getExtAddr after 6000ms
Zigbee2MQTT:error 2021-12-10 22:49:10: Error: SRSP - ZDO - startupFromApp after 40000ms
Zigbee2MQTT:error 2021-12-10 22:50:05: Error: SRSP - ZDO - startupFromApp after 40000ms
Zigbee2MQTT:error 2021-12-10 22:51:01: Error: SRSP - ZDO - startupFromApp after 40000ms
Zigbee2MQTT:error 2021-12-10 22:51:22: Error: SRSP - SYS - getExtAddr after 6000ms
Zigbee2MQTT:error 2021-12-10 22:51:36: Error: SRSP - SYS - getExtAddr after 6000ms
Zigbee2MQTT:error 2021-12-10 22:52:25: Error: SRSP - ZDO - startupFromApp after 40000ms

**Comment by Keishusan** [comment]
> I have the same error i use sonoff zigbee 3.0 usb dongle plus flashed CC1352P2_CC2652P_launchpad_coordinator_20210708 zigbee2mqtt; 1.22.1-1 Core: core-2021.11.5 Host OS: Home Assistant OS 64

were you able to solve? I have the same problem...

**Comment by MPowerData** [comment]
> Probably something wrong on the adapter side, try reflashing it.

Reflashing solved it for me...

**Comment by Skovens** [comment]
I reflashed it and it started working again. But now it is throwing new errors without me touching it or updating it. It is to unreliable for day to day use. Im gonna find something else instead, because it is simply not "smart" home at all, when you have to reflash and reinstall everything at random times without any idea what is going wrong or what is causing it.

**Comment by Ferrari2** [comment]
Same issue here when using a brand new and z-stack flashed "sonoff zigbee 3.0 usb dongle plus".

I can pair clients and it all looks very fine, but node red give the error "**502: Bad Gateway**". 
From the log I have this information:
**22-01-23 15:41:22 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.5:8099 ssl:default [Connect call failed ('172.30.33.5', 8099)]**

Hmm wondering what the new gateway IP address and port is...

Everything has been working a kind of stable before I change from a 2531 based dongle to the new sonoff zigbee 3.0 usb dongle plus.

Best regards
Bjarke

**Comment by carbone15** [comment]
Hello, does somebody find a solution?
because I have the problem too :)  with a CC2652, HA detect directly the key, but I can't start Z2M with error on payload.

**Comment by Skovens** [comment]
Mine randomly worked at one point. But I never got it working properly as intended. So I ended up just abandoning the project, seeing as no one was able to help. Everyone else seems to make it work, so I assume it’s me. I tried suggesting them that I could a better tutorial is they could me get going. as all the tutorials are all lacking in some aspect. But no one ever replied. So i gave up. 

Sorry i Can’t help you better. You Might be better of with a network version indstead of That USB version.

**Comment by carbone15** [comment]
I found the reason of my problem.  Ans it's a very stupid reason :(
When I plug my key, HA detected it and try to install an integration, I configure it, ... and didn't pay attention any more.
The name of this integration is "Zigbee Home Automation" aka ZHA, and ZHA use the key, so you can't use it with zigbee in the same time!!
So I just disabled ZHA and it's work :), 
So it's solved for me

**Comment by Skovens** [comment]
Well done, mate! I did not know This! I’m gonna give it another go when I have the time, and report back!

**Comment by Skovens** [comment]
That was indeed the problem. I always let it setup, after plugging it in, not knowing that I would take up the spot, so mqtt couldn’t acces it.
Well spotted, and thank you for your time!

mine works now as well!

**Comment by wayheming** [comment]
> I found the reason of my problem. Ans it's a very stupid reason :( When I plug my key, HA detected it and try to install an integration, I configure it, ... and didn't pay attention any more. The name of this integration is "Zigbee Home Automation" aka ZHA, and ZHA use the key, so you can't use it with zigbee in the same time!! So I just disabled ZHA and it's work :), So it's solved for me

mate you save my life) thank you

**Comment by robbebobbe** [comment]
> I found the reason of my problem. Ans it's a very stupid reason :( When I plug my key, HA detected it and try to install an integration, I configure it, ... and didn't pay attention any more. The name of this integration is "Zigbee Home Automation" aka ZHA, and ZHA use the key, so you can't use it with zigbee in the same time!! So I just disabled ZHA and it's work :), So it's solved for me

Thanks! This solved it for me as well.
