### ISSUE TITLE
Does this integration block direct access to Z2M frontend?

### ISSUE THREAD

**Issue by SHxKM** [zigbee2mqtt/hassio-zigbee2mqtt#206]
I can access the Z2M frontend from within my HassOS instance - inside a HA window. 

But I can’t access it through either: 
- homeassistant.local:8099
- 192.168.x.x:8099

Does this integration block direct access to the UI? If so, I’m curious about the reasons for this. 

Thanks!

**Comment by Bascht74** [comment]
Me, too. 
As I have some problems via the HassOS instance, I wanted to see if those issues are gone via direct access / port of the Z2M frontend...

**Comment by Bascht74** [comment]
Hi, I tried something here: 
https://github.com/Bascht74/hassio-zigbee2mqtt

changed two files. Now I have the web interface working:

![image](https://user-images.githubusercontent.com/66269310/144139320-f84740be-3eb7-4cb0-a23c-3674552c061b.png)

But I don't know if the maintainer wants that...
