### ISSUE TITLE
eWeLink SA-003-Zigbee(firmware version 1.0.5) error

### ISSUE THREAD

**Issue by frfstu** [zigbee2mqtt/hassio-zigbee2mqtt#209]
During the operation of the device, an error occurs periodically (sometimes several times a day): the device turns off but freezes in the "active" state of the on / off switch and does not respond.  The only way to return the device to working condition is to completely de-energize it.
 
Error Publish 'set' 'state' to '0x00124b0023592ffe' failed: 'Error: Command 0x00124b0023592ffe/1 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))'
Error Publish 'set' 'state' to '0x00124b0023592ffe' failed: 'Error: Command 0x00124b0023592ffe/1 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))'
Error Failed to bind cluster 'genOnOff' from '0x00124b0023592ffe' to 'Coordinator' (Error: Bind 0x00124b0023592ffe/1 genOnOff from '0x00124b0020cd1ed5/1' failed (AREQ - ZDO - bindRsp after 10000ms))
Error Failed to bind
Error Failed to bind cluster 'genOnOff' from '0x00124b0023592ffe' to 'Coordinator' (Error: Bind 0x00124b0023592ffe/1 genOnOff from '0x00124b0020cd1ed5/1' failed (AREQ - ZDO - bindRsp after 10000ms))
Error Failed to bind
Error Failed to bind cluster 'genOnOff' from '0x00124b0023592ffe' to 'Coordinator' (Error: Bind 0x00124b0023592ffe/1 genOnOff from '0x00124b0020cd1ed5/1' failed (AREQ - ZDO - bindRsp after 10000ms))
Error Failed to bind
Error Failed to execute LQI for '0x00124b0023592ffe

**Comment by RubenKelevra** [comment]
At least for firmware 1.0.2 there's no issue to report here. Can we downgrade the firmware?
