### ISSUE TITLE
deprecated add-on option

### ISSUE THREAD

**Issue by andriej** [zigbee2mqtt/hassio-zigbee2mqtt#21]
**zigbee2mqtt add-on version (if edge, please report commit hash):** 0.17.0

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):** Debian 10 Supervised

**Description of problem:**
New Supervisor (2021.2.5) prints error in Supervisor's log:
```
21-02-10 06:19:14 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Zigbee2mqtt
21-02-10 06:19:14 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Zigbee2mqtt Edge
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
n/a
```

**Your logs from Home Assistant**
n/a

**Comment by ciotlosm** [comment]
Fixed in 1.17.1-1
