### ISSUE TITLE
not major, but most of the device pics disappeared and a couple even changed, I looked at website and its showing as not secure in all browsers.

### ISSUE THREAD

**Issue by rchiileea** [zigbee2mqtt/hassio-zigbee2mqtt#210]
not major, but most of the device pics disappeared and a couple even changed, I looked at website and its showing as not secure in all browsers. fire, edge, opera, chrome

**Comment by JaegermeisterS** [comment]
> not major, but most of the device pics disappeared and a couple even changed, I looked at website and its showing as not secure in all browsers. fire, edge, opera, chrome

I am experiencing the same issue...
