### ISSUE TITLE
Malformed ingress of z2m UI in Home Assistant

### ISSUE THREAD

**Issue by Calimerorulez** [zigbee2mqtt/hassio-zigbee2mqtt#236]
**Description of problem:**
I just installed the addon, and when I use ingress in HA, the page is malformed, because there is a .css missing Chrome tells me :)

`http://homeassistant.local:8123/api/hassio_ingress/k9QpGAriW-uh-KQe1lBMZR80xirg3xP0WkcV7_ymq2o/main.3d1da3b8dbc50333ee92.css.map`

When I visit the link, the error is:

`Cannot GET /main.3d1da3b8dbc50333ee92.css.map`

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.22.0-2
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.11.3
Supervisor: supervisor-2021.10.8
Operating System: HassOS 6.6
```

![image](https://user-images.githubusercontent.com/1130552/141745333-ed9044ab-7927-4220-b8f0-e86664dbc020.png)

**Comment by habitoti** [comment]
Just wanted to create the same ticket, seeing I am seemingly not the only one ;-)

Usually the very first time after restart of HA it works w/o issues, but navigating away and then back here, it more often than not fails to load css. Sometimes, though, it also might work. Looks like some timing issue. So the css is not missing, but sometimes the access simply fails with a 404.

![2021-11-18_16-26-47](https://user-images.githubusercontent.com/220421/142444818-e219aaa5-ce15-4823-9621-200499a237e0.png)

**Comment by habitoti** [comment]
Seems like this Github is pretty much abandoned? This is a very annoying behaviour, tbh, because it's kind of random whether you get a proper UI or just garbage. But no responses from devs (in most of the issues raised lately here...)

**Comment by Cycor** [comment]
The missing map css isn't the problem, that just debugging help, for me it seems to be a theme key saved in the chrome Local Storage, if you use the developer console and remove the Theme key, the layout is back ok.

This is saved on the homeassistant host level so any other ha app using ingress can set that value, it contained a bootstrap skin name that didn't exist.

**Comment by habitoti** [comment]
It's not really missing, it just sometimes can't be loaded (it's BTW Safari, not Chrome, but I think it happens for both). If you reload a few times or navigate somewhere else and then back, it might show up ok. So it seems like some shady timing somewhere....

**Comment by Cycor** [comment]
Ok, found the cause of the theme key, the DoubleTake addon creates it, so every time I open that app, z2m is messed up

**Comment by habitoti** [comment]
So how comes that even a freshly opened HA straight on Ingress Z2M might already be messed up then?

**Comment by habitoti** [comment]
It's the light theme for me because I switched dark theme off. I believe the root cause is the same (and again, it's not really "missing" -- though I have no clue what mechanism other than a pure file access is responsible for delivering it...and only doing so every once in a while correctly)

**Comment by Bascht74** [comment]
I have similar problems: 

It takes a long time to load this really very big js file:
![image](https://user-images.githubusercontent.com/66269310/144130386-78c8bade-1f9d-4400-9f57-9c8bd5b6e1dc.png)

Sometimes there is an error:
![image](https://user-images.githubusercontent.com/66269310/144130623-6b84cc07-27dd-4013-a513-a28b1eb44c56.png)

Chrome is not very responsive if it happens. I even doesn't reload the page. But if you go elsewhere and back, sometimes it works...

If I try a couple of times or switch to another section in HA and back, it works sometimes...

If not, it looks like that:
![image](https://user-images.githubusercontent.com/66269310/144131464-7ed25a52-bb66-494d-b784-7e8b4e33753b.png)

**Comment by habitoti** [comment]
Seems to work now with V 1.22.1-1. It still comes up scrambled initially, but then manages to (re)load properly.
