### ISSUE TITLE
Addon wont start because /dev/ttyZ2M is read only

### ISSUE THREAD

**Issue by KennieNL** [zigbee2mqtt/hassio-zigbee2mqtt#24]
I'm using zigbee2mqtt with socat with the default configuration values where /dev/ttyZ2M gets created as device (as per example config).

Since latest version of supervisor (supervisor-2021.02.6) this does break and throws a error stating that /dev/ttyZ2M is read-only in the 1.17.1-1 release. 1.17.1 release would just keep restarting socat without extra information. (sorry dont have logs anymore!)

It seems that changing from the socat configuration from /dev/ttyZ2M to /share/zigbee2mqtt/ttyZ2M would fix my issue.

After investigation it seems that this supervisor commit does change /dev/ to read-only state:
https://github.com/home-assistant/supervisor/commit/b8a976b3440c57bc6cd3f8617afcc632f57906ff

I would like to suggest to change config.json from:
`"master": "pty,raw,echo=0,link=/dev/ttyZ2M,mode=777",`
to
`"master": "pty,raw,echo=0,link=/share/zigbee2mqtt/ttyZ2M,mode=777",`

**Comment by mleenaerts** [comment]
Thanks for the report. This indeed also fixed my issue.

**Comment by ciotlosm** [comment]
@KennieNL I will try to make a fix in 1.17.1-2 by updating the default to your suggestion for Socat.

**Comment by thehaxxa** [comment]
The `/share/zigbee2mqtt/` directory is used for data, logging and configuration. It might make sense to expose the serial device from `/tmp/ttyZ2M` instead?

**Comment by KennieNL** [comment]
Might be better to expose in /tmp/ yeah. But since it was late I didn't want to run into any other pemission issues.

I'll leave that for the devs to decide :)

**Comment by curlydingo** [comment]
So it seems like this helps for those using socat, but for people who use the device directly (or passed through to the VM) we're out of luck until the supervisor change gets reverted right?

My instance is failing to open /dev/ttyUSB0 with an  "Operation not permitted" error which I assume is due to the same supervisor change.

**Comment by adeepn** [comment]
> My instance is failing to open /dev/ttyUSB0 with an "Operation not permitted" error which I assume is due to the same supervisor change.
I have this problem too. The supervisor identifies devices by the major device number in /dev. But on my hardware, these numbers are different from those built into the supervisor. For example, my /dev/ttyAML2 has a major of 243 and falls into the  audio devices, but in the supervisor's major 244 is searched for ttyAML devices.

**Comment by ciotlosm** [comment]
I'm not sure if this issue is the correct place to report the problems with usb as those are related to the supervisor update. changes in the  add-on won't be able to fix.
