### ISSUE TITLE
Zigbee2mqtt group do not go offline when all the devices in group are offline

### ISSUE THREAD

**Issue by lonebaggie** [zigbee2mqtt/hassio-zigbee2mqtt#245]
**Description of problem:**
I have a number of light group containing Ikea Bulbs . When bulbs go offline when power removed (availability: true) groups winthin home assistant indicate off not Unavailable . When checking groups and dashboard  in Zigbee2mqtt frontend,bulbs are not grayed out and allow changes to be made.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
Current version: 1.22.1-1

**Running platform (details from Suypervisor > System)**
```
core-2021.11.5
Home Assistant OS 6.6
```

`

**Comment by deviantintegral** [comment]
I think this would be best fixed upstream at https://github.com/Koenkk/zigbee2mqtt/issues/9176.
