### ISSUE TITLE
Addon does not want to run because can't create './node_modules/zigbee-herdsman-converters/devices.js'

### ISSUE THREAD

**Issue by MarekCoufal** [zigbee2mqtt/hassio-zigbee2mqtt#25]
config:
```json
zigbee_shepherd_devices: true
```

log:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[07:17:15] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[07:17:16] INFO: MQTT available, fetching server detail ...
[07:17:16] INFO: Previous config file found, checking backup
[07:17:16] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[07:17:17] INFO: File devices.js found, copying to ./node_modules/zigbee-herdsman-converters/
cp: can't create './node_modules/zigbee-herdsman-converters/devices.js': No such file or directory
[cont-init.d] zigbee2mqtt.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

Where should the directory be?
Thank you for your help
Marek

**Comment by ciotlosm** [comment]
The devices.js method is getting deprecated because of multiple problems during version upgrades. Please use the new custom device method in the docs: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/master/zigbee2mqtt/DOCS.md#adding-support-for-new-devices

**Comment by Murada99** [comment]
Well, the new method is applied but I don't get the same results, some states are missing and i lost functionnalities.
My devices.js was just running fine and now with this update, I lost states and exposes.
My changes in devices.js was just to allow a new manufacturer and was a copy of an existing one changing the model and manufacturerName.

const device = 
    {
        zigbeeModel: ['wdxldoj'],
        fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_ywdxldoj'}],
        model: 'TS0601_thermostat',
        vendor: 'TuYa',
        description: 'Radiator valve with thermostat',
        whiteLabel: [{vendor: 'Moes', model: 'HY369RT'}, {vendor: 'SHOJZJ', model: '378RT'}],
        meta: {tuyaThermostatPreset: tuya.thermostatPresets, tuyaThermostatSystemMode: tuya.thermostatSystemModes3},
        ota: ota.zigbeeOTA,
        onEvent: tuya.onEventSetLocalTime,
        fromZigbee: [fz.tuya_thermostat, fz.ignore_basic_report, fz.ignore_tuya_set_time],
        toZigbee: [tz.tuya_thermostat_child_lock, tz.tuya_thermostat_window_detection, tz.tuya_thermostat_valve_detection,
            tz.tuya_thermostat_current_heating_setpoint, tz.tuya_thermostat_auto_lock,
            tz.tuya_thermostat_calibration, tz.tuya_thermostat_min_temp, tz.tuya_thermostat_max_temp,
            tz.tuya_thermostat_boost_time, tz.tuya_thermostat_comfort_temp, tz.tuya_thermostat_eco_temp,
            tz.tuya_thermostat_force_to_mode, tz.tuya_thermostat_force, tz.tuya_thermostat_preset, tz.tuya_thermostat_away_mode,
            tz.tuya_thermostat_window_detect, tz.tuya_thermostat_schedule, tz.tuya_thermostat_week, tz.tuya_thermostat_away_preset],
        exposes: [
            e.child_lock(), e.window_detection(), e.battery_low(), e.valve_detection(), e.position(),
            exposes.climate().withSetpoint('current_heating_setpoint', 5, 35, 0.5, ea.STATE_SET)
                .withLocalTemperature(ea.STATE).withSystemMode(['heat', 'auto', 'off'], ea.STATE_SET)
                .withRunningState(['idle', 'heat'], ea.STATE)
                .withLocalTemperatureCalibration(ea.STATE_SET)
                .withAwayMode().withPreset(['schedule', 'manual', 'boost', 'complex', 'comfort', 'eco']),
            e.auto_lock(), e.away_mode(), e.away_preset_days(), e.boost_time(), e.comfort_temperature(), e.eco_temperature(), e.force(),
            e.max_temperature(), e.min_temperature(), e.week(), e.away_preset_temperature()],
    };
module.exports = device;

This was working perfectly !!! **How can I go back to the previous version ?**

**Comment by kloodhu** [comment]
Murada, just put the next few lines to beginning of the new js:

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

and any other constants from the device.js your device is using.

**Comment by Murada99** [comment]
@kloodhu
Thanks for your help.
That's what i did, below is the complete code for this external_converter but instead of all states of the TRV, I only get the following:

```
{
    "away_mode": "OFF",
    "away_preset_days": 1,
    "away_preset_temperature": 15,
    "boost_time": 300,
    "comfort_temperature": 20,
    "current_heating_setpoint": 9,
    "eco_temperature": 15,
    "force": "normal",
    "linkquality": 10,
    "local_temperature": 20.5,
    "local_temperature_calibration": -1,
    "max_temperature": 25,
    "min_temperature": 9,
    "position": 0,
    "preset": "manual",
    "system_mode": "auto",
    "update": {
        "state": "idle"
    },
    "update_available": false,
    "week": "7"
}
```
Something is missing or the external_converters solution does not work as it should be.

The external_converters js file:
```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const constants = require('zigbee-herdsman-converters/lib/constants');
const {repInterval, defaultBindGroup, OneJanuary2000} = require('zigbee-herdsman-converters/lib/constants');
const reporting = require('zigbee-herdsman-converters/lib/reporting');

const e = exposes.presets;
const ea = exposes.access;
const device = 
    {
        zigbeeModel: ['wdxldoj'],
        fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_ywdxldoj'}],
        model: 'TS0601_thermostat',
        vendor: 'TuYa',
        description: 'Radiator valve with thermostat',
        whiteLabel: [{vendor: 'Moes', model: 'HY369RT'}, {vendor: 'SHOJZJ', model: '378RT'}],
        meta: {tuyaThermostatPreset: tuya.thermostatPresets, tuyaThermostatSystemMode: tuya.thermostatSystemModes3},
        ota: ota.zigbeeOTA,
        onEvent: tuya.onEventSetLocalTime,
        fromZigbee: [fz.tuya_thermostat, fz.ignore_basic_report, fz.ignore_tuya_set_time],
        toZigbee: [tz.tuya_thermostat_child_lock, tz.tuya_thermostat_window_detection, tz.tuya_thermostat_valve_detection,
            tz.tuya_thermostat_current_heating_setpoint, tz.tuya_thermostat_auto_lock,
            tz.tuya_thermostat_calibration, tz.tuya_thermostat_min_temp, tz.tuya_thermostat_max_temp,
            tz.tuya_thermostat_boost_time, tz.tuya_thermostat_comfort_temp, tz.tuya_thermostat_eco_temp,
            tz.tuya_thermostat_force_to_mode, tz.tuya_thermostat_force, tz.tuya_thermostat_preset, tz.tuya_thermostat_away_mode,
            tz.tuya_thermostat_window_detect, tz.tuya_thermostat_schedule, tz.tuya_thermostat_week, tz.tuya_thermostat_away_preset],
        exposes: [
            e.child_lock(), e.window_detection(), e.battery_low(), e.valve_detection(), e.position(),
            exposes.climate().withSetpoint('current_heating_setpoint', 5, 35, 0.5, ea.STATE_SET)
                .withLocalTemperature(ea.STATE).withSystemMode(['heat', 'auto', 'off'], ea.STATE_SET)
                .withRunningState(['idle', 'heat'], ea.STATE)
                .withLocalTemperatureCalibration(ea.STATE_SET)
                .withAwayMode().withPreset(['schedule', 'manual', 'boost', 'complex', 'comfort', 'eco']),
            e.auto_lock(), e.away_mode(), e.away_preset_days(), e.boost_time(), e.comfort_temperature(), e.eco_temperature(), e.force(),
            e.max_temperature(), e.min_temperature(), e.week(), e.away_preset_temperature()],
    };
module.exports = device;
```

**Comment by wiredcow** [comment]
Same problem with devices.js.

It should be possible to override an existing device in external_converters, right? I could not it to work with the XHS2-SE device.

```
external_converters:
- xhs2_se.js
```

/share/zigbee2mqtt/xhs2_se.js:
```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const e = exposes.presets;
const reporting = require('zigbee-herdsman-converters/lib/reporting');

const XHS2_SE = {
	zigbeeModel: ['XHS2-SE'],
	model: 'XHS2-SE',
	vendor: 'Sercomm',
	description: 'Magnetic door & window contact sensor (modified ext)',
	fromZigbee: [fz.ias_contact_alarm_1, fz.temperature, fz.battery],
	toZigbee: [],
	meta: {configureKey: 1, battery: {voltageToPercentage: '3V_2100'}},
	configure: async (device, coordinatorEndpoint, logger) => {
		const endpoint = device.getEndpoint(1);
		await reporting.bind(endpoint, coordinatorEndpoint, ['msTemperatureMeasurement', 'genPowerCfg']);
		await reporting.temperature(endpoint);
		await reporting.batteryVoltage(endpoint);
	},
	exposes: [e.contact(), e.battery_low(), e.tamper(), e.temperature(), e.battery(), e.voltage().withUnit('mV'), e.linkquality()]
};

module.exports = XHS2_SE;
```

I don't see any errors in the logs about it. If I do add an obvious error, like typing a nonsense "xyzxyz," I do see the error, so it seems to be loading the script, just not using it.

It worked fine in devices.js.

Any ideas?

**Comment by kloodhu** [comment]
Unfortunatelly i cant help more, but if you have a snapshot, you can restore an earlier version of the addon.

**Comment by Murada99** [comment]
Thanks Kloodhu, that's an option. I see that's possible to just restore the addon and nothing else.
It seems that my device will be in the next update of zigbee2mqqt, that's the other option: wait for the update. 

Probably, I will restore it and update when the new one is available.
Meanwhile, something is wrong when working with external converters. I hope that it will be fixed in the next releases.

**Comment by ciotlosm** [comment]
@Koenkk can you please assist here? I think it's better to fix problems with external_converter than have people still use devices.js for mods.

**Comment by dinhchinh82** [comment]
@ciotlosm actually the devices.js method is quite simple for most of users and we expect you can get it back.

**Comment by Murada99** [comment]
Hi clotlosm, this is for your help. 
While trying to find a solution, I upgraded to the latest version 1.17.1-4 and lost connectivity with the adapter. 
Trying to download a previous snapshot was not the solution. 
After spending a lot of time, I decided to change the adapter with a newly flashed CC2531 adpater. 
After booting up with this new adapter, everything works again, connectivity and external converters... Awesome !!!

**Comment by Koenkk** [comment]
@Murada99 what is the problem with the external converters here?

**Comment by Murada99** [comment]
@Koenkk I made an external converter for a new model of TRV TS0601 and the states of the model were not complete: missing power state and others. After a change with a newly flashed adapter (CC2531), everything seems to work and I get all states back. 
This issue can be closed.

**Comment by MarekCoufal** [comment]
@Murada99 And what version do you have? And can I ask for a link?

**Comment by Murada99** [comment]
@MarekCoufal 
The devices.js method is getting deprecated, you need to use esternal converters. 
On the top of your zigbee2mqtt configuration.yaml (in the folder share) just add the following lines
{
  "external_converters": [
    "external_converters.js"
  ],

external_converters.js is a file that you need to create in the share directory with the device definition (see above my external_converts.js file).

**Comment by MarekCoufal** [comment]
@Murada99 Yes, I have an external converter, but I have the same problem you are describing: some states have stopped appearing to me. That's why I ask about the reflash and the FW version (I have version 20190608). Thank you

**Comment by Murada99** [comment]
@MarekCoufal  My CC2531 is flashed with the last version 20200929. I got problems with the previous version 20190608.
https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/default

I have to pair 2 times to get everything working correctly.
