### ISSUE TITLE
Problem opening the Zigbee2mqtt web interface

### ISSUE THREAD

**Issue by motogon** [zigbee2mqtt/hassio-zigbee2mqtt#255]
**Description of problem:**
Problem opening the Zigbee2mqtt web interface

![изображение](https://user-images.githubusercontent.com/12997195/145994737-db178636-d3db-421b-9f22-2647b1ce51e6.png)

// Please do a short description of the problem

![изображение](https://user-images.githubusercontent.com/12997195/145994412-a624d6c5-5c97-4943-be91-30bc48d79cb8.png)

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
Current version: 1.22.1-1

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
// replace this line with your pasted configuration
```

**Running platform (details from Suypervisor > System)**
```
core-2021.12.1
supervisor-2021.12.1

Операционная система Ubuntu 20.04.3 LTS
Версия Docker 20.10.12 
```

**Your logs from Home Assistant Supervisor**

21-12-14 14:53:45 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-12-14 14:53:45 INFO (MainThread) [supervisor.homeassistant.core] Successfully started Home Assistant 2021.12.1
21-12-14 14:53:45 INFO (SyncWorker_4) [supervisor.docker.interface] Cleanup images: ['ghcr.io/home-assistant/qemux86-64-homeassistant:2021.11.5']
21-12-14 14:57:17 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:8099 ssl:default [Connect call failed ('172.30.33.0', 8099)]
21-12-14 15:02:44 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:8099 ssl:default [Connect call failed ('172.30.33.0', 8099)]
```
// Your logs here
```
ping 172.30.33.0
PING 172.30.33.0 (172.30.33.0) 56(84) bytes of data.
64 bytes from 172.30.33.0: icmp_seq=1 ttl=64 time=0.066 ms
64 bytes from 172.30.33.0: icmp_seq=2 ttl=64 time=0.047 ms
^C
--- 172.30.33.0 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 0.047/0.056/0.066/0.009 ms

**Comment by kuduacz** [comment]
same here

**Comment by glogiotatidis** [comment]
Same for me with a fresh install. I don't see any logs about starting the web interface, so maybe it's never started?

**Comment by glogiotatidis** [comment]
Updating to the latest versions of hass-os and HA fixed it for me. probably a dup of https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/259
