### ISSUE TITLE
Supervisor Problem

### ISSUE THREAD

**Issue by drako86** [zigbee2mqtt/hassio-zigbee2mqtt#271]
core-2021.12.8
supervisor-2021.12.2
Home Assistant OS 7.1
Z2M 1.22.2-1 

Hi, in my log, this keeps appearing  WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (45df7312_zigbee2mqtt) and even deleting the line [ experimental new api]  it creates a configuration error for me, so I'm forced to leave it ... how can I fix ???

**Comment by FirstRulez** [comment]
core-2021.12.10
supervisor-2022.01.1
Home Assistant OS 7.2
Zigbee2mqtt 1.23.0-1

22-02-02 18:09:50 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (45df7312_zigbee2mqtt)

I am seeing the same
