### ISSUE TITLE
Wierd error codes that makes no sense

### ISSUE THREAD

**Issue by mikalj2009** [zigbee2mqtt/hassio-zigbee2mqtt#273]
**Description of problem:**

Everything works, but getting errors in the log. It also seems like i have random delays on some bulbs when turning on, or changing.
I am using node red for automations.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**

1.22.2-1

**Your entire configuration from the frontend (with sensitive fields redacted)**:
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  user: xxx
  password: xxx
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2254696-if00
  adapter: deconz
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - x
    - x
    - x
    - x
    - x
    - xx
    - xx
    - xx
    - x
    - x
    - x
    - x
    - x
    - xx
    - xx
    - xx
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

**Running platform (details from Suypervisor > System)**

core-2021.12.7
supervisor-2021.12.2
Home Assistant OS 7.0

**Your logs from Home Assistant Supervisor**

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[13:36:53] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[13:36:53] INFO: MQTT available, fetching server detail ...
[13:36:53] INFO: MQTT server settings not configured, trying to auto-discovering ...
[13:36:53] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[13:36:53] INFO: Previous config file found, checking backup
[13:36:53] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[13:36:53] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:36:54] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.2 start
> node index.js
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2022-01-15 13:38:17: Publish 'set' 'color' to 'kontor_hue' failed: 'Error: Command 0x0017880103611463/11 lightingColorCtrl.moveToColor({"transtime":50,"colorx":45809,"colory":19661}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)'
Zigbee2MQTT:error 2022-01-15 13:39:36: Publish 'set' 'brightness' to 'kontor_hue' failed: 'Error: Command 0x0017880103611463/11 genLevelCtrl.moveToLevelWithOnOff({"level":102,"transtime":50}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)'
Zigbee2MQTT:error 2022-01-15 13:42:44: Publish 'set' 'brightness' to 'tuva_taklys2' failed: 'Error: Command 0x0017880104192267/11 genLevelCtrl.moveToLevelWithOnOff({"level":203,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)'

**Comment by duceduc** [comment]
Yes, I am getting the same errors and the lights does have delay or not turn on after several presses. Seems to a happening after the remove of the experimental api message I get when starting the integration. Not sure if that is the issue though.
