### ISSUE TITLE
No traffic to MQTT after upgrade

### ISSUE THREAD

**Issue by DaveOke** [zigbee2mqtt/hassio-zigbee2mqtt#28]
**Description of problem:**
Version upgraded to latest. Edge version will boot, non-edge version crashes immediately.

[16:16:51] INFO: MQTT available, fetching server detail ...
[16:16:52] INFO: MQTT credentials not configured, trying to auto-discovering ...
[16:16:52] INFO: Configuring'addons' mqtt user

If I monitor MQTT, absolutely nothing is received from zigbee2mqtt
Monitoring for this: Zigbee2MQTT:info  2021-02-12 16:16:59: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'

All other devices using MQTT are working fine.

**Comment by ciotlosm** [comment]
Do you have default mosquitto add-on? or you have your own custom mqtt? You can try setting credentials manually. 
What version of the add-on are you running? What message do you get when it's crashing?

**Comment by Xites** [comment]
I had exactly the same problem. After installing 1.17.1 there was no connection between Zigbee2mqtt and Hassio anymore.
In the end the probleem seems to be something with the client_id in de Zigbee2mqtt configuration. I added the following to the config.
```
mqtt:
  client_id: zigbee
```
But I've to say I tried more. I also added some ports and IP addresses to the (Debian) firewall and I introduced a username and password for mqtt. Than I also added the following to '/usr/share/hassio/share/mosquitto/accesscontrollist'.
```
topic readwrite #

user [username]
topic readwrite #

```
I don't know what exactly helped to solve this, maybe someone knows.

**Comment by EmilFlach** [comment]
I had this same issue and I think it is related to running zigbee2mqtt anonymously.

I fixed it by adding a zigbee2mqtt user to my Mosquitto config as follows:
```
logins:
  - username: zigbee2mqtt
    password: ************
 ```

Then this user needed to be added to my accesscontrollist (`/usr/share/hassio/share/mosquitto/accesscontrollist`), as mentioned by @Xites. My accesscontrollist file looks like this now:
```
topic readwrite #

user zigbee2mqtt
topic readwrite #
```

Then lastly I added this user to the zigbee2mqtt config as follows:

```
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: zigbee2mqtt
  password: ************
```

I guess I finally got punished for running things in an insecure manner 😃

**Comment by deltazerorsan** [comment]
@EmilFlach Thanks a lot, you save my day (night really)

Have a beer and take care!

😃
