### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by jb123567** [zigbee2mqtt/hassio-zigbee2mqtt#283]
Currently using Zigbee2MQTT Edge with the ZZH stick running the latest firmware. I've been experiencing the add on taking a huge amount of CPU capacity, currently 30% of an i3 processor.

Nothing in the logs stands out.

The CPU usage does not occur immediately after a restart, it seems to occur suddenly after a few hours.

Network has 42 devices, mixture of battery and routers.

**Comment by LUBANG37** [comment]
Me too! Problem of the new version.

**Comment by DarwinData** [comment]
I am also seeing this using Zigbee2MQTT addon in HA OS, using a Sonoff USB dongle plus and about 50 devices  If I restart the Z2M addon the CPU usage goes back down but then creeps back up after a few hours as can be seen in the CPU graph below.
![HA-Processor-Usage](https://user-images.githubusercontent.com/46134687/153424270-7b01eb4f-1387-413d-bc80-6bf27ad0e6b7.PNG)

I need to restart the Z2M addon about twice a day.  Not sure what other debug info that I can provide?
thanks

**Comment by cociweb** [comment]
+1 around 110-120% of the cpu (with only 1 device. - the same without any device as well)

**Comment by DarwinData** [comment]
I wonder if we have a common device.  It could be that there is a specific device causing the problem because no one else is reporting this.  My devices are:

```
IKEA	LED1545G12
IKEA	LED1842G3
IKEA	LED1649C5
Linkind	ZS110050078
LivingWise	LVS-ZB15R
Moes	ZTS-EU_2gang
Philips	9290011998B
Philips	9290012573A
SONOFF	BASICZBR3
SONOFF	S31ZB
Sengled	E1C-NB7
Sinopé	TH1123ZB
Sinopé	TH1124ZB
TuYa	TS0002
TuYa	TS0201
Xiaomi	RTCGQ01LM
Xiaomi	RTCGQ11LM
Xiaomi	WSDCGQ11LM
Xiaomi	JTYJ-GD-01LM/BW
Xiaomi	SJCGQ11LM	
Xiaomi	DJT11LM
Xiaomi	MCCGQ11LM
Xiaomi	WSDCGQ11LM
Xiaomi	WXKG11LM
eWeLink	SA-003-Zigbee
```

**Comment by jb123567** [comment]
This seems to resolved itself for me, is anyone else still have issues?

**Comment by No14you** [comment]
Same issue here. Is there any solution?
