### ISSUE TITLE
[1.17.1-1] transit_power option removed from settings  ...

### ISSUE THREAD

**Issue by thiscantbeserious** [zigbee2mqtt/hassio-zigbee2mqtt#29]
> Nothing has changed regarding this option from the z2m perspective. Likely something in the addon so create an issue her: https://github.com/danielwelch/hassio-zigbee2mqtt/issues
> 
> _Originally posted by @Koenkk in https://github.com/Koenkk/zigbee2mqtt/discussions/6251#discussioncomment-365845_

**Description of problem:**
transmit_power was removed from experimental settings - this functionality didn't change and is still implemented in zigbee2mqtt itself in the same place.

This currently results in the transit_power setting not working at all in the addon itself (it did with 1.17.1).

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
 > zigbee2mqtt@1.17.1-1
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.2.1
Supervisor: supervisor-2021.02.6
Operating System: HassOS 5.10
```

**Comment by goodwin** [comment]
For users with 2652P sticks - this is a severity 0 issue. So, I assume that has to be addressed ASAP.

**Comment by ciotlosm** [comment]
This will get added back in 1.17.1-3. Would be good if someone could document this option in z2m docs as well. It was removed in a cleanup of older options as it was not visible in the docs as supported https://www.zigbee2mqtt.io/information/configuration.html

**Comment by ciotlosm** [comment]
This has now been released with 1.17.1-4

**Comment by ciotlosm** [comment]
@goodwin @thiscantbeserious can you please check the new version and let me know if the issue can be closed?

**Comment by thiscantbeserious** [comment]
> @goodwin @thiscantbeserious can you please check the new version and let me know if the issue can be closed?

Will do likely by tomorrow :)

**Comment by thiscantbeserious** [comment]
@ciotlosm works for me, no unknown option log and signal seems better again

**Comment by ciotlosm** [comment]
Thanks for testing

**Comment by thiscantbeserious** [comment]
I've tried to document this and opened up a PR in the zigbee2mqtt documentation repo @ciotlosm
