### ISSUE TITLE
Zigbee2mqtt doesnot start.

### ISSUE THREAD

**Issue by KarelHaruda** [zigbee2mqtt/hassio-zigbee2mqtt#291]
Zigbee2mqtt doesnot start..

Zigbee2mqtt add-on version 1.23.0-1

Front end also does not run show only 502: Bad Gateway

**Running platform (details from Suypervisor > System)**

Core: core-2022.2.6
Supervisor: supervisor-2022.01.1
Operating System: Home Assistant OS 7.4 running in VirtualBox

Zigbee2mqtt LOG
`Zigbee2MQTT:error` 2022-02-13 17:48:52: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-02-13 17:48:52: Failed to start zigbee
Zigbee2MQTT:error 2022-02-13 17:48:52: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-02-13 17:48:52: Exiting...
Zigbee2MQTT:error 2022-02-13 17:48:52: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:101:5)
`

Supervisor LOG

`22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-02-13 16:34:09 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-02-13 17:04:10 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-02-13 17:06:20 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
22-02-13 17:06:59 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
22-02-13 17:07:13 INFO (SyncWorker_5) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/qemux86-64-homeassistant
22-02-13 17:07:28 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-02-13 17:07:29 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-02-13 17:07:29 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-02-13 17:07:38 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
22-02-13 17:07:50 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
22-02-13 17:07:52 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
22-02-13 17:07:53 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
22-02-13 17:07:54 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
22-02-13 17:11:32 INFO (SyncWorker_0) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/qemux86-64-homeassistant
22-02-13 17:11:47 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-02-13 17:11:48 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-02-13 17:11:48 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-02-13 17:11:57 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
22-02-13 17:13:17 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
22-02-13 17:16:11 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
22-02-13 17:16:27 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
22-02-13 17:16:31 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_45df7312_zigbee2mqtt application
22-02-13 17:16:35 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt application
22-02-13 17:16:35 INFO (SyncWorker_3) [supervisor.docker.interface] Removing image zigbee2mqtt/zigbee2mqtt-amd64 with latest and 1.23.0-1
22-02-13 17:16:35 INFO (MainThread) [supervisor.addons.addon] Removing add-on data folder /data/addons/data/45df7312_zigbee2mqtt
22-02-13 17:16:35 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 45df7312_zigbee2mqtt
22-02-13 17:16:35 INFO (MainThread) [supervisor.addons] Add-on '45df7312_zigbee2mqtt' successfully removed
22-02-13 17:16:38 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/45df7312_zigbee2mqtt
22-02-13 17:16:38 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image zigbee2mqtt/zigbee2mqtt-amd64 with tag 1.23.0-1.
22-02-13 17:16:51 INFO (MainThread) [supervisor.addons] Add-on '45df7312_zigbee2mqtt' successfully installed
22-02-13 17:16:55 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 45df7312_zigbee2mqtt
22-02-13 17:16:59 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.23.0-1
22-02-13 17:17:19 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
22-02-13 17:20:52 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_45df7312_zigbee2mqtt application
22-02-13 17:20:55 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt application
22-02-13 17:20:55 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.23.0-1
22-02-13 17:23:16 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
22-02-13 17:30:14 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-02-13 17:30:14 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
22-02-13 17:30:14 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-02-13 17:31:34 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
22-02-13 17:31:39 INFO (SyncWorker_1) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/qemux86-64-homeassistant
22-02-13 17:31:54 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-02-13 17:31:55 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-02-13 17:31:55 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-02-13 17:32:04 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-02-13 17:34:09 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-02-13 17:34:10 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-02-13 17:38:01 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
22-02-13 17:40:49 INFO (MainThread) [supervisor.host.info] Updating local host information
22-02-13 17:40:49 INFO (MainThread) [supervisor.host.services] Updating service information
22-02-13 17:40:49 INFO (MainThread) [supervisor.host.network] Updating local network information
22-02-13 17:40:49 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
22-02-13 17:40:49 INFO (MainThread) [supervisor.host.manager] Host information reload completed
22-02-13 17:48:59 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
22-02-13 17:51:23 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
22-02-13 17:53:40 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]`

**Comment by mhzawadi** [comment]
I too have this issue, have had to build my HA from backup and now I cant zigbee at all :(

Core
Version core-2022.2.6
Newest Version core-2022.2.6

Supervisor
Version supervisor-2022.01.1
Newest Version supervisor-2022.01.1

Zigbee2mqtt
Current version: 1.23.0-1

**Comment by mhzawadi** [comment]
scratch that, if you have a Conbee2 you will need this `adapter: deconz`  under the `port` option

```
serial:
  port: /dev/ttyACM0
  adapter: deconz
```

**Comment by KarelHaruda** [comment]
Yes I have it there ..

**Comment by tomekswx** [comment]
It is something with core-2022.2.6, I also have 502 bad gateway.

**Comment by mhzawadi** [comment]
Maybe try a reinstall of Zigbee2mqtt?
I had your issue, till I did a full upgrade of core and OS. Then I found I had the deCONZ addon still running, turned that off and it all works on my pi.

**Comment by Belaial** [comment]
Add me to the list, I can't for the life of me get Zigbee2mqtt to work in HA, I have been running Domoticz and Zigbee2mqtt for around 2 years, never had an issue there.

I got curious about HA so I got myself a new pi4 and a second CC2652RB from slae.sh to test things out while still having my trusty Domoticz setup untouched.

I have been at this issue for about 4-5 days now, reading around the forums, trying guides and so on. I truly started to believe I had some form of hardware issue since I could not get it to work, I decided to set things up with Domoticz just to test since I know how that works, after 48 hours of Domoticz running absolutely rock solid I decided to got back to HA, without touching a single thing except re-flashing the SD card with a clean HA installation... but here I am again, can't get it to work. I get a few different errors, these are some of them I have in the log right now.

Zigbee2MQTT:error 2022-02-23 21:30:12: Error: SRSP - SYS - getExtAddr after 6000ms
Zigbee2MQTT:error 2022-02-23 21:31:49: Error: AREQ - ZDO - stateChangeInd after 60000ms
Zigbee2MQTT:error 2022-02-23 21:33:05: TypeError: Cannot read property 'payload' of undefined
Zigbee2MQTT:error 2022-02-23 21:34:41: Error: SRSP - APP_CNF - bdbStartCommissioning after 40000ms
Zigbee2MQTT:error 2022-02-23 21:36:46: Error: startup failed - configuration-adapter mismatch - see logs above for more information

Som older log entries
Zigbee2MQTT:error 2022-02-19 19:13:12: TypeError: Cannot read property 'length' of null
Zigbee2MQTT:error 2022-02-19 18:55:16: Error: AREQ - SYS - resetInd after 30000ms


I am running currently running

Core
Version
core-2022.2.9

Supervisor
Version
supervisor-2022.01.1

Operating System
Home Assistant OS 7.4


My stick is flashed with latest coordinator firmware CC2652RB_coordinator_20211217, I have re-flashed this stick probably 20+ times since I read over and over again that people have solved errors like the ones above with a re-flash. I have tried older firmware's also but nothing helps. I have re-formatted the SD card 4-5 times with a clean HA installation just to be sure when I start over that I don't have any old settings messing things up but nothing helps.


I am truly stuck and have almost given up... the only thing I know for sure is that exactly the same hardware works flawlessly with Domoticz so not sure what to do, any help is welcome.

**Comment by Belaial** [comment]
So a few more days have passed and I think I finally solved my own issue.... what I had misunderstood is that when you integrate Zigbee in HA integration (Configuration -> Devices & Services -> Integrations) it actually installs it's own Zigbee functions, so what I then did was adding Zigbee2mqtt on top of that... no wonder I had all these issues..... I feel so stupid, I just though I integrated the Zigbee USB stick when I did that integration and that I then on top of that needed Zigbee2mqtt and Mosquitto broker for things to work.... which I know almost a week later figured out was not the case.

I guess a good thing would be if some form of check could be added in Zigbee2mqtt (or maybe HA) that checks if HA's own Zigbee-stuff is already running and that way prevent users from using both systems at the same time.

Again, I am a complet noob when it comes to HA so this was totally my own mistake... but if possible some check to see that not both HA Zigbee and Zigbee2mqtt is running at the same time would be awesome to have.

**Comment by mundeczek** [comment]
> Zigbee2mqtt doesnot start..
> 
> Zigbee2mqtt add-on version 1.23.0-1
> 
> Front end also does not run show only 502: Bad Gateway
> 
> **Running platform (details from Suypervisor > System)**
> 
> Core: core-2022.2.6 Supervisor: supervisor-2022.01.1 Operating System: Home Assistant OS 7.4 running in VirtualBox
> 
> Zigbee2mqtt LOG `Zigbee2MQTT:error` 2022-02-13 17:48:52: Error while starting zigbee-herdsman Zigbee2MQTT:error 2022-02-13 17:48:52: Failed to start zigbee Zigbee2MQTT:error 2022-02-13 17:48:52: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions Zigbee2MQTT:error 2022-02-13 17:48:52: Exiting... Zigbee2MQTT:error 2022-02-13 17:48:52: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms) at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27) at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29) at Zigbee.start (/app/lib/zigbee.ts:58:27) at Controller.start (/app/lib/controller.ts10027) at start (/app/index.js:101:5) `
> 
> Supervisor LOG
> 
> `22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING 22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON 22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE 22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN 22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR 22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE 22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM 22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.check] System checks complete 22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING 22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete 22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING 22-02-13 16:33:42 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete 22-02-13 16:34:09 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token 22-02-13 17:04:10 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token 22-02-13 17:06:20 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)] 22-02-13 17:06:59 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)] 22-02-13 17:07:13 INFO (SyncWorker_5) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/qemux86-64-homeassistant 22-02-13 17:07:28 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready 22-02-13 17:07:29 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING 22-02-13 17:07:29 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete 22-02-13 17:07:38 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance 22-02-13 17:07:50 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)] 22-02-13 17:07:52 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)] 22-02-13 17:07:53 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)] 22-02-13 17:07:54 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)] 22-02-13 17:11:32 INFO (SyncWorker_0) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/qemux86-64-homeassistant 22-02-13 17:11:47 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready 22-02-13 17:11:48 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING 22-02-13 17:11:48 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete 22-02-13 17:11:57 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance 22-02-13 17:13:17 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)] 22-02-13 17:16:11 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)] 22-02-13 17:16:27 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)] 22-02-13 17:16:31 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_45df7312_zigbee2mqtt application 22-02-13 17:16:35 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt application 22-02-13 17:16:35 INFO (SyncWorker_3) [supervisor.docker.interface] Removing image zigbee2mqtt/zigbee2mqtt-amd64 with latest and 1.23.0-1 22-02-13 17:16:35 INFO (MainThread) [supervisor.addons.addon] Removing add-on data folder /data/addons/data/45df7312_zigbee2mqtt 22-02-13 17:16:35 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 45df7312_zigbee2mqtt 22-02-13 17:16:35 INFO (MainThread) [supervisor.addons] Add-on '45df7312_zigbee2mqtt' successfully removed 22-02-13 17:16:38 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/45df7312_zigbee2mqtt 22-02-13 17:16:38 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image zigbee2mqtt/zigbee2mqtt-amd64 with tag 1.23.0-1. 22-02-13 17:16:51 INFO (MainThread) [supervisor.addons] Add-on '45df7312_zigbee2mqtt' successfully installed 22-02-13 17:16:55 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 45df7312_zigbee2mqtt 22-02-13 17:16:59 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.23.0-1 22-02-13 17:17:19 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)] 22-02-13 17:20:52 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_45df7312_zigbee2mqtt application 22-02-13 17:20:55 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt application 22-02-13 17:20:55 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.23.0-1 22-02-13 17:23:16 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)] 22-02-13 17:30:14 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize 22-02-13 17:30:14 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode 22-02-13 17:30:14 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running 22-02-13 17:31:34 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed 22-02-13 17:31:39 INFO (SyncWorker_1) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/qemux86-64-homeassistant 22-02-13 17:31:54 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready 22-02-13 17:31:55 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING 22-02-13 17:31:55 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete 22-02-13 17:32:04 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance 22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING 22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON 22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE 22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN 22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR 22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE 22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM 22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.check] System checks complete 22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING 22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete 22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING 22-02-13 17:33:42 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete 22-02-13 17:34:09 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json 22-02-13 17:34:10 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token 22-02-13 17:38:01 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)] 22-02-13 17:40:49 INFO (MainThread) [supervisor.host.info] Updating local host information 22-02-13 17:40:49 INFO (MainThread) [supervisor.host.services] Updating service information 22-02-13 17:40:49 INFO (MainThread) [supervisor.host.network] Updating local network information 22-02-13 17:40:49 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information 22-02-13 17:40:49 INFO (MainThread) [supervisor.host.manager] Host information reload completed 22-02-13 17:48:59 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)] 22-02-13 17:51:23 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)] 22-02-13 17:53:40 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]`

Have you tried to reconnect the adapter to the usb port (in my case it helped)?

**Comment by KarelHaruda** [comment]
I tried it many times, it also rebooted many times and reinstalled several times from scratch
