### ISSUE TITLE
The 'away_mode_state_topic' option is deprecated and more

### ISSUE THREAD

**Issue by shirou93** [zigbee2mqtt/hassio-zigbee2mqtt#299]
Home Assistant 2022.3.1
Z2M 1.24.0-1

Logger: homeassistant.components.mqtt.climate
Source: helpers/config_validation.py:817
Integration: MQTT (documentation, issues)
First occurred: 22:58:06 (16 occurrences)
Last logged: 22:58:06

The 'away_mode_state_topic' option is deprecated, please remove it from your configuration
The 'hold_command_topic' option is deprecated, please remove it from your configuration
The 'hold_state_template' option is deprecated, please remove it from your configuration
The 'hold_state_topic' option is deprecated, please remove it from your configuration
The 'hold_modes' option is deprecated, please remove it from your configuration

**Comment by kds69** [comment]
see [home-assistant /core/#67875](https://github.com/home-assistant/core/issues/67875)
