### ISSUE TITLE
2 coordinators on 2 separate Raspberries working in the same LAN network

### ISSUE THREAD

**Issue by Hajsiu** [zigbee2mqtt/hassio-zigbee2mqtt#302]
Hi,

Is there any possibility to run 2 coordinators connected to 2 separate Raspberries working in the same LAN network?
I know that i should use powered zigbee devices to extend the range but as so far i have two zigbee sticks and two raspberries. I used one to reach the outdoor zigbee devices (one of them is really far) and now i want to mount first device indoor (motion sensor) so i thought i can use another stick (is laing on the shelf for a year) and mount in second Raspberry (both are running anyway) but i stucked with issues - when running second one then the first one is failing.

I would really appreciate if you have any solution for this case.

Thanks

**Comment by joshuaspence** [comment]
A workaround is to install both the stable and edge versions of Z2M and run them side by side.
