### ISSUE TITLE
Consider creating a hassio proxy addon

### ISSUE THREAD

**Issue by SamMousa** [zigbee2mqtt/hassio-zigbee2mqtt#305]
Currently you either integrate with HASSIO fully via the addon, or not at all running zigbee2mqtt externally.

Frigate has an approach where they offer a very simple proxy addon that allows you to get the integration UX while running the service externally.

https://github.com/blakeblackshear/frigate-hass-addons/tree/main/frigate_proxy

I could make a PR to create this, I feel it should live in here though, not in my own repository.

**Comment by SamMousa** [comment]
Bump

**Comment by SamMousa** [comment]
Bump

**Comment by SamMousa** [comment]
Bump

**Comment by Koenkk** [comment]
Would this just provide the Z2M logo in the HA sidebar and by clicking on it open the dashboard?

**Comment by SamMousa** [comment]
Yes, but the interesting part is that it would work through homeassistant ingress, which means you can use it when not on the LAN, while protecting it via HA authentication

**Comment by SamMousa** [comment]
New addon, but very little work. Essentially just config. Check the link for how frigate does it. It is the same idea

**Comment by Koenkk** [comment]
Yes I see, would you want to create the initial version? I can create a new repo under https://github.com/zigbee2mqtt if you want

**Comment by SamMousa** [comment]
Currently the addon lives in the main repo. The proxy can live here too. I'll make a PR when I have time!

**Comment by SamMousa** [comment]
Unstale!

**Comment by SamMousa** [comment]
Implemented via #400
