### ISSUE TITLE
z2m not working after transition to SSD - already tried ALL recommended fixes - RasPi4, RaspBee II

### ISSUE THREAD

**Issue by freaked1234** [zigbee2mqtt/hassio-zigbee2mqtt#306]
**Description of problem:**

Transitioned HA from SD to SSD via fresh install and restore backup. Everything works after that except zigbee2MQTT. 
RasPi4 with original power supply and RaspBee II

I literally tried EVERYTHING I could find after googling forever:
- Use long USB extension for SSD
- Use powered USB Hub for SSD
- Try all USB-Ports
- Use jumper cables to get distance between RaspBee II and RasPi
- Put the RasPi between 2 aluminum dishes and let the RaspBee II hang outside to shield it from interference
- Upgraded RaspBee II firmware
- Disconnect SSD, boot from SD, reconnect SSD (is recognized by HA), restart z2m = z2m works !!!

Put all the hardware in a long line on my table like this:
RasbBee II --------*0,5m/19in Jumper cable* ------- RasPi4 -------- *1m/40in USB cable* --------- SSD

I am 100% lost...
 
**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.24.0-1
```
**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyAMA0
  adapter: deconz
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2022.3.5
Supervisor: supervisor-2022.03.5
Operating System: Home Assistant OS 7.5
```

**Your logs from Home Assistant Supervisor**
```
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2022-03-26 18:42:38: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-03-26 18:42:38: Failed to start zigbee
Zigbee2MQTT:error 2022-03-26 18:42:38: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-03-26 18:42:38: Exiting...
Zigbee2MQTT:error 2022-03-26 18:42:38: undefined
[18:42:38] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.24.0 start
> node index.js
CREATED DECONZ ADAPTER
```

**Supervisor Hardware entry**
```
DEVLINKS: /dev/serial1
DEVNAME: /dev/ttyAMA0
DEVPATH: /devices/platform/soc/fe201000.serial/tty/ttyAMA0
MAJOR: '204'
MINOR: '64'
SUBSYSTEM: tty
TAGS: ':systemd:'
USEC_INITIALIZED: '3369964'
```

**Comment by pplucky** [comment]
[Please check if you have your SSD connected in a different USB port (not above or below) than the Zigbee adapter](https://community.home-assistant.io/t/conbee-2-not-working-while-ssd-connected-on-rpi-4-model-b/367045).

I had this issue and it all went away with an extension plugged in side by side with the SSD (connected to USB3 port).

**Comment by Sashik259** [comment]
I soldered external antenna to my Raspbee II to move antenna away from USB3. You should cut 2 PCB tracks (look at the pic) a and connect in 1 place. Then your should solder SMA-connector to the place, where you cut PCB tracks - it ideal can be placed there! And I use aluminum case with my Raspberry Pi4
![FB3C1F1F-2FDA-420B-9329-AEFC210A2CBD](https://user-images.githubusercontent.com/77446865/166409746-4aa2d533-4357-4f39-806c-ff6e0ecf3163.jpeg)
