### ISSUE TITLE
WARNING (MainThread)

### ISSUE THREAD

**Issue by salopette** [zigbee2mqtt/hassio-zigbee2mqtt#309]
After the last update there are a lot of messages

> 22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-01 13:45:52 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)

**Comment by GerdRuetten** [comment]
I can confirm

After update to V 1.25.0-1 i have several errors and problems

- Like @salopette, numerous warnings in the supervisor log 
- 10 IKEA LED1650R5 go offline
- 1 sonoff zigbee 3.0 usb dongle plus, flashed as router go offline

After that, i update the coordinator-firmware (also sonoff zigbee 3.0 usb dongle plus) with the new firmware from today, but the problems remain

@Koenkk what have we done false?

**Comment by ikke-zelf** [comment]
It seems to me that within the configuration tab of the 'Zigbee2MQTT' addon the following lines need to be present (and the rest removed):
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  server: mqtt://core-mosquitto:1883
serial:
  port: [your reference to the used usb port]
```

**Comment by ikke-zelf** [comment]
> > As you could have read in the zigbee1mqtt release notes there are breaking changes in this update. I'm having a hard time understanding the steps to be taking to get things up and running again
> 
> I read the breaking changes but i cant find in the three points a notice to this problems

sorry Gerd, I was responding to the topic starter.

**Comment by Koterak** [comment]
> ⚠️ Breaking changes
Most Zigbee2MQTT configuration is now done in Zigbee2MQTT directly (either via the UI or by modifying the configuration file, usually /config/zigbee2mqtt/configuration.yaml, directly).

As Zigbee2MQTT won't start with an [MQTT server](https://www.zigbee2mqtt.io/guide/configuration/mqtt.html) or [serial adapter](https://www.zigbee2mqtt.io/guide/configuration/adapter-settings.html) you must configure these through the add-on configuration page before you can start Zigbee2MQTT for the first time.

Existing installations should be able to safely remove the Zigbee2MQTT configuration from the add-on configuration as these values should have already been persisted to the configuration file.

It's everything. You simply have to delete from config this lines which you have error. It's now done by zigbee2mqtt itself.

**Comment by GerdRuetten** [comment]
> 
> It's everything. You simply have to delete from config this lines which you have error. It's now done by zigbee2mqtt itself.

I reduce the config-Code to

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  server: mqtt://core-mosquitto:1883
serial:
  port: /dev/ttyUSB0

```

I cant't delete the code completely, because then I get an error message:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/97361636/161281405-779e6fa1-0848-4784-a2b2-f519fac16c29.png">

But that doesn't solve the problem either

**Comment by AbeltjeNL** [comment]
> It seems to me that within the configuration tab of the 'Zigbee2MQTT' addon the following lines need to be present (and the rest removed):
> 
> ```
> 
> data_path: /config/zigbee2mqtt
> 
> socat:
> 
>   enabled: false
> 
>   master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
> 
>   slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
> 
>   options: '-d -d'
> 
>   log: false
> 
> mqtt:
> 
>   server: mqtt://core-mosquitto:1883
> 
> serial:
> 
>   port: [your reference to the used usb port]
> 
> ```

Can confirm that this works.

**Comment by ArtJames** [comment]
Stop the addon
Update it to 1.25
Change configuration as mentioned by [ikke zelf](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/309#issuecomment-1085903044)
Start the addon

Worked well on my side

**Comment by salopette** [comment]
Thx works for me!

**Comment by mgiebels** [comment]
When i changed it to what is writen above my whole config is gone!

**Comment by AbeltjeNL** [comment]
> When i changed it to what is writen above my whole config is gone!

How do you mean, gone? Is the config.yaml file in /config/zigbee2mqtt gone? Is your addon config gone?

**Comment by mgiebels** [comment]
If I put this config in my zigbee2mqtt 1.25.0-1 and also the below in the config folder it doesn't work. 

data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

mqtt:
  server: mqtt://core-mosquitto:1883
serial:
  port: /dev/ttyACM0

And these is config.yaml in the zigbee2mqtt map


{
  "external_converters": [],
  "devices": [
    "devices.yaml"
  ],
  "groups": [
    "groups.yaml"
  ],
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://core-mosquitto:1883",
    "user": "mqtt",
    "password": "XXXXXXXX"
  },
  "serial": {
    "port": "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2225559-if00",
    "adapter": "deconz"
  },
  "advanced": {
    "log_level": "info",
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blocklist": [],
    "availability_passlist": []
  },
  "device_options": {},
  "blocklist": [],
  "passlist": [],
  "queue": {},
  "frontend": {
    "port": 8099
  },
  "experimental": {},
  "availability": false
}

then i need to restore a backup from mosquitobroker.
And then restore the config in the configuration tab again as it was before the upgrade to 1.25.0-1 and restore it in the configuration tab to make it work again, otherwise my whole zigbee2mqtt is empty and all my devices are gone

**Comment by AbeltjeNL** [comment]
> If I put this config in my zigbee2mqtt 1.25.0-1 and also the below in the config folder it doesn't work. 
> 
> 
> 
> data_path: /config/zigbee2mqtt
> 
> socat:
> 
>   enabled: false
> 
>   master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
> 
>   slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
> 
>   options: '-d -d'
> 
>   log: false
> 
> 
> 
> mqtt:
> 
>   server: mqtt://core-mosquitto:1883
> 
> serial:
> 
>   port: /dev/ttyACM0
> 
> 
> 
> And these is config.yaml in the zigbee2mqtt map
> 
> 
> 
> 
> 
> {
> 
>   "external_converters": [],
> 
>   "devices": [
> 
>     "devices.yaml"
> 
>   ],
> 
>   "groups": [
> 
>     "groups.yaml"
> 
>   ],
> 
>   "homeassistant": true,
> 
>   "permit_join": false,
> 
>   "mqtt": {
> 
>     "base_topic": "zigbee2mqtt",
> 
>     "server": "mqtt://core-mosquitto:1883",
> 
>     "user": "mqtt",
> 
>     "password": "XXXXXXXX"
> 
>   },
> 
>   "serial": {
> 
>     "port": "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2225559-if00",
> 
>     "adapter": "deconz"
> 
>   },
> 
>   "advanced": {
> 
>     "log_level": "info",
> 
>     "pan_id": 6754,
> 
>     "channel": 11,
> 
>     "network_key": [
> 
>       1,
> 
>       3,
> 
>       5,
> 
>       7,
> 
>       9,
> 
>       11,
> 
>       13,
> 
>       15,
> 
>       0,
> 
>       2,
> 
>       4,
> 
>       6,
> 
>       8,
> 
>       10,
> 
>       12,
> 
>       13
> 
>     ],
> 
>     "availability_blocklist": [],
> 
>     "availability_passlist": []
> 
>   },
> 
>   "device_options": {},
> 
>   "blocklist": [],
> 
>   "passlist": [],
> 
>   "queue": {},
> 
>   "frontend": {
> 
>     "port": 8099
> 
>   },
> 
>   "experimental": {},
> 
>   "availability": false
> 
> }
> 
> 
> 
> then i need to restore a backup from mosquitobroker.
> 
> And then restore the config in the configuration tab again as it was before the upgrade to 1.25.0-1 and restore it in the configuration tab to make it work again, otherwise my whole zigbee2mqtt is empty and all my devices are gone

Wauw, you do not change your config.yaml file! Only change the config in the addon configuration tab. Al other data is entered and stored automatically from within the Z2M GUI.

**Comment by mgiebels** [comment]
i didn't change config.yaml that was all these before the upgrade

{
  "external_converters": [],
  "devices": [
    "devices.yaml"
  ],
  "groups": [
    "groups.yaml"
  ],
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://core-mosquitto:1883",
    "user": "mqtt",
    "password": "XXXXXXXX"
  },
  "serial": {
    "port": "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2225559-if00",
    "adapter": "deconz"
  },
  "advanced": {
    "log_level": "info",
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blocklist": [],
    "availability_passlist": []
  },
  "device_options": {},
  "blocklist": [],
  "passlist": [],
  "queue": {},
  "frontend": {
    "port": 8099
  },
  "experimental": {},
  "availability": false

but it was always the same in my addon configuration tab.
And so I had now adjusted to what was above

data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

mqtt:
  server: mqtt://core-mosquitto:1883
serial:
  port: /dev/ttyACM0

So when this is in my configuration addon tab it doesn't work and I don't see any devices anymore.

**Comment by AbeltjeNL** [comment]
> "port": "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2225559-if00"

In your original config your port is: "port": "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2225559-if00".
Maybe you should change this in the current addon config.

**Comment by mgiebels** [comment]
Already tried but it doesn't help.
Have it now also in both /dev/ttyACM0
So in my config.yaml it's also there and in the config tab too.

Both are now the same again.
So in my configuration tab in the add on there is now the long config and then everything works

Because with the small config in the configuration tab it doesn't work for me unfortunately

**Comment by AbeltjeNL** [comment]
> Already tried but it doesn't help.
> 
> Have it now also in both /dev/ttyACM0
> 
> So in my config.yaml it's also there and in the config tab too.
> 
> 
> 
> Both are now the same again.
> 
> So in my configuration tab in the add on there is now the long config and then everything works
> 
> 
> 
> Because with the small config in the configuration tab it doesn't work for me unfortunately

Hmm.. And if you try this in the addon config?:

serial: /path to adapter
  adapter: deconz

https://www.zigbee2mqtt.io/guide/adapters/#recommended

**Comment by mgiebels** [comment]
Doesnt work!

in log is these

Zigbee2MQTT:info  2022-04-02 01:01:49: MQTT publish: topic 'homeassistant/device_automation/0x5c0272fffed9bf67/action_2_double/config', payload 'null'
Zigbee2MQTT:info  2022-04-02 01:01:49: MQTT publish: topic 'homeassistant/device_automation/0x5c0272fffed9bf67/action_3_double/config', payload 'null'
Zigbee2MQTT:info  2022-04-02 01:01:49: MQTT publish: topic 'homeassistant/device_automation/0x00158d00067c4034/action_single/config', payload 'null'
Zigbee2MQTT:info  2022-04-02 01:01:49: MQTT publish: topic 'homeassistant/device_automation/0x00158d00067c4034/click_single/config', payload 'null'
Zigbee2MQTT:info  2022-04-02 01:01:49: MQTT publish: topic 'homeassistant/device_automation/0x00158d00067c4034/action_double/config', payload 'null'

**Comment by AbeltjeNL** [comment]
> Doesnt work!
> 
> 
> 
> in log is these
> 
> 
> 
> Zigbee2MQTT:info  2022-04-02 01:01:49: MQTT publish: topic 'homeassistant/device_automation/0x5c0272fffed9bf67/action_2_double/config', payload 'null'
> 
> Zigbee2MQTT:info  2022-04-02 01:01:49: MQTT publish: topic 'homeassistant/device_automation/0x5c0272fffed9bf67/action_3_double/config', payload 'null'
> 
> Zigbee2MQTT:info  2022-04-02 01:01:49: MQTT publish: topic 'homeassistant/device_automation/0x00158d00067c4034/action_single/config', payload 'null'
> 
> Zigbee2MQTT:info  2022-04-02 01:01:49: MQTT publish: topic 'homeassistant/device_automation/0x00158d00067c4034/click_single/config', payload 'null'
> 
> Zigbee2MQTT:info  2022-04-02 01:01:49: MQTT publish: topic 'homeassistant/device_automation/0x00158d00067c4034/action_double/config', payload 'null'

Alright, with al due respect, I can't work with 'doesn't work'..
Please post the complete HA-addon config which is working and the complete config.yaml file which is working from /config/zigbee2mqtt.

In

**Comment by mgiebels** [comment]
HA adon config:
data_path: /share/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
  restartdelay: 1
  initialdelay: 1
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: mqtt
  password: XXXXXXXX
serial:
  port: /dev/ttyACM0
  adapter: deconz
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  ikea_ota_use_test_url: true
  lpog_level: info
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
availability: false


And config.yaml 

external_converters: []
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: mqtt
  password: Vernes_5213!
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/ttyACM0
  adapter: deconz
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false

**Comment by AbeltjeNL** [comment]
Thanks mate. Gonna check this tomorrow in the afternoon to (hopefully) help you out. I'm now gonna take a nap.

**Comment by groenmarsmannetje** [comment]
Could somebody please update the documentation page of this addon. I think it shows all kind of configurations that no longer exists and the configuration that should be done after the breaking change is not documented at all. What a strange release.

**Comment by mgiebels** [comment]
> Thanks mate. Gonna check this tomorrow in the afternoon to (hopefully) help you out. I'm now gonna take a nap.

Mate i found the problem.
if you reset to default values, there will be a wrong data_path with me. (I'm running homeassistant on a nuc and homeassistant is on it standalone no docker)

Default is: data_path: /config/zigbee2mqtt
But in my old tab it said: data_path: /share/zigbee2mqtt

Now I have modified the data_path like :

data_path: /share/zigbee2mqtt
socat:
   enabled: false
   master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
   slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
   options: '-d -d'
   log: false

mqtt:
   server: mqtt://core-mosquitto:1883
serial:
   port: /dev/ttyACM0

And now it works! :D

**Comment by AbeltjeNL** [comment]
> > Thanks mate. Gonna check this tomorrow in the afternoon to (hopefully) help you out. I'm now gonna take a nap.
> 
> 
> 
> Mate i found the problem.
> 
> if you reset to default values, there will be a wrong data_path with me. (I'm running homeassistant on a nuc and homeassistant is on it standalone no docker)
> 
> 
> 
> Default is: data_path: /config/zigbee2mqtt
> 
> But in my old tab it said: data_path: /share/zigbee2mqtt
> 
> 
> 
> Now I have modified the data_path like :
> 
> 
> 
> data_path: /share/zigbee2mqtt
> 
> socat:
> 
>    enabled: false
> 
>    master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
> 
>    slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
> 
>    options: '-d -d'
> 
>    log: false
> 
> 
> 
> mqtt:
> 
>    server: mqtt://core-mosquitto:1883
> 
> serial:
> 
>    port: /dev/ttyACM0
> 
> 
> 
> And now it works! :D

Good to hear that you found a fix! 😃
