### ISSUE TITLE
Update documentation page of addon after breaking change

### ISSUE THREAD

**Issue by groenmarsmannetje** [zigbee2mqtt/hassio-zigbee2mqtt#312]
Could somebody please update the documentation page of this addon. I think it shows all kind of configurations that no longer exists and the (minimal) configuration that should be done after the breaking change is not documented at all. This is very confusing for your users. Thank you!

**Comment by smulle48** [comment]
@groenmarsmannetje You are free to help updating the documentation :-)

![Skærmbillede 2022-04-04 kl  17 51 20](https://user-images.githubusercontent.com/24297824/161583094-391a8858-6e0c-4cb6-a08e-57185d918962.png)

**Comment by groenmarsmannetje** [comment]
Whahaha now you have done all this effort... while you could have opened the document page and described it there...

**Comment by smulle48** [comment]
> Whahaha now you have done all this effort... while at the same time you could have opened the document page and described it there...

https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/pull/318 ;-)
