### ISSUE TITLE
Entity 'Termogolovka_komnata' is unknown

### ISSUE THREAD

**Issue by AntoxaSa** [zigbee2mqtt/hassio-zigbee2mqtt#314]
![zigbee](https://user-images.githubusercontent.com/71827946/161395780-ee48ac49-d542-4faa-b199-a42946f9ccce.jpg)

deleted the device.But a red error appears periodically in the interface.How to clean? remove this entity that has already been deleted.

**Comment by Sashik259** [comment]
Watch your logs. Possibly it’s used by some automation
