### ISSUE TITLE
Unsupported Radiator Valve TS0601 ( Moes Zigbee Radiator Valve)

### ISSUE THREAD

**Issue by Gagge89** [zigbee2mqtt/hassio-zigbee2mqtt#328]
Hello, I have chosen zigbee2mqtt mainly to put the thermostatic valves of the Moes model TS0601 directly in my Home Assistant (of which I am attaching the image) and I find that while doing the scan the device is detected but it does not connect me as Manifacturer errors come out Unsupported. Now I have 5 thermostatic valves that I can't get to work. Can you put them in the code so that they are displayed to me and I can use them through zigbee2mqtt?
My Dongle is the Sonoff Zigbee USB Dongle.
Thanks

P.S : Small note. When I get the series of errors in red at the bottom right the device is called TZE200 while then in the model it is called TS0601

EXAMPLE OF VALVES
![Valve MOES](https://user-images.githubusercontent.com/57711468/164890745-6a782569-6fef-4a91-ab0b-f5ac87067bf5.JPG)

ERROR MODEL UNSUPPORTED
![2](https://user-images.githubusercontent.com/57711468/164890775-d17941ee-11cb-405d-821d-a4fe0dd423c2.JPG)

ERROR RED IN HOME ASSISTANT ZIGBEE2MQTT PAGE
![error](https://user-images.githubusercontent.com/57711468/164890872-b4f39a87-b2f1-423b-a733-e6754bee0027.JPG)

I have the last version of Zigbee2Mqtt ( Current version: 1.18.1-1 )

Versione | core-2022.2.8
-- | --
Tipo di installazione | Home Assistant OS
Sviluppo | false
Supervisore | true
Docker | true
Utente | root
Ambiente virtuale | false
Versione Python | 3.9.7
Famiglia del sistema operativo | Linux
Versione del sistema operativo | 5.10.92-v8
Architettura della CPU | aarch64
Fuso orario | Europe/Rome

Thanks

**Comment by behindthebeard** [comment]
Hi!

I am just a user so feel free to judge my comments based on that:

- latest version is `1.25.0`, **not** `1.18.1-1`, so try to update first
- I think I have the same radiator valve, and it is working, but I am using [the edge version](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/tree/master/zigbee2mqtt-edge) of `Zigbee2MQTT`:

![ts0601](https://user-images.githubusercontent.com/16793376/165115320-66e18a42-25d3-4246-857d-f38c470dcda3.jpg)

Hope this helps.
