### ISSUE TITLE
Transition does not work for Lonsonho QS-Zigbee-D02-TRIAC-2C-LN

### ISSUE THREAD

**Issue by IKukushkin7** [zigbee2mqtt/hassio-zigbee2mqtt#329]
hello, i have a problem with the device transition (https://www.zigbee2mqtt.io/devices/QS-Zigbee-D02-TRIAC-2C-LN.html#lonsonho-qs-zigbee-d02-triac-2c-ln), when i turn on the light with transition it turns on instantly.

zigbee2mqtt@1.24.0 -1 

Core: core-2022.3.0
Supervisor: supervisor-2022.04.0
Operating System: Debian GNU/Linux 11 (bullseye)
```
Logs:
```
No converter available for 'transition' (20)
```

**Comment by bbccdd** [comment]
Related to https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/356 ?
