### ISSUE TITLE
Home Assistant frontend not working on 1.25.1

### ISSUE THREAD

**Issue by andreas-git** [zigbee2mqtt/hassio-zigbee2mqtt#333]
Hi, 

after updating to 1.25.1 is frontend on Home Assistant not availible but z2m works behind.
Rolling back to 1.25.0-1 seems fine .
Im running HA on RPi 4 with the prebuild Image.

`
Frontend-Version: 20220405.0 - latest
`

## System Health

version | core-2022.4.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v8
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.9
disk_total | 58.9 GB
disk_used | 4.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | eWeLink Smart Home (1.2.4), File editor (5.3.3), Mosquitto broker (6.0.2), Terminal & SSH (9.3.0), Zigbee2mqtt (1.25.1-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

My /config/zigbee2mqtt/configuration.yaml

`
homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
   #password:********
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: tcp://192.168.178.23:8888
  adapter: ezsp
  baudrate: 115200
  rtscts: true
frontend:
  port: 8099
permit_join: true
devices:
  '0x847127fffedd1a9d':
    friendly_name: '0x847127fffedd1a9d'
  '0xcc86ecfffe951311':
    friendly_name: '0xcc86ecfffe951311'
  '0xcc86ecfffe9550ba':
    friendly_name: '0xcc86ecfffe9550ba'
  '0x00158d0002ffeaa3':
    friendly_name: 0x00158d0002ffeaa3 Tint Remote
    legacy: false
  '0x804b50fffe052b4e':
    friendly_name: '0x804b50fffe052b4e'
advanced:
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  channel: 15
  network_key: *******
groups: {}
`

Any Ideas ?

Best Regards

**Comment by hhromic** [comment]
Same issue here. Seems to be a web-packaging problem as the following resources are no longer found:
```
<script defer="defer" src="scripts/vendor.f3635c6dc09aacfa6bae.js"></script>
<script defer="defer" src="main.e47e35f1394ea10dd81d.js"></script>
```

**Comment by snowyu** [comment]
workaround: uninstall and install again.

**Comment by ippo112** [comment]
Same problem for me, Frontend doesn't appear on HA after upgrading to 1.25.1:


Versione | core-2022.4.7
Tipo di installazione | Home Assistant OS
Sviluppo | false
Supervisore | true
Docker | true
Utente | root
Ambiente virtuale | false
Versione Python | 3.9.9
Famiglia del sistema operativo | Linux
Versione del sistema operativo | 5.10.108
Architettura della CPU | x86_64
Fuso orario | Europe/Rome

**Comment by Koenkk** [comment]
Could this be some caching problem? Does a CTRL+F5 fix it?

**Comment by ippo112** [comment]
> Could this be some caching problem? (CC: @nurikk) Does a CTRL+F5 fix it?

no, I try to clear chache, but doesn't fix it. 
I try also to restart HA OS , but nothing

**Comment by hrosak88** [comment]
The same problem here. On my phone works GUI normal, but on my tablet only blank page.

**Comment by navycrow** [comment]
i confirm @snowyu workaround. uninstall / install resolves the problem

**Comment by zorruno** [comment]
Same issue, rolled back to 1.25.0-1 from backup

## System Health

version | core-2022.4.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.108
arch | x86_64
timezone | Pacific/Auckland

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.24.5
Stage | running
Available Repositories | 1094
Downloaded Repositories | 34

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.9
disk_total | 116.7 GB
disk_used | 45.2 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.10.0), motionEye (0.18.0), Studio Code Server (5.0.1), Spotify Connect (0.11.0), Terminal & SSH (9.3.0), Grocy (0.17.0), AppDaemon (0.8.2), Zigbee2mqtt (1.25.0-1), Node-RED (11.1.1), Mosquitto broker (6.0.2), ESPHome (2022.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 18
views | 7
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by ippo112** [comment]
now working, 
problably was a chache problem of my browser ....

**Comment by avdgaag1984** [comment]
The same problem here, works not on my phone and laptop. Clear the cache, but the problem is not fixed

**Comment by hhromic** [comment]
It fixed itself for me too today. Maybe Home Assistant's frontend server is caching too aggressively.

**Comment by nurikk** [comment]
> 

it's definitely some aggressive caching, `zigbee2mqtt-frontend@0.6.83` doesn't contain this files in package or index.html
tarball can be found here:
`https://registry.npmjs.org/zigbee2mqtt-frontend/-/zigbee2mqtt-frontend-0.6.83.tgz`

**Comment by Lynetk** [comment]
I managed to get the frontend to show in Chrome by using Developer Tools -> Network -> Disable cache

**Comment by pblanar** [comment]
I have the same problem. I restored 1.25.0.1 from backup last night and tried again this morning with no success. 

Will my devices need to be paired anew if I uninstall and reinstall?

**Comment by ScottG489** [comment]
Fixed for me (Chrome) by opening **dev tools**, right clicking on the **reload button**, and selecting **"Empty Cache and Hard Reload"**

**Comment by Cyril-E** [comment]
I open in a other web browser (safari) and they work properly

**Comment by keithr59** [comment]
Fixed for me as follows:

**Opera** by opening **Update & Recovery**, selecting **Recover** then **Keep my data and only reset Opera Settings**

**Android** by uninstalling and re-installing the **Home Assistant** app

**Comment by Tanjohnson99** [comment]
> Fixed for me (Chrome) by opening **dev tools**, right clicking on the **reload button**, and selecting **"Empty Cache and Hard Reload"**

Working for me like this ! Thanks

**Comment by marcbritten** [comment]
> **Android** by uninstalling and re-installing the **Home Assistant** app

Just go into app settings and clear the cache, no need to uninstall.

**Comment by keithr59** [comment]
> > **Android** by uninstalling and re-installing the **Home Assistant** app
> 
> Just go into app settings and clear the cache, no need to uninstall.

Did that. Didn't work so uninstall/reinstall was next logical step

**Comment by Clasper101** [comment]
> Fixed for me (Chrome) by opening **dev tools**, right clicking on the **reload button**, and selecting **"Empty Cache and Hard Reload"**

This worked on my pc, now to sort out my phone. Forced stop and uninstall worked on the phone.

**Comment by Feedy88** [comment]
Same issue here. Manually deleting Browser-Cache fixed the problem for me.

**Comment by dominicusmento** [comment]
> > **Android** by uninstalling and re-installing the **Home Assistant** app
> 
> Just go into app settings and clear the cache, no need to uninstall.

Worked for me.. Closed the app from 'recent apps', cleared cache, run the app again.. and works immediately..

**Comment by michalw2-alt** [comment]
> > **Android** by uninstalling and re-installing the **Home Assistant** app
> 
> Just go into app settings and clear the cache, no need to uninstall.

Do you mean to clear Home Assistant cache in Development Tools?

**Comment by michalw2-alt** [comment]
I think I have found a problem.
Whenever I do local curl command on port 8099 while being connected to HomeAssistant with SSH I see proper response.

[core-ssh ~]$ curl http://localhost:8099 -I
HTTP/1.1 200 OK
server: ttyd/1.6.3-3e37e33 (libwebsockets/4.2.1-v4.2.1)
content-type: text/html
content-length: 498757

However when I try to open connection from browser on my client PC - I'm getting TCP Reset from my TCP SYN.
I'm wondering what is reseting connection - process listening on port 8099 (tied) or some sort of internal firewall?

[core-ssh ~]$ netstat -pan
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8099            0.0.0.0:*               LISTEN      138/ttyd
