### ISSUE TITLE
Aqara roller shade companion E1: MAC transaction expired 

### ISSUE THREAD

**Issue by nitro41992** [zigbee2mqtt/hassio-zigbee2mqtt#340]
**Description of problem:**
I setup the Aqara roller shade companion E1 ([ZNJLBL01LM](https://www.zigbee2mqtt.io/devices/ZNJLBL01LM.html#xiaomi-znjlbl01lm)) on Z2M a couple days ago and initially everything seemed to be working properly. More recently, every now and then, the roller shade stops working with the error (Data request failed with error: 'MAC transaction expired' (240))'

I have other devices using Z2M that are working without any issues so the problem seems to be isolated only to this device. Also to note, after a while, the device works again as intended regardless of the errors still showing up in the Z2M logs.

Using the Sonoff Zigbee 3.0 with the firmware upgrade and attached via a USB extension cable.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
zigbee2mqtt@1.25.1-1
``` 

**Running platform (details from Suypervisor > System)**
```
Core: core-2022.5.2 
Supervisor: supervisor-2022.05.2 
Operating System: HassOS 7.6
```

**Your logs from Home Assistant Supervisor**
```
Zigbee2MQTT:error 2022-05-10 16:55:53: Error: Read [REDACTED By ME] /1
genAnalogOutput(["presentValue{"sendWhen":"immediate","timeout":10000,"
disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,
"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,
"transactionSequenceNumber":null,"writeUndiv":false}) failed
(Data request failed with error: 'MAC transaction expired' (240))

Zigbee2MQTT:error 2022-05-10 16:56:21: Publish 'set' 'state' to 'window_roller_shade' failed:
'Error: Write [REDACTED By ME] /1 genAnalogOutput({"85":{"value":0,"type":57}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery"
:false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,
"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed
(Data request failed with error: 'MAC transaction expired' (240))'
```

**Comment by nitro41992** [comment]
I realized recently that this issue only happens sporadically from my phone using the companion app.

When it does, I seem to be able to still control it via Home Assistant on my computer which is connected via Ethernet. I'm assuming it has something to do with the IP so I setup a static IP using the DHCP server. Not sure if this is the solution though.

**Comment by lluisd** [comment]
I have the same problem and I don't use the companion app. why is happening?
