### ISSUE TITLE
Question : How to check edge version running vs latest one available ?

### ISSUE THREAD

**Issue by klona** [zigbee2mqtt/hassio-zigbee2mqtt#347]
Hi,
at first a huge thanks for this wonderful piece of software that you deliver to community. A huge work just shared with others and with a very great level of  regular improovements/bug fixes and support. This is just amazing.

I feel dumb with my question, but I recently moved to edge version and I wonder where I can find version running at present on my system and latest version available ?
I spent some time checking in HA where I can find this info, and ... can't. 
I am quite sure it's somewhere, but just cant find where..

TIA,
/Klona

**Comment by DavyRoswinkel** [comment]
In the UI click settings ---> about. There you see: 
Zigbee2MQTT version 1.25.1-dev commit: a1db076 ( for example, remember in this case a1db076)

Then see https://github.com/Koenkk/zigbee2mqtt/commits/dev
There you see the latest version...

But this is how I check it ( if easier ways are possible, please let me know)

**Comment by klona** [comment]
Hi, sorry i forget to answer. Thanks for the tip, it's great.
Should be nice to have version in an attribute somewhere, but it's egde, not supposed to follow every update..
