### ISSUE TITLE
[Bug]: Zigbee2mqtt edge does not start with error: "s6-overlay-suexec: fatal: can only run as pid 1"

### ISSUE THREAD

**Issue by rosch100** [zigbee2mqtt/hassio-zigbee2mqtt#349]
### Description of the issue

On Home Assistant Core 2022.6.4, Zigbee2mqtt edge reports an error trying to start: 
`6-overlay-suexec: fatal: can only run as pid 1`

This bug report is marked as closed, but it either re-appeared or is not resolved:
[335](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/335)

### Addon version

edge from 9. June 2022

### Platform

core-2022.6.4
Home Assistant OS 8.1
supervisor-2022.05.3

**Comment by Koenkk** [comment]
Is this with the latest version of the edge addon? You need to uninstall and install it again to update to the latest

**Comment by rosch100** [comment]
Yes, latest version. To make sure, just uninstalled, restarted HassIO and re-installed the add-on.
The error message ist the same.

**Comment by Koenkk** [comment]
@[mdegat01](https://github.com/mdegat01) do you have an idea how this can happen? AFAIK edge and stable should be the same now

**Comment by itpcss** [comment]
I have a similar problem "s6-overlay-suexec: fatal: can only run as pid 1"  reinstalling the addon doesn't help.
On the platform raspberry pi 4 raspbian in docker HA+zigbee2mqtt EDGE works.
On the platform x86x64 with ubuntu 20.04  in docker HA+zigbee2mqtt EDGE does not work.

Tell me what else can I do or is it related to the addon? and wait for update?

**Comment by smpillai11** [comment]
my zigbee2mqtt was not updating which was causing this issue. Update worked after adding repo to add-on store. Link below helped me

https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/134

**Comment by Mecallie** [comment]
Darn @smpillai11 that was it!

I was still using https://github.com/danielwelch/hassio-zigbee2mqtt (which was still updating?!?) << WRONG
You need to use: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt .

Here's what I did to fix it:

1. Remove BOTH Z2M addons.
2. Reboot HA
3. Noticed the addons where still there and the normal version was still yellow.
4. Installed the normal Z2M addon again
5. Removed it AGAIN, both Z2M addons now gone.
6. After that I was able to remove the danielwelch repo without a reboot.
7. Add repo https://github.com/zigbee2mqtt/hassio-zigbee2mqtt .
8. Install Z2M edge (or normal version): VICTORY!

Man, never noticed I was still using that old repo...

**Comment by Koenkk** [comment]
Great, the legacy addon indeed has this issue
