### ISSUE TITLE
Zigbee2MQTT is not sending the transition time in MQTT message

### ISSUE THREAD

**Issue by giulianofichera** [zigbee2mqtt/hassio-zigbee2mqtt#356]
### Description of the issue

Hi, I'm trying to set a transition time as I used to have in the Philips Hue Hub. Reading the documentation, I stumbled upon many ways to add this configuration, but none of them seem to work.

I added `transition: 4` in every way possible:
- In devices.yaml as a [default value](https://www.zigbee2mqtt.io/guide/configuration/devices-groups.html#specific-device-options):
```
device_options:  
  transition: 4
```
- In devices.yaml as a single light option:
```
'0x0017880103fd3b4f':  
    friendly_name: Roof 2   
    transition: 4
```
    
- And in configuration.yaml:
`  "device_options": {"transition": 4},`

Yet when I examine the message through MQTT Explorer, there is no transition argument:
`{"state": "ON", "brightness": 254}`

The light in question is a hue bulb that [supports transition](https://www.zigbee2mqtt.io/devices/9290012573A.html#philips-9290012573a), as when I manually send `{"state": "ON", "brightness": 254,"transition":5}` the bulb transitions to the new brightness. It also transitioned correctly with the hue hub I previously used

Zigbee2MQTT is missing the transition argument when sending the message.

I would appreciate any help and can provide logs if needed, thank you!

### Addon version

1.18.1-1

### Platform

Core: core-2022.6.7
Supervisor: supervisor-2022.05.3
Operating System: Linux Mint 20.2

**Comment by Koenkk** [comment]
- You are using a very old z2m version 
If you are still on 1.18.1 check first point of https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0
- When `transition` is specified in the config, it will not be send over MQTT but will directly be applied (so internally it will convert `{"state": "ON", "brightness": 254}` to `{"state": "ON", "brightness": 254, "transition": 5}`

**Comment by giulianofichera** [comment]
@Koenkk I totally missed the repo change! I switched the repo, reinstalled the addon and configured using `device_options` in zigbee2mqtt configuration.yaml and everything is working great.

Sorry for the issue and thank you very much!

**Comment by bbccdd** [comment]
Sorry to re-open this issue. 

I still can't get transition settings to work using zigbee groups. Please advice!

It works when adding a transition value in the ui on device specific pages, but there is no such option for zigbee groups in the zigbee2mqtt webinterface and setting the device_option, option does not seem to be respected.
![image](https://user-images.githubusercontent.com/29344993/221829654-5b1de9c1-f0cd-4bb0-b16a-d1184aaeafd1.png)

Setup details:
Using Zigbee2MQTT stable, version: 1.30.1-1 from the official home assistant repo: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/

/config/zigbee2mqtt/configuration.yaml
homeassistant: true
device_options:
  transition: 0.4
![image](https://user-images.githubusercontent.com/29344993/221827884-32411d92-b959-4f81-ad53-7dba2424ca81.png)

Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest
