### ISSUE TITLE
Set Sensitivity Fail

### ISSUE THREAD

**Issue by drako86** [zigbee2mqtt/hassio-zigbee2mqtt#358]
### Description of the issue

Hello, I have several Xiaomi vibration sensors, but they all give error when I try to set the sensitivity

### Addon version

V 1.26.0-1

### Platform

OS: 8.2
Core : 2022.6.7
Supervisor : 2022.6.2
Coordinator : zStack3x0
Firmware : 20220219

### Logs of the issue (if applicable)

 2022-07-06 16:58:35Publish 'set' 'sensitivity' to 'Vibrazione_Tapparella_Porta_Finestra_Sala' failed: 'Error: Write 0x00158d0003d23063/1 genBasic({"65293":{"value":11,"type":32}}, {"sendWhen":"immediate","timeout":35000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 8668 - 1 - 7 - 0 - 4 after 35000ms)'

**Comment by Koenkk** [comment]
Make sure to wake them up right before sending the command (press a button on the sensors)

**Comment by drako86** [comment]
> Make sure to wake them up right before sending the command (press a button on the sensors)

Hello, I tried both to press the button (it is detected by the interface) and then change the sensitivity, and change the sensitivity and then press the button ... the error remains ... other ideas ?

**Comment by Koenkk** [comment]
Then it may be that the router it is connected to doesn't relay the message correctly. Repair the device very close to the coordinator such that it has a direct connection with it and try again.

**Comment by drako86** [comment]
> Then it may be that the router it is connected to doesn't relay the message correctly. Repair the device very close to the coordinator such that it has a direct connection with it and try again.

Ok, turning off the repeaters and pressing the button about 3/4 times (with 1 second of scrap) they took the configuration...thank you
