### ISSUE TITLE
Wont start - Error: Cannot find module '../lib/exposes'

### ISSUE THREAD

**Issue by lcsneil** [zigbee2mqtt/hassio-zigbee2mqtt#362]
### Description of the issue

Simply wont start - throw's errors. 
THis just suddenly started happening last night without provocation. Originally on a 
_usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E3352F-if00_

So I tried swapping to the Sonoff co-ordinator. Made no difference.

### Addon version

Current version: 1.26.0-1 

### Platform

Home Assistant Core 2022.7.4
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.0 - latest

### Logs of the issue (if applicable)

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/socat.sh
[16:15:20] INFO: Socat not enabled, marking service as down
cont-init: info: /etc/cont-init.d/socat.sh exited 0
cont-init: info: running /etc/cont-init.d/zigbee2mqtt.sh
cont-init: info: /etc/cont-init.d/zigbee2mqtt.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun socat (no readiness notification)
services-up: info: copying legacy longrun zigbee2mqtt (no readiness notification)
[16:15:23] INFO: Handing over control to Zigbee2MQTT Core ...
> zigbee2mqtt@1.26.0 start
> node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module '../lib/exposes'
Require stack:
- /app/dist/util/utils.js
- /app/dist/util/settings.js
- /app/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /app/dist/util/externally-loaded.js:1:17
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)
    at Object.runInNewContext (node:vm:298:38)
    at loadModuleFromText (/app/lib/util/utils.ts:148:8)
    at loadModuleFromFile (/app/lib/util/utils.ts:155:12)
[16:15:31] INFO: Handing over control to Zigbee2MQTT Core ...
> zigbee2mqtt@1.26.0 start
> node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module '../lib/exposes'
Require stack:
- /app/dist/util/utils.js
- /app/dist/util/settings.js
- /app/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /app/dist/util/externally-loaded.js:1:17
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)
    at Object.runInNewContext (node:vm:298:38)
    at loadModuleFromText (/app/lib/util/utils.ts:148:8)
    at loadModuleFromFile (/app/lib/util/utils.ts:155:12)

**configuration.yaml**

external_converters:
  - tuya.js
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  user: addons
  password: "redacted"
  server: mqtt://core-mosquitto:1883
serial:
  port: /dev/ttyUSB0
  disable_led: true
  adapter: auto
  rtscts: false
advanced:
  log_level: debug
  pan_id: 6754
  channel: 26
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  ikea_ota_use_test_url: false
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: true

**Hardware info** 

subsystem: vc-mem
  sysfs: /sys/devices/virtual/vc-mem/vc-mem
- attributes:
    BUSNUM: "001"
    DEVNAME: /dev/bus/usb/001/019
    DEVNUM: "019"
    DEVPATH: /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4
    DEVTYPE: usb_device
    DRIVER: usb
    ID_BUS: usb
    ID_FOR_SEAT: usb-platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_4
    ID_MODEL: Sonoff_Zigbee_3.0_USB_Dongle_Plus
    ID_MODEL_ENC: Sonoff\x20Zigbee\x203.0\x20USB\x20Dongle\x20Plus
    ID_MODEL_ID: ea60
    ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4
    ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_4
    ID_REVISION: "0100"
    ID_SERIAL: ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_7ed8b1392186ec11b2105b1719c2d21c
    ID_SERIAL_SHORT: 7ed8b1392186ec11b2105b1719c2d21c
    ID_USB_INTERFACES: ':ff0000:'
    ID_VENDOR: ITead
    ID_VENDOR_ENC: ITead
    ID_VENDOR_ID: 10c4
    MAJOR: "189"
    MINOR: "18"
    PRODUCT: 10c4/ea60/100
    SUBSYSTEM: usb
    TAGS: ':seat:'
    TYPE: 0/0/0
    USEC_INITIALIZED: "68459344891"
  by_id: null
  children:
  - /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.0
  - /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.0/gpio/gpiochip497
  - /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.0/gpiochip2
  - /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0
  - /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0/tty/ttyUSB0
  dev_path: /dev/bus/usb/001/019
  name: 1-1.4
  subsystem: usb
  sysfs: /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4
- attributes:
    DEVNAME: /dev/gpiochip2
    DEVPATH: /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.0/gpiochip2
    DRIVER: gpio_stub_drv
    MAJOR: "254"
    MINOR: "2"
    SUBSYSTEM: gpio
  by_id: null
  children: []
  dev_path: /dev/gpiochip2
  name: gpiochip2
  subsystem: gpio
  sysfs: /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.0/gpiochip2
- attributes:
    DEVLINKS: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_7ed8b1392186ec11b2105b1719c2d21c-if00-port0
      /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0-port0
    DEVNAME: /dev/ttyUSB0
    DEVPATH: /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0/tty/ttyUSB0
    ID_BUS: usb
    ID_MODEL: Sonoff_Zigbee_3.0_USB_Dongle_Plus
    ID_MODEL_ENC: Sonoff\x20Zigbee\x203.0\x20USB\x20Dongle\x20Plus
    ID_MODEL_ID: ea60
    ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0
    ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_4_1_0
    ID_REVISION: "0100"
    ID_SERIAL: ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_7ed8b1392186ec11b2105b1719c2d21c
    ID_SERIAL_SHORT: 7ed8b1392186ec11b2105b1719c2d21c
    ID_TYPE: generic
    ID_USB_DRIVER: cp210x
    ID_USB_INTERFACE_NUM: "00"
    ID_USB_INTERFACES: ':ff0000:'
    ID_VENDOR: ITead
    ID_VENDOR_ENC: ITead
    ID_VENDOR_ID: 10c4
    MAJOR: "188"
    MINOR: "0"
    SUBSYSTEM: tty
    TAGS: ':systemd:'
    USEC_INITIALIZED: "68459402963"
  by_id: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_7ed8b1392186ec11b2105b1719c2d21c-if00-port0
  children: []
  dev_path: /dev/ttyUSB0
  name: ttyUSB0
  subsystem: tty
  sysfs: /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0/tty/ttyUSB0

**Comment by Koenkk** [comment]
Try removing all your external converters, the error is in there.

**Comment by lcsneil** [comment]
Wow - thanks for the quick response.

I have removed the 
External convertors:
  -tuya.js

And it has now started (I think I had a previous problem with the Texas co-ordinator as well). So sticking to the Sonoff Dongle Plus. 
Now waiting for all the devices to come 'online' as they are all showing off line. Think I might have to re-pair them
