### ISSUE TITLE
Configuration problems

### ISSUE THREAD

**Issue by Jens-Wymeersch** [zigbee2mqtt/hassio-zigbee2mqtt#364]
### Description of the issue

I'm trying to get an external converter to work for one of my devices. 
When I look at the UI - I only have the following options : socat, mqtt and serial. When you go to edit in Yaml, you see the configuration file, but this one is different from the one found in the directory.

### Addon version

v1.26.0-1

### Platform

core-2022.7.5
supervisor-2022.07.0
Home Assistant OS 8.2

**Comment by PandaUnit-TWL** [comment]
I've got the same issue. When trying to save/update the config yaml through the UI it errors out without saving/updating. I have no idea what I am doing but I was able to get Z2Mqtt started. Even so I haven't tried connecting anything yet.

To get past the startup errors from the log files I edited the config yaml directly (while Z2M was stopped) instead using [this](https://www.zigbee2mqtt.io/guide/configuration/) and [this](https://www.zigbee2mqtt.io/guide/configuration/adapter-settings.html#adapter-settings) and added these lines: 

```
permit_join: true
serial:
  port: /dev/serial/by-id/**YOURUSBIDINFOHERE**
Will run frontend on port 8080
frontend: true
```

Find your /dev/serial/by-id/XXXXXXX from CLI with "ha hardware info" or through the browser UI. Once I added the right serial path and started up Z2M the webpage worked and my log looked like this:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/socat.sh
[11:18:27] INFO: Socat not enabled, marking service as down
cont-init: info: /etc/cont-init.d/socat.sh exited 0
cont-init: info: running /etc/cont-init.d/zigbee2mqtt.sh
cont-init: info: /etc/cont-init.d/zigbee2mqtt.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun socat (no readiness notification)
services-up: info: copying legacy longrun zigbee2mqtt (no readiness notification)
[11:18:28] INFO: Handing over control to Zigbee2MQTT Core ...
> zigbee2mqtt@1.26.0 start
> node index.js
Zigbee2MQTT:info  2022-07-31 11:18:33: Logging to console and directory: '/config/zigbee2mqtt/log/2022-07-31.11-18-33' filename: log.txt
Zigbee2MQTT:info  2022-07-31 11:18:34: Starting Zigbee2MQTT version 1.26.0 (commit #unknown)
Zigbee2MQTT:info  2022-07-31 11:18:34: Starting zigbee-herdsman (0.14.40)
Zigbee2MQTT:info  2022-07-31 11:18:53: zigbee-herdsman started (reset)
Zigbee2MQTT:info  2022-07-31 11:18:53: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20220219,"transportrev":2},"type":"zStack3x0"}'
Zigbee2MQTT:info  2022-07-31 11:18:53: Currently 0 devices are joined:
Zigbee2MQTT:warn  2022-07-31 11:18:53: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2022-07-31 11:18:53: Allowing new devices to join.
Zigbee2MQTT:warn  2022-07-31 11:18:53: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2022-07-31 11:18:53: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2022-07-31 11:18:53: Connecting to MQTT server at mqtt://core-mosquitto:1883
Zigbee2MQTT:info  2022-07-31 11:18:54: Connected to MQTT server
Zigbee2MQTT:info  2022-07-31 11:18:54: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"online"}'
Zigbee2MQTT:info  2022-07-31 11:18:54: Started frontend on port 0.0.0.0:8099
Zigbee2MQTT:info  2022-07-31 11:18:54: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"online"}'
```

**Comment by PandaUnit-TWL** [comment]
I see you got past this issue. How did you go about it?

**Comment by Jens-Wymeersch** [comment]
@PandaUnit-TWL I've set up a clean test environment and did the tests again. There is still a difference btw the UI and actually configuration.yaml file found in the MQTT directory. As i'm trying to add new capabilities, the impact is minimal, but I would like to get this sorted one of these days.

**Comment by MDSDM** [comment]
Same issue here. Tried doing changes via:
- Zigbee2MQTT UI
- SSH
- Samba

No changes seems to affect. Only the Add-On seems to work.
