### ISSUE TITLE
Battery symbol shows full while % is very low

### ISSUE THREAD

**Issue by bverkron** [zigbee2mqtt/hassio-zigbee2mqtt#367]
### Description of the issue

Several devices currently have a very low battery (all < 20%) and are flashing but most of them still show the battery full icon which contradicts it status.

This screenshot was taken mid-blink (so they icons show slightly transparent) with the column shorted by battery %. So the one with the tool tip at the top is the highest of all of them. The rest below are 15% or lower, going all the way down to last one which is 11%. That is the only one that shows a low / empty battery symbol

![image](https://user-images.githubusercontent.com/19174503/182048594-747d672f-004a-400f-bd6e-964f81e47ba7.png)

### Addon version

1.26.0-1

### Platform

Version | core-2022.7.7
Host Operating System | Home Assistant OS 8.4
Supervisor Version | supervisor-2022.07.0

### Logs of the issue (if applicable)

n/a

**Comment by Koenkk** [comment]
Please create issues related to the frontend here: https://github.com/nurikk/zigbee2mqtt-frontend/issues

**Comment by bverkron** [comment]
My apologies. I was navigating the front end GitHub issues earlier (and that's where I intended to submit it) but must have followed a path the get back here before submitting the issue.
