### ISSUE TITLE
Homeassistant Addon files seem not available on github

### ISSUE THREAD

**Issue by RVC69** [zigbee2mqtt/hassio-zigbee2mqtt#369]
### Description of the issue

Only 6 files found in folder ?
![image](https://user-images.githubusercontent.com/36585182/184367656-bd46b8e5-c57b-4d27-a26f-ae2d7066e69c.png)

### Addon version

v1.22.1

### Platform

?

**Comment by Koenkk** [comment]
It downloads z2m from the official z2m repo during build: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/d1c4a1e6d77455cdc4dbefef967ed1c4006e3b83/common/Dockerfile#L19
