### ISSUE TITLE
Update icons not shown anymore in GUI

### ISSUE THREAD

**Issue by jd1900** [zigbee2mqtt/hassio-zigbee2mqtt#37]
After updating from 1.17 to latest (1.17.1-4) the update icons in the GUI.

This is shown now:
![image](https://user-images.githubusercontent.com/63632981/108598694-5d6eeb80-738f-11eb-805a-4a8f5d0dc9bc.png)

For this device with this state:
![image](https://user-images.githubusercontent.com/63632981/108598698-68298080-738f-11eb-8639-a84db8b16cac.png)

So now it is now possible to update from GUI.

**Comment by ciotlosm** [comment]
Maybe try 1.18.1-1 and see how that behaves.
