### ISSUE TITLE
Unknown option 'base_topic' for Zigbee2MQTT

### ISSUE THREAD

**Issue by RaptorPR443** [zigbee2mqtt/hassio-zigbee2mqtt#371]
### Description of the issue

tons of warning about unknown option called base_topic every 5 minutes.

### Addon version

1.27.0-1

### Platform

Home Assistant 2022.8.4
Supervisor 2022.08.3
Operating System 8.4

### Logs of the issue (if applicable)

22-08-17 19:34:49 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-08-17 19:39:57 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-08-17 19:45:05 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-08-17 19:50:13 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-08-17 19:55:21 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)

**Comment by Koenkk** [comment]
You can remove this option, it can now be configured via the z2m frontend (see https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/releases/tag/v1.25.0-1).

**Comment by mekanoid** [comment]
Nice to know that I can remove the option, but **from where** should I remove it? I can't figure it out even if I follow the link... :-(

**Comment by Koenkk** [comment]
In the Z2M HA addon configuration page
