### ISSUE TITLE
Zigbee2MQTT addon does not start 

### ISSUE THREAD

**Issue by RatheeM** [zigbee2mqtt/hassio-zigbee2mqtt#374]
### Description of the issue

A couple of days back all my zigbee devices stopped working after a restart. I also updated the HA core to 2022.8.7 around the same time. Now the addon does not start at all. I configured new instance of HA in another machine and restored from backup from two weeks back but same problem exists. In the fresh HA install on another machine and configuring Z2M afresh works well. Requesting support on how to rescue my Z2M on my original HA instance.

### Addon version

Latest

### Platform

Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220802.0 - latest

### Logs of the issue (if applicable)

Zigbee2mqtt Edge
s6-overlay-suexec: fatal: can only run as pid 1

**Comment by donster22** [comment]
I have the same problem. Z2M does not restart after a reboot. Toggle restart is "on" and so is the restart watchdog.
Zigbee2MQTT 1.27.0-1
Home Assistant Core 2022.6.6
Home Assistant Supervisor 2022.08.5
Home Assistant OS 8.2
no Z2M logs visible

**Comment by sultanhq** [comment]
The solution I found (no guarantees of course... 😉  )

1. make a copy of the add-on configuration (I just took it in yaml format)
2. uninstall the add-on
3. re-install the add-on
4. restore configuration via yaml
5. start add-on and 🤞

**Comment by FirstRulez** [comment]
I have also started seeing this issue on my setup (HAOS on rpi4 installed as add-on).

> The solution I found (no guarantees of course... 😉 )
> 
> 1. make a copy of the add-on configuration (I just took it in yaml format)
> 2. uninstall the add-on
> 3. re-install the add-on
> 4. restore configuration via yaml
> 5. start add-on and 🤞

I would like to follow the above to see if I can resolve, but not sure how best to export and re-import the configuration - where is it stores?

I have the file editor add-on installed if that helps

**Comment by smcnab1** [comment]
> The solution I found (no guarantees of course... 😉 )
> 
> 1. make a copy of the add-on configuration (I just took it in yaml format)
> 2. uninstall the add-on
> 3. re-install the add-on
> 4. restore configuration via yaml
> 5. start add-on and 🤞

Tried this of which also didn't work. Having the same issue. Log stalling at:
```
s6-rc: info: service z2m: starting
s6-rc: info: service socat: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service z2m successfully started
s6-rc: info: service socat successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[14:11:52] INFO: Socat not enabled
[14:11:55] INFO: Handing over control to Zigbee2MQTT Core ...
Zigbee2MQTT:info  2022-09-16 14:12:04: Logging to console and directory: '/config/zigbee2mqtt/log/2022-09-16.14-12-04' filename: log.txt
Zigbee2MQTT:info  2022-09-16 14:12:04: Starting Zigbee2MQTT version 1.27.2 (commit #unknown)
Zigbee2MQTT:info  2022-09-16 14:12:04: Starting zigbee-herdsman (0.14.53)
Zigbee2MQTT:info  2022-09-16 14:12:05: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2022-09-16 14:12:05: Coordinator firmware version: '{"meta":{"maintrel":0,"majorrel":38,"minorrel":114,"product":0,"revision":"0x26720700","transportrev":0},"type":"ConBee2/RaspBee2"}'
Zigbee2MQTT:info  2022-09-16 14:12:05: Currently 0 devices are joined:
Zigbee2MQTT:info  2022-09-16 14:12:05: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2022-09-16 14:12:06: Connecting to MQTT server at mqtt://core-mosquitto:1883
Zigbee2MQTT:info  2022-09-16 14:12:07: Connected to MQTT server
Zigbee2MQTT:info  2022-09-16 14:12:07: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2022-09-16 14:12:07: Started frontend on port 0.0.0.0:8099
Zigbee2MQTT:info  2022-09-16 14:12:07: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"unknown","coordinator":{"meta":{"maintrel":0,"majorrel":38,"minorrel":114,"product":0,"revision":"0x26720700","transportrev":0},"type":"ConBee2/RaspBee2"},"log_level":"info","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":false,"version":"1.27.2"}'
Zigbee2MQTT:info  2022-09-16 14:12:07: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
```

Supervisor log states add-on already started but told not started in sidebar UI. No Open Web UI on Add-On page

**Comment by SMS0815** [comment]
> > The solution I found (no guarantees of course... 😉 )
> > 
> > 1. make a copy of the add-on configuration (I just took it in yaml format)
> > 2. uninstall the add-on
> > 3. re-install the add-on
> > 4. restore configuration via yaml
> > 5. start add-on and 🤞
> 
> Tried this of which also didn't work. Having the same issue. Log stalling at:
> 
> ```
> s6-rc: info: service z2m: starting
> s6-rc: info: service socat: starting
> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service z2m successfully started
> s6-rc: info: service socat successfully started
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service legacy-services: starting
> s6-rc: info: service legacy-services successfully started
> [14:11:52] INFO: Socat not enabled
> [14:11:55] INFO: Handing over control to Zigbee2MQTT Core ...
> Zigbee2MQTT:info  2022-09-16 14:12:04: Logging to console and directory: '/config/zigbee2mqtt/log/2022-09-16.14-12-04' filename: log.txt
> Zigbee2MQTT:info  2022-09-16 14:12:04: Starting Zigbee2MQTT version 1.27.2 (commit #unknown)
> Zigbee2MQTT:info  2022-09-16 14:12:04: Starting zigbee-herdsman (0.14.53)
> Zigbee2MQTT:info  2022-09-16 14:12:05: zigbee-herdsman started (resumed)
> Zigbee2MQTT:info  2022-09-16 14:12:05: Coordinator firmware version: '{"meta":{"maintrel":0,"majorrel":38,"minorrel":114,"product":0,"revision":"0x26720700","transportrev":0},"type":"ConBee2/RaspBee2"}'
> Zigbee2MQTT:info  2022-09-16 14:12:05: Currently 0 devices are joined:
> Zigbee2MQTT:info  2022-09-16 14:12:05: Zigbee: disabling joining new devices.
> Zigbee2MQTT:info  2022-09-16 14:12:06: Connecting to MQTT server at mqtt://core-mosquitto:1883
> Zigbee2MQTT:info  2022-09-16 14:12:07: Connected to MQTT server
> Zigbee2MQTT:info  2022-09-16 14:12:07: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
> Zigbee2MQTT:info  2022-09-16 14:12:07: Started frontend on port 0.0.0.0:8099
> Zigbee2MQTT:info  2022-09-16 14:12:07: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"unknown","coordinator":{"meta":{"maintrel":0,"majorrel":38,"minorrel":114,"product":0,"revision":"0x26720700","transportrev":0},"type":"ConBee2/RaspBee2"},"log_level":"info","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":false,"version":"1.27.2"}'
> Zigbee2MQTT:info  2022-09-16 14:12:07: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
> ```
> 
> Supervisor log states add-on already started but told not started in sidebar UI. No Open Web UI on Add-On page

same Problem...

**Comment by denman1991** [comment]
Same problem overhere.
logging says it's started but frontend ui says: it is not.

stopped and start add-on with service call:
this is the logging:
```
debug 2023-05-31 21:41:42: Loaded state from file /config/zigbee2mqtt/state.json
info  2023-05-31 21:41:42: Logging to console and directory: '/config/zigbee2mqtt/log/2023-05-31.21-41-42' filename: log.txt
info  2023-05-31 21:41:42: Starting Zigbee2MQTT version 1.30.4 (commit #unknown)
info  2023-05-31 21:41:42: Starting zigbee-herdsman (0.14.111)
debug 2023-05-31 21:41:42: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"deconz","path":"/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2149150-if00"}}'
info  2023-05-31 21:41:42: zigbee-herdsman started (resumed)
info  2023-05-31 21:41:42: Coordinator firmware version: '{"meta":{"maintrel":0,"majorrel":38,"minorrel":114,"product":0,"revision":"0x26720700","transportrev":0},"type":"ConBee2/RaspBee2"}'
debug 2023-05-31 21:41:42: Zigbee network parameters: {"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754}
info  2023-05-31 21:41:42: Currently 0 devices are joined:
info  2023-05-31 21:41:42: Zigbee: disabling joining new devices.
info  2023-05-31 21:41:43: Connecting to MQTT server at mqtt://core-mosquitto:1883
debug 2023-05-31 21:41:43: Using MQTT login with username: addons
info  2023-05-31 21:41:44: Connected to MQTT server
info  2023-05-31 21:41:44: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
info  2023-05-31 21:41:44: Started frontend on port 0.0.0.0:8099
debug 2023-05-31 21:41:44: Received MQTT message on 'zigbee2mqtt/bridge/config' with data '{"commit":"unknown","coordinator":{"meta":{"maintrel":0,"majorrel":38,"minorrel":114,"product":0,"revision":"0x26720700","transportrev":0},"type":"ConBee2/RaspBee2"},"log_level":"info","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":false,"version":"1.30.4"}'
info  2023-05-31 21:41:44: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"unknown","coordinator":{"meta":{"maintrel":0,"majorrel":38,"minorrel":114,"product":0,"revision":"0x26720700","transportrev":0},"type":"ConBee2/RaspBee2"},"log_level":"debug","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":false,"version":"1.30.4"}'
info  2023-05-31 21:41:44: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
info  2023-05-31 21:41:44: Zigbee2MQTT started!
debug 2023-05-31 21:41:44: Received MQTT message on 'homeassistant/status' with data 'offline'
debug 2023-05-31 21:41:44: Received MQTT message on 'homeassistant/status' with data 'offline'
```
