### ISSUE TITLE
NAS-PD07 doesn't report values

### ISSUE THREAD

**Issue by Rubquila** [zigbee2mqtt/hassio-zigbee2mqtt#377]
### Description of the issue

Hi!!
I have a motion sensor NAS-PD07 (_TZ3000_kmh5qpmb). When updating Z2M to the latest version, the attributes that it obtained from the sensor have changed and now it does not receive any type of value from any of them.

In version 1.25.1-1 it worked

### Addon version

1.27.2-1

### Platform

Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220802.0 - latest

### Logs of the issue (if applicable)

```
2022-09-08 00:46:20Received Zigbee message from 'Detector de la cocina', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":0}' from endpoint 1 with groupID 0
2022-09-08 00:46:20No converter available for 'NAS-PD07' with cluster 'ssIasZone' and type 'commandStatusChangeNotification' and data '{"extendedstatus":0,"zonestatus":0}'
```

**Comment by Rubquila** [comment]
It looks like "zonestatus" its occupancy, but doesn't report like occupancy.

**Comment by leghissa** [comment]
I have the same issue. The main difference I see is that in version `1.25.1-1` the sensor is identified wrongly as a `TuYa TS0202` (and it works), but with more recent versions it's identified as `NAS PD07` and it stops working.

**Comment by russbrenner** [comment]
I can confirm that I have two NAS-PD07 sensors and both provide no updates to their sensors save for link quality. 

Both sensors report they're online. 

Z2M Current version: 1.28.1-1

Home Assistant 2022.11.0
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221102.1 - latest

**Comment by Rubquila** [comment]
I think it's an issue with converters, because the issue doesn't exist on previous versions of Z2M from 1.25.1-1. Something changed on the code.
Since then, i can't upgrade Z2M because i loose the sensor.
