### ISSUE TITLE
Zigbee2mqqt is not restarting with Home Assistant.

### ISSUE THREAD

**Issue by bergdahl** [zigbee2mqtt/hassio-zigbee2mqtt#378]
### Description of the issue

When restarting Home Assistant, the add-on is not able to restart Zigbee2Mqtt. 

In the supervisor log I see that HA stops the add-on [14:27:16] but then reports that it is already running [14:27:34]. Looks to me that it takes too long to shut down before HA tries to start it? 

I am running HA Blue so it is way faster than a standard RPi installations due to the eMMC drive.

### Addon version

1.27.2-1

### Platform

Home Assistant 2022.9.1
Supervisor 2022.08.6
Operating System 8.5
Frontend-version: 20220907.0 - latest

### Logs of the issue (if applicable)

22-09-09 14:26:40 INFO (MainThread) [supervisor.store] Loading add-ons from store: 78 all - 0 new - 0 remove
22-09-09 14:26:40 INFO (MainThread) [supervisor.store] Loading add-ons from store: 78 all - 0 new - 0 remove
22-09-09 14:27:16 INFO (SyncWorker_1) [supervisor.docker.interface] Stopping addon_45df7312_zigbee2mqtt application
22-09-09 14:27:19 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-09-09 14:27:19 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
22-09-09 14:27:21 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
22-09-09 14:27:21 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-09-09 14:27:34 WARNING (MainThread) [supervisor.addons.addon] 45df7312_zigbee2mqtt is already running!
22-09-09 14:27:46 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt application

**Comment by tomlut** [comment]
I've just started seeing this behaviour too. 

If the supervisor updates then the addon stops and I have to restart it manually. 

If the host is rebooted the addon also has to be restarted manually. 

I do have the addon "Start on boot" toggle on.

**Comment by bergdahl** [comment]
Thinking about it, I am not sure why HA needs to restart the add-on at all?
