### ISSUE TITLE
Where might I change the theme/coloring for the pages/tables?

### ISSUE THREAD

**Issue by MostHated** [zigbee2mqtt/hassio-zigbee2mqtt#38]
Hey there,
    Where might I change the theme/coloring for the pages/tables? Is that within the addon, or is that something I need to ask on the Zigbee2MQTT pages? I spent some time trying to customize the CSS using Stylus, only to realize when I refreshed the page that (presumably) because it was in an iframe that the changes don't seem to keep. It seems like I would need to change it at the source.

Thanks,
-MH

**Comment by ciotlosm** [comment]
This is something for https://github.com/Koenkk/zigbee2mqtt/issues as it's part of the built-in UI. I'm not sure if there is an option to customise this, but at the very least you could get a feature request.
