### ISSUE TITLE
Unable to change log level in hass addon

### ISSUE THREAD

**Issue by not-poma** [zigbee2mqtt/hassio-zigbee2mqtt#381]
### Description of the issue

Bulk logging by zigbee2mqtt is killing my sd cards.

[zigbee2mqtt docs state](https://www.zigbee2mqtt.io/guide/configuration/logging.html) that log level is adjusted by config entry

```yaml
advanced:
  log_level: warn
```

I have Pi with hass os and I've tried to go into addon config, edit as yaml and add that entry but it doesn't seem to have any effect and supervisor logs show that 

```
22-09-11 22:52:59 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
```

So how do I set it?

### Addon version

v1.27.2-1

### Platform

 Home Assistant 2022.9.4
Supervisor 2022.08.6
Operating System 9.0
Frontend 20220907.2 - latest

**Comment by Koenkk** [comment]
You can change it via the z2m frontend
