### ISSUE TITLE
zigbee2mqtt device mistaken for another brand

### ISSUE THREAD

**Issue by micheleformia** [zigbee2mqtt/hassio-zigbee2mqtt#382]
### Description of the issue

Hi I bought a Bticino brand device model "L4531C", this is seen as another LEGRAND brand device model "067775/741811". how can i make it become Btcino L4531C? thank you

### Addon version

v 1.27.2-1

### Platform

home assistant add-on

**Comment by Koenkk** [comment]
Legrand and Bticino is the same manufacturer, they use the same identifier so we cannot distinguish them from each other. Therefore they will appear as Legrand. https://www.bticino.com/about-us/
