### ISSUE TITLE
Failed to restart add-on

### ISSUE THREAD

**Issue by ugidj** [zigbee2mqtt/hassio-zigbee2mqtt#383]
### Description of the issue

Hi,

trying to restart the addon i have this issue:

Failed to restart add-on
Can't create container from addon_45df7312_zigbee2mqtt: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_45df7312_zigbee2mqtt: Conflict ("Conflict. The container name "/addon_45df7312_zigbee2mqtt" is already in use by container "e56001e5d21b0df8a885090d7414936e15296d589e3b38e898e6680e6c451843". You have to remove (or rename) that container to be able to reuse that name.")

Today i tried to reinstall Z2M and Mosquitto broker because i changed the coordinator stick.

I'm having big issues when i try to join with new devices:

Info 2022-09-18 17:08:27Zigbee: allowing new devices to join.
Error 2022-09-18 17:08:29Request 'zigbee2mqtt/bridge/request/permit_join' failed with error: 'sendDATA error: Error: {"sequence":7} after 1000ms'
Info 2022-09-18 17:08:29MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{},"error":"sendDATA error: Error: {\"sequence\":7} after 1000ms","status":"error","transaction":"jea9p-1"}'

Thank you in advance for the support
Best

### Addon version

Current version: 1.27.2-1

### Platform

Home Assistant 2022.9.4
Supervisor 2022.08.6
Operating System 9.0
Frontend 20220907.2 - latest

### Logs of the issue (if applicable)

Info 2022-09-18 17:09:49Zigbee: allowing new devices to join.
Error 2022-09-18 17:09:52Request 'zigbee2mqtt/bridge/request/permit_join' failed with error: 'sendDATA error: Error: {"sequence":2} after 1000ms'
Info 2022-09-18 17:09:52MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{},"error":"sendDATA error: Error: {\"sequence\":2} after 1000ms","status":"error","transaction":"ftblk-1"}'

**Comment by niklas007** [comment]
I have the same issue as you , got a fix for it ?

**Comment by niklas007** [comment]
Failed to restart add-on
Can't create container from addon_45df7312_zigbee2mqtt: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_45df7312_zigbee2mqtt: Conflict ("Conflict. The container name "/addon_45df7312_zigbee2mqtt" is already in use by container "f648d2cab0710d3d1c8061b3df380e5713b6b87a564fc803cab70ffe9a5f6507". You have to remove (or rename) that container to be able to reuse that name.")
