### ISSUE TITLE
Home assitant UI controll returns error when trying to control custom device

### ISSUE THREAD

**Issue by vidsec** [zigbee2mqtt/hassio-zigbee2mqtt#385]
### Description of the issue

I created an external converter for a 6ch zigbee device.
[https://gist.github.com/vidsec/1e4d2c586d9e6bbc0d9c65dec00fce8b](url)
it works within the zigbee2mqtt integrations dashboard and gives the following logs

`Debug 2022-09-22 10:30:01Received MQTT message on 'zigbee2mqtt/0xa4c138e71034fb88/set' with data '{"state_ch1":"ON"}`
`Debug 2022-09-22 10:30:01Publishing 'set' 'state_ch1' to '0xa4c138e71034fb88'`
`Debug 2022-09-22 10:30:01Received Zigbee message from '0xa4c138e71034fb88', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":1,"dp":19}],"seq":0}' from endpoint 1 with groupID 0`
`Info 2022-09-22 10:30:01MQTT publish: topic 'zigbee2mqtt/0xa4c138e71034fb88', payload '{"linkquality":176,"state_ch1":"ON","state_ch2":"OFF","state_ch3":"OFF","state_ch4":"OFF","state_ch5":"OFF","state_ch6":"OFF"}'`
`Debug 2022-09-22 10:30:06Received MQTT message on 'zigbee2mqtt/0xa4c138e71034fb88/set' with data '{"state_ch1":"OFF"}'`
`Debug 2022-09-22 10:30:06Publishing 'set' 'state_ch1' to '0xa4c138e71034fb88'`
`Debug 2022-09-22 10:30:06Received Zigbee message from '0xa4c138e71034fb88', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":1,"dp":19}],"seq":0}' from endpoint 1 with groupID 0`
`Info 2022-09-22 10:30:06MQTT publish: topic 'zigbee2mqtt/0xa4c138e71034fb88', payload '{"linkquality":176,"state_ch1":"OFF","state_ch2":"OFF","state_ch3":"OFF","state_ch4":"OFF","state_ch5":"OFF","state_ch6":"OFF"}`
 but when I try to control it through the home assistant UI (settings/devices & services/Mosquito broker/{device name}/controls) it can read the status of the device, but control commands (ON/OFF) give me an error 

`Debug 2022-09-22 10:24:13Received MQTT message on 'zigbee2mqtt/0xa4c138e71034fb88/ch1/set' with data 'ON'
Info 2022-09-22 10:24:13MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0xa4c138e71034fb88/ch1"},"type":"entity_not_found"}'
Error 2022-09-22 10:24:13Entity '0xa4c138e71034fb88/ch1' is unknown`

I'm unsure if this is the fault of the integration, MQTT or the Zigbee2Mqtt external converter I made.
I tried it on 2 different devices running HA (VM and hardware) with different zigbee controllers and the issue stays the same.

I'm quite new to creating custom integrations and zigbee2mqtt so if I missed anything please let me know

### Addon version

commit: 615c70f

### Platform

Core: 2022.9.5
Supervisor 2022.09.1
Operating System 9.0

### Logs of the issue (if applicable)

same as the last logs in the description:

Debug 2022-09-22 10:24:13Received MQTT message on 'zigbee2mqtt/0xa4c138e71034fb88/ch1/set' with data 'ON' Info 2022-09-22 10:24:13MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0xa4c138e71034fb88/ch1"},"type":"entity_not_found"}' Error 2022-09-22 10:24:13Entity '0xa4c138e71034fb88/ch1' is unknown

**Comment by Koenkk** [comment]
`chx` (e.g. `ch2`) is not a valid enpoint name, use `lx` (e.g `l2` instead). 


The endpoint name should be in the following list: https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/util/utils.ts#L30
