### ISSUE TITLE
`Can't open config file at null/configuration.yaml` startup error

### ISSUE THREAD

**Issue by Koenkk** [zigbee2mqtt/hassio-zigbee2mqtt#387]
### Description of the issue

The HA addon fails with an error on startup: `can't open config file at null/configuration.yaml`. This probably occurs due to a s6 bug: https://github.com/just-containers/s6-overlay/issues/477

Since there are many different issues about this same problem and some are already closed I created this one.

**I want to let you know I'm working on a fix** so no need for "me too" responses.

### Addon version

v1.27.2-1

### Platform

Applies to all HA versions

**Comment by Koenkk** [comment]
@ all; please check if this issue is fixed in the latest edge addon.

**Comment by oNSXo** [comment]
Looks good @Koenkk , thanks!

**Comment by stu1811** [comment]
@Koenkk So far so good

**Comment by mariokil** [comment]
So far so good. System works since 2 hours. No bugs

**Comment by leenemo** [comment]
> @ all; please check if this issue is fixed in the latest edge addon.

I stoped the mqtt sever and zigbee2mqtt sever,when the ha start. I fixed it.
But I don’t think it’s a good method. You mention the last add on. I can’t find it. Is it z2m?or ha?

**Comment by Koenkk** [comment]
z2m edge version, however the fix will also be included in the next z2m release on 1 October

**Comment by leenemo** [comment]
> z2m edge version, however the fix will also be included in the next z2m release on 1 October
I find that if the yaml channel is different from the  adapter channel ,the z2m can’t start up.

**Comment by Koenkk** [comment]
@leenemo that is expected behavior. Changing the channel requires repairing all devices, as a safety mechanism users have to delete the `data/coordinator_backup.json` file first. This is also stated in the error that can be seen in the z2m log.

**Comment by auanasgheps** [comment]
This problem is not relevant to this issue, but to your MQTT broker.

**Comment by mariokil** [comment]
> This problem is not relevant to this issue, but to your MQTT broker.

Yes indeed. MQTT broker restart has been solved problem.
