### ISSUE TITLE
SONOFF SNZB-02 not detected 

### ISSUE THREAD

**Issue by Darozas** [zigbee2mqtt/hassio-zigbee2mqtt#394]
### Description of the issue

Hi All spend all day reading trough google but didn get anywhere. I have  [SONOFF SNZB-02] sensors and non of them is detected by zigbee2mqtt 

Can any one lead me to right direction 

https://www.zigbee2mqtt.io/devices/SNZB-02.html
https://www.zigbee2mqtt.io/guide/adapters/#recommended  (ZIGstar Stick v4)

All 3 sensors i have even installed custom firmware on one but sill no joy .

![image](https://user-images.githubusercontent.com/19796221/194349424-eedd6ba7-e9e1-42bd-b1d9-383126b1835d.png)

### Addon version

1.28

### Platform

Latest 

### Logs of the issue (if applicable)

no logs as  cant discover devices

**Comment by FredD35** [comment]
Did you get them integrated into your network by now? 

Seems like I'm having the same issue right and I did ask in another area for help:
[https://github.com/Koenkk/zigbee2mqtt/issues/14913](url)

**Comment by Darozas** [comment]
> Did you get them integrated into your network by now?
> 
> Seems like I'm having the same issue right and I did ask in another area for help: [https://github.com/Koenkk/zigbee2mqtt/issues/14913](url)

Yes i have done.

Its super weird one here.  i could not get it to work on mqtt2zigbee. Installed ZHA got them to pair. But ZHA dont work with my Hive thermostats so i have to go back to mqtt2zigbee next day. And as i was doing re-pairing for my Thermostats magickly sonofs appeared when i allowed to join. I had 300 reboots first day and could not connect next day all fine super weird. And all been working well ever since .

**Comment by FredD35** [comment]
Strange. That means that you basically did not change anything and out of a sudden it worked. 
Do you know in which log we should be seeing the device requesting access?
