### ISSUE TITLE
zigbee2mqtt is broken after restore of Home Assistant Backup

### ISSUE THREAD

**Issue by smartmatic** [zigbee2mqtt/hassio-zigbee2mqtt#398]
### Description of the issue

Update to latest Home Assistant releases 2022.10 crashes automations. Therefore a restore to HA 2022.9.7 was necessary.
Since that zigbee2mqtt is broken. I am not able to get the UI back running. I've tried several time to reinstall the Add-On without success. 
The logs does not show any error or warning why the Add-On can not started! Nothing is reported.
![Bildschirmfoto 2022-10-07 um 16 30 27](https://user-images.githubusercontent.com/74932663/194578166-8290e1cb-d0df-4043-afd1-e9fa8fd5b2fb.png)

The only information which is popping up that i should start the Add-On

![Bildschirmfoto 2022-10-07 um 14 50 29](https://user-images.githubusercontent.com/74932663/194557797-6471d2a1-5fb8-4020-8478-0c6943be67e5.png)

**It seems that the Add-On does not read the path /config/zigbee2mqtt beacause when i change something in Add-On configuration via UI and save the changes it's not stored in /config/zigbee2mqtt/configuration.yaml**

What is really crazy is that my zigbee devices are sending payloads. So i can control devices and they are sending state changes.

This is my config:

data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  server: mqtt://core-mosquitto
  user: mypw
  password: mypw
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2415155-if00
  adapter: deconz
zigbee_herdsman_debug: true

Please support!

### Addon version

v.1.28.0-1

### Platform

Home Assistant 2022.9.7
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest

### Logs of the issue (if applicable)

I found in Terminal via dmesg a lot of those messages

![Bildschirmfoto 2022-10-07 um 16 47 20](https://user-images.githubusercontent.com/74932663/194581940-08f0696c-f17b-410f-803c-7ca5d20c7012.png)

Is this causing the issue?

**Comment by sirpilz** [comment]
Same problem for me.

**Comment by djmaze** [comment]
Same problem here. It seems the config in the UI is not saved correctly.

As a workaround, I manually edited the configuration in `/usr/share/hassio/homeassistant/zigbee2mqtt/configuration.yaml`. Afterwards, I could start the addon successfully.

**Comment by CoreyJ87** [comment]
> Same problem here. It seems the config in the UI is not saved correctly.
> 
> As a workaround, I manually edited the configuration in `/usr/share/hassio/homeassistant/zigbee2mqtt/configuration.yaml`. Afterwards, I could start the addon successfully.

So, I dont have a configuration in that path. Mine is in config/zigbee2mqtt/configuration.yaml is that the same one? Or should I have one in the location you mentioned? Also what does your config look like?

**Comment by djmaze** [comment]
@CoreyJ87 Sorry, forgot to answer! Yes, that should be the same file.
