### ISSUE TITLE
Addon fails to auto start

### ISSUE THREAD

**Issue by tomlut** [zigbee2mqtt/hassio-zigbee2mqtt#399]
### Description of the issue

If the supervisor updates then the addon stops and I have to restart it manually.

If the host is rebooted the addon also has to be started manually.

I do have the addon "Start on boot" toggle on.

![Screenshot 2022-10-08 at 22-10-55 Home Assistant](https://user-images.githubusercontent.com/10679300/194704562-54b23421-aa33-489c-a6b9-7fe386dba2fa.png)

### Addon version

1.28.0-1 

### Platform

 Home Assistant 2022.10.1 
Supervisor 2022.10.0 
Operating System 9.0

### Logs of the issue (if applicable)

No logs as the addon does not start. When it is started manually there is no issue.

**Comment by Koenkk** [comment]
This looks to be a HA issue.

**Comment by tomlut** [comment]
Other addons are not suffering from the issue.

**Comment by lexvx** [comment]
Same problem on HAOS

**Comment by tomlut** [comment]
I've worked out when this happens. It's when the supervisor auto updates.

**Comment by tomlut** [comment]
Other addons do not suffer this.
