### ISSUE TITLE
Error while starting zigbee-herdsman 

### ISSUE THREAD

**Issue by dprovoker** [zigbee2mqtt/hassio-zigbee2mqtt#401]
### Description of the issue

I need help. zigbee2mqtt does not start
Home assistant is installed on NAS Asustor. Used this guide: https://youtu.be/FhW4HO-dbG0

### Addon version

1.28.0-1

### Platform

Home Assistant 2022.10.1
Supervisor 2022.10.0
Operating System 9.0
Frontend 20221006.0 - latest

### Logs of the issue (if applicable)

[21:56:06] INFO: Preparing to start...
[21:56:06] INFO: Socat not enabled
[21:56:08] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2022-10-10 21:56:18: Logging to console and directory: '/config/zigbee2mqtt/log/2022-10-10.21-56-18' filename: log.txt
Zigbee2MQTT:info  2022-10-10 21:56:18: Starting Zigbee2MQTT version 1.28.0 (commit #unknown)
Zigbee2MQTT:info  2022-10-10 21:56:18: Starting zigbee-herdsman (0.14.62)
Zigbee2MQTT:error 2022-10-10 21:56:19: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-10-10 21:56:19: Failed to start zigbee
Zigbee2MQTT:error 2022-10-10 21:56:19: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-10-10 21:56:19: Exiting...
Zigbee2MQTT:error 2022-10-10 21:56:19: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0:/dev/ttyACM0'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/@serialport/stream/lib/index.js:242:12

**Comment by bjornberg** [comment]
Have had the same error message since a week. 

Wanted to copy Data to an SSD drive and since then I have been getting this error message.

What I have already tried is restoring backups. 
Flashed CC2652RD again.

So far no success...

**Comment by koen241** [comment]
I have exactly the same problem since I updated to the last core and operating system. Did you find a fix already?

**Comment by Sorin-1** [comment]
Same here. CC2531. Used to drop zigbee devices before.

**Comment by AE-PAVAN** [comment]
"Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)"
Same error for me. I obtain a "502" if I try to open "Zigbee2MQTT"

**Comment by brantmacga** [comment]
I have the exact same error described.

**Comment by Sorin-1** [comment]
_Ok, I have sorted it out for me. 
1. Disable integeration "Zigbee Home Automation", which may have been automatically installed while plugging in "E"-type Sonoff adapter. Interation ZHA causes port malfunction when Zigbee2mqtt tries to use port.
2. Look for the port assigned to adpter, don't forget "ezsp" parameter (see at the end). Try this zigbee2mqtt configuration (use Your IP and password, check other things):_
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.10:1883
advanced:
  log_level: error
  pan_id: 6744
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  last_seen: ISO_8601
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false  user: mqtt-user
  password: devicepassword
serial:
  port: /dev/ttyACM0
  user: mqtt-user
  password:  devicepassword
  server: mqtt://192.168.1.10:1883
  adapter: ezsp

**Comment by Hanskn** [comment]
Also have the same problem
Zigbee2MQTT:error 2022-11-30 14:34:07: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-11-30 14:34:07: Failed to start zigbee
Zigbee2MQTT:error 2022-11-30 14:34:07: Exiting...
Zigbee2MQTT:error 2022-11-30 14:34:07: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-30T13_34_08_014Z-debug.log
[14:34:08] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js

**Comment by Sorin-1** [comment]
> Also have the same problem
What Zigbee stick do You use? Have You looked for ZHA integration? It has to be disabled,

**Comment by lawful76** [comment]
After few hours made id working with this /config/zigbee2mqtt/configuration.yaml:
homeassistant: true
permit_join: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: [type homeassistant here, after successful connection it will change by itself to 'addon']
  password: [take password from mqtt broker, you can obtain it tapping 're-configure mqtt']
serial:
  port: >-
    /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220706183154-if00
  adapter: ezsp
adapter: ezsp
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false

**Comment by Sorin-1** [comment]
> Stick is Sonoff_Zigbee_3.0_USB_Dongle_Plus, ZHA integration disabled

Assuming that You use "P" version of Sonoff stick,  "adapter: ezsp" not needed, and port may be "port: /dev/ttyUSB0"
