### ISSUE TITLE
Cant load the webpage when using external url but is ok with internal url

### ISSUE THREAD

**Issue by wifiuk** [zigbee2mqtt/hassio-zigbee2mqtt#403]
### Description of the issue

i am unable to load the zigbee2mqtt webpag when using my external URL, but it loads fine using the internal URL.

This is the only add-on that exhibits this behaviour, all my other add-ons are fine.

### Addon version

1.28.0-01

### Platform

Home Assistant 2022.10.4
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest

**Comment by Arquiteto** [comment]
Are you by any chance using Cloudflared as external access? I have the same issue.

**Comment by wifiuk** [comment]
Yeah

**Comment by Arquiteto** [comment]
So far I was able to find out that it doesn't work on Chrome and HA Android App. Even clearing cache and using incognito mode doesn't help. However, it does work under Firefox, for unknown reasons.

**Comment by wifiuk** [comment]
its working for me today, its just intermittent

**Comment by GerdRuetten** [comment]
I have the same problem. 
All other add-ons i use working under the external access.

Zigbee2MQTT
Current version: 1.28.2-1

Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest
