### ISSUE TITLE
Error while opening socket

### ISSUE THREAD

**Issue by Stefan28L** [zigbee2mqtt/hassio-zigbee2mqtt#405]
### Description of the issue

I'm using a Silvercrest Zigbee gateway that has been hacked to work without the cloud.
It runs in HA with no problems with ZHA, so the EZSP adapter works I think.
However, the addon does not start.
I removed the ZHA integration before testing.

I upgradet the gateway to the EZSP Version V6.7.8.0

my serial configuration:

serial:
  port: tcp://192.168.0.20:8888
  adapter: ezsp

### Addon version

v1.28.0

### Platform

Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest

### Logs of the issue (if applicable)

Zigbee2MQTT:info  2022-10-21 19:15:12: Starting Zigbee2MQTT version 1.28.0 (commit #unknown)
Zigbee2MQTT:info  2022-10-21 19:15:12: Starting zigbee-herdsman (0.14.62)
Zigbee2MQTT:error 2022-10-21 19:15:16: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-10-21 19:15:16: Failed to start zigbee
Zigbee2MQTT:error 2022-10-21 19:15:16: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-10-21 19:15:16: Exiting...
Zigbee2MQTT:error 2022-10-21 19:15:16: Error: Error while opening socket
    at Socket.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:146:24)
    at Socket.emit (node:events:539:35)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by bulosh** [comment]
Stefan i have the same problem.
QNAP + zigbee2mqtt + ezsp configuration to Xiaomi Gateway v3

Did you solve?
Only zha is working (but zigbee2mqtt is better!!)
