### ISSUE TITLE
Authentication for the proxy

### ISSUE THREAD

**Issue by SamMousa** [zigbee2mqtt/hassio-zigbee2mqtt#411]
> Passing the token is now supported in the latest dev branch (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html). E.g. `http://192.168.2.43:8085?token=my_token_123`.
> 
> However this does not seem to work in the proxy addon yet:
> 
> <img alt="Screenshot 2022-11-08 at 21 48 28" width="1142" src="https://user-images.githubusercontent.com/2892853/200672202-68bf8005-64ac-473b-8b23-3833513c91bd.png">
> 
> @SamMousa could you look into this? Without an auth token the frontend is unsafe.

Can we pass the token via a header? That's more secure. If so I can add that to nginx.

_Originally posted by @SamMousa in https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/400#issuecomment-1307919099_

**Comment by Koenkk** [comment]
This sounds like a good idea, https://github.com/Koenkk/zigbee2mqtt/blob/e66fe8534e81b6199dbb4dfdacaf3e5b8ba4210b/lib/extension/frontend.ts#L79 has to be updated to check the headers. This also means the frontend should always include this header when making requests to the z2m webserver. @nurikk what do you think?

**Comment by nurikk** [comment]
> This sounds like a good idea, https://github.com/Koenkk/zigbee2mqtt/blob/e66fe8534e81b6199dbb4dfdacaf3e5b8ba4210b/lib/extension/frontend.ts#L79 has to be updated to check the headers. This also means the frontend should always include this header when making requests to the z2m webserver. @nurikk what do you think?

What’s the difference in sending token in header or as get parameter to the endpoint?

**Comment by SamMousa** [comment]
Get params are more likely to appear in logs.

**Comment by Koenkk** [comment]
But in order to view the logs the person has to have access to the system. 

I thought you chose the headers over the get param because Ingress doesn't seem to work for get params? (at least now how the addon is currently implemented)

**Comment by SamMousa** [comment]
That doesn't matter. The headers will be sent by the addon proxy (since HA has its own authentication). In general it's better practice to avoid get params for long lived access tokens.

**Comment by Koenkk** [comment]
@SamMousa but would it technical be possible to work with get params?

**Comment by SamMousa** [comment]
Yes. This answer shows the example: https://serverfault.com/questions/912090/how-to-add-parameter-to-nginx-query-string-during-redirect

In case you want to go ahead and try for yourself! Note that nginx will not reload configuration automatically.


The idea is that the nginx proxy in HA proxy addon adds the param, so when using this vis HA because you're already logged in you don't need to do it again. Note that basic auth would also work.

**Comment by Koenkk** [comment]
I've implemented a fix. I guess the reason it didn't work before is that Ingress add some query params by itself?

Anyway, thanks and this can be closed now. Release v0.2.0 of the proxy addon.

**Comment by SamMousa** [comment]
Did you test this without auth enabled? I feel like it might break stuff

**Comment by Koenkk** [comment]
Yes I tested this, in this case the token query param will be empty which will work fine.
