### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by Ma3er** [zigbee2mqtt/hassio-zigbee2mqtt#417]
### Description of the issue

The app keeps crashing, Watchdog does not restart?

### Addon version

1.28.2-1

### Platform

Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest

**Comment by brubaked** [comment]
Not sure if it’s the same cause, but my add on is also crashing. I am running Zigbee2MQTT in Home Assistant OS on the x86 (NUC) platform with a Conbee II stick. 

This is what I get in the logs after the crash: /app/node_modules/@serialport/bindings/lib/poller.js:101    const err = new Error('Canceled')

Manually restarting the add on works fine.

**Comment by xklech** [comment]
Crashing for us as well. Its running for about 1 day and then devices stop communicating. After restarting add-on status is updated again.

Current version: 1.28.2-1

Watchdog does not help. Log shows nothing.

**Comment by xklech** [comment]
Downgrading to 1.26.0-1 helped. Now devices are working more than 24 hours

**Comment by CrazyCoder** [comment]
Same here, constant crashes on Home Assistant Yellow with the 1.28.4-dev (commit #b0e352b) and 1.28.4 (commit #unknown).

Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

Nothing in logs, frontend not available with 502: Bad Gateway. Watchdog doesn't help. Sometimes have to restart it several times until it starts to work.

Is there an easy way to downgrade on HAOS?

**Comment by xklech** [comment]
I have backups in Home Assistant gui. 

Settings => System => Backup and restore some older version.
