### ISSUE TITLE
Zigbee2mqtt not visible in  Official add-ons (version for PI4 64 bit) 

### ISSUE THREAD

**Issue by Bach-Danielsson** [zigbee2mqtt/hassio-zigbee2mqtt#42]
**Description of problem:**
Zigbee2mqtt is not listed in the add-on store on my RPI4 running Home Assistant OS 5.12 

https://github.com/home-assistant/operating-system/releases/download/5.12/hassos_rpi4-64-5.12.img.xz

**Comment by ewoutdenheijer** [comment]
You have to add the repository. Just follow the installation instructions.

**Comment by ciotlosm** [comment]
Read https://github.com/zigbee2mqtt/hassio-zigbee2mqtt#installation
