### ISSUE TITLE
Zigbee2MQTT configurations not present in the schema add-on

### ISSUE THREAD

**Issue by raelix** [zigbee2mqtt/hassio-zigbee2mqtt#421]
### Description of the issue

Zigbee2MQTT has a lot of great available configuration that could be set but the schema provided on the add-on doesn't allow many of them to be configured.
Some of these configuration of the add-on are required in many case e.g. to change the base_topic. This is currently not possible due to the schema validation and the only way is to start the add-on first and then change the parameter from the UI. 
This behavior has a side effect in fact the add-on is started with the default topic which cause the creating of the devices under the wrong topic.

The previous example is just one of the possible side-effect of the poor schema provided in the home assistant add-on.

### Addon version

v1.28.2-1

### Platform

Core: 2022.11.4
Supervisor: 2022.11.2

### Logs of the issue (if applicable)

22-11-26 14:25:34 WARNING (MainThread) [supervisor.addons.options] Unknown option 'keepalive' for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:34 WARNING (MainThread) [supervisor.addons.options] Unknown option 'reject_unauthorized' for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:34 WARNING (MainThread) [supervisor.addons.options] Unknown option 'version' for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:34 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:34 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:34 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:34 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:34 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:34 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:47 WARNING (MainThread) [supervisor.addons.options] Unknown option 'keepalive' for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:47 WARNING (MainThread) [supervisor.addons.options] Unknown option 'reject_unauthorized' for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:47 WARNING (MainThread) [supervisor.addons.options] Unknown option 'version' for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:47 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:47 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:47 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:47 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:47 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2MQTT (058ba649_zigbee2mqtt)
22-11-26 14:25:47 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2MQTT (058ba649_zigbee2mqtt)

**Comment by Koenkk** [comment]
Only the necessary options to start Zigbee2MQTT are provided via the addon page, the rest needs to be configured via the web interface. See https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/pull/270

**Comment by raelix** [comment]
@Koenkk so no way of automating it right? I have to spawn multiple instances and I would also be able to reproduce the same configuration in case of failures.

**Comment by Koenkk** [comment]
Then you can copy the `configuration.yaml` file of Z2M
