### ISSUE TITLE
Configuration Problems

### ISSUE THREAD

**Issue by DerDet** [zigbee2mqtt/hassio-zigbee2mqtt#422]
### Description of the issue

HI,
I added the Add-On into HA
running HA in Virtual BOX, the stick is presnt into HA at ttyACM0
/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDCED5E-if00

I try to set up the serial port on configuration tab inside the Add-On
When I try to save, get the error:

Fehler beim Speichern der Add-on-Konfiguration, Invalid dict for option 'serial' in Zigbee2MQTT (45df7312_zigbee2mqtt). Got {'data_path': '/config/zigbee2mqtt', 'socat': {'enabled': False, 'master': 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777', 'slave': 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5', 'options': '-d -d', 'log': False}, 'mqtt': {}, 'serial': '/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDCED5E-if00'}

No chance to start the ADd-On.

Any suggetions?

### Addon version

1.28.2-1

### Platform

Home Assistant 2022.11.4
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

**Comment by psixilambda** [comment]
you'll need to enter

"**port:** /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDCED5E-if00"

into the serial: field.
