### ISSUE TITLE
many new updates available after updating to 1.28.4-1

### ISSUE THREAD

**Issue by duceduc** [zigbee2mqtt/hassio-zigbee2mqtt#426]
### Description of the issue

This is weird trying to update from from 1.28.3-1 to 1.28.4-1. After updating, I am getting these new updates which I have never seen before.

Oh. Maybe it's letting me know my lights have new update available.

![2022-12-02_05-21-40](https://user-images.githubusercontent.com/20457723/205153161-83dd075d-a73f-4033-8a16-d9fea83fd797.jpg)

### Addon version

v1.28.4-1

### Platform

Home Assistant 2022.11.4
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

**Comment by cchrkk** [comment]
Sorry, probably really dumb question but, is there any setting to disable update checking(or at least reporting via mqtt)? 
Every time I restart zigbee2mqtt, homeassistant receives lots of notification with tons of updates ton (that fail when tried to install). Skipping updates doesn't work unfortunately.

Thanks a lot for Zigbee2MQTT @Koenkk  ✨
