### ISSUE TITLE
Addon cannot start after update to newest version

### ISSUE THREAD

**Issue by schmielinski** [zigbee2mqtt/hassio-zigbee2mqtt#427]
### Description of the issue

Image zigbee2mqtt/zigbee2mqtt-amd64:1.28.4-1 does not exist for addon_45df7312_zigbee2mqtt

### Addon version

1.28.4-1

### Platform

Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

**Comment by Koenkk** [comment]
Image should be available now: https://hub.docker.com/layers/zigbee2mqtt/zigbee2mqtt-amd64/1.28.4-1/images/sha256-8056cfddb193eec0f2d127caf7e6a0b22797460a6c3a63505415cfff1f06ede8?context=explore

**Comment by GravitySandwichh** [comment]
Still not working here, could the new image please be pushed with a new version number?

**Comment by nahuelarg86** [comment]
Same exact issue. Any pointers on how to re-download the image perhaps?

**Comment by nahuelarg86** [comment]
Ok, for what it's worth, I got it fixed using the CLI command "ha su repair"

**Comment by webguy-nz** [comment]
> 

This also worked for me. Thanks.

**Comment by mikey6283** [comment]
> > 
> 
> This also worked for me. Thanks.

Hi  i am having the same issues could  share on how to managed to solve it "ha su repair" as a newbie  i do not understand how you do it. Thanks in advance

**Comment by nahuelarg86** [comment]
> > > 
> > 
> > 
> > This also worked for me. Thanks.
> 
> Hi i am having the same issues could share on how to managed to solve it "ha su repair" as a newbie i do not understand how you do it. Thanks in advance

Hey, sorry I didn't see this before. Basically, you have to go to the terminal add-on and run the command if I remember correctly. I should keep a journal for this kind of things...
