### ISSUE TITLE
Error while starting zigbee-herdsman after Home Assistant upgrade

### ISSUE THREAD

**Issue by Jangomnz** [zigbee2mqtt/hassio-zigbee2mqtt#435]
### Description of the issue

The addon refuses to start after HA update. 

I have checked the tips on https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html , without luck.  I'm running a Conbee2 stick with FW 0x26580700.

Ha anyone experienced a similar issue?

### Addon version

1.28.4-1

### Platform

Home Assistant 2022.12.7
Supervisor 2022.11.2
Operating System 9.4
Interface 20221213.1 – latest

### Logs of the issue (if applicable)

[14:37:07] INFO: Preparing to start...
[14:37:08] INFO: Socat not enabled
[14:37:09] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2022-12-19 14:37:15: Logging to console and directory: '/config/zigbee2mqtt/log/2022-12-19.14-37-14' filename: log.txt
Zigbee2MQTT:info  2022-12-19 14:37:15: Starting Zigbee2MQTT version 1.28.4 (commit #unknown)
Zigbee2MQTT:info  2022-12-19 14:37:15: Starting zigbee-herdsman (0.14.76)
Zigbee2MQTT:error 2022-12-19 14:37:25: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-12-19 14:37:25: Failed to start zigbee
Zigbee2MQTT:error 2022-12-19 14:37:25: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-12-19 14:37:25: Exiting...
Zigbee2MQTT:error 2022-12-19 14:37:25: undefined

**Comment by lu-as0001** [comment]
same issue no idea how to fix it

**Comment by Michelobb** [comment]
Same here, no way to get out of this.

**Comment by strusic** [comment]
Same here, new fresh hassio install and z2m wont start

**Comment by Koenkk** [comment]
Can you provide the herdsman debug log when trying to start?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by strusic** [comment]
Well.. I was trying to figure it out by myself and the problem was with ZHA running in background when I plug in Sonoff ZB Dongle-P. When I turn integration off then Z2M is working properly. 🤦

**Comment by Michelobb** [comment]
Problem solved here too.  One of the isssues was that I had entered parameters in the MQTT config, while I'm using Mosquitto, HA and Z2M on the same device (need to let this blank in that case).

I was led to that mistake following that link, so if it can help other french talking users, here it is : 

https://www.domo-blog.fr/installer-mqtt-zigbee2mqtt-home-assistant-en-mode-supervision-guide-domotique-all-inclusive/

**Comment by Jangomnz** [comment]
> Can you provide the herdsman debug log when trying to start?
> 
> See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

I have enabled the herdsman debug option, but need some guidance on how to view the STOUT logs..

**Comment by Jangomnz** [comment]
Problem solved.  Stupid conflict of integrations as indicated earlier.. Deconz integration was starting automatically at reboot.
Only slightly embarrassing..
