### ISSUE TITLE
hass reports "not started", but zigbee2mqtt is running and working outside of integration

### ISSUE THREAD

**Issue by zeroflag0** [zigbee2mqtt/hassio-zigbee2mqtt#436]
### Description of the issue

When starting zigbee2mqtt from the addon-configuration, log-view will stop after a couple of seconds and the add-on reports "not running" (also when trying to open the UI from sidebar).
![image](https://user-images.githubusercontent.com/11450358/208927928-05488317-ea66-4e78-a91a-db79e3f90c40.png)
![image](https://user-images.githubusercontent.com/11450358/208927949-df186987-4e9c-4742-bf72-7e37140b33c6.png)
![image](https://user-images.githubusercontent.com/11450358/208927969-771d13a2-b8dc-40af-8b18-670a9a2ca73e.png)

however zigbee2mqtt is running and working fine.
![image](https://user-images.githubusercontent.com/11450358/208928367-a8abeb86-1a2b-4a41-8b4c-ee536d9c0e64.png)

### Addon version

v1.28.4-1

### Platform

 Home Assistant 2022.12.7 
Supervisor 2022.11.2 
Operating System 9.4 
Frontend 20221213.1 - latest 

### Logs of the issue (if applicable)

info  2022-12-21 15:21:01: Logging to console and directory: '/config/zigbee2mqtt/log/2022-12-21.15-21-01' filename: log.txt
info  2022-12-21 15:21:01: Starting Zigbee2MQTT version 1.28.4 (commit #unknown)
info  2022-12-21 15:21:01: Starting zigbee-herdsman (0.14.76)
info  2022-12-21 15:21:01: zigbee-herdsman started (resumed)
info  2022-12-21 15:21:01: Coordinator firmware version: '{"meta":{"maintrel":0,"majorrel":38,"minorrel":114,"product":0,"revision":"0x26720700","transportrev":0},"type":"ConBee2/RaspBee2"}'
info  2022-12-21 15:21:01: Currently 7 devices are joined:
info  2022-12-21 15:21:01: heating_livingroom (0x04cd15fffe26ef3f): BHT-002-GCLZB - Moes Moes BHT series Thermostat (Router)
info  2022-12-21 15:21:01: led_livingroom (0xa4c1380b0a7772fc): GL-C-008P - Gledopto Zigbee LED Controller RGB+CCT (pro) (Router)
info  2022-12-21 15:21:01: door_livingroom (0x00158d0008ad5d57): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
info  2022-12-21 15:21:01: window_livingroom (0x00158d00084dda7c): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
info  2022-12-21 15:21:01: movement (0x001788010bcf3592): 9290030675 - Philips Hue motion sensor (EndDevice)
info  2022-12-21 15:21:01: window_bathroom (0x00158d0008837678): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
info  2022-12-21 15:21:01: remote (0x001788010b76ac10): 929002398602 - Philips Hue dimmer switch (EndDevice)
warn  2022-12-21 15:21:01: `permit_join` set to  `true` in configuration.yaml.
warn  2022-12-21 15:21:01: Allowing new devices to join.
warn  2022-12-21 15:21:01: Set `permit_join` to `false` once you joined all devices.
info  2022-12-21 15:21:01: Zigbee: allowing new devices to join.
info  2022-12-21 15:21:01: Connecting to MQTT server at mqtt://zerohome:1883
info  2022-12-21 15:21:01: Connected to MQTT server
info  2022-12-21 15:21:01: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
info  2022-12-21 15:21:02: MQTT publish: topic 'zigbee2mqtt/heating_livingroom/availability', payload 'online'
info  2022-12-21 15:21:02: MQTT publish: topic 'zigbee2mqtt/led_livingroom/availability', payload 'online'
info  2022-12-21 15:21:02: MQTT publish: topic 'zigbee2mqtt/door_livingroom/availability', payload 'online'
info  2022-12-21 15:21:02: MQTT publish: topic 'zigbee2mqtt/window_livingroom/availability', payload 'online'
info  2022-12-21 15:21:02: MQTT publish: topic 'zigbee2mqtt/movement/availability', payload 'online'
info  2022-12-21 15:21:02: MQTT publish: topic 'zigbee2mqtt/window_bathroom/availability', payload 'online'
info  2022-12-21 15:21:02: MQTT publish: topic 'zigbee2mqtt/remote/availability', payload 'online'
info  2022-12-21 15:21:02: Started frontend on port 0.0.0.0:8099
info  2022-12-21 15:21:02: MQTT publish: topic 'zigbee2mqtt/led_livingroom', payload '{"brightness":254,"color":{"h":40,"hue":40,"s":51,"saturation":51,"x":0.5245,"y":0.4136},"color_mode":"color_temp","color_temp":495,"linkquality":255,"power_on_behavior":"on","state":"ON","update":{"installed_version":"10751203","state":"idle"},"update_available":false}'
[...]
info  2022-12-21 15:21:02: MQTT publish: topic 'zigbee2mqtt/led_livingroom', payload '{"brightness":254,"color":{"h":40,"hue":40,"s":51,"saturation":51,"x":0.5245,"y":0.4136},"color_mode":"color_temp","color_temp":495,"linkquality":255,"power_on_behavior":"on","state":"ON","update":{"installed_version":"10751203","state":"idle"},"update_available":false}'
info  2022-12-21 15:21:02: MQTT publish: topic 'zigbee2mqtt/door_livingroom', payload '{"battery":100,"contact":true,"device_temperature":25,"linkquality":255,"power_outage_count":11,"voltage":3035}'
info  2022-12-21 15:21:02: MQTT publish: topic 'zigbee2mqtt/window_livingroom', payload '{"battery":100,"contact":true,"device_temperature":17,"linkquality":255,"power_outage_count":203,"voltage":3005}'
info  2022-12-21 15:21:02: MQTT publish: topic 'zigbee2mqtt/movement', payload '{"battery":100,"illuminance":18407,"illuminance_lux":69,"led_indication":false,"linkquality":255,"motion_sensitivity":"high","occupancy":false,"occupancy_timeout":0,"temperature":20.05,"update":{"installed_version":"2.53.6","state":"idle"},"update_available":false}'
info  2022-12-21 15:21:02: MQTT publish: topic 'zigbee2mqtt/window_bathroom', payload '{"battery":100,"contact":true,"device_temperature":23,"linkquality":252,"power_outage_count":8,"voltage":3085}'
info  2022-12-21 15:21:02: MQTT publish: topic 'zigbee2mqtt/remote', payload '{"action":null,"battery":100,"linkquality":255,"update":{"installed_version":"2.45.2_hF4400CA","state":"idle"},"update_available":false}'
info  2022-12-21 15:21:02: Zigbee2MQTT started!

**Comment by kizio1000** [comment]
Hi, had the same yesterday, tried CLI command for restarting and repairing supervisor, didn't help. Restarted VM with HA and problem was solved.

**Comment by alaeddin14** [comment]
I'm having the same issue. The zigbee devices are working fine but the Addon is refusing to start, restoring an older backup and restarting the RPi didn't help. Any help would be very much appreciated. 

Thanks! 

![image](https://user-images.githubusercontent.com/8335681/215287450-bbcea5b2-4d81-444a-902e-391dd1d05c46.png)

**Comment by UryDanko** [comment]
I had similar problem. Total reboot helped.
