### ISSUE TITLE
[Bug]: Hue bulbs are not updated anymore - wrong padding

### ISSUE THREAD

**Issue by Fridolin34** [zigbee2mqtt/hassio-zigbee2mqtt#438]
### Description of the issue

In HA/configuration and in Z2M/OTA the system shows that there would be an update for two of my light bulbs:
![image](https://user-images.githubusercontent.com/73740504/210132840-c36c88f2-7b6b-4f26-8122-6be73349e2fc.png)

But after pressing 'update', I'm getting the following message:
![image](https://user-images.githubusercontent.com/73740504/210132857-f7bc51d6-aee8-4b0b-9e5a-acf41b8e431f.png)

Is there anything I can do?

### Addon version

1.28.4-1

### Platform

Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest

### Logs of the issue (if applicable)

Zigbee2MQTT:debug 2022-12-31 11:51:45: Received MQTT message on 'zigbee2mqtt/bridge/request/device/ota_update/update' with data '{"id":"Schlafzimmerlicht","transaction":"5glo4-1"}'
Zigbee2MQTT:info  2022-12-31 11:51:45: Updating 'Schlafzimmerlicht' to latest firmware
Zigbee2MQTT:info  2022-12-31 11:51:45: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Updating 'Schlafzimmerlicht' to latest firmware","meta":{"device":"Schlafzimmerlicht","status":"update_in_progress"},"type":"ota_update"}'
Zigbee2MQTT:debug 2022-12-31 11:51:45: Received Zigbee message from 'Schlafzimmerlicht', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20220502","swBuildId":"1.93.11"}' from endpoint 11 with groupID 0
Zigbee2MQTT:info  2022-12-31 11:51:45: MQTT publish: topic 'zigbee2mqtt/Schlafzimmerlicht', payload '{"brightness":254,"last_seen":"2022-12-31T11:51:45+01:00","linkquality":68,"power_on_behavior":null,"state":"OFF","update":{"installed_version":"1.93.11","state":"available"},"update_available":true}'
Zigbee2MQTT:debug 2022-12-31 11:51:45: Updating to latest '0x001788010940c3d2' (LWU001)
Zigbee2MQTT:debug 2022-12-31 11:51:45: Using endpoint '11'
Zigbee2MQTT:debug 2022-12-31 11:51:45: Received Zigbee message from 'Schlafzimmerlicht', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16784402,"imageType":276,"manufacturerCode":4107}' from endpoint 11 with groupID 0
Zigbee2MQTT:info  2022-12-31 11:51:45: MQTT publish: topic 'zigbee2mqtt/Schlafzimmerlicht', payload '{"brightness":254,"last_seen":"2022-12-31T11:51:45+01:00","linkquality":68,"power_on_behavior":null,"state":"OFF","update":{"installed_version":"1.93.11","state":"available"},"update_available":true}'
Zigbee2MQTT:debug 2022-12-31 11:51:45: Got OTA request '{"fieldControl":0,"manufacturerCode":4107,"imageType":276,"fileVersion":16784402}'
Zigbee2MQTT:debug 2022-12-31 11:51:46: ZigbeeOTA: downloaded main index
Zigbee2MQTT:debug 2022-12-31 11:51:46: getNewImage for '0x001788010940c3d2', meta {"fileVersion":16784906,"fileSize":478740,"url":"https://otau.meethue.com/storage/ZGB_100B_0114/090d8075-bcc7-4bf6-aead-bfc9d4926468/100B-0114-01001E0A-ConfLightBLE-Lamps-EFR32MG21.zigbee","sha512":"e097485e23a42329b6c18c0ab3561fd1491fcc2eda0058487987190566b6e3eecc788164cc89bee326083c799aa61a3bf077d375667f4aeb628060784c494599"}
Zigbee2MQTT:debug 2022-12-31 11:51:46: ZigbeeOTA: downloading firmware image from https://otau.meethue.com/storage/ZGB_100B_0114/090d8075-bcc7-4bf6-aead-bfc9d4926468/100B-0114-01001E0A-ConfLightBLE-Lamps-EFR32MG21.zigbee
Zigbee2MQTT:debug 2022-12-31 11:51:46: OTA update checksum validation succeeded for '0x001788010940c3d2'
Zigbee2MQTT:debug 2022-12-31 11:51:46: getNewImage for '0x001788010940c3d2', image header {"otaUpgradeFileIdentifier":{"type":"Buffer","data":[30,241,238,11]},"otaHeaderVersion":256,"otaHeaderLength":56,"otaHeaderFieldControl":0,"manufacturerCode":4107,"imageType":276,"fileVersion":16784906,"zigbeeStackVersion":2,"otaHeaderString":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","totalImageSize":478740}
Zigbee2MQTT:debug 2022-12-31 11:51:46: Update of 'Schlafzimmerlicht' failed (AssertionError [ERR_ASSERTION]: Image padding contains invalid bytes)
Zigbee2MQTT:info  2022-12-31 11:51:46: MQTT publish: topic 'zigbee2mqtt/Schlafzimmerlicht', payload '{"brightness":254,"last_seen":"2022-12-31T11:51:45+01:00","linkquality":68,"power_on_behavior":null,"state":"OFF","update":{"installed_version":"1.93.11","state":"available"},"update_available":true}'
Zigbee2MQTT:info  2022-12-31 11:51:46: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Update of 'Schlafzimmerlicht' failed (Image padding contains invalid bytes)","meta":{"device":"Schlafzimmerlicht","status":"update_failed"},"type":"ota_update"}'
Zigbee2MQTT:info  2022-12-31 11:51:46: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"Schlafzimmerlicht"},"error":"Update of 'Schlafzimmerlicht' failed (Image padding contains invalid bytes)","status":"error","transaction":"5glo4-1"}'
Zigbee2MQTT:error 2022-12-31 11:51:46: Update of 'Schlafzimmerlicht' failed (Image padding contains invalid bytes)
Zigbee2MQTT:debug 2022-12-31 11:51:46: AssertionError [ERR_ASSERTION]: Image padding contains invalid bytes
    at validateSilabsGbl (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:149:13)
    at validateImageData (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:93:13)
    at getNewImage (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:450:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.updateToLatest (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:286:19)
    at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:255:21)
Zigbee2MQTT:debug 2022-12-31 11:51:54: Received Zigbee message from 'Aquarium', type 'attributeReport', cluster 'genBasic', data '{"65506":54,"65508":0,"appVersion":192}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2022-12-31 11:51:54: MQTT publish: topic 'zigbee2mqtt/Aquarium', payload '{"child_lock":"UNLOCK","current":0.56,"energy":27.4,"indicator_mode":"off/on","last_seen":"2022-12-31T11:51:54+01:00","linkquality":70,"power":93,"power_outage_memory":"off","state":"OFF","update":{"installed_version":"unknown","state":"idle"},"update_available":false,"voltage":233}'
Zigbee2MQTT:debug 2022-12-31 11:51:55: Received Zigbee message from 'Schlafzimmerlicht', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16784402,"imageType":276,"manufacturerCode":4107}' from endpoint 11 with groupID 0

**Comment by AbeltjeNL** [comment]
I've got the same error message when trying to update.

**Comment by TheJulianJES** [comment]
This is not an issue with the HA addon itself, but rather with Z2M 1.18.x and before.

See https://github.com/Koenkk/zigbee2mqtt/issues/15805#issuecomment-1367777902 or https://github.com/Koenkk/zigbee-OTA/issues/218#issuecomment-1367170277.

**Comment by Koenkk** [comment]
Will be fixed in z2m 1.29.0 which will be released today.

**Comment by Fridolin34** [comment]
Thanks a lot
