### ISSUE TITLE
Failed to to call zigbee2mqtt/stats - Container addon is not running

### ISSUE THREAD

**Issue by ottoketney** [zigbee2mqtt/hassio-zigbee2mqtt#442]
### Description of the issue

I am encountering an issue when trying to retrieve statistics from the "zigbee2mqtt" add-on. The error message states that the container for the add-on is not running, which means that the add-on is not currently active and cannot provide the requested information. This log entry occurred twice.

### Addon version

1.29.1-1

### Platform

Home Assistant 2023.1.4
Supervisor 2022.12.1
Frontend 20230110.0 - latest

Installation Type	Home Assistant Supervised
Development	false
Supervisor	true
Docker	true
User	root
Virtual Environment	false
Python Version	3.10.7
Operating System Family	Linux
Operating System Version	5.10.0-19-amd64
CPU Architecture	x86_64
Host Operating System	Debian GNU/Linux 11 (bullseye)
Update Channel	stable
Supervisor Version	supervisor-2022.12.1
Agent Version	1.4.1
Docker Version	20.10.21

### Logs of the issue (if applicable)

Log Details (ERROR)
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:124
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 10:06:51 AM (2 occurrences)
Last logged: 10:07:13 AM

Failed to to call /addons/45df7312_zigbee2mqtt/stats - Container addon_45df7312_zigbee2mqtt is not running

**Comment by alienatedsec** [comment]
Core doesn't support containers nor addons

![image](https://user-images.githubusercontent.com/73167064/212332298-96c17d6e-fddc-4444-8030-26dd0402ad02.png)

**Comment by alienatedsec** [comment]
There will be more logs in the addon itself indicating where the problem is.

Go to the addon and paste logs from there.

![image](https://user-images.githubusercontent.com/73167064/212342430-be5db523-69e3-467c-a430-a91b784920b9.png)
