### ISSUE TITLE
HA / zigbee2mqtt problem with integration 

### ISSUE THREAD

**Issue by Ropuh** [zigbee2mqtt/hassio-zigbee2mqtt#443]
### Description of the issue

Config: 

enabled: false
master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
options: "-d -d"
log: false
base_topic: zigbee2mqtt
server: mqtt://core-mosquitto
port: /dev/serial/by-path/platform-fe3a0000.usb-usb-0:1:1.0-port0

(also tested with /dev/ttyUSB0) 

I got this:
Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby

I changed pan_id, ext_pan_id and channel - always got the same. I reflashed my Sonoff dongle on Windows with last firmware - same result. Any help?

### Addon version

v1.29.2-1

### Platform

Orange PI 4 LTS with Debian GNU/Linux 11 (bullseye)
Home Assistant 2023.1.4
Supervisor 2023.01.dev1301
Mosquitto broker 6.1.3
Zigbee2MQTT 1.29.2-1

### Logs of the issue (if applicable)

[12:15:07] INFO: Preparing to start...
[12:15:07] INFO: Socat not enabled
[12:15:09] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-01-15 12:15:13: Logging to console and directory: '/config/zigbee2mqtt/log/2023-01-15.12-15-13' filename: log.txt
Zigbee2MQTT:info  2023-01-15 12:15:13: Starting Zigbee2MQTT version 1.29.2 (commit #unknown)
Zigbee2MQTT:info  2023-01-15 12:15:13: Starting zigbee-herdsman (0.14.83-hotfix.0)
Zigbee2MQTT:error 2023-01-15 12:16:19: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-01-15 12:16:19: Failed to start zigbee
Zigbee2MQTT:error 2023-01-15 12:16:19: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-01-15 12:16:19: Exiting...
Zigbee2MQTT:error 2023-01-15 12:16:20: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

**Comment by Ropuh** [comment]
BTW: the same hardware setup on the same base system Debian 11 but with homebridge 1.6. on board (zigbee2mqtt 1.29.2 and module homebridge-z2m 1.9.2) works perfect!

**Comment by MarcelW85** [comment]
Same problem here!
Restoring to an older version doesn't help.
Previously a conbee was installed.

**Comment by Ropuh** [comment]
BTW2: setting config on this system HA with ZHA (The same Sonoff dongle) works without problem.

**Comment by Pankuha** [comment]
Same problem here!
Restoring to an older version doesn't help

**Comment by Teunhen** [comment]
Same here. Zha works but zigbee2mqtt not

**Comment by Teunhen** [comment]
I fixed the issue by starting the integration without the antenna screwed on the sonof stick. Then i changed the channel and id. No problems since.

**Comment by rsporsche** [comment]
I'm getting the same thing, how do you change the panID and other advanced settings? The configuration tab in home assistant doesn't include an advanced section and I can't figure out which configuration file to edit - when I set the serial settings I don't find them in any *.yaml file on the system.

**Comment by Victor4X** [comment]
> I'm getting the same thing, how do you change the panID and other advanced settings? The configuration tab in home assistant doesn't include an advanced section and I can't figure out which configuration file to edit - when I set the serial settings I don't find them in any *.yaml file on the system.

The file you want to edit is `/config/zigbee2mqtt/configuration.yaml`
