### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by TrustedFloppa** [zigbee2mqtt/hassio-zigbee2mqtt#449]
### Description of the issue

I configured my configuration and it worked before on old hass but i installed hass on new hard drive and used same configuration and it didn't work

### Addon version

1.29.2-1

### Platform

Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.4

### Logs of the issue (if applicable)

[19:51:40] INFO: Preparing to start...
[19:51:40] INFO: Socat enabled
[19:51:40] INFO: Starting socat
Socat startup parameters:
Options:     -d -d
Master:      pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
Slave:       tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
[19:51:40] INFO: Starting socat process ...
2023/01/26 19:51:40 socat[53] N PTY is /dev/pts/0
2023/01/26 19:51:40 socat[53] N listening on AF=2 0.0.0.0:8485
[19:51:41] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-01-26 19:51:43: Logging to console and directory: '/config/zigbee2mqtt/log/2023-01-26.19-51-43' filename: log.txt
Zigbee2MQTT:info  2023-01-26 19:51:43: Starting Zigbee2MQTT version 1.29.2 (commit #unknown)
Zigbee2MQTT:info  2023-01-26 19:51:43: Starting zigbee-herdsman (0.14.83-hotfix.0)
Zigbee2MQTT:error 2023-01-26 19:52:02: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-01-26 19:52:02: Failed to start zigbee
Zigbee2MQTT:error 2023-01-26 19:52:02: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-01-26 19:52:02: Exiting...
Zigbee2MQTT:error 2023-01-26 19:52:02: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

**Comment by RobertusIT** [comment]
same here....

**Comment by faken** [comment]
Having the same issue.

**Comment by TrustedFloppa** [comment]
I fixed it! here is what i did.
## Serial in addon
serial:
  port: tcp://192.168.1.7:8888
adapter: ezsp
**Used ezsp because i have Xiaomi Gateway 3 with zigbee2mqtt, Replace with your serial port**
## Serial in configuration.yaml in zigbee2mqtt folder
homeassistant: true
frontend:
  port: 8099
serial:
  port: tcp://192.168.1.7:8888
  adapter: ezsp
**Also replace**

Thats all i did. Also make sure you have right mqtt info
