### ISSUE TITLE
Zigbee2mqtt HA add-on won't start after updating from 1.17.1-4 to 1.18.0-1

### ISSUE THREAD

**Issue by fss** [zigbee2mqtt/hassio-zigbee2mqtt#45]
**Description of problem:**
Zigbee2mqtt HA add-on won't start after updating from 1.17.1-4 to 1.18.0-1

After today's update my add-on refused to start, I had to manually edit configuration file by adding:
```
ota:
  update_check_interval: 10
  disable_automatic_update_check: false
```

This should be done automatically during update

**Comment by dude75** [comment]
tnx bro

**Comment by avdeevsv91** [comment]
Just this is enough:
```
ota: {}
```

**Comment by McGiverGim** [comment]
Yes, same problem here.
I did a rollback using a snapshot until fixed officially.

**Comment by ciotlosm** [comment]
Adding options automatically is a bit problematic, as it's a one time thing. Usually such breaking changes should be addressed in the changelog. Ideally Home Assistant Supervisor would give some sort of functionality for two levels and optional parameters. 

Can you try 1.18.1-1 and see if that fixes your problem?

**Comment by McGiverGim** [comment]
I'm my case yes, it fixed the problem.
