### ISSUE TITLE
Unable to start zigbee2MQTT after Home Assistant Core Operating System 9.5 update 

### ISSUE THREAD

**Issue by ht38f** [zigbee2mqtt/hassio-zigbee2mqtt#450]
### Description of the issue

After the update from 9.4 to 9.5 zigbee2MQTT is not able to start.
It does not start at reboot, it does not start after a power cycle and it is not possible to start it manually.

I restored to the backup before updating to 9.5, but the core update is not rolled back so its still not able to start.

### Addon version

v 1.29.2-1

### Platform

Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230110.0 - latest

### Logs of the issue (if applicable)

[22:43:17] INFO: Preparing to start...
[22:43:18] INFO: Socat not enabled
[22:43:21] INFO: Starting Zigbee2MQTT...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            READ THIS CAREFULLY
Refusing to start because configuration is not valid, found the following errors:
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5
If you don't know how to solve this, read https://www.zigbee2mqtt.io/guide/configuration
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ht38f** [comment]
Solved
Added version: 5 

homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt-user
  password: my_password
  version: 5

**Comment by crazymonster999** [comment]
I had the same issue after updating HA Core.
To solve this issue, I updated the Z2M config file under /config/zigbee2mqtt/configuration.yaml
Then, I added **version: 5** under mqtt topic : 
```
mqtt:
  base_topic: zigbee2mqtt
  user: addons
  password: ***
  server: mqtt://core-mosquitto:1883
  version: 5
```
And restarted the Z2M addon...
