### ISSUE TITLE
Zigbee2MQTT Add-on is not running. Please start it first

### ISSUE THREAD

**Issue by Prosper-Thaels** [zigbee2mqtt/hassio-zigbee2mqtt#453]
### Description of the issue

After an upgrade Zigbee2Mqtt is not working anymore. USB dongle works perfect. No errors in all logfiles. 

Uninstalled Zigbee2Mqtt. Removed all files. Reinstalled. Same problem

### Addon version

1.30.0-1

### Platform

Home Assistant 2023.2.1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

### Logs of the issue (if applicable)

[14:42:12] INFO: Preparing to start...
[14:42:12] INFO: Socat not enabled
[14:42:12] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-02-03 14:42:14: Logging to console and directory: '/config/zigbee2mqtt/log/2023-02-03.14-42-14' filename: log.txt
Zigbee2MQTT:info  2023-02-03 14:42:14: Starting Zigbee2MQTT version 1.30.0 (commit #unknown)
Zigbee2MQTT:info  2023-02-03 14:42:14: Starting zigbee-herdsman (0.14.89)
Zigbee2MQTT:info  2023-02-03 14:42:24: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2023-02-03 14:42:24: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20220219,"transportrev":2},"type":"zStack3x0"}'
Zigbee2MQTT:info  2023-02-03 14:42:24: Currently 0 devices are joined:
Zigbee2MQTT:info  2023-02-03 14:42:24: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2023-02-03 14:42:24: Connecting to MQTT server at mqtt://192.168.2.6:1883
Zigbee2MQTT:info  2023-02-03 14:42:24: Connected to MQTT server
Zigbee2MQTT:info  2023-02-03 14:42:24: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2023-02-03 14:42:24: Started frontend on port 0.0.0.0:8099
Zigbee2MQTT:info  2023-02-03 14:42:24: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"unknown","coordinator":{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20220219,"transportrev":2},"type":"zStack3x0"},"log_level":"info","network":{"channel":11,"extendedPanID":"0x00124b0024c0c43d","panID":6754},"permit_join":false,"version":"1.30.0"}'
Zigbee2MQTT:info  2023-02-03 14:42:24: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2023-02-03 14:42:24: Zigbee2MQTT started!

**Comment by Prosper-Thaels** [comment]
Ow, also tried to restore from backup. Did not work as well.

**Comment by Prosper-Thaels** [comment]
Reboot HA docker did not work. Complete restart pc did the trick.

**Comment by Littleislandbrewing** [comment]
same here - exact same thing. Complete restart required
