### ISSUE TITLE
TS0601_dimmer max_brightness doesn't work

### ISSUE THREAD

**Issue by Sashik259** [zigbee2mqtt/hassio-zigbee2mqtt#454]
### Description of the issue

I set "max_brightness" value for TS0601_dimmer at "Exposes" tab in Zigbbee2TQTT add-on.
Then I go to another tab and return to "Exposes" tab.
I see the "max_brightness" value is empty.

State tab shows this:
```
{
    "brightness": 103,
    "last_seen": "2023-02-04T07:14:51.923Z",
    "linkquality": 61,
    "min_brightness": 40,
    "state": "OFF"
}
```

### Addon version

1.30.0-1

### Platform

System Information

version | core-2023.2.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8+
arch | aarch64
timezone | Europe/Moscow
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 113.1 GB
disk_used | 10.2 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.1.3), Zigbee2MQTT (1.30.0-1), File editor (5.5.0), ESPHome (2022.12.8), Studio Code Server (5.5.2), Samba share (10.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 27, 2023, 6:39 PM
-- | --
current_recorder_run | February 4, 2023, 9:05 AM
estimated_db_size | 928.16 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Logs of the issue (if applicable)

Debug 2023-02-04 10:15:00Received MQTT message on 'zigbee2mqtt/bedroom_lamp/set' with data '{"max_brightness":120}'
Debug 2023-02-04 10:15:00Publishing 'set' 'max_brightness' to 'bedroom_lamp'

**Comment by Sashik259** [comment]
`{"id":19,"type":"Router","ieeeAddr":"","nwkAddr":37147,"manufId":4098,"manufName":"_TZE200_w4cryh2i","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0005","65506":31,"65508":0,"65534":0,"modelId":"TS0601","manufacturerName":"_TZE200_w4cryh2i","powerSource":1,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c83f95","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c83f95","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-24894193},"lastSeen":1675525973559,"defaultSendRequestWhen":"immediate"}
`

**Comment by Sashik259** [comment]
The same with 1.30.2-1 Zigbee2MQTT Addon

**Comment by Sashik259** [comment]
The same with 1.30.3-1 Zigbee2MQTT Addon

**Comment by Sashik259** [comment]
The same with 1.30.4-1 Zigbee2MQTT Addon

**Comment by gdbd** [comment]
i am have that issue too on MOES version of TS0601: _TZE200_w4cryh2i

@Koenkk can it bee fixed?

**Comment by Koenkk** [comment]
Let's continue in https://github.com/Koenkk/zigbee2mqtt/issues/16701
