### ISSUE TITLE
Senic Gira Friends of hue Smart Switch support

### ISSUE THREAD

**Issue by platini76** [zigbee2mqtt/hassio-zigbee2mqtt#455]
### Description of the issue

I have problem on supporting this switch: system says that it is supported but no actions are displayed.

<img width="1298" alt="Screenshot 2023-02-04 alle 16 38 07" src="https://user-images.githubusercontent.com/10352902/216776204-21dc9fd3-3b9b-45ff-8e41-4a1113f029a9.png">
<img width="1433" alt="Screenshot 2023-02-04 alle 16 38 01" src="https://user-images.githubusercontent.com/10352902/216776209-810176e1-dda2-4ca9-aec7-633473f13bf8.png">

### Addon version

 1.30.0-1 

### Platform

Home Assistant 2023.2.1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

**Comment by platini76** [comment]
noone can help me?

**Comment by TrustedFloppa** [comment]
is it like a wall switch to switch light or button?
