### ISSUE TITLE
Moes (TuYa) TS0011 does not have backlight mode available under Configuration.

### ISSUE THREAD

**Issue by Sashik259** [zigbee2mqtt/hassio-zigbee2mqtt#456]
### Description of the issue

Moes (TuYa) TS0011 does not have backlight mode available under Configuration.
Moes (TuYa) TS0012 works fine

### Addon version

1.30.0-1

## System Information

version | core-2023.2.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8+
arch | aarch64
timezone | Europe/Moscow
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 113.1 GB
disk_used | 10.0 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.1.3), Zigbee2MQTT (1.30.0-1), File editor (5.5.0), ESPHome (2022.12.8), Studio Code Server (5.5.2), Samba share (10.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 27, 2023, 6:39 PM
-- | --
current_recorder_run | February 4, 2023, 9:05 AM
estimated_db_size | 928.16 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by Sashik259** [comment]
`{"id":7,"type":"EndDevice","ieeeAddr":"0xbc33acfffe11f671","nwkAddr":58318,"manufId":4098,"manufName":"_TYZB01_qeqvmvti","powerSource":"Mains (single phase)","modelId":"TS0011","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,4,5,6],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"65506":19,"65534":0,"modelId":"TS0011","manufacturerName":"_TYZB01_qeqvmvti","powerSource":3,"appVersion":65,"zclVersion":3,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff0622f3","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c83f95","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1071524409},"lastSeen":1675524597209,"defaultSendRequestWhen":"immediate"}
`

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
