### ISSUE TITLE
 Invalid state encountered for entity ID: sensor.xxx. State max length is 255 characters

### ISSUE THREAD

**Issue by osre77** [zigbee2mqtt/hassio-zigbee2mqtt#459]
### Description of the issue

Starting with V1.30.0 I get the following error for all of my thermostats of the type Moes Model BHT-002-GCLZB every 80 milliseconds.
After about 10 to 12 hours Home Assistant does not respond anymore and I have to power off the hardware.
Turning the log level to critical so the logfile does not get that huge did not stop the issue.
But going back to 1.29.2 got rid of the error message again.

### Addon version

v1.30.0

### Platform

Home Assistant 2023.2.3
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

### Logs of the issue (if applicable)

2023-02-07 18:03:51.368 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback MQTT._mqtt_handle_message(<paho.mqtt.cl...xffff78fa2420>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 693, in _mqtt_handle_message
    self._mqtt_data.state_write_requests.process_write_state_requests()
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 267, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 683, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1512, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1144, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.thermostat_buro_program. State max length is 255 characters.

**Comment by osre77** [comment]
With 1.29.2 HA does not get unresponsive anymore, but now I have a different isse.
After a while the log goes from this:
`info  2023-02-09 19:36:10: MQTT publish: topic 'zigbee2mqtt/temp/eg/child', payload '{"child_lock":"UNLOCK","current_heating_setpoint":17,"deadzone_temperature":1,"heat":"OFF","last_seen":"2023-02-09T19:36:10+01:00","linkquality":172,"local_temperature":19,"local_temperature_calibration":-2,"max_temperature":35,"max_temperature_limit":35,"min_temperature_limit":1,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":6,"saturday_p1_minute":0,"saturday_p1_temperature":24,"saturday_p2_hour":12,"saturday_p2_minute":0,"saturday_p2_temperature":23,"saturday_p3_hour":14,"saturday_p3_minute":30,"saturday_p3_temperature":22,"saturday_p4_hour":17,"saturday_p4_minute":30,"saturday_p4_temperature":21,"sunday_p1_hour":6,"sunday_p1_minute":0,"sunday_p1_temperature":19,"sunday_p2_hour":12,"sunday_p2_minute":30,"sunday_p2_temperature":20,"sunday_p3_hour":14,"sunday_p3_minute":30,"sunday_p3_temperature":21,"sunday_p4_hour":18,"sunday_p4_minute":30,"sunday_p4_temperature":20,"weekdays_p1_hour":6,"weekdays_p1_minute":0,"weekdays_p1_temperature":20,"weekdays_p2_hour":11,"weekdays_p2_minute":30,"weekdays_p2_temperature":21,"weekdays_p3_hour":13,"weekdays_p3_minute":30,"weekdays_p3_temperature":22,"weekdays_p4_hour":17,"weekdays_p4_minute":30,"weekdays_p4_temperature":23},"running_state":"idle","sensor":"AL","system_mode":"heat"}'
info  2023-02-09 19:36:10: MQTT publish: topic 'zigbee2mqtt/temp/ug/bedroom', payload '{"child_lock":"UNLOCK","current_heating_setpoint":16,"deadzone_temperature":1,"heat":"OFF","last_seen":"2023-02-09T19:36:10+01:00","linkquality":180,"local_temperature":18,"local_temperature_calibration":-2,"max_temperature":35,"max_temperature_limit":35,"min_temperature_limit":1,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":6,"saturday_p1_minute":0,"saturday_p1_temperature":24,"saturday_p2_hour":12,"saturday_p2_minute":0,"saturday_p2_temperature":23,"saturday_p3_hour":14,"saturday_p3_minute":30,"saturday_p3_temperature":22,"saturday_p4_hour":17,"saturday_p4_minute":30,"saturday_p4_temperature":21,"sunday_p1_hour":6,"sunday_p1_minute":0,"sunday_p1_temperature":19,"sunday_p2_hour":12,"sunday_p2_minute":30,"sunday_p2_temperature":20,"sunday_p3_hour":14,"sunday_p3_minute":30,"sunday_p3_temperature":21,"sunday_p4_hour":18,"sunday_p4_minute":30,"sunday_p4_temperature":20,"weekdays_p1_hour":6,"weekdays_p1_minute":0,"weekdays_p1_temperature":20,"weekdays_p2_hour":11,"weekdays_p2_minute":30,"weekdays_p2_temperature":21,"weekdays_p3_hour":13,"weekdays_p3_minute":30,"weekdays_p3_temperature":22,"weekdays_p4_hour":17,"weekdays_p4_minute":30,"weekdays_p4_temperature":23},"running_state":"idle","sensor":"AL","system_mode":"heat"}'
info  2023-02-09 19:36:11: MQTT publish: topic 'zigbee2mqtt/temp/ug/bathroom', payload '{"child_lock":"UNLOCK","current_heating_setpoint":21,"deadzone_temperature":1,"heat":"OFF","last_seen":"2023-02-09T19:36:10+01:00","linkquality":164,"local_temperature":20.5,"local_temperature_calibration":-2,"max_temperature":35,"max_temperature_limit":35,"min_temperature_limit":1,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":6,"saturday_p1_minute":0,"saturday_p1_temperature":24,"saturday_p2_hour":12,"saturday_p2_minute":0,"saturday_p2_temperature":23,"saturday_p3_hour":14,"saturday_p3_minute":30,"saturday_p3_temperature":22,"saturday_p4_hour":17,"saturday_p4_minute":30,"saturday_p4_temperature":21,"sunday_p1_hour":6,"sunday_p1_minute":0,"sunday_p1_temperature":19,"sunday_p2_hour":12,"sunday_p2_minute":30,"sunday_p2_temperature":20,"sunday_p3_hour":14,"sunday_p3_minute":30,"sunday_p3_temperature":21,"sunday_p4_hour":18,"sunday_p4_minute":30,"sunday_p4_temperature":20,"weekdays_p1_hour":6,"weekdays_p1_minute":0,"weekdays_p1_temperature":20,"weekdays_p2_hour":11,"weekdays_p2_minute":30,"weekdays_p2_temperature":21,"weekdays_p3_hour":13,"weekdays_p3_minute":30,"weekdays_p3_temperature":22,"weekdays_p4_hour":17,"weekdays_p4_minute":30,"weekdays_p4_temperature":23},"running_state":"idle","sensor":"AL","system_mode":"heat"}'
info  2023-02-09 19:36:11: MQTT publish: topic 'zigbee2mqtt/temp/ug/roomwest', payload '{"child_lock":"UNLOCK","current_heating_setpoint":18,"deadzone_temperature":1,"heat":"OFF","last_seen":"2023-02-09T19:36:10+01:00","linkquality":232,"local_temperature":18.5,"local_temperature_calibration":-2,"max_temperature":35,"max_temperature_limit":35,"min_temperature_limit":1,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":6,"saturday_p1_minute":0,"saturday_p1_temperature":24,"saturday_p2_hour":12,"saturday_p2_minute":0,"saturday_p2_temperature":23,"saturday_p3_hour":14,"saturday_p3_minute":30,"saturday_p3_temperature":22,"saturday_p4_hour":17,"saturday_p4_minute":30,"saturday_p4_temperature":21,"sunday_p1_hour":6,"sunday_p1_minute":0,"sunday_p1_temperature":19,"sunday_p2_hour":12,"sunday_p2_minute":30,"sunday_p2_temperature":20,"sunday_p3_hour":14,"sunday_p3_minute":30,"sunday_p3_temperature":21,"sunday_p4_hour":18,"sunday_p4_minute":30,"sunday_p4_temperature":20,"weekdays_p1_hour":6,"weekdays_p1_minute":0,"weekdays_p1_temperature":20,"weekdays_p2_hour":11,"weekdays_p2_minute":30,"weekdays_p2_temperature":21,"weekdays_p3_hour":13,"weekdays_p3_minute":30,"weekdays_p3_temperature":22,"weekdays_p4_hour":17,"weekdays_p4_minute":30,"weekdays_p4_temperature":23},"running_state":"idle","sensor":"AL","system_mode":"heat"}'
`
to this
`warn  2023-02-09 19:39:53: Failed to ping 'socket/valve_index_2' (attempt 1/2, Read 0xf0d1b800001cc3bc/1 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error))
warn  2023-02-09 19:39:56: Failed to ping 'socket/valve_index_2' (attempt 2/2, Read 0xf0d1b800001cc3bc/1 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error))
info  2023-02-09 19:39:59: MQTT publish: topic 'zigbee2mqtt/socket/valve_index_2/availability', payload 'offline'
`
and does not recover until I restart Zigbee2MQTT.
Something is seriously wrong here.
Any help, hint whatever is much appreciated.

**Comment by osre77** [comment]
With 1.29.2 HA does not get unresponsive anymore, but now I have a different isse.
After a while the log goes from this:
`info  2023-02-09 19:36:10: MQTT publish: topic 'zigbee2mqtt/temp/eg/child', payload '{"child_lock":"UNLOCK","current_heating_setpoint":17,"deadzone_temperature":1,"heat":"OFF","last_seen":"2023-02-09T19:36:10+01:00","linkquality":172,"local_temperature":19,"local_temperature_calibration":-2,"max_temperature":35,"max_temperature_limit":35,"min_temperature_limit":1,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":6,"saturday_p1_minute":0,"saturday_p1_temperature":24,"saturday_p2_hour":12,"saturday_p2_minute":0,"saturday_p2_temperature":23,"saturday_p3_hour":14,"saturday_p3_minute":30,"saturday_p3_temperature":22,"saturday_p4_hour":17,"saturday_p4_minute":30,"saturday_p4_temperature":21,"sunday_p1_hour":6,"sunday_p1_minute":0,"sunday_p1_temperature":19,"sunday_p2_hour":12,"sunday_p2_minute":30,"sunday_p2_temperature":20,"sunday_p3_hour":14,"sunday_p3_minute":30,"sunday_p3_temperature":21,"sunday_p4_hour":18,"sunday_p4_minute":30,"sunday_p4_temperature":20,"weekdays_p1_hour":6,"weekdays_p1_minute":0,"weekdays_p1_temperature":20,"weekdays_p2_hour":11,"weekdays_p2_minute":30,"weekdays_p2_temperature":21,"weekdays_p3_hour":13,"weekdays_p3_minute":30,"weekdays_p3_temperature":22,"weekdays_p4_hour":17,"weekdays_p4_minute":30,"weekdays_p4_temperature":23},"running_state":"idle","sensor":"AL","system_mode":"heat"}'
info  2023-02-09 19:36:10: MQTT publish: topic 'zigbee2mqtt/temp/ug/bedroom', payload '{"child_lock":"UNLOCK","current_heating_setpoint":16,"deadzone_temperature":1,"heat":"OFF","last_seen":"2023-02-09T19:36:10+01:00","linkquality":180,"local_temperature":18,"local_temperature_calibration":-2,"max_temperature":35,"max_temperature_limit":35,"min_temperature_limit":1,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":6,"saturday_p1_minute":0,"saturday_p1_temperature":24,"saturday_p2_hour":12,"saturday_p2_minute":0,"saturday_p2_temperature":23,"saturday_p3_hour":14,"saturday_p3_minute":30,"saturday_p3_temperature":22,"saturday_p4_hour":17,"saturday_p4_minute":30,"saturday_p4_temperature":21,"sunday_p1_hour":6,"sunday_p1_minute":0,"sunday_p1_temperature":19,"sunday_p2_hour":12,"sunday_p2_minute":30,"sunday_p2_temperature":20,"sunday_p3_hour":14,"sunday_p3_minute":30,"sunday_p3_temperature":21,"sunday_p4_hour":18,"sunday_p4_minute":30,"sunday_p4_temperature":20,"weekdays_p1_hour":6,"weekdays_p1_minute":0,"weekdays_p1_temperature":20,"weekdays_p2_hour":11,"weekdays_p2_minute":30,"weekdays_p2_temperature":21,"weekdays_p3_hour":13,"weekdays_p3_minute":30,"weekdays_p3_temperature":22,"weekdays_p4_hour":17,"weekdays_p4_minute":30,"weekdays_p4_temperature":23},"running_state":"idle","sensor":"AL","system_mode":"heat"}'
info  2023-02-09 19:36:11: MQTT publish: topic 'zigbee2mqtt/temp/ug/bathroom', payload '{"child_lock":"UNLOCK","current_heating_setpoint":21,"deadzone_temperature":1,"heat":"OFF","last_seen":"2023-02-09T19:36:10+01:00","linkquality":164,"local_temperature":20.5,"local_temperature_calibration":-2,"max_temperature":35,"max_temperature_limit":35,"min_temperature_limit":1,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":6,"saturday_p1_minute":0,"saturday_p1_temperature":24,"saturday_p2_hour":12,"saturday_p2_minute":0,"saturday_p2_temperature":23,"saturday_p3_hour":14,"saturday_p3_minute":30,"saturday_p3_temperature":22,"saturday_p4_hour":17,"saturday_p4_minute":30,"saturday_p4_temperature":21,"sunday_p1_hour":6,"sunday_p1_minute":0,"sunday_p1_temperature":19,"sunday_p2_hour":12,"sunday_p2_minute":30,"sunday_p2_temperature":20,"sunday_p3_hour":14,"sunday_p3_minute":30,"sunday_p3_temperature":21,"sunday_p4_hour":18,"sunday_p4_minute":30,"sunday_p4_temperature":20,"weekdays_p1_hour":6,"weekdays_p1_minute":0,"weekdays_p1_temperature":20,"weekdays_p2_hour":11,"weekdays_p2_minute":30,"weekdays_p2_temperature":21,"weekdays_p3_hour":13,"weekdays_p3_minute":30,"weekdays_p3_temperature":22,"weekdays_p4_hour":17,"weekdays_p4_minute":30,"weekdays_p4_temperature":23},"running_state":"idle","sensor":"AL","system_mode":"heat"}'
info  2023-02-09 19:36:11: MQTT publish: topic 'zigbee2mqtt/temp/ug/roomwest', payload '{"child_lock":"UNLOCK","current_heating_setpoint":18,"deadzone_temperature":1,"heat":"OFF","last_seen":"2023-02-09T19:36:10+01:00","linkquality":232,"local_temperature":18.5,"local_temperature_calibration":-2,"max_temperature":35,"max_temperature_limit":35,"min_temperature_limit":1,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":6,"saturday_p1_minute":0,"saturday_p1_temperature":24,"saturday_p2_hour":12,"saturday_p2_minute":0,"saturday_p2_temperature":23,"saturday_p3_hour":14,"saturday_p3_minute":30,"saturday_p3_temperature":22,"saturday_p4_hour":17,"saturday_p4_minute":30,"saturday_p4_temperature":21,"sunday_p1_hour":6,"sunday_p1_minute":0,"sunday_p1_temperature":19,"sunday_p2_hour":12,"sunday_p2_minute":30,"sunday_p2_temperature":20,"sunday_p3_hour":14,"sunday_p3_minute":30,"sunday_p3_temperature":21,"sunday_p4_hour":18,"sunday_p4_minute":30,"sunday_p4_temperature":20,"weekdays_p1_hour":6,"weekdays_p1_minute":0,"weekdays_p1_temperature":20,"weekdays_p2_hour":11,"weekdays_p2_minute":30,"weekdays_p2_temperature":21,"weekdays_p3_hour":13,"weekdays_p3_minute":30,"weekdays_p3_temperature":22,"weekdays_p4_hour":17,"weekdays_p4_minute":30,"weekdays_p4_temperature":23},"running_state":"idle","sensor":"AL","system_mode":"heat"}'
`
to this
`warn  2023-02-09 19:39:53: Failed to ping 'socket/valve_index_2' (attempt 1/2, Read 0xf0d1b800001cc3bc/1 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error))
warn  2023-02-09 19:39:56: Failed to ping 'socket/valve_index_2' (attempt 2/2, Read 0xf0d1b800001cc3bc/1 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error))
info  2023-02-09 19:39:59: MQTT publish: topic 'zigbee2mqtt/socket/valve_index_2/availability', payload 'offline'
`
and does not recover until I restart Zigbee2MQTT.
Something is seriously wrong here

**Comment by osre77** [comment]
Another day, another behavior:
This time it simply stopped doing anything, looks like it dosn't want to update any sensor anymore.
The last log entry was a success, but then for multiple hours nothing.
When I tried to turn a Zigbee power sockt on I got the follosing in the log:
`error 2023-02-10 16:18:03: Publish 'set' 'state' to 'socket/valve_index_1' failed: 'Error: Command 0xf0d1b800001cd022/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)'
info  2023-02-10 16:18:03: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'socket/valve_index_1' failed: 'Error: Command 0xf0d1b800001cd022/1 genOnOff.on({}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (sendZclFrameToEndpointInternal error)'","meta":{"friendly_name":"socket/valve_index_1"},"type":"zigbee_publish_error"}'
`

**Comment by samourai64** [comment]
Hello
No solution at this time with and update....

**Comment by osre77** [comment]
I have monitored this for a couple of days now.
HASS_Zigbee2mqtt always stops working after a while. This can be right after startup/restart, or sometimes a couple of hours later.
Then it does nothing (no logs, no new values, ....) for a couple of hours.
Eventually it restarts on its own. I assume it crashes and the HA watchdog restarts it.
The logs say nothing.
In the current state my HA system is completely useless.
If anyone would ask me to activate some additional logs, test something out, ... I would happily do so and provide more information.

**Comment by osre77** [comment]
Issue is still there

**Comment by samourai64** [comment]
Yes issue has no solution at this moment
Thank's

**Comment by dvbit** [comment]
This is due to some state in homeassistant that is longer than 255 chars.

**Comment by samourai64** [comment]
Yes issue has no solution at this moment
Thank's

`Logger: homeassistant.components.mqtt.models
Source: core.py:1196
Integration: MQTT (documentation, issues)
First occurred: 29 avril 2023 à 17:52:30 (1345 occurrences)
Last logged: 09:16:51

Exception raised when updating state of sensor.thermostat_program, topic: 'zigbee2mqtt/Thermostat' with payload: b'{"child_lock":"UNLOCK","current_heating_setpoint":18,"deadzone_temperature":0,"heat":"OFF","linkquality":185,"local_temperature":16.5,"local_temperature_calibration":-3,"max_temperature_limit":33,"min_temperature_limit":null,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":0,"saturday_p1_minute":0,"saturday_p1_temperature":7,"saturday_p2_hour":6,"saturday_p2_minute":0,"saturday_p2_temperature":7,"saturday_p3_hour":16,"saturday_p3_minute":0,"saturday_p3_temperature":7,"saturday_p4_hour":21,"saturday_p4_minute":0,"saturday_p4_temperature":7,"sunday_p1_hour":0,"sunday_p1_minute":0,"sunday_p1_temperature":7,"sunday_p2_hour":6,"sunday_p2_minute":0,"sunday_p2_temperature":7,"sunday_p3_hour":16,"sunday_p3_minute":0,"sunday_p3_temperature":7,"sunday_p4_hour":21,"sunday_p4_minute":0,"sunday_p4_temperature":7,"weekdays_p1_hour":0,"weekdays_p1_minute":0,"weekdays_p1_temperature":7,"weekdays_p2_hour":6,"weekdays_p2_minute":0,"weekdays_p2_temperature":15,"weekdays_p3_hour":16,"weekdays_p3_minute":0,"weekdays_p3_temperature":7,"weekdays_p4_hour":21,"weekdays_p4_minute":0,"weekdays_p4_temperature":7},"running_state":"idle","sensor":"AL","system_mode":"off"}'
Exception raised when updating state of sensor.thermostat_program, topic: 'zigbee2mqtt/Thermostat' with payload: b'{"child_lock":"UNLOCK","current_heating_setpoint":18,"deadzone_temperature":0,"heat":"OFF","linkquality":182,"local_temperature":16.5,"local_temperature_calibration":-3,"max_temperature_limit":33,"min_temperature_limit":null,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":0,"saturday_p1_minute":0,"saturday_p1_temperature":7,"saturday_p2_hour":6,"saturday_p2_minute":0,"saturday_p2_temperature":7,"saturday_p3_hour":16,"saturday_p3_minute":0,"saturday_p3_temperature":7,"saturday_p4_hour":21,"saturday_p4_minute":0,"saturday_p4_temperature":7,"sunday_p1_hour":0,"sunday_p1_minute":0,"sunday_p1_temperature":7,"sunday_p2_hour":6,"sunday_p2_minute":0,"sunday_p2_temperature":7,"sunday_p3_hour":16,"sunday_p3_minute":0,"sunday_p3_temperature":7,"sunday_p4_hour":21,"sunday_p4_minute":0,"sunday_p4_temperature":7,"weekdays_p1_hour":0,"weekdays_p1_minute":0,"weekdays_p1_temperature":7,"weekdays_p2_hour":6,"weekdays_p2_minute":0,"weekdays_p2_temperature":15,"weekdays_p3_hour":16,"weekdays_p3_minute":0,"weekdays_p3_temperature":7,"weekdays_p4_hour":21,"weekdays_p4_minute":0,"weekdays_p4_temperature":7},"running_state":"idle","sensor":"AL","system_mode":"off"}'
Exception raised when updating state of sensor.thermostat_program, topic: 'zigbee2mqtt/Thermostat' with payload: b'{"child_lock":"UNLOCK","current_heating_setpoint":18,"deadzone_temperature":0,"heat":"OFF","linkquality":145,"local_temperature":16.5,"local_temperature_calibration":-3,"max_temperature_limit":33,"min_temperature_limit":null,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":0,"saturday_p1_minute":0,"saturday_p1_temperature":7,"saturday_p2_hour":6,"saturday_p2_minute":0,"saturday_p2_temperature":7,"saturday_p3_hour":16,"saturday_p3_minute":0,"saturday_p3_temperature":7,"saturday_p4_hour":21,"saturday_p4_minute":0,"saturday_p4_temperature":7,"sunday_p1_hour":0,"sunday_p1_minute":0,"sunday_p1_temperature":7,"sunday_p2_hour":6,"sunday_p2_minute":0,"sunday_p2_temperature":7,"sunday_p3_hour":16,"sunday_p3_minute":0,"sunday_p3_temperature":7,"sunday_p4_hour":21,"sunday_p4_minute":0,"sunday_p4_temperature":7,"weekdays_p1_hour":0,"weekdays_p1_minute":0,"weekdays_p1_temperature":7,"weekdays_p2_hour":6,"weekdays_p2_minute":0,"weekdays_p2_temperature":15,"weekdays_p3_hour":16,"weekdays_p3_minute":0,"weekdays_p3_temperature":7,"weekdays_p4_hour":21,"weekdays_p4_minute":0,"weekdays_p4_temperature":7},"running_state":"idle","sensor":"AL","system_mode":"off"}'
Exception raised when updating state of sensor.thermostat_program, topic: 'zigbee2mqtt/Thermostat' with payload: b'{"child_lock":"UNLOCK","current_heating_setpoint":18,"deadzone_temperature":0,"heat":"OFF","linkquality":149,"local_temperature":16.5,"local_temperature_calibration":-3,"max_temperature_limit":33,"min_temperature_limit":null,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":0,"saturday_p1_minute":0,"saturday_p1_temperature":7,"saturday_p2_hour":6,"saturday_p2_minute":0,"saturday_p2_temperature":7,"saturday_p3_hour":16,"saturday_p3_minute":0,"saturday_p3_temperature":7,"saturday_p4_hour":21,"saturday_p4_minute":0,"saturday_p4_temperature":7,"sunday_p1_hour":0,"sunday_p1_minute":0,"sunday_p1_temperature":7,"sunday_p2_hour":6,"sunday_p2_minute":0,"sunday_p2_temperature":7,"sunday_p3_hour":16,"sunday_p3_minute":0,"sunday_p3_temperature":7,"sunday_p4_hour":21,"sunday_p4_minute":0,"sunday_p4_temperature":7,"weekdays_p1_hour":0,"weekdays_p1_minute":0,"weekdays_p1_temperature":7,"weekdays_p2_hour":6,"weekdays_p2_minute":0,"weekdays_p2_temperature":15,"weekdays_p3_hour":16,"weekdays_p3_minute":0,"weekdays_p3_temperature":7,"weekdays_p4_hour":21,"weekdays_p4_minute":0,"weekdays_p4_temperature":7},"running_state":"idle","sensor":"AL","system_mode":"off"}'
Exception raised when updating state of sensor.thermostat_program, topic: 'zigbee2mqtt/Thermostat' with payload: b'{"child_lock":"UNLOCK","current_heating_setpoint":18,"deadzone_temperature":0,"heat":"OFF","linkquality":178,"local_temperature":16.5,"local_temperature_calibration":-3,"max_temperature_limit":33,"min_temperature_limit":null,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":0,"saturday_p1_minute":0,"saturday_p1_temperature":7,"saturday_p2_hour":6,"saturday_p2_minute":0,"saturday_p2_temperature":7,"saturday_p3_hour":16,"saturday_p3_minute":0,"saturday_p3_temperature":7,"saturday_p4_hour":21,"saturday_p4_minute":0,"saturday_p4_temperature":7,"sunday_p1_hour":0,"sunday_p1_minute":0,"sunday_p1_temperature":7,"sunday_p2_hour":6,"sunday_p2_minute":0,"sunday_p2_temperature":7,"sunday_p3_hour":16,"sunday_p3_minute":0,"sunday_p3_temperature":7,"sunday_p4_hour":21,"sunday_p4_minute":0,"sunday_p4_temperature":7,"weekdays_p1_hour":0,"weekdays_p1_minute":0,"weekdays_p1_temperature":7,"weekdays_p2_hour":6,"weekdays_p2_minute":0,"weekdays_p2_temperature":15,"weekdays_p3_hour":16,"weekdays_p3_minute":0,"weekdays_p3_temperature":7,"weekdays_p4_hour":21,"weekdays_p4_minute":0,"weekdays_p4_temperature":7},"running_state":"idle","sensor":"AL","system_mode":"off"}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 689, in _async_write_ha_state
    hass.states.async_set(entity_id, state, attr, self.force_update, self._context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1547, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1196, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.thermostat_program. State max length is 255 characters.
`

**Comment by osre77** [comment]
I switched to ZHA today. It dosn't support all of the features (like Child Lock) out of the box, but at least it works.

**Comment by blackmasterbeast** [comment]
Yes issue has no solution at this moment
Thank's

**Comment by Spica2000** [comment]
I also have this issue.

**Comment by Koenkk** [comment]
Should be fixed in the next z2m release
