### ISSUE TITLE
Home assistant addon, how to use  zigbee-herdsman-converters

### ISSUE THREAD

**Issue by viciovb** [zigbee2mqtt/hassio-zigbee2mqtt#460]
### Description of the issue

I'm trying to add some unsupported device with the zigbee-herdsman-converters but the js I need to create specify some folder that I don't know where to find like

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');

I tried downloading zigbee-herdsman-converters from github, put it on home assistant and change the path but it doesn't work. 

How can I use zigbee-herdsman-converters with zigbee2mqtt as an HA addon and not in a docker container?

### Addon version

1.30.1-1 and Edge

### Platform

Home Assistant 2023.2.3
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

**Comment by Koenkk** [comment]
This is not needed, you can add support for a new device by creating an external converter as explained in https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

**Comment by Nailik** [comment]
@Koenkk could you please give a hint in which folder the custom converters should be?
The linked website says next to the configuration.yaml (which i think means the configuration of the addon itself - but where is this folder)?

**Comment by Koenkk** [comment]
The z2m addon folder should be under /config or /share, you can use the HA file explorer addon

**Comment by Nailik** [comment]
I think i found it, it's the folder that's set as `data_path` (/share/zigbee2mqtt) 

How can i be sure the custom converter correctly started? 
According to the tutorial i should see` No converter available for ...` but in the log i still get `Received message from unsupported device with Zigbee model '1GANG/DIMMER/1' and manufacturer name 'Schneider Electric'`

**Comment by Nailik** [comment]
nvm i added the converter into the addon configuration rather than the z2mqtt configuration - works now

**Comment by netcruiser2k10** [comment]
Hi

im having a issue where everytime i add a zigbee device that is supported according to zigbee2mqtt website there a red box that appears saying failed to configure.... (see screenshot for my most recent)

I am running on the most upto date Home Assistant and have installed the eclipse mqtt broker and zigbee2mtqq add on.

Looking in the folders on the error code there are no converters or folders to suggest that they are there. Is it possible the add on does not install the converters anymore ? if so how would i put them in to the folders that zigbee2mqtt expects to find them ?
![Screenshot 2024-04-05 234341](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/104116318/2b8542cd-3e2a-4a7e-bd06-e6ddc8794cdc)

**Comment by netcruiser2k10** [comment]
Also how do i get the OTA working as well as i can get any of my devices to update their firmware with zigbee2mqtt

**Comment by hallard** [comment]
Sorry to Hijack but can someone put the full folder path where to put custom  .js files (from HA view) ?

Thanks

**Comment by Nailik** [comment]
@hallard depends on what path is set in the addonconfiguration under data_path.
I have `/share/zigbee2mqtt` set so i need to place my .js files in `/root/share/zigbee2mqtt`
