### ISSUE TITLE
ZBDongle-P fails to start after upgrading from Conbee 2 Stick

### ISSUE THREAD

**Issue by Shariner** [zigbee2mqtt/hassio-zigbee2mqtt#461]
### Description of the issue

Hey,
i wanted to upgrade to a ZBDongle-P stick from Sonoff because it should work better, faster and with more reach than the Conbee II stick. 

- I stopped Z2M
- Unplugged Conbee II stick
- Plugged ZBDongle-P stick
- deleted/changed serial configuration and added the new ID of the sonoff stick from hardware/allhardware
- Started the addon

Addon fails to start.

serial config:
port: /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
#port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2667712-if00
#adapter: deconz

Of cause i also tried it with port: /dev/ttyUSB0 - no luck
I tried reinstalling the addon - no luck
I tried reinstalling mosquitto - no luck

Are there any special steps or is the current version of Z2M just broken as it should work out of the box?
I don't think there is anything wrong with the configuration as it was working before. I now switched back to the Conbee stick, but i prefer the SonOff if it's supported.

### Addon version

1.30.1-1

### Platform

Home Assistant 2023.2.3
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest 

### Logs of the issue (if applicable)

[18:00:51] INFO: Preparing to start...
[18:00:51] INFO: Socat not enabled
[18:00:52] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:error 2023-02-10 18:01:03: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-02-10 18:01:03: Failed to start zigbee
Zigbee2MQTT:error 2023-02-10 18:01:03: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-02-10 18:01:03: Exiting...
Zigbee2MQTT:error 2023-02-10 18:01:03: undefined

**Comment by Koenkk** [comment]
Can you provide the herdsman debug log of this?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by Shariner** [comment]
Hello @Koenkk ,

i will provide the logs tomorrow. I tested the same dongle on my RPI 3 at home. It was working without any issues on first try. 
We are using a Lenovo M710 in our company as HA server, maybe that's a critical point. 

I will let you know.

**Comment by Shariner** [comment]
Notice to myself: Read the correct instructions for migrating to a different adapter. https://www.zigbee2mqtt.io/guide/faq/#how-do-i-migrate-from-one-adapter-to-another

I wasn't aware that such an article exist. 

After deleting all files in config/zigbee2mqtt/ and reconfiguration of the Z2M configuration i could start the addon and add all devices to Z2M.

Sorry
