### ISSUE TITLE
Error writing serial Port: EIO: i/o error, write Error: EIO: i/o error, write

### ISSUE THREAD

**Issue by NetJaro** [zigbee2mqtt/hassio-zigbee2mqtt#462]
### Description of the issue

Hi!

I am getting an error while starting the add-on
Conbee II stick connected by 5m USB 2.0 cable.

Sometimes, after a few resets, the addon will start, but after the next reset (e.g. update in HA) the error appears again.

Log:

> [11:52:50] INFO: Preparing to start...
> [11:52:52] INFO: Socat not enabled
> [11:52:53] INFO: Zigbee Herdsman debug logging enabled
> [11:53:00] INFO: Starting Zigbee2MQTT...
> Zigbee2MQTT:debug 2023-02-12 11:53:36: Loaded state from file /config/zigbee2mqtt/state.json
> Zigbee2MQTT:info  2023-02-12 11:53:36: Logging to console and directory: '/config/zigbee2mqtt/log/2023-02-12.11-53-36' filename: log.txt
> Zigbee2MQTT:debug 2023-02-12 11:53:36: Removing old log directory '/config/zigbee2mqtt/log/2023-02-01.00-29-35'
> Zigbee2MQTT:info  2023-02-12 11:53:37: Starting Zigbee2MQTT version 1.30.1 (commit #unknown)
> Zigbee2MQTT:info  2023-02-12 11:53:37: Starting zigbee-herdsman (0.14.89)
> Zigbee2MQTT:debug 2023-02-12 11:53:37: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"deconz","baudRate":38400,"path":"/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2672078-if00"}}'
> 2023-02-12T10:53:39.989Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
> 2023-02-12T10:53:40.065Z zigbee-herdsman:deconz:driver Set delay to 0
> 2023-02-12T10:53:40.068Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"baudRate":38400,"path":"/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2672078-if00","adapter":"deconz"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
> 2023-02-12T10:53:40.081Z zigbee-herdsman:deconz:driver Opening with /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2672078-if00
> 2023-02-12T10:53:40.523Z zigbee-herdsman:deconz:driver Serialport opened
> 2023-02-12T10:53:40.524Z zigbee-herdsman:controller:log Started with result 'resumed'
> 2023-02-12T10:53:40.525Z zigbee-herdsman:controller:log Injected database: true, adapter: true
> 2023-02-12T10:53:40.651Z zigbee-herdsman:controller:database:log Writing database to '/config/zigbee2mqtt/database.db'
> 2023-02-12T10:53:40.985Z zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 1 paramId: 1
> 2023-02-12T10:53:41.006Z zigbee-herdsman:deconz:driver Error writing serial Port: EIO: i/o error, write
> Error: EIO: i/o error, write

Config: 

> data_path: /config/zigbee2mqtt
> socat:
>   enabled: false
>   master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
>   slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
>   options: "-d -d"
>   log: false
> mqtt: {}
> serial:
>   port: >-
>     /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2672078-if00
>   adapter: deconz
>   baudrate: 38400
> zigbee_herdsman_debug: true

In HA devices:

> DEVLINKS: >-
>   /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2672078-if00
>   /dev/serial/by-path/pci-0000:00:1d.0-usb-0:1:1.0
> DEVNAME: /dev/ttyACM0
> DEVPATH: /devices/pci0000:00/0000:00:1d.0/usb3/3-1/3-1:1.0/tty/ttyACM0
> ID_BUS: usb
> ID_MODEL: ConBee_II
> ID_MODEL_ENC: ConBee\x20II
> ID_MODEL_ID: '0030'
> ID_PATH: pci-0000:00:1d.0-usb-0:1:1.0
> ID_PATH_TAG: pci-0000_00_1d_0-usb-0_1_1_0
> ID_REVISION: '0100'
> ID_SERIAL: dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2672078
> ID_SERIAL_SHORT: DE2672078
> ID_TYPE: generic
> ID_USB_DRIVER: cdc_acm
> ID_USB_INTERFACES: ':020201:0a0000:'
> ID_USB_INTERFACE_NUM: '00'
> ID_VENDOR: dresden_elektronik_ingenieurtechnik_GmbH
> ID_VENDOR_ENC: dresden\x20elektronik\x20ingenieurtechnik\x20GmbH
> ID_VENDOR_ID: 1cf1
> MAJOR: '166'
> MINOR: '0'
> SUBSYSTEM: tty
> TAGS: ':systemd:'
> USEC_INITIALIZED: '521183343830'

What baudrate should be set for Conbee II?

### Addon version

1.30.1

### Platform

Home Assistant 2023.2.3
Supervisor 2023.01.1
Operating System 9.5

**Comment by Stromber03** [comment]
I have the same issue

**Comment by wlfbck** [comment]
Same here, with the following log:
```
zigbee2mqtt  | [2025-01-04 11:31:03] error: 	z2m: MQTT error: Keepalive timeout
zigbee2mqtt  | [2025-01-04 11:31:03] error: 	z2m: Not connected to MQTT server!
zigbee2mqtt  | Error: EIO: i/o error, write
```
