### ISSUE TITLE
Cover _TZE200_nv6nxo0c Unsupported 

### ISSUE THREAD

**Issue by raymentj** [zigbee2mqtt/hassio-zigbee2mqtt#467]
### Description of the issue

This cover  TS0601 shows as unsupported manufacturer? _TZE200_nv6nxo0c 

I have 2 other roller blind motors from same seller that work fine _ TZE200_zuz7f94z

Please support  _TZE200_nv6nxo0c  🙏🙏🙏 wonderful work 🥳👌

### Addon version

1.30.1-1

### Platform

Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest
on Raspberry Pi

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by raymentj** [comment]
Very kind, words do not come close to appreciation I feel. Thank You 🙏

**Comment by raymentj** [comment]
Alas it worked half briefly with a very long delay pressing a button to the blind moving a little, it does now state supported under devices but took many attempts to connect but does not respond at all, tried reconnectin, restoring HA on the Pi:

Error 2023-03-02 17:00:35Publish 'set' 'state' to 'Studio Blind' failed: 'Error: Command 0x84ba20fffef872b2/1 manuSpecificTuya.dataRequest({"seq":0,"dpValues":[{"dp":1,"datatype":4,"data":[0]}]}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'
Info 2023-03-02 17:00:35MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'Studio Blind' failed: 'Error: Command 0x84ba20fffef872b2/1 manuSpecificTuya.dataRequest({\"seq\":0,\"dpValues\":[{\"dp\":1,\"datatype\":4,\"data\":[0]}]}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'","meta":{"friendly_name":"Studio Blind"},"type":"zigbee_publish_error"}'

Friendly name
Studio Blind
Description
Last seen
N/A
Availability
Online
Device type
EndDevice
Zigbee Model
TS0601
Zigbee Manufacturer
_TZE200_nv6nxo0c
Description
Curtain motor/roller blind motor/window pusher/tubular motor
Support status
Supported
IEEE Address
0x84ba20fffef872b2
Network address
0x0D03
Manufacturer
[TuYa](https://www.zigbee2mqtt.io/supported-devices/#v=TuYa)
Model
[TS0601_cover_1](https://www.zigbee2mqtt.io/devices/TS0601_cover_1.html#tuya-ts0601_cover_1)
Power
Battery 
Interview completed
True


under current state it just has curly brackets no info between them, unlike my other blinds where it states link quality, position etc


Any help is highly appreciated
