### ISSUE TITLE
After updating to 1.18.0-1 Zigbee2mqtt does not start because: "No such image: zigbee2mqtt/zigbee2mqtt-aarch64:1.18.0-1"

### ISSUE THREAD

**Issue by attkri** [zigbee2mqtt/hassio-zigbee2mqtt#47]
Hi,

after updating to 1.18.0-1 and changing the configuration regarding ota: i get the following error when trying to start:

**404 Client Error for http+docker://localhost/v1.40/containers/create?name=addon_45df7312_zigbee2mqtt: Not Found ("No such image: zigbee2mqtt/zigbee2mqtt-aarch64:1.18.0-1")**

I have already restarted RaPi4.

How do I get the missing image?

**Comment by attkri** [comment]
And this is still in the log:

21-03-02 15:19:14 ERROR (SyncWorker_3) [supervisor.docker] Image zigbee2mqtt/zigbee2mqtt-aarch64 not exists for addon_45df7312_zigbee2mqtt
21-03-02 15:23:58 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-ssh with version 9.0.2
21-03-02 15:24:03 INFO (MainThread) [supervisor.api.security] /network/info access from core_ssh
21-03-02 15:24:03 INFO (MainThread) [supervisor.api.security] /host/info access from core_ssh
21-03-02 15:24:03 INFO (MainThread) [supervisor.api.security] /core/info access from core_ssh
21-03-02 15:28:24 WARNING (MainThread) [supervisor.addons.options] Unknown options new_api
21-03-02 15:31:39 WARNING (MainThread) [supervisor.addons.options] Unknown options new_api
21-03-02 15:31:39 WARNING (MainThread) [supervisor.addons.options] Unknown options new_api
21-03-02 15:31:39 WARNING (SyncWorker_3) [supervisor.addons.options] Unknown options new_api
21-03-02 15:31:39 ERROR (SyncWorker_3) [supervisor.docker] Image zigbee2mqtt/zigbee2mqtt-aarch64 not exists for addon_45df7312_zigbee2mqtt
21-03-02 15:51:40 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
21-03-02 15:51:40 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
21-03-02 15:51:40 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-03-02 15:51:43 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
21-03-02 15:51:43 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove

**Comment by ASNNetworks** [comment]
Has the update been revoked? I don't even see newer add-on tham 1.17.1-4

**Comment by AbeltjeNL** [comment]
> Has the update been revoked? I don't even see newer add-on tham 1.17.1-4. I hit reload a few times through the add-on page. 

Same question here 😅

**Comment by attkri** [comment]
I have not found a solution. I had no choice but to uninstall Zigbee2MQTT and then reinstall it, losing all devices and having to set everything up again.

**Comment by ciotlosm** [comment]
The new version is only on zigbee2mqtt/hassio-zigbee2mqtt. If you are using the older repo danielwelch/hassio-zigbee2mqtt you are still getting the old version. We're keeping them with a delay in case of problems so people can rollback.

**Comment by ciotlosm** [comment]
@attkri there seems to have been a bug in 1.18.0-1 that got fixed in 1.18.1-1. Maybe you got the update when the fix released.

**Comment by ASNNetworks** [comment]
Installed 1.18.1-1 through the newer repo (I always used the older one). Using Conbee II, everything works. It did need a good amount of time in order to communicate with HA though. Within GUI everything worked, but in HA states didn't get reflected. Restarter MQTT server as well and after a couple of minutes everything started to work again. So if the update does work, but you experience the same issues as me, just be patient :)

**Comment by ciotlosm** [comment]
Thanks for reporting @ASNNetworks
