### ISSUE TITLE
MQTT error: Connection refused: Not authorized

### ISSUE THREAD

**Issue by ThierryBourbon** [zigbee2mqtt/hassio-zigbee2mqtt#473]
### Description of the issue

Hi,
My z2m was working normally. but now returns an error
MQTT error: Connection refused: Not authorized
I tried uninstalling it and reinstalling it after deleting the zigbe2mqtt folder.
But I still get the error

I have a tostcorp module also connected at mosquitto. It works fine.
(previously z2m and tost both worked)

I also restored full backups where everything worked but I still get the error

### Addon version

1.30.2-1

### Platform

Home Assistant 2023.3.4
Supervisor 2023.03.1
Interface utilisateur : 20230309.0 - latest

### Logs of the issue (if applicable)

**log Z2m**
[00:32:09] INFO: Preparing to start...
[00:32:11] INFO: Socat not enabled
[00:32:16] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-03-17 00:32:24: Logging to console and directory: '/config/zigbee2mqtt/log/2023-03-17.00-32-24' filename: log.txt
Zigbee2MQTT:info  2023-03-17 00:32:24: Starting Zigbee2MQTT version 1.30.2 (commit #unknown)
Zigbee2MQTT:info  2023-03-17 00:32:24: Starting zigbee-herdsman (0.14.96)
Zigbee2MQTT:info  2023-03-17 00:32:34: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2023-03-17 00:32:34: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210708,"transportrev":2},"type":"zStack3x0"}'
Zigbee2MQTT:info  2023-03-17 00:32:34: Currently 0 devices are joined:
Zigbee2MQTT:info  2023-03-17 00:32:34: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2023-03-17 00:32:34: Connecting to MQTT server at mqtt://core-mosquitto:1883
Zigbee2MQTT:error 2023-03-17 00:32:36: MQTT error: Connection refused: Not authorized
Zigbee2MQTT:error 2023-03-17 00:32:36: MQTT failed to connect, exiting...
Zigbee2MQTT:info  2023-03-17 00:32:36: Stopping zigbee-herdsman...
Zigbee2MQTT:error 2023-03-17 00:32:37: MQTT error: Connection refused: Not authorized
...
Zigbee2MQTT:info  2023-03-17 00:32:45: Stopped zigbee-herdsman

**log mosquitto**
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/mosquitto.sh
[00:23:04] INFO: Setting up user tost
[00:23:06] INFO: Certificates found: SSL is available
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun mosquitto (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[00:23:07] INFO: Starting NGINX for authentication handling...
[00:23:08] INFO: Starting mosquitto MQTT broker...
2023-03-17 00:23:08: Warning: Mosquitto should not be run as root/administrator.
[00:23:10] INFO: Successfully send discovery information to Home Assistant.
[00:23:11] INFO: Successfully send service information to the Supervisor.

**Config mosquitto**
logins:
  - username: tost      _'I added this user because I have a tostcorp module to control my Somfy shutters_
    password: xxxxxxx
require_certificate: false
certfile: fullchain.pem
keyfile: privkey.pem
customize:
  active: false
  folder: mosquitto

**Config Z2m**
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt: {}
serial:
  port: /dev/ttyUSB0

**Comment by thierry-rhone** [comment]
Reinstalling all the problem has changed. So I close this issue
