### ISSUE TITLE
can’t edit zigbee 2 MQTT addon configuration 

### ISSUE THREAD

**Issue by obot101** [zigbee2mqtt/hassio-zigbee2mqtt#479]
### Description of the issue

What happened?

Just installed zigbee 2 mqtt but when i try and edit the config it does not give me any option to do that both in UI and in yaml:

- Yaml:
![IMG_2623](https://user-images.githubusercontent.com/112019174/230073400-9a5f7be9-37f2-4a03-a35a-0b0ae07f2a0c.jpeg)

- UI:
![IMG_2622](https://user-images.githubusercontent.com/112019174/230073574-cc7a8877-25b6-4c05-bffd-9e5b523d3284.jpeg)

As i can’t edit this i can’t change settings to see the frontend

### Addon version

1.30.3-1

### Platform

Core: 2023.3.6
Hardware: Raspberry pi4

### Logs of the issue (if applicable)

Zigbee2MQTT:info  2023-04-05 13:03:26: Starting zigbee-herdsman (0.14.103)
Zigbee2MQTT:error 2023-04-05 13:03:27: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-04-05 13:03:27: Failed to start zigbee
Zigbee2MQTT:error 2023-04-05 13:03:27: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-04-05 13:03:27: Exiting...
Zigbee2MQTT:error 2023-04-05 13:03:27: Error: spawn udevadm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by ice-age68** [comment]
I have the same problem

**Comment by patrinif** [comment]
same issue with rasberry3b

**Comment by jim4tech** [comment]
Same issue with Raspberry Pi 4b

**Comment by Koenkk** [comment]
This seems like a HA bug, does 2023.4 solve this?

**Comment by obot101** [comment]
Yes! seems all good now. Anyone else still have the same problem?

**Comment by ice-age68** [comment]
I still have the problem. HA 2023.4.2 zigbee2mqtt 1.30.3-1

**Comment by ice-age68** [comment]
it works with chrome browser, but not with safari

**Comment by Koenkk** [comment]
@ice-age68 I see, then is is definitely a HA bug, please open an issue here: https://github.com/home-assistant/core/issues
