### ISSUE TITLE
Database Problem

### ISSUE THREAD

**Issue by milandzuris** [zigbee2mqtt/hassio-zigbee2mqtt#483]
### Description of the issue

Hi, model: TS0601_smart_human_presence_sensor every second write to DB not need write when state is the same, plasese fix this write to DB only when state is changed, same for other zigbee devices entities.
![image](https://user-images.githubusercontent.com/42905545/233426303-d78c3eee-f544-4275-846e-ae60f0c741de.png)

these entities increased the database by 1 GB in 3 days

### Addon version

*

### Platform

Home Assistant 2023.4.5
Supervisor 2023.04.1
Operating System 10.0

**Comment by ashwin2101** [comment]
I noticed that also and I have added these exclussions:

recorder:
db_url: postgresql://xxx:xxxxx@xxxx-timescaledb/xxxxxx
exclude:
entity_globs:
- sensor._presensedetector_illuminance_lux
- sensor._presensedetector_self_test
- sensor._presensedetector_target_distance
- number.presensedetector*

**Comment by milandzuris** [comment]
> I noticed that also and I have added these exclussions:
> 
> recorder: db_url: postgresql://xxx:xxxxx@xxxx-timescaledb/xxxxxx exclude: entity_globs:
> 
> * sensor._presensedetector_illuminance_lux
> * sensor._presensedetector_self_test
> * sensor._presensedetector_target_distance
> * number.presensedetector*

same i have this

**Comment by milandzuris** [comment]
@Koenkk
