### ISSUE TITLE
TuYa TS011F_plug_3 - OTA update not working

### ISSUE THREAD

**Issue by capsel22** [zigbee2mqtt/hassio-zigbee2mqtt#484]
### Description of the issue

Hi,

I just paired 3 [TS011F_plug_3 ](https://www.zigbee2mqtt.io/devices/TS011F_plug_3.html) and noticed the OTA check functionality doesn't work.

When manually checking I get error listed below in logs.
The version reports as -1

{
    "current": 0.1,
    "energy": 0,
    "linkquality": 39,
    "power": 23,
    "power_outage_memory": "restore",
    "state": "ON",
    "voltage": 244,
    "child_lock": null,
    "indicator_mode": null,
    "update": {
        "installed_version": -1,
        "latest_version": -1,
        "state": null
    },
    "update_available": null
}

### Addon version

1.30.3-1

### Platform

Home Assistant 2023.4.5 
Supervisor 2023.04.1 
Operating System 9.5 
Frontend 20230411.1 - latest 

### Logs of the issue (if applicable)

error 2023-04-26 16:22:21Failed to check if update available for 'Power Socket - TuYa03' (Failed to find endpoint which support OTA cluster)
debug 2023-04-26 16:22:21AssertionError [ERR_ASSERTION]: Failed to find endpoint which support OTA cluster at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:243:9) at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/zigbeeOTA.js:144:19) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:203:73) at EventEmitter.emit (node:events:525:35) at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22) at MQTT.onMessage (/app/lib/mqtt.ts:140:27) at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:126:27) at WebSocket.emit (node:events:513:28) at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1184:20) at Receiver.emit (node:events:513:28)

**Comment by ashwin2101** [comment]
I noticed that also and I have added these exclussions:

recorder:
  db_url: postgresql://xxx:xxxxx@xxxx-timescaledb/xxxxxx
  exclude:
    entity_globs:
      - sensor.*_presensedetector_illuminance_lux
      - sensor.*_presensedetector_self_test
      - sensor.*_presensedetector_target_distance
      - number.*_presensedetector_*

**Comment by capsel22** [comment]
bump
