### ISSUE TITLE
TuYa YSR-MINI-Z remote control is wrongly identified as TS0044

### ISSUE THREAD

**Issue by Soulfly999** [zigbee2mqtt/hassio-zigbee2mqtt#489]
### Description of the issue

After adding the [TuYa YSR-MINI-Z](https://www.zigbee2mqtt.io/devices/YSR-MINI-Z.html) in Zigbee2Mqtt it is wrongly identified as [TS0044](https://www.zigbee2mqtt.io/devices/TS0044.html) switch. 

### Addon version

v1.30.4

### Platform

 Home Assistant 2023.5.3
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

**Comment by Koenkk** [comment]
Please fill in https://github.com/Koenkk/zigbee2mqtt/issues/new?assignees=&labels=wrong+device&projects=&template=wrong_device.yaml&title=%5BWrong+device%5D%3A+
