### ISSUE TITLE
RFI: How to migrate from separate Docker Z2M to HASSIO integrated Z2M add-on?

### ISSUE THREAD

**Issue by netweaver1970** [zigbee2mqtt/hassio-zigbee2mqtt#49]
Hi,
After a long death struggle, I gave up. I wanted to migrate my HA from my slow/small RasPi 3B to a decent RasPi 4 (4GB), 
Initially I was going to use again a supervised HA install, as I have on my RasPi 3B for a good year now but after so many issues over a long time (which I could all fix, learned a lot along the way) today I had enough. 

I just decided I'm going to the dark (but hopefully more stable working) side of a 64 bit HASSIO, running on the RasPi 4. 
I'm currently have a decent size (about 90 devices) network of which 60+ Zigbee. 
So I would like to move my coordinator and move the Z2M relevant files (incl. device names, settings etc) to the Add-on install of Z2M. 

How would I best to go about it?

I can see probably the following files need to be transferred but how to do it easiest?

-  configuration.yaml 
- database.db  
- state.json 
- coordinator_backup.json

Thanks.

I'll have to figure the same out for my influxdb db files :)

**Comment by ciotlosm** [comment]
I've not done such a migration. My recommendation is to:
- install new rpi4 with 64bit hassio (do not connect adapter)
- install z2m add-on
- check all files that are there, including configs & db - write down the paths
- copy from your older setup the correct files over the new ones
- shutdown rpi4 , plugin the adapter and start it up

**Comment by netweaver1970** [comment]
I guessed that, but in the brave new world of HASS OS, where do I find the specific add-on config files? And how to do the 'copy'?
After installing the Z2M add-on (and the Samba add-on) I can't see/find the Z2M (and other add-on containers) configuration files. 
There's a Samba share called 'addons', so called for local add-ons but it's empty. 
I rather not go the Dev. SSH via port 2222 route, if not needed, there should be an easier way of getting files over to the HASS OS box.

**Comment by netweaver1970** [comment]
mmmm, I did see (after a reboot) that the persistent data directory /config/zigbee2mqtt all of a sudden was created in the 'config' share. So far so good, I could copy my database.db file in there. I also see that the file configuration.yaml is actually a JSON file, as per documentation. Can you give a full real world example of z2m add-on config JSON file, incl. the devices and groups separate files, so I can split up my by now old-school monolitic YAML file into the format the add-on expects?

And is it really true that each time you upgrade the z2m add-on in HA, that you have to re-adjust the newly delivered config file as per the backed-up previous config file? There's no automatic upgrade as in the standalone z2m docker container?

**Comment by herik63** [comment]
The format is different, I had a installation over raspbian rp3, and now I passed the adapter (hat CC2538) over a pizero W and begun using ser2net, which went fine, so I installed the add on in HA.
the file "configuration.yaml" is different, even if the version of the same 1.18.1, the rp3 was recently upgraded.

in any case I was not able to restore the friendly name of the devices, and I'm having issues with the groups :(

**Comment by netweaver1970** [comment]
For the same base component(z2m), there shouldn't be soo much trouble to migrate, for sure as there are only a few (config) files involved. Get the only real necessary (container config) parameters from the Supervisor config screen and let the container itself deal with the zigbee device and group settings. That's how the Conbee (and influxdb, esphome, etc) plugin works. For now mi migration is halted. No persistent config via the gui is a deal breaker, after being used to it for a long time. I was always on the dev channel for z2m docker container in my older setup so it's not a new new thing for me anymore. So I'll wait till it gets possible and the migration is a bit more thought through at the software setup side.

**Comment by herik63** [comment]
after some check and rewrite seems that the groups are workin now, at last :)

**Comment by netweaver1970** [comment]
> after some check and rewrite seems that the groups are workin now, at last :)

 @herik63  Care to document a bit what exactly you did? Since there's no (visible) process on enabling a more official migration path? I'm up to almost 70 devices (and 6 groups) now, doing them all manually sounds like a bad dream.

**Comment by massaquah** [comment]
Is there any news / new experiences on this matter?
I am exactly in the same situation now and I would like to migrate my existing z2m docker data into the HA addon data folder (whereever that might be located).

**Comment by Koenkk** [comment]
@OXERY yes please, PRs are always welcome :)
