### ISSUE TITLE
Can't write options.json - No such file or directory

### ISSUE THREAD

**Issue by komariq** [zigbee2mqtt/hassio-zigbee2mqtt#494]
### Description of the issue

After a restore of HomeAssistant on a new installation, I am not able to start Zigbee2MQTT and am getting the following issue in Home Assistant Core logs.

```
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:125
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 00:39:24 (5 occurrences)
Last logged: 09:35:45

Failed to to call /addons/45df7312_zigbee2mqtt/start - Unknown error, see supervisor
```

I attached the supervisor logs below.

```
23-06-02 09:34:53 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons/data/45df7312_zigbee2mqtt/options.json: [Errno 2] No such file or directory: '/data/addons/data/45df7312_zigbee2mqtt/tmp2ux_xcoa'
23-06-02 09:34:53 ERROR (MainThread) [supervisor.addons.addon] Add-on 45df7312_zigbee2mqtt can't write options
23-06-02 09:35:45 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons/data/45df7312_zigbee2mqtt/options.json: [Errno 2] No such file or directory: '/data/addons/data/45df7312_zigbee2mqtt/tmp4zlos6ey'
23-06-02 09:35:45 ERROR (MainThread) [supervisor.addons.addon] Add-on 45df7312_zigbee2mqtt can't write options
```

### Addon version

1.31.0-1

### Platform

Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.2
Frontend 20230503.3 - latest

### Logs of the issue (if applicable)

23-06-02 09:34:53 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons/data/45df7312_zigbee2mqtt/options.json: [Errno 2] No such file or directory: '/data/addons/data/45df7312_zigbee2mqtt/tmp2ux_xcoa'
23-06-02 09:34:53 ERROR (MainThread) [supervisor.addons.addon] Add-on 45df7312_zigbee2mqtt can't write options
23-06-02 09:35:45 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons/data/45df7312_zigbee2mqtt/options.json: [Errno 2] No such file or directory: '/data/addons/data/45df7312_zigbee2mqtt/tmp4zlos6ey'
23-06-02 09:35:45 ERROR (MainThread) [supervisor.addons.addon] Add-on 45df7312_zigbee2mqtt can't write options

**Comment by gtibrett** [comment]
bump. experiencing this same issue
