### ISSUE TITLE
Image zigbee2mqtt/zigbee2mqtt-aarch64:1.31.2-1 does not exist

### ISSUE THREAD

**Issue by Didel** [zigbee2mqtt/hassio-zigbee2mqtt#495]
### Description of the issue

After upgrading HomeAssistant to version 2023.6, Zigbee2MQTT won’t start any more. Trying to start the addon shows the following error:

`Image zigbee2mqtt/zigbee2mqtt-aarch64:1.31.2-1 does not exist for addon_45df7312_zigbee2mqtt`

My hardware is a Raspberry Pi 4. The Zigbee adapter is a Homeassistant SkyConnect stick (but I don’t assume that is relevant, as the addon won’t even start up). It has worked perfectly fine before upgrading Homeassistant.

### Addon version

v1.31.2-1

### Platform

Home Assistant 2023.6.0
Supervisor 2023.06.1
Operating System 10.2
Frontend-versie: 20230607.0 - latest

**Comment by Koenkk** [comment]
Seems to be an issue on your side as the image exists: https://hub.docker.com/layers/zigbee2mqtt/zigbee2mqtt-aarch64/1.31.2-1/images/sha256-d74c9a7a5bb3600fbcc696fa58ca4fc02b950d81c1eeb22165f6639f50ed2be9?context=explore

**Comment by Didel** [comment]
Thank you for the reply. Still no idea what the problem was, but I created a backup of the config, removed the addon and removed the repository from HACS, re-added and reinstalled the addon and restored the config. Everything now works again properly.
