### ISSUE TITLE
Zigbee2mqtt Proxy / UI / The token in fulltext mode but the server is hidden

### ISSUE THREAD

**Issue by Pulpyyyy** [zigbee2mqtt/hassio-zigbee2mqtt#496]
### Description of the issue

Hi,
A fairly minor issue:
The token value is in fulltext mode while the server is hidden
![image](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/32004297/29c63378-f55b-4a6a-9171-eac4111fd00e)

### Addon version

Zigbee2mqtt Proxy 0.2.0 

### Platform

Home Assistant 2023.6.1
Supervisor 2023.06.2

**Comment by danka621** [comment]
I see the same issue. Same version of zigbee2mqtt proxy (0.2.0).
