### ISSUE TITLE
Unable to define the configuration_url

### ISSUE THREAD

**Issue by fthiery** [zigbee2mqtt/hassio-zigbee2mqtt#498]
### Description of the issue

Is it possible to define something in `url` option of the Z2M `frontend` configuration so that devices in HomeAssistant have a direct link to the device ?

![Capture d’écran du 2023-06-29 00-22-45](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/87642/44385e0f-0a56-46dc-829a-c9a6d9c4e1a8)

With a "regular" setup, you would define the base URL `http://1.2.3.4:8080` in Z2M's configuration file, and HA's `configuration_url` gets defined like this (visible in HA's `.storage/core.device_registry` file):

 `        "configuration_url": "http://1.2.3.4:8080/#/device/0x70ac08fffe87636c/info",`

I tried to define the `url` value to `http://myhomeassistant.local:8123/api/hassio_ingress/1234567913521651651/` (where this URL is what i see when opening the Z2M UI into a new tab, i.e. the iframe URL, but it does not work: HA does not seem to update the `configuration_url` at all, and also the Z2M UI does not show the value after i enter it (but it shows in the `zigbee2mqtt/configuration.yaml` file).

Worse, because i migrated from a regular deployment, HA keeps the old (now broken) configuration url, and at least i'd like to purge these.

Any hints appreciated

### Addon version

1.31.2-1

### Platform

Home Assistant 2023.6.3
Supervisor 2023.06.2
OS: https://github.com/foreign-sub/ha_fbx

**Comment by fthiery** [comment]
This is the code i'm referring to in Z2M: 
```
        if (settings.get().frontend?.url) {
            const url = settings.get().frontend?.url;
            payload.configuration_url = entity.isDevice() ? `${url}/#/device/${entity.ieeeAddr}/info` :
                `${url}/#/group/${entity.ID}`;
        }
```

https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/homeassistant.ts#L1465C1-L1469C10

**Comment by fthiery** [comment]
I think i understand what is happening, the `/docker-entrypoint.sh` script overrides the frontend configuration section:

`export ZIGBEE2MQTT_CONFIG_FRONTEND='{"port": 8099}'`

https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/master/common/rootfs/docker-entrypoint.sh#L63

What would be needed is that HA provides HA's URL and "ingress code" (1234567913521651651) as env var, and that the entrypoint script does

`export ZIGBEE2MQTT_CONFIG_FRONTEND='{"port": 8099, "url": http://$HA_URL/api/hassio_ingress/$INGRESS_CODE}'`

**Comment by fthiery** [comment]
I found out that `bashio::addon.ingress_entry` provides the appropriate path (i.e. `/api/hassio_ingress/$INGRESS_CODE`) , so it seems possible !

**Comment by fthiery** [comment]
I think this PR might enable this feature, can anyone help testing (i don't know how) ?

 https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/pull/499

**Comment by jpbede** [comment]
I have installed the addon update which causes all devices to become unavailable. The log contains many of the following error messages:

```
2023-07-01 13:20:20.252 ERROR (MainThread) [homeassistant.components.mqtt.mixins] Error 'invalid url for dictionary value @ data['device']['configuration_url']' when processing MQTT discovery message topic: 
'homeassistant/select/0x001788010bd22725/motion_sensitivity/config', message: '{'availability': [{'topic': 'zigbee2mqtt/bridge/state', 'value_template': '{{ value_json.state }}'}, {'topic': 'zigbee2mqtt/Garten Bewegungsmelder/availability', 'value_template': '{{ value_json.state }}'}], 'availability_mode': 'all', 'command_topic': 'zigbee2mqtt/Garten Bewegungsmelder/set/motion_sensitivity', 'device': {'configuration_url': '/api/hassio_ingress/MHPSVu_8PjPBi6vc27fKsyvKTUS4USdVuT5kwq1FwwU/#/device/0x001788010bd22725/info', 'identifiers': ['zigbee2mqtt_0x001788010bd22725'], 'manufacturer': 'Philips', 'model': 'Hue motion outdoor sensor (9290030674)', 'name': 'Garten Bewegungsmelder', 'sw_version': '2.53.6'}, 'entity_category': 'config', 'icon': 'mdi:tune', 'name': 'Garten Bewegungsmelder motion sensitivity', 'options': ['low', 'medium', 'high', 'very_high', 'max'], 'state_topic': 'zigbee2mqtt/Garten Bewegungsmelder', 'unique_id': '0x001788010bd22725_motion_sensitivity_zigbee2mqtt', 'value_template': '{{ value_json.motion_sensitivity }}', 'platform': 'mqtt'}'
```

Based on the code in the HA core, the configuration_url must be an absolute URL:
```python
[...]
            vol.Optional(CONF_CONFIGURATION_URL): cv.url,
[...]
```

```python
# pylint: disable=no-value-for-parameter
def url(value: Any) -> str:
    """Validate an URL."""
    url_in = str(value)

    if urlparse(url_in).scheme in ["http", "https"]:
        return cast(str, vol.Schema(vol.Url())(url_in))

    raise vol.Invalid("invalid url")
```

**Comment by wilqq-the** [comment]
I can confirm - after updating to newer version it fails to autodiscovery devices.

```
`Exception in async_discover when dispatching 'mqtt_discovery_new_select_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}], 'command_topic': 'zigbee2mqtt/Garden_Sensor2/set/temperature_unit', 'device': {'configuration_url': '/api/hassio_ingress/kIMye0iSR_ZQqqA9fePfYMh-TRvUVqWOV_h2tm4DnD4/#/device/0xa4c1381686efeade/info', 'identifiers': ['zigbee2mqtt_0xa4c1381686efeade'], 'manufacturer': 'TuYa', 'model': 'Soil sensor (TS0601_soil)', 'name': 'Garden_Sensor2'}, 'name': 'Garden_Sensor2_temperature_unit', 'options': ['celsius', 'fahrenheit'], 'state_topic': 'zigbee2mqtt/Garden_Sensor2', 'unique_id': '0xa4c1381686efeade_temperature_unit_zigbee2mqtt', 'value_template': '{{ value_json.temperature_unit }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 270, in async_discover config: DiscoveryInfoType = discovery_schema(discovery_payload) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 232, in __call__ return self._exec((Schema(val) for val in self.validators), v) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 355, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 351, in _exec v = func(v) ^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable return schema(data) ^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict return base_validate(path, iteritems(data), out) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: invalid url for dictionary value @ data['device']['configuration_url']
`
```

Additionally, there is no way to edit the URL trough frontend - it always goes back to the /api/hassio_ingress/............
even if it saves in the congfiguration.yaml

**Comment by wilqq-the** [comment]
https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/pull/500

 we can just delete it from entrypoint for quick fix

**Comment by daaex1** [comment]
same issue here. anyone fixed?

**Comment by fthiery** [comment]
Sorry for the mess i caused with my PR; the change has been reverted with PR https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/pull/500 and koenkk has released  v1.32.0 which fixes the regression.

I still think it's worth digging and will try to have HA tolerate relative URLs.

**Comment by fthiery** [comment]
Not stale

**Comment by fthiery** [comment]
Not stale
