### ISSUE TITLE
Zigbee2MQTT Current version: 1.32.0-2 is not running but working

### ISSUE THREAD

**Issue by oomichalekoo** [zigbee2mqtt/hassio-zigbee2mqtt#501]
### Description of the issue

Zigbee2MQTT Current version: 1.32.0-2 is not running but working.I cant add new devices becouse is red button and it is stoped but i can turn on and turn off all devices.Zigbee2mqt web is unaivable

### Addon version

v1.32.0-2

### Platform

All update to new version

### Logs of the issue (if applicable)

    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/zemismart.ts:58:29)
    at Configure.configure (/app/lib/extension/configure.ts:117:13)
    at Immediate.<anonymous> (/app/lib/extension/configure.ts:69:17))
Zigbee2MQTT:info  2023-07-01 17:41:14: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:14: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:18: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"ON"}'
Zigbee2MQTT:info  2023-07-01 17:41:18: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"ON"}'
Zigbee2MQTT:info  2023-07-01 17:41:18: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"ON"}'
Zigbee2MQTT:info  2023-07-01 17:41:19: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:19: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:19: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:26: MQTT publish: topic 'zigbee2mqtt/Okno salon', payload '{"backlight_mode":"low","calibration":"OFF","calibration_time":48,"linkquality":255,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE"}'
Zigbee2MQTT:info  2023-07-01 17:41:26: MQTT publish: topic 'zigbee2mqtt/Okno salon', payload '{"backlight_mode":"low","calibration":"OFF","calibration_time":48,"linkquality":255,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE"}'
Zigbee2MQTT:info  2023-07-01 17:41:32: MQTT publish: topic 'zigbee2mqtt/Okno salon', payload '{"backlight_mode":"low","calibration":"OFF","calibration_time":48,"linkquality":255,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE"}'
Zigbee2MQTT:info  2023-07-01 17:41:32: MQTT publish: topic 'zigbee2mqtt/Okno salon', payload '{"backlight_mode":"low","calibration":"OFF","calibration_time":48,"linkquality":255,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Światło Nocne', payload '{"linkquality":255,"state_l1":"OFF","state_l2":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Światło Salon', payload '{"linkquality":255,"state_l1":"OFF","state_l2":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Przełącznik xxx', payload '{"linkquality":255,"state":"ON"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/TVWentylator', payload '{"linkquality":255,"state_l1":"OFF","state_l2":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Czujnik LUX', payload '{"battery":100,"illuminance":17635,"illuminance_lux":58,"linkquality":255,"power_outage_count":57,"voltage":3027}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Czujnik Ruchu Salon', payload '{"battery":45,"battery_low":false,"linkquality":255,"occupancy":true,"tamper":false,"voltage":1800}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Rekuperator', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Światło Blaty', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Okno czujnik', payload '{"battery":82,"battery_low":false,"contact":false,"linkquality":255,"tamper":false,"voltage":2900}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Światło schody', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Światło Skos', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Okno salon', payload '{"backlight_mode":"low","calibration":"OFF","calibration_time":48,"linkquality":255,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Czujnik Garderoba 2', payload '{"battery":2.5,"battery_low":false,"contact":true,"linkquality":255,"tamper":false,"voltage":2500}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Światło Korytarz', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Światło Garderoba', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Drzwi alarm', payload '{"battery":79.5,"battery_low":false,"contact":true,"linkquality":255,"tamper":false,"voltage":2900}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Drzwi wejsciowe', payload '{"battery":64,"battery_low":false,"contact":true,"linkquality":255,"tamper":false,"voltage":2900}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Pilot', payload '{"action":null,"battery":100,"linkquality":255,"voltage":3000}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Czujnik Deszczu', payload '{"battery":47,"battery_low":false,"linkquality":255,"tamper":false,"voltage":2700,"water_leak":true}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Czujnik Garderoba 1', payload '{"battery":73,"battery_low":false,"contact":true,"linkquality":255,"tamper":false,"voltage":2900}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Światło Sypialnia', payload '{"linkquality":255,"state_center":null,"state_left":"OFF","state_right":null}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/dwor', payload '{"battery":69,"humidity":57.96,"linkquality":255,"temperature":20.91,"voltage":2800}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Wyrownawczy', payload '{"battery":100,"battery_low":false,"contact":false,"linkquality":255,"tamper":false,"voltage":3000}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Włącznik TVdekoder', payload '{"linkquality":255,"power_on_behavior":"off","state":"ON","switch_type":"toggle"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/zmywarka', payload '{"child_lock":"UNLOCK","current":0,"energy":62.94,"indicator_mode":"off","linkquality":255,"power":0,"power_outage_memory":"off","state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null,"voltage":226}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Pompa', payload '{"linkquality":255,"power_on_behavior":"previous","state":"OFF","switch_type":"toggle"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Swiatlo Oliwier', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Garaż', payload '{"battery":100,"humidity":56,"humidity_calibration":0,"linkquality":255,"temperature":21.7,"temperature_calibration":0,"temperature_unit":"celsius"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/PompaMama', payload '{"linkquality":240,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:37: MQTT publish: topic 'zigbee2mqtt/Niski poziom wody', payload '{"battery":100,"battery_low":false,"contact":true,"linkquality":255,"tamper":false,"voltage":3100}'
Zigbee2MQTT:info  2023-07-01 17:41:38: MQTT publish: topic 'zigbee2mqtt/Rekuperator', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:38: MQTT publish: topic 'zigbee2mqtt/Światło Garderoba', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:38: MQTT publish: topic 'zigbee2mqtt/Rekuperator', payload '{"linkquality":152,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:38: MQTT publish: topic 'zigbee2mqtt/Światło Garderoba', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:50: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"ON"}'
Zigbee2MQTT:info  2023-07-01 17:41:50: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"ON"}'
Zigbee2MQTT:info  2023-07-01 17:41:50: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"ON"}'
Zigbee2MQTT:info  2023-07-01 17:41:50: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:50: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:50: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:41:56: Configuring 'Pilot'
Zigbee2MQTT:info  2023-07-01 17:41:57: MQTT publish: topic 'zigbee2mqtt/Pilot', payload '{"action":null,"battery":100,"linkquality":255,"voltage":3000}'
Zigbee2MQTT:info  2023-07-01 17:41:57: MQTT publish: topic 'zigbee2mqtt/Pilot', payload '{"action":null,"battery":100,"linkquality":255,"voltage":3000}'
Zigbee2MQTT:info  2023-07-01 17:42:22: MQTT publish: topic 'zigbee2mqtt/Rekuperator', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:42:39: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"ON"}'
Zigbee2MQTT:info  2023-07-01 17:42:39: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":252,"state":"ON"}'
Zigbee2MQTT:info  2023-07-01 17:42:39: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"ON"}'
Zigbee2MQTT:info  2023-07-01 17:42:41: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:42:41: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:42:41: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:42:50: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:42:56: Configuring 'Światło Sypialnia'
Zigbee2MQTT:error 2023-07-01 17:42:56: Failed to configure 'Światło Sypialnia', attempt 2 (TypeError: Cannot read properties of undefined (reading 'bind')
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:43:24)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/zemismart.ts:58:29)
    at Configure.configure (/app/lib/extension/configure.ts:117:13))
Zigbee2MQTT:error 2023-07-01 17:42:58: Failed to configure 'Pilot', attempt 1 (Error: Bind 0x00124b001f8ad338/1 genOnOff from '0x00124b0014dbe4d3/1' failed (waiting for response TIMEOUT)
    at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:766:19)
    at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:643:13)
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:43:9)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/sonoff.ts:126:13)
    at Configure.configure (/app/lib/extension/configure.ts:117:13))
Zigbee2MQTT:info  2023-07-01 17:43:21: MQTT publish: topic 'zigbee2mqtt/Światło Skos', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:43:35: MQTT publish: topic 'zigbee2mqtt/Światło schody', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:43:51: MQTT publish: topic 'zigbee2mqtt/PompaMama', payload '{"linkquality":252,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:43:57: MQTT publish: topic 'zigbee2mqtt/Swiatlo Oliwier', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:44:57: MQTT publish: topic 'zigbee2mqtt/zmywarka', payload '{"child_lock":"UNLOCK","current":0,"energy":62.94,"indicator_mode":"off","linkquality":255,"power":0,"power_outage_memory":"off","state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null,"voltage":226}'
Zigbee2MQTT:info  2023-07-01 17:44:57: MQTT publish: topic 'zigbee2mqtt/zmywarka', payload '{"child_lock":"UNLOCK","current":0,"energy":62.94,"indicator_mode":"off","linkquality":255,"power":0,"power_outage_memory":"off","state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null,"voltage":224}'
Zigbee2MQTT:info  2023-07-01 17:45:07: MQTT publish: topic 'zigbee2mqtt/dwor', payload '{"battery":69,"humidity":57.96,"linkquality":255,"temperature":20.82,"voltage":2800}'
Zigbee2MQTT:info  2023-07-01 17:45:07: MQTT publish: topic 'zigbee2mqtt/dwor', payload '{"battery":69,"humidity":59.65,"linkquality":255,"temperature":20.82,"voltage":2800}'
Zigbee2MQTT:info  2023-07-01 17:45:08: MQTT publish: topic 'zigbee2mqtt/zmywarka', payload '{"child_lock":"UNLOCK","current":0,"energy":62.94,"indicator_mode":"off","linkquality":255,"power":0,"power_outage_memory":"off","state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null,"voltage":224}'
Zigbee2MQTT:info  2023-07-01 17:45:08: MQTT publish: topic 'zigbee2mqtt/zmywarka', payload '{"child_lock":"UNLOCK","current":0,"energy":62.94,"indicator_mode":"off","linkquality":255,"power":0,"power_outage_memory":"off","state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null,"voltage":224}'
Zigbee2MQTT:info  2023-07-01 17:45:56: Configuring 'Światło Sypialnia'
Zigbee2MQTT:error 2023-07-01 17:45:57: Failed to configure 'Światło Sypialnia', attempt 3 (TypeError: Cannot read properties of undefined (reading 'bind')
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:43:24)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/zemismart.ts:58:29)
    at Configure.configure (/app/lib/extension/configure.ts:117:13))
Zigbee2MQTT:info  2023-07-01 17:46:21: MQTT publish: topic 'zigbee2mqtt/Rekuperator', payload '{"linkquality":252,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:46:49: MQTT publish: topic 'zigbee2mqtt/Światło Komputer', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:47:20: MQTT publish: topic 'zigbee2mqtt/Światło Skos', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:47:34: MQTT publish: topic 'zigbee2mqtt/Światło schody', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:47:50: MQTT publish: topic 'zigbee2mqtt/PompaMama', payload '{"linkquality":232,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:47:57: MQTT publish: topic 'zigbee2mqtt/Swiatlo Oliwier', payload '{"linkquality":255,"state":"OFF"}'
Zigbee2MQTT:info  2023-07-01 17:48:08: MQTT publish: topic 'zigbee2mqtt/Czujnik LUX', payload '{"battery":100,"illuminance":16233,"illuminance_lux":42,"linkquality":255,"power_outage_count":57,"voltage":3027}'

**Comment by varadujagan** [comment]
**Platform**
Home Assistant 2023.6.3
Supervisor 2023.06.4
Operating System 10.3
Frontend 20230608.0 - latest

Today (jun-03-2023) only I updated my Zigbee2MQTT from 1.31.2-1  to 1.32.0-2

Zigbee2MQTT didn't start 

here is the log 
```
[18:40:37] INFO: Preparing to start...
[18:40:37] INFO: Socat not enabled
[18:40:38] INFO: Starting Zigbee2MQTT...
/app/node_modules/jszip/lib/zipEntries.js:94
<
^
SyntaxError: Unexpected token '<'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1126:15)
    at Module._compile (node:internal/modules/cjs/loader:1162:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/app/node_modules/jszip/lib/load.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)

```
Config
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  server: mqtt://core-mosquitto:1883
  user: <redacted>
  password: <redacted>
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_22_98_8E_30-if00-port0

```

I Rolled back to Zigbee2MQTT (1.31.2-1) problem disappears
