### ISSUE TITLE
Image missing after 1.32.0-2 update; addon cannot start.

### ISSUE THREAD

**Issue by surfrock66** [zigbee2mqtt/hassio-zigbee2mqtt#502]
### Description of the issue

Following the automatic upgrade of Zigbee2MQTT in Home assistant, the addon is not running.  When I go to start it, I get the following message:

Image zigbee2mqtt/zigbee2mqtt-aarch64:1.32.0-2 does not exist for addon_45df7312_zigbee2mqtt

In file editor, I can see the contents of the directory (which I think is the correct directory) and this is what's in there:

![image](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/1345467/8249c2af-6ec3-448a-8ffa-66688ede333b)

There is a previous issue for a user who had an issue but the addon was working; mine is not, all of my Zigbee devices are unresponsive, hence opening a separate issue.

### Addon version

1.32.0-2

### Platform

Home Assistant 2023.6.3 
Supervisor 2023.06.4 
Operating System 10.3 
Frontend 20230608.0 - latest

**Comment by Sightseff** [comment]
Same issue here

**Comment by copetogo** [comment]
i think this holds true for both zigbee2mqtt and mqtt both addons dont start

**Comment by afkdk** [comment]
No Zigbee integration - hope it will soon be assigned and fixed 🤞

**Comment by Koenkk** [comment]
The image is there (https://hub.docker.com/layers/zigbee2mqtt/zigbee2mqtt-aarch64/1.32.0-2/images/sha256-a9ed6d541fe977fdecd2827b023752ce83260e80817d68acbaf771c228464f80?context=explore) so looks like some local caching/HA issue

**Comment by surfrock66** [comment]
Do you have a suggested fix that preserves the existing data?  An uninstall-reinstall would purge existing config, and on HASS OS docker isn't installed to just pull the image at the terminal.  I can do a "docker save zigbee2mqtt/zigbee2mqtt-aarch64:latest -o zigbee2mqtt-aarch64:1.32.0-2" but if I transfer that over it doesn't seem to work.  How would you get the image into home assistant from docker hub; I don't know enough about docker in hass to know how to get the image in place.

**Comment by surfrock66** [comment]
I was able to fix this from the terminal, here's what I did:

```
cp -Rp /root/config/zigbee2mqtt /root/config/zigbee2mqtt.bak
cp -Rp /root/config/zigbee.db /root/config/zigbee.db.bak #  probably not needed

# Uninstall add-on from the GUI

# Re-Install add-on from the GUI

# Stop the add-on from the GUI

cp -Rp /root/config/zigbee2mqtt.bak/* /root/config/zigbee2mqtt/

# Start the add-on from the GUI
```

My configuration was preserved.  I dunno if this is the cleanest solution, but there it is.

**Comment by lennvilardi** [comment]
> I was able to fix this from the terminal, here's what I did:
> 
> ```
> cp -Rp /root/config/zigbee2mqtt /root/config/zigbee2mqtt.bak
> cp -Rp /root/config/zigbee.db /root/config/zigbee.db.bak #  probably not needed
> 
> # Uninstall add-on from the GUI
> 
> # Re-Install add-on from the GUI
> 
> # Stop the add-on from the GUI
> 
> cp -Rp /root/config/zigbee2mqtt.bak/* /root/config/zigbee2mqtt/
> 
> # Start the add-on from the GUI
> ```
> 
> My configuration was preserved. I dunno if this is the cleanest solution, but there it is.

Hmm not working for me still not possible to start the addon

**Comment by mikkjant** [comment]
I had this same problem.
I made backup from config files and did the add-on uninstall and re-installation. I checked the files were there in the folder after installation so I did not need to do any recovering actions. 
Seems that uninstall/re-install is only needed (at least for me). 
Making backups is still always good practice.
