### ISSUE TITLE
Failed (AREQ - ZDO - bindRsp after 10000ms)

### ISSUE THREAD

**Issue by vlad36N** [zigbee2mqtt/hassio-zigbee2mqtt#504]
### Description of the issue

After update to version: 1.32.0-2 have errors in Zigbee2MQTT log and supervisor.
Some devices Sonoff ([SNZB-02D](https://www.zigbee2mqtt.io/devices/SNZB-02D.html#sonoff-snzb-02d)) not updating values.
0x84ba20fffed23459 is Sonoff ([SNZB-02D](https://www.zigbee2mqtt.io/devices/SNZB-02D.html#sonoff-snzb-02d)) device.
Errors in Zigbee2MQTT Log:
Zigbee2MQTT:error 2023-07-04 09:35:21: Failed to configure '0x84ba20fffed23459', attempt 1 (Error: Bind 0x84ba20fffed23459/1 msTemperatureMeasurement from '0x00124b0021b953bf/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7))
Zigbee2MQTT:warn  2023-07-04 09:35:58: Device '0x84ba20fffed23459' left the network
Zigbee2MQTT:error 2023-07-04 09:36:25: Failed to configure '0x84ba20fffed23459', attempt 2 (Error: Bind 0x84ba20fffed23459/1 msRelativeHumidity from '0x00124b0021b953bf/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7))

Errors in Supervisor:
23-07-05 15:18:24 WARNING (SyncWorker_2) [supervisor.addons.validate] Add-on config 'startup' with 'after' is deprecated. Please report this to the maintainer of obihai2mqtt
23-07-05 15:18:24 WARNING (SyncWorker_2) [supervisor.store.data] Can't read /data/addons/git/2ceff5c9/obihai2mqtt/config.json: required key not provided @ data['arch']. Got None

### Addon version

none

### Platform

Home Assistant 2023.7.0
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230608.0 - latest 

### Logs of the issue (if applicable)

Errors in Zigbee2MQTT Log:
Zigbee2MQTT:error 2023-07-04 09:35:21: Failed to configure '0x84ba20fffed23459', attempt 1 (Error: Bind 0x84ba20fffed23459/1 msTemperatureMeasurement from '0x00124b0021b953bf/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7))
Zigbee2MQTT:warn  2023-07-04 09:35:58: Device '0x84ba20fffed23459' left the network
Zigbee2MQTT:error 2023-07-04 09:36:25: Failed to configure '0x84ba20fffed23459', attempt 2 (Error: Bind 0x84ba20fffed23459/1 msRelativeHumidity from '0x00124b0021b953bf/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7))

Errors in Supervisor:
23-07-05 15:18:24 WARNING (SyncWorker_2) [supervisor.addons.validate] Add-on config 'startup' with 'after' is deprecated. Please report this to the maintainer of obihai2mqtt
23-07-05 15:18:24 WARNING (SyncWorker_2) [supervisor.store.data] Can't read /data/addons/git/2ceff5c9/obihai2mqtt/config.json: required key not provided @ data['arch']. Got None

**Comment by Sladgela** [comment]
Hi, I have the same error right after adding my EcoDim dimmer that has been working fornthe last 2 years via the Hue bridge. I moved all lights from the bridge to HA via Zigbee2MQTT, this dimmer gives me the error below (from the Z2M log).

```
Zigbee2MQTT:info  2023-08-08 22:33:43: Zigbee2MQTT started!
Zigbee2MQTT:info  2023-08-08 22:33:43: Configuring '0x086bd7fffe5d8330'
Zigbee2MQTT:error 2023-08-08 22:33:53: Failed to configure '0x086bd7fffe5d8330', attempt 1 (Error: Bind 0x086bd7fffe5d8330/1 genOnOff from '0x00124b002a2eacfe/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7))

```
The below is the device after is has been added in Zigbee2MQTT:

Friendly name
0x086bd7fffe5d8330
Description
Last seen
N/A
Availability
Disabled
Device type
Router
Zigbee Model
Dimmer-Switch-ZB3.0
Zigbee Manufacturer
EcoDim BV
Description
Zigbee & Z-wave dimmer
Support status
Supported

IEEE Address
0x086bd7fffe5d8330
Network address
0xCD33
Firmware build date
20200701
Firmware version
3.09
Manufacturer
EcoDim
Model
Eco-Dim.07/Eco-Dim.10
Power
Interview completed
True



Current version: 1.32.2-1
