### ISSUE TITLE
Cannot build addon on aarch64

### ISSUE THREAD

**Issue by fthiery** [zigbee2mqtt/hassio-zigbee2mqtt#506]
### Description of the issue

Because this add-on is completely hardware-dependant, i think documenting a test workflow (with rollback instructions) would be very helpful, especially without requiring to add multiple test devices (like a coordinator).

My initial idea is to build a local docker image on the target device which takes the same tag as the one provided by the "normal" add-on, then restart the add-on. After testing, i would delete the image with `docker image rm` and restart the add-on (i believe it should fallback to re-downloading the image from the manifest).

I tried to follow instructions from https://developers.home-assistant.io/docs/add-ons/testing/ and https://github.com/home-assistant/builder#run for deploying a locally built version (for testing) on my production hardware (an aarch64 device), but it fails with error.

On my target device:
```
$ docker pull homeassistant/aarch64-builder
Using default tag: latest
latest: Pulling from homeassistant/aarch64-builder
08409d417260: Already exists 
355a0f419466: Pull complete 
44ed650c8b77: Pull complete 
404a50862a2e: Pull complete 
c495ca20fd60: Pull complete 
c5f0e1b4dc66: Pull complete 
Digest: sha256:fa363d4aed2007a4efc97651adcfcd92c04391ace90b41c27c888a792fcc345d
Status: Downloaded newer image for homeassistant/aarch64-builder:latest
docker.io/homeassistant/aarch64-builder:latest

$ docker run \                             
        --rm \
        --privileged \
        -v ~/.docker:/root/.docker \
        homeassistant/aarch64-builder \
                --all \
                -t addon-folder \
                -r https://github.com/zigbee2mqtt/hassio-zigbee2mqtt \
                -b master
[07:42:57] INFO: No crossbuild support on host
[07:42:57] INFO: Starting docker.
[07:42:57] INFO: Waiting for docker to initialize...
[07:43:06] INFO: Docker was initialized
[07:43:06] INFO: Checkout repository https://github.com/zigbee2mqtt/hassio-zigbee2mqtt
[07:43:10] INFO: Run addon build for: armhf armv7 amd64 i386 aarch64
jq: error: Could not open file /tmp/build_config/config.json: No such file or directory
jq: error: Could not open file /tmp/build_config/config.json: No such file or directory
jq: error: Could not open file /tmp/build_config/config.json: No such file or directory
jq: error: Could not open file /tmp/build_config/config.json: No such file or directory
jq: error: Could not open file /tmp/build_config/config.json: No such file or directory
```

### Addon version

1.32.1-1

### Platform

Home Assistant 2023.6.3
Supervisor 2023.07.1
Interface utilisateur : 20230608.0 - latest

**Comment by Koenkk** [comment]
I'm not sure how to do this, but you need to point it to a subfolder (https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/tree/master/zigbee2mqtt or https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/tree/master/zigbee2mqtt-edge). This folder also has to contain all the files from https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/tree/master/common

**Comment by fthiery** [comment]
Thanks, i had not seen the https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/master/common/local_build.sh script. I understand better now.

I followed https://github.com/zigbee2mqtt/hassio-zigbee2mqtt#testing-changes-locally and i was suprised to see changes to the container persisting between restarts, i was still thinking that it would not. This allowed me to patch the entrypoint script and see that it does not work as expected, so i'll stick to this method now, thx !
