### ISSUE TITLE
Error during installation in HA

### ISSUE THREAD

**Issue by AldoLodos** [zigbee2mqtt/hassio-zigbee2mqtt#531]
### Description of the issue

When I try to install in HA on a raspberry 3 B+ i have the following error :

 Can't install zigbee2mqtt/zigbee2mqtt-aarch64:1.33.2-1: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=1.33.2-1&fromImage=zigbee2mqtt%2Fzigbee2mqtt-aarch64&platform=linux%2Farm64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": EOF") 

any idea on what could happen ?

### Addon version

1.33.2-1

### Platform

Home Assistant

    Core 2023.11.2
    Supervisor 2023.11.0
    Operating System 11.1
    Interface utilisateur 20231030.2

**Comment by sdotter** [comment]
Same issue here...

`Error response from daemon: Head "https://registry-1.docker.io/v2/zigbee2mqtt/zigbee2mqtt-edge-aarch64/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Azigbee2mqtt%2Fzigbee2mqtt-edge-aarch64%3Apull&service=registry.docker.io": EOF`

Did you managed to install in an other way?

**Comment by glower0617** [comment]
Same issue. Switching from ZHA

**Comment by sdotter** [comment]
Ohh whooow you post was 2 minutes ago 😂🤪

**Comment by sdotter** [comment]
Heyy its working again... maybe some issue at docker hub services?

**Comment by glower0617** [comment]
Yep. Just tried again. All good

**Comment by AldoLodos** [comment]
It's also now working on my side !

**Comment by AldoLodos** [comment]
As it seems to be ok for everybody, I close
