### ISSUE TITLE
Accessoire keeps updating in HA

### ISSUE THREAD

**Issue by RikMe** [zigbee2mqtt/hassio-zigbee2mqtt#533]
### Description of the issue

IKEA Vindstyrka starts to update automatically when added but does not progress 

### Addon version

1.33.2-1

### Platform

Core
2023.11.2
Supervisor
2023.11.3
Operating System
11.1
Frontend
20231030.2

### Logs of the issue (if applicable)

![IMG_0859](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/44720237/404f2610-b18f-45b2-a5f1-eed0692f4b87)

**Comment by jokerigno** [comment]
Same issue (with another device). Please notice that I did not start the update process.

**Comment by erikdewildt** [comment]
Having the same issue with Ikea Tradfri Remotes.

<img width="582" alt="image" src="https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/6085985/6e820686-921d-4424-88cc-95f14edc8621">

**Comment by Koenkk** [comment]
This will be fixed in the 1 December release
