### ISSUE TITLE
Aqara E1 2 gang switch (without neutral) don’t work Decoupled mode 

### ISSUE THREAD

**Issue by valikgram** [zigbee2mqtt/hassio-zigbee2mqtt#541]
### Description of the issue

The decoupling mode does not work. When I try to enable this feature, the system gives an error  - _**Publish 'set' 'operation_mode' to 'device name' failed: 'Error: undefined is not a object, got string ("decoupled")'**_
Is there a plan to solve this problem in the next updates?

### Addon version

1.34.0-1

### Platform

Core 2023.11.3
Supervisor 2023.11.6
Operating System 11.2

**Comment by midlan** [comment]
Have same problem. Should be fixed with new release:
https://github.com/Koenkk/zigbee2mqtt/issues/20264
