### ISSUE TITLE
Can't get EFR32MG21 based ZB-GW04 dongle to work

### ISSUE THREAD

**Issue by MikealSouth** [zigbee2mqtt/hassio-zigbee2mqtt#544]
### Description of the issue

Hi all,
I was gifted a EFR32MG21 based ZB-GW04 dongle that seems to work.
`# python3 Elelabs_EzspFwUtility.py probe -p /dev/ttyUSB0
2023/12/08 13:00:04 Elelabs_EzspFwUtility:   Generic Zigbee EZSP adapter detected:
2023/12/08 13:00:04 Elelabs_EzspFwUtility:   Firmware: 6.10.3-41
2023/12/08 13:00:04 Elelabs_EzspFwUtility:   EZSP v8`

So I wanted to integrate it into my HA mosquitto (6.4.0) setup, added zigbee2mqtt via the repo. The dongle is directly plugged into a RasPi 4, it shows up as /dev/ttyUSB0 aka /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0053-if00-port0 in Systems > Hardware > All Hardware.

My zigbee2mqtt/configuration.yml > https://pastebin.com/2uHcqrQG
My WebGUI config: https://i.imgur.com/NaNM337.png

Could someone please show me what I'm doing wrong? When I search for the error message in the logs, I only find people with the same problem but no solutions.
Thanks a lot,
Mike

### Addon version

1.34.0 (commit #unknown)

### Platform

Core: 2023.12.0
Supervisor: 2023.11.6
Operating System: 11.2

### Logs of the issue (if applicable)

[13:53:53] INFO: Preparing to start...
[13:53:53] INFO: Socat not enabled
[13:53:56] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-12-08 13:54:01: Logging to console and directory: '/config/zigbee2mqtt/log/2023-12-08.13-54-01' filename: log.txt
Zigbee2MQTT:info  2023-12-08 13:54:02: Starting Zigbee2MQTT version 1.34.0 (commit #unknown)
Zigbee2MQTT:info  2023-12-08 13:54:02: Starting zigbee-herdsman (0.25.0)
Error: Reset error: Error: {"sequence":-1} after 10000ms
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:299:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)

**Comment by Nerivec** [comment]
From what you linked, your `zigbee2mqtt/configuration.yaml` seems to be missing a few values, most notably the serial port config, and yet it appears in the UI...

I'd start by removing Z2M, deleting the config folder manually, and reinstall/reconfig everything from scratch.

**Comment by Da-Hermit** [comment]
> ### Description of the issue
> Hi all, I was gifted a EFR32MG21 based ZB-GW04 dongle that seems to work. `# python3 Elelabs_EzspFwUtility.py probe -p /dev/ttyUSB0 2023/12/08 13:00:04 Elelabs_EzspFwUtility: Generic Zigbee EZSP adapter detected: 2023/12/08 13:00:04 Elelabs_EzspFwUtility: Firmware: 6.10.3-41 2023/12/08 13:00:04 Elelabs_EzspFwUtility: EZSP v8`
> 

I have the same dongle and had similar issues until I upgraded the firmware. It is pretty painless and easy to do through a web browser via: https://darkxst.github.io/silabs-firmware-builder/
