### ISSUE TITLE
HEIMAN HS2WD-E Siren does not expose warning state

### ISSUE THREAD

**Issue by hasifm2010** [zigbee2mqtt/hassio-zigbee2mqtt#549]
### Description of the issue

Hi

I bought a HS2WD-E model (siren) and i was trying to configure it and it didn't work as expected. It always gives error when setting the topic.

Debug 2023-12-15 22:05:25Received MQTT message on 'zigbee2mqtt/Siren/set' with data '{"warning": {"mode": fire, "level": low, "strobe_level": low, "strobe": true, "strobe_duty_cycle": 10, "duration": 2 }}'
Error 2023-12-15 22:05:25Invalid message 'null', skipping...

![Screenshot 2023-12-16 at 8 15 31 PM](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/18568536/64a0984f-fd4e-40cb-b16f-24fe4b169ef9)

![Screenshot 2023-12-16 at 8 16 28 PM](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/18568536/6b360f65-1568-49ee-ab54-8ec0762b253b)

![Screenshot 2023-12-16 at 8 17 21 PM](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/18568536/917045aa-ac53-4d62-9846-3019fe6b5238)

![Screenshot 2023-12-16 at 8 17 51 PM](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/18568536/9968064c-ddb2-4268-ba42-ed6a2178964c)

### Addon version

1.34.0-1 

### Platform

Core: 2023.12.3
Supervisor: 2023.11.6
Operating System: 11.2
Frontend: 20231208.2

### Logs of the issue (if applicable)

Debug 2023-12-15 22:05:25Received MQTT message on 'zigbee2mqtt/Siren/set' with data '{"warning": {"mode": fire, "level": low, "strobe_level": low, "strobe": true, "strobe_duty_cycle": 10, "duration": 2 }}'
Error 2023-12-15 22:05:25Invalid message 'null', skipping...

**Comment by mirml** [comment]
I've got same problem. Any news about that?
