### ISSUE TITLE
Add-on can not start after update 

### ISSUE THREAD

**Issue by DevRedOWL** [zigbee2mqtt/hassio-zigbee2mqtt#552]
### Description of the issue

Z2M is unable to start after update to latest version, same problem persists even after rollback to 34
(For some reason, add-on is trying to use image not maching architecture)

### Addon version

v1.35.0-1

### Platform

Core 2023.12.4
Supervisor 2023.12.0
Operating System (was empty but actually Debian 11 bullseye | aarch64 Linux 6.1.69-v8+ | Raspberry Pi 4 Model B Rev 1.4)
Frontend 20231208.2

### Logs of the issue (if applicable)

exec /sbin/tini: exec format error

**Comment by DevRedOWL** [comment]
Also, could be a reason, that my system is on aarch64, but image somehow is for amd64
<img width="856" alt="image" src="https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/22500953/778430a4-3893-4ebc-8ff7-32161c49e241">

**Comment by Alter001** [comment]
Hi, I had the same problem however it was actually not because of the update. I decided to add Dreame vacuum integration (Tasshack/dreame-vacuum) to HA. For some reason, when I have it enabled, I cannot turn on Zigbee2MQTT, it gives me basically different error every time. When I disable Dreame in Integrations, it turns on and works just fine.

**Comment by Maggan0** [comment]
Same problems here. Add-On doesn't start after Update.

Log FIles:
[13:29:31] INFO: Preparing to start...
[13:29:31] INFO: Socat not enabled
[13:29:32] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2024-01-05 13:29:34: Logging to console and directory: '/config/zigbee2mqtt/log/2024-01-05.13-29-34' filename: log.txt
Zigbee2MQTT:info  2024-01-05 13:29:34: Starting Zigbee2MQTT version 1.35.0 (commit #unknown)
Zigbee2MQTT:info  2024-01-05 13:29:34: Starting zigbee-herdsman (0.30.0)
Assertion failed: Command (setConfigurationValue) returned unexpected state: [object Object]
Assertion failed: Command (setValue) returned unexpected state: 55
Error: {"address":0,"clusterId":32770,"sequence":2} after 10000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
