### ISSUE TITLE
Temperature sensor from Aqara TVOC air quality monitor (VOCKQJK11LM) is not transferred from Zigbee2MQTT 1.35.0 to HomeKit!

### ISSUE THREAD

**Issue by asan84** [zigbee2mqtt/hassio-zigbee2mqtt#554]
### Description of the issue

The problem
Temperature sensor from Aqara TVOC air quality monitor (VOCKQJK11LM) is not transferred from Zigbee2MQTT 1.35.0 to HomeKit!

Errors in Logs:
 1.

Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:232
Integration: Сенсор ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 14:00:04 (1 occurrences)
Last logged: 14:00:04

The unit of sensor.0x54ef4410007be710_temperature (ºC) cannot be converted to the unit of previously compiled statistics (°C). Generation of long term statistics will be suppressed unless the unit changes back to °C or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this

2)

Logger: homeassistant.components.sensor
Source: components/sensor/init.py:719
Integration: Сенсор ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 14:00:24 (1 occurrences)
Last logged: 14:00:24

Entity sensor.0x54ef4410007be710_temperature (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'ºC' which is not a valid unit for the device class ('temperature') it is using; expected one of ['°C', '°F', 'K']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22

3)

Logger: homeassistant.helpers.event
Source: helpers/event.py:296
First occurred: 14:00:24 (2 occurrences)
Last logged: 14:07:33

Error while dispatching event for sensor.0x54ef4410007be710_temperature to <Job track state_changed event ['sensor.0x54ef4410007be710_temperature'] HassJobType.Callback <bound method HomeAccessory.async_update_event_state_callback of <accessory display_name='Temperature' services=['AccessoryInformation', 'BatteryService', 'TemperatureSensor']>>>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 296, in _async_dispatch_entity_id_event
hass.async_run_hass_job(job, event)
File "/usr/src/homeassistant/homeassistant/core.py", line 715, in async_run_hass_job
hassjob.target(*args)
File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 501, in async_update_event_state_callback
self.async_update_state_callback(new_state)
File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 525, in async_update_state_callback
self.async_update_state(new_state)
File "/usr/src/homeassistant/homeassistant/components/homekit/type_sensors.py", line 135, in async_update_state
temperature = temperature_to_homekit(temperature, unit)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/homekit/util.py", line 404, in temperature_to_homekit
TemperatureConverter.convert(temperature, unit, UnitOfTemperature.CELSIUS), 1
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 73, in convert
return cls.converter_factory(from_unit, to_unit)(value)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 375, in converter_factory
return cls._converter_factory(from_unit, to_unit)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 430, in _converter_factory
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: ºC is not a recognized temperature unit.

It seems to me that somewhere in Zigbee2Mqqt there is an error in the configuration of the Aqara TVOC air quality monitor device (VOCKQJK11LM).

**The degree sign "º" is not correct before the letter "C".
Comparison of ºC and °C!**

https://github.com/home-assistant/core/issues/107063

### Addon version

1.35.0

### Platform

Core 2024.1.0 Supervisor 2023.12.0 Debian 12

**Comment by Koenkk** [comment]
Already fixed in the dev branch.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
