### ISSUE TITLE
Not getting update notifications

### ISSUE THREAD

**Issue by arnonel** [zigbee2mqtt/hassio-zigbee2mqtt#556]
### Description of the issue

Not getting new release/update notifications
![image](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/7973889/4fefdc4e-bb7f-4b0e-92d6-fe3a04a287a1)

### Addon version

1.33.2-1 

### Platform

Core: 2024.1.2
Supervisor 2023.12.0
Operating System 
Frontend 20240104.0

**Comment by Koenkk** [comment]
I don't think this issue is related to the addon, HA should handle the update notifications.

**Comment by arnonel** [comment]
Any ideas on what I should do to remediate?

**Comment by Koenkk** [comment]
I suggest opening an issue in the HA tracker.

**Comment by arnonel** [comment]
I ran updates on Debian and seemed to fix
