### ISSUE TITLE
Zigbee2Mqtt proxy doesnt fully load UI

### ISSUE THREAD

**Issue by dreed47** [zigbee2mqtt/hassio-zigbee2mqtt#570]
### Description of the issue

The iframe in HomeAssistant is missing styling and formatting.  I've tried clearing browser cache and the problem persists. 

### Addon version

v0.2.0

### Platform

Core 2024.2.1
Supervisor 2024.01.1
Operating System 11.5
Frontend 20240207.1

**Comment by hoskerism** [comment]
I have the same issue since installing 1.35.3-1:
![image](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/6742488/840c9f30-f413-4679-84d2-81cc093c705d)

**Comment by netweaver1970** [comment]
duplicate issue. flipping between dark mode and 'normal/white' mode should fix it.

**Comment by thelvyn777** [comment]
Same issue with 1.35.3
switch between dark/white mode doesnot work for me

**Comment by hoskerism** [comment]
> duplicate issue. flipping between dark mode and 'normal/white' mode should fix it.

Worked for me, thanks.

**Comment by thelvyn777** [comment]
> Same issue with 1.35.3 switch between dark/white mode doesnot work for me

It worked (what i was doiing wrong was flipping dark/white mode in HA, not Z2M)

**Comment by maheshpunchi** [comment]
Worked for me, thanks.
