### ISSUE TITLE
Zigbee2MQTT Addon crashes randomly after update

### ISSUE THREAD

**Issue by JohnnyVi** [zigbee2mqtt/hassio-zigbee2mqtt#571]
### Description of the issue

The Zigbee2MQTT Addon crashes and fails to restart after updating it to the newest version. Watchdog does noething. 
No log-entries are created, it just stops working. 
The Web-UI says "Bad Gateway"
Also randomly, bluetooth stops working. All Bluetooth Devices are shown as Unavailable after a few hours.
Sometimes a restart (of HAOS) helps. 
Zigbee works with a Zonoff Stick on an extension cord.
Reverting back to 1.34-0 helps and Zigbee2MQTT runs perfectly again, so does bluetooth. 

### Addon version

1.35-1

### Platform

Core 2024.2.1
Supervisor 2024.01.1
Operating System 11.5
Frontend 20240207.1
On a Raspberry Pi 3

### Logs of the issue (if applicable)

No logs are created on the addon-log-page. The Web-UI just says Bad Gateway. Home Assistant will ask to restart the addon. Sometimes it works, sometimes this fails.

**Comment by KitHubek** [comment]
the same here. Restart addon helps, but its not a good idea. 

HA: core-2024.2.2
zigbee2mqtt: 1.35.3-1

**Comment by charltondurie** [comment]
Same issue here. Crashes multiple times a day.

**Comment by dekagramzla** [comment]
I seem to have the same issue after upgrading to the newer Z2M version 1.36. For me the addon crashes once every one to two days. 
HA core: 2024.2.5
zigbee2mqtt: 1.36.0-1

Unfortunately my backup got corrupted and I cannot easily revert to the previous Z2M versions. Are there any leads on this problem ?

**Comment by casadeivison** [comment]
Same problem here, hope an update resolves it.

**Comment by charltondurie** [comment]
Can we get an update on this issue please? It has been plaguing me for months and after multiple updates still not fixed.

I have ended up implementing automation to monitor multiple devices around the house and when they go offline (because of Zigbee2MQTT crashing), I trigger the Zigbee2MQTT Addon to restart which then fixes this issue and gets me out of trouble however this is not ideal.

Please let me know if there is anything you need from me to troubleshoot this, happy to provide anything you need.

**Comment by charltondurie** [comment]
Since the most recent update on the 1st April, this seems to have fixed the problem for me. It has been 2 days without a crash, I will check back in a week or so with another update. I have read the release notes and there have been a number of fixes, any idea what fix may have fixed this?

**Comment by thomasGomes** [comment]
I have the same problem.
My actual version is 1.36.1-1 and always the random device lost without no log...

**Comment by Destroyer061090** [comment]
Same problem…

**Comment by JohnnyVi** [comment]
For me it works with ezsp as adaptor on the config and 1.36.1.1Gesendet von Outlook für Android

**Comment by whocarezpt** [comment]
I have the same problem, on more recent software versions.. opened a new issue before finding this. https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/832
