### ISSUE TITLE
Mi wireless switch (WXKG01LM) problem after update to v1.36.0

### ISSUE THREAD

**Issue by GregoryZet** [zigbee2mqtt/hassio-zigbee2mqtt#579]
### Description of the issue

After update zigbee2mqtt Addon to v1.36.0, the button Mi wireless switch (WXKG01LM) started to interpret a single click as a long press. Automations triggered by a single click no longer work. 
The situation occurs on all Mi wireless switch (WXKG01LM)

### Addon version

v1.36.0

### Platform

Core 2024.2.4
Supervisor 2024.02.1
Operating System 12.0 

### Logs of the issue (if applicable)

In Z2M log "single click" looks like this (MQTT publish two different action topics)  :

info 2024-03-02 19:01:29MQTT publish: topic 'zigbee2mqtt/switch_1', payload '{"action":"single","battery":100,"click":null,"linkquality":54,"power_outage_count":95,"voltage":3022}'
info 2024-03-02 19:01:29MQTT publish: topic 'zigbee2mqtt/switch_1', payload '{"action":"","battery":100,"click":null,"linkquality":54,"power_outage_count":95,"voltage":3022}'
info 2024-03-02 19:01:30MQTT publish: topic 'zigbee2mqtt/switch_1/action', payload 'single'
info 2024-03-02 19:01:30MQTT publish: topic 'zigbee2mqtt/switch_1', payload '{"action":null,"battery":100,"click":"long","linkquality":54,"power_outage_count":95,"voltage":3022}'
info 2024-03-02 19:01:30MQTT publish: topic 'zigbee2mqtt/switch_1', payload '{"action":null,"battery":100,"click":"","linkquality":54,"power_outage_count":95,"voltage":3022}'
info 2024-03-02 19:01:30MQTT publish: topic 'zigbee2mqtt/switch_1/click', payload 'long'

**Comment by engal89** [comment]
I reported the same issue in the Z2M official repo: https://github.com/Koenkk/zigbee2mqtt/issues/21661 .
Hope can be useful.

**Comment by LagaV** [comment]
+1

**Comment by Koenkk** [comment]
will be fixed in the 1 April release.
