### ISSUE TITLE
Add-on wont start after 1.36.0-1 update

### ISSUE THREAD

**Issue by raptordemon** [zigbee2mqtt/hassio-zigbee2mqtt#581]
### Description of the issue

everything was working perfectly until the 1.36.0-1 update was applied and now the add on won't start.

all i see in the zigbee2mqtt logs is this:

[11:07:33] INFO: Preparing to start...
[11:07:33] INFO: Socat not enabled
[11:07:33] INFO: Zigbee Herdsman debug logging enabled
[11:07:34] INFO: Starting Zigbee2MQTT...

here is my add-on config:
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  server: mqtt://core-mosquitto:1883
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_[redcated]-if00-port0
zigbee_herdsman_debug: true

i cannot find any other logs anywhere.

### Addon version

v1.36.0-1

### Platform

Core: 2024.2.5
Supervisor: 2024.02.1
Operating System: 12.0
Frontend: 20240207.1

### Logs of the issue (if applicable)

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 10:28:40 AM (4 occurrences)
Last logged: 11:08:19 AM

Failed to to call /addons/45df7312_zigbee2mqtt/stats - Container addon_45df7312_zigbee2mqtt is not running

**Comment by raptordemon** [comment]
an uninstall and reinstall of zigbee2mqtt fixed this issue, still don't know what caused it

**Comment by akcasoy** [comment]
scary.. did u have to let join all your zigbee devices again?

**Comment by steveafrost** [comment]
Removing and reinstalling the add-on did resolve the issue for me as well. Note that when you remove the add-on, the configuration gets wiped so take note of the configuration page or make a copy of your `configuration.yml`

**Comment by zephyr550** [comment]
Hey guys, i have the same problem as well.
im new in z2mqtt and followed the instruction of the documentation and some youtube vids.
Unfortunately, reinstalling didn't help.
I hope you guys can help me

my config:
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
  zigbee_herdsman_debug: true
mqtt:
  server: mqtt://core-mosquitto:8883
serial:
  port: /dev/ttyUSB0



logs:
[22:52:54] INFO: Preparing to start...
[22:52:55] INFO: Socat not enabled
[22:52:56] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2024-03-29 22:52:59: Logging to console and directory: '/config/zigbee2mqtt/log/2024-03-29.22-52-59' filename: log.txt
Zigbee2MQTT:info  2024-03-29 22:52:59: Starting Zigbee2MQTT version 1.36.0 (commit #unknown)
Zigbee2MQTT:info  2024-03-29 22:52:59: Starting zigbee-herdsman (0.35.1)
Zigbee2MQTT:error 2024-03-29 22:53:32: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-03-29 22:53:32: Failed to start zigbee
Zigbee2MQTT:error 2024-03-29 22:53:32: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-03-29 22:53:32: Exiting...
Zigbee2MQTT:error 2024-03-29 22:53:32: TypeError: Cannot read properties of null (reading 'length')
    at AdapterNvMemory.init (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/adapter-nv-memory.ts:28:42)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:60:9)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)

**Comment by gaggio** [comment]
> an uninstall and reinstall of zigbee2mqtt fixed this issue, still don't know what caused it

I'm experiencing the same behaviour, can you clarify if after uninstall/reinstall you had to re-pair all devices?
Thanks
