### ISSUE TITLE
Z2M needs an effective watchdog function

### ISSUE THREAD

**Issue by XtosX** [zigbee2mqtt/hassio-zigbee2mqtt#583]
### Description of the issue

Z2M needs an effective watchdog function. When the connection between the Zigbee gateway and Z2M is lost for a period of time, Z2M will stop running, rather than continuously attempting to reconnect with the Zigbee gateway until successful.

### Addon version

V1.36

### Platform

all version

**Comment by VictorSoldatenko** [comment]
Freezing occurs every day and the service has to be restarted. Please resolve this issue.
