### ISSUE TITLE
V1.36.1 update RGB lights no longer have color

### ISSUE THREAD

**Issue by fireheadman** [zigbee2mqtt/hassio-zigbee2mqtt#585]
### Description of the issue

Applied update v1.36.1 today
Notice all my sengled bulbs no longer have RGB color options. I only have Kelvin temperature available.  

Something in the update caused this

### Addon version

V1.36.1

### Platform

Core
2024.3.3
Supervisor
2024.03.1
Operating System
Frontend
20240307.0

**Comment by fireheadman** [comment]
Performed restore back to v1.36.0-1 and all RGB bulbs (sengled) have color options again... will sit this latest version out until others have reported the same issue and it is corrected.

If by chance there needs to be another task performed on the latest version to make this work, please let me know (ie.  cache? some type of flush or reset?)

Thanks

**Comment by nckmh** [comment]
I am having the same issue after the update. The only sengled devices that I can still control RGB color on are the LED strips. All bulbs are color temperature only.

**Comment by Koenkk** [comment]
- Could you provide the data/database.db entry of this device?
- Could you provide the [generated external converter](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_2-creating-the-external-definition)?

**Comment by fireheadman** [comment]
Here is the generated external converter data

```
const {light, electricityMeter} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['E12-N1E'],
    model: 'E12-N1E',
    vendor: 'sengled',
    description: 'Automatically generated definition',
    extend: [light({"colorTemp":{"range":[154,500]},"color":{"modes":["xy","hs"]}}), electricityMeter({"cluster":"metering"})],
    meta: {},
};

module.exports = definition;
```

**Comment by fireheadman** [comment]
actually... maybe this is it.
looked up the IEEE Address and grep'd against the zigbee2mqtt database.db
let me know if this works....


```

homeassistant:/config/zigbee2mqtt# grep 0xb0ce181403529cc6 database.db
{"id":15,"type":"EndDevice","ieeeAddr":"0xb0ce181403529cc6","nwkAddr":8267,"manufId":4448,"manufName":"sengled","powerSource":"Mains (single phase)","modelId":"E12-N1E","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":258,"inClusterList":[0,3,4,5,6,8,768,1794,2821,64515,64516,64531],"outClusterList":[25],"clusters":{"64531":{"attributes":{"2":0}},"genBasic":{"attributes":{"stackVersion":0,"zclVersion":1}},"lightingColorCtrl":{"attributes":{"colorCapabilities":25,"colorTempPhysicalMin":154,"colorTempPhysicalMax":500,"colorMode":1,"currentX":38600,"currentY":21561,"colorTemperature":370}},"seMetering":{"attributes":{"divisor":10000,"multiplier":1,"instantaneousDemand":4,"currentSummDelivered":[0,147826]}},"genLevelCtrl":{"attributes":{"currentLevel":3}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x000d6f001736b0ae","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x000d6f001736b0ae","endpointID":1}],"configuredReportings":[{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1],"manufacturerCode":null},{"cluster":1794,"attrId":1024,"minRepIntval":5,"maxRepIntval":3600,"repChange":1,"manufacturerCode":null}],"meta":{}}},"appVersion":30,"stackVersion":0,"hwVersion":1,"zclVersion":1,"interviewCompleted":true,"meta":{"configured":-86389688},"lastSeen":1712065287393}
```

**Comment by Koenkk** [comment]
Issue should be fixed now!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
