### ISSUE TITLE
No GUI loading

### ISSUE THREAD

**Issue by ChillZwix** [zigbee2mqtt/hassio-zigbee2mqtt#593]
### Description of the issue

Been some time, that the GUI does not show up. Have not gotten in up on my phone using the HA app for a very long time. Browser I have been on off if it will load, but mostly not. Sometimes I can get it to load IF i restart Z2M. But now, It just is a blank screen showing up..

Z2M is working perfect  ut no GUI sowing up, so cant add new devices..

### Addon version

1.36.1-1

### Platform

Core
2024.4.2
Supervisor
2024.04.0
Operating System
12.1
Frontend
20240404.1

Zigbee2MQTT
Current version: 1.36.1-1

**Comment by 24hourbullshit** [comment]
Same for me, since like yesterday or maybe since the last update of HA.

It says Z2M is not running, but I can still control my devices and if I want to start it. 

Have exactly the same versions as ChillZwix.
