### ISSUE TITLE
Zigbee2mqtt addon not starting, no useful log

### ISSUE THREAD

**Issue by gaggio** [zigbee2mqtt/hassio-zigbee2mqtt#598]
### Description of the issue

After some time of intermittent issues (addon working for few hours, then stopping), the issue intensified up to complete inability to start the addon. No useful log apparently, see section below which is showing that the addon is startup is aborting after logging only three lines. 
Tried:

- unistall and reinstall addon
- updating stick firmware, now on zig-a-zig-ah! CC2652R_coordinator_20230507.hex which is the most recent

### Addon version

1.36.1-1

### Platform

Core: 2024.3.3
Operating System: Home Assistant OS 12.1

### Logs of the issue (if applicable)

[13:03:27] INFO: Preparing to start...
[13:03:30] INFO: Socat not enabled
[13:03:38] INFO: Starting Zigbee2MQTT...

**Comment by nukleuz80** [comment]
I have the same issue…

**Comment by gaggio** [comment]
Updated to 1.38.0-1, same issue is happening in the same way.
