### ISSUE TITLE
Error while opening socket

### ISSUE THREAD

**Issue by ZhuDaHai** [zigbee2mqtt/hassio-zigbee2mqtt#599]
### Description of the issue

zigbee2mqtt regularly crashes and the watchdog tries to restart it, but zigbee2mqtt fails to start with the error "Error while opening socket"

A manual 'Start' from its Addon page works without issue.

This is possibly related to an older issue: Error while opening socket #405

Here is my configuration:

<img width="773" alt="image" src="https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/14084743/aee79814-e1c1-48fc-80e6-4ddb76cf5865">

### Addon version

1.36.1-1

### Platform

Core 2024.4.3
Supervisor 2024.04.0
Operating System 12.2
Frontend 20240404.2

Raspberry Pi 5

### Logs of the issue (if applicable)

[19:59:14] INFO: Preparing to start...
[19:59:15] INFO: Socat not enabled
[19:59:15] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2024-04-22 19:59:17: Logging to console and directory: '/config/zigbee2mqtt/log/2024-04-22.19-59-17' filename: log.txt
Zigbee2MQTT:info  2024-04-22 19:59:17: Starting Zigbee2MQTT version 1.36.1 (commit #unknown)
Zigbee2MQTT:info  2024-04-22 19:59:17: Starting zigbee-herdsman (0.40.3)
Zigbee2MQTT:error 2024-04-22 19:59:18: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-04-22 19:59:18: Failed to start zigbee
Zigbee2MQTT:error 2024-04-22 19:59:18: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-04-22 19:59:18: Exiting...
Zigbee2MQTT:error 2024-04-22 19:59:18: Error: Error while opening socket
    at Socket.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:198:24)
    at Socket.emit (node:events:529:35)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by The-Croz** [comment]
I am having this exact log output and fail to start after trying to move my Sonoff Zigbee stick over to a Remote Adapter using ser2net on a raspberry pi. Any luck on this? I can't seem to find anything.
