### ISSUE TITLE
Can the addon share styles with the Home Assistant?

### ISSUE THREAD

**Issue by lorenc88** [zigbee2mqtt/hassio-zigbee2mqtt#60]
Hello, can't add this one as a feature request so I created an issue.

Is there any reason why zigbe2mqtt don't share the look and components with the home assistant? Isn't it more efficient and elegant? Was it considered in the past?

Thank you for the brilliant job and for the answer in advance.

Kind regards,
Przemek.

**Comment by ciotlosm** [comment]
The answer to this is a bit more complicated:

The add-ons usually are just outside software packaged in a way that Home Assistant can manage easier using their own Supervisor. They are just docker containers packaged in a certain way. 

The code inside the add-on has nothing to do with Home Assistant, and usually interaction is done through APIs. 

Recently (not so recently anymore), Home Assistant Supervisor introduced `ingress` method to expose any UI that an add-on might expose in the side bar. This blurred the line by making the add-on in feel to Home Assistant, but code is still separate. 

For the frontend to share styles and components with Home Assistant, there must be a conscious decision by the UI team (@nurikk) to use styles in that direction or allow skinning. 

The repository here (zigbee2mqtt/hassio-zigbee2mqtt) is only the add-on packaging for home assistant and does not modify code inside the UI of z2m, so unfortunately I can't be of much help on how to support this, unless a specific config is exposed on how to skin the UI. 

I hope this helps.

**Comment by lorenc88** [comment]
Thank you for comprehensive answer.
