### ISSUE TITLE
WXCJKG11LM, WXCJKG12LM, WXCJKG12LM battery level indicator drops to 0%, device operates normally, then % goes back to normal battery level

### ISSUE THREAD

**Issue by dnedeltchev** [zigbee2mqtt/hassio-zigbee2mqtt#601]
### Description of the issue

Randomly, or at least it seems to be it's random, the battery level indicator of these Aqara devices drops to 0%. When that happens, the devices operates normally. If I try to configure the device, wake up the device and press the reconfigure option in the z2m addon, I get the following error. The battery level indicator stays on 0%. If I leave it, after some time the battery level indicator goes back up to normal level. Another way to fix this is by deleting the device and re-pairing it.

[2.168.1.5](http://192.168.1.5:8123/api/hassio_ingress/J0or_vM6IpOl5Uu-EbInrdVQNYlisqwtHAjLUkykiKw/#/)

Show only
all
Filter by text
9ca
Log level
error
Logging level
 
Error 2024-04-25 17:07:33Failed to configure '0x04cf8cdf3c7c09ca', attempt 6 (Error: Bind 0x04cf8cdf3c7c09ca/1 genPowerCfg from '0x00124b0021600630/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:692:28 at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:469:13) at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:43:9) at configure (/app/node_modules/zigbee-herdsman-converters/src/devices/lumi.ts:2150:13) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:162:21) at Configure.configure (/app/lib/extension/configure.ts:122:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

### Addon version

1.36.1

### Platform

Core
2024.4.4
Supervisor
2024.04.0
Operating System
12.2
Frontend
20240404.2

### Logs of the issue (if applicable)

Already pasted in description

**Comment by prior-philip** [comment]
Even if this ticket is "Stale". 
Not sure where Battery level comes from... At least the device reports 2784mV, which shouldn't be 0% IMHO.
So the question is: Is Battery level a calculated value or transmitted by device?

`2024-11-02 10:51:44z2m:mqtt: MQTT publish: topic 'Blammer79/Livingroom/z2m@pi/2xPushButton_2', payload '{"action":"","battery":0,"last_seen":"2024-11-02T09:51:44.321Z","linkquality":193,"operation_mode":null,"power_outage_count":101,"voltage":2784}''`
