### ISSUE TITLE
ECONNREFUSED error after 1.37.0-1

### ISSUE THREAD

**Issue by zezo-git** [zigbee2mqtt/hassio-zigbee2mqtt#605]
### Description of the issue

After the update, the add on won’t start with this error: (MQTT failed to connect: connect ECONNREFUSED) and I fixed it by going back to 1.36.1-1. I am using EMQX as my MQTT broker. No other fixes worked but I’m not a professional. No other errors appeared in the log

### Addon version

v1.37.0-1

### Platform

Core: 2024.5.1
Supervisor: 2024.04.4
Operating System: 12.2
Frontend: 20240501.0

**Comment by anti-spy** [comment]
I'm getting exactly the same error. Both in Docker and in Home Assistant.

error:  z2m: MQTT error: connect ECONNREFUSED /

**Comment by bartbh** [comment]
Same error. I'm using zigbee2mqtt 1.37.0-1 as a Home Assistant Addon (docker container) with Home Assitant Supervised install.

`error: 	z2m: MQTT error: connect ECONNREFUSED /`

I've tried loggin in with the command line in the docker container. I'm able to connect to the ip+port of the mqtt server, but I don't see any failed logins in the logging of the mqtt broker.

**Comment by mfalkvidd** [comment]
Which version of Home Assistant are you using?

https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.37.0 Says at least version 2024.4 is required.

**Comment by bartbh** [comment]
Current HA version:

Core 2024.5.1
Supervisor 2024.04.4

**Comment by Koenkk** [comment]
Could you check if this is fixed in the latest-dev?[dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by bartbh** [comment]
Switching to the dev/edge addon unfortunately did no solve this issue. I'll try switching to an older version if that's possible.

**Comment by fschaeck** [comment]
I had the same error for HA Z2M Addon version 1.37.0-1 with Home Assistant Core 2024.4.x and 2024.5.x using the Moskito Browser Addon of HA as MQTT server. Reverting to HA Z2M Addon version 1.36.1-1 resolved the issue. No changes were made to MQTT during this process.

**Comment by Koenkk** [comment]
Pushed a fix, does it work now?

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by bartbh** [comment]
Just installed the new edge add-on and for me z2m is working again.
