### ISSUE TITLE
Topics are no longer showing on the Logs page

### ISSUE THREAD

**Issue by Hulumanu** [zigbee2mqtt/hassio-zigbee2mqtt#607]
### Description of the issue

Since the upgrade to 1.37.0, logs have changed to log.log (from the previous log.txt) and none of the topics state changes are getting logged.  There are a few logs that show up, but no device topics.  Logs page remains empty.

![SNAG-0066](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/20768501/10d8ade5-8f95-4d8b-906d-3c81903b2302)

![SNAG-0067](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/20768501/f4cf7d3e-cc58-4d7d-bb2c-3826c3eae548)

![SNAG-0069](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/20768501/19e7b3a2-d4d0-4f4a-95ff-4b4449b35f76)

Before upgrade:

![SNAG-0070](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/20768501/0b642e6f-1938-44d7-a79e-1e0d9a079106)

### Addon version

v1.37.0

### Platform

![SNAG-0071](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/20768501/9963a0d0-fbef-4132-8c28-1a70ae3ca8a2)

**Comment by Koenkk** [comment]
That's expected, `MQTT publish` has been moved to the debug logging

**Comment by Hulumanu** [comment]
Thanks Koen, I see them in the Logbook... Is there a way that I can see the payload that actually received, like we could before in the logs?

**Comment by Koenkk** [comment]
Only in the debug logs files or log screen from the addon (when `log_level: debug` is set)
