### ISSUE TITLE
Can not see debug log records in WEB interface

### ISSUE THREAD

**Issue by maxifly** [zigbee2mqtt/hassio-zigbee2mqtt#608]
### Description of the issue

I set log level = debug
I can see debug records in log file, but can not see this records in WEB interface

### Addon version

 1.37.0-1

### Platform

Core: core-2024.5.2
supervisor-2024.05.1
OS: raspberrypi Debian GNU/Linux 12 (bookworm)

**Comment by Koenkk** [comment]
This has been removed to improve performance, check the z2m 1.37.0 release notes.
