### ISSUE TITLE
Promote EZSP (PR#50) from dev to master -edge branch (for supervisor users)

### ISSUE THREAD

**Issue by DanielPiccoli** [zigbee2mqtt/hassio-zigbee2mqtt#61]
No issue - just asking to promote the EZSP adapter build from dev to master (-edge) so hass.io supervisor users can also install and test. We`re unable to install a specific branch tag from home assistant .

as of now, master -edge branch is on 1.17.1-4

**Comment by ciotlosm** [comment]
Both add-ons should be on 1.18.1 versions. If you still see 1.17.1-4 you have some weird repo. I've just promoted the release for 1.18.1-2 which should contain ezsp. This should show up if you are using the add-on from: `zigbee2mqtt/hassio-zigbee2mqtt`
