### ISSUE TITLE
All items in dashboard and devices tabs are gone after clicking "unlabeled" button in Z2M.

### ISSUE THREAD

**Issue by Lymkin** [zigbee2mqtt/hassio-zigbee2mqtt#617]
### Description of the issue

I was creating a backup from the Settings -> Tools Menu and accidentally hit an incomplete or unrendered button that had no label (see image). After that all my devices were gone from the Devices and Dashboard tabs. What is this button as I can find no reference. How do I get my devices back? They are still working in Home Assistant for the time being.

![BadButton](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/19554960/2e234489-64f3-493b-9596-c640abff6c0f)

### Addon version

1.38.0-1

### Platform

OS Version: Home Assistant OS 12.3
Home Assistant Core: 2024.5.5
Current version: 1.38.0-1

**Comment by Koenkk** [comment]
Please create issues related to the frontend in this repository: https://github.com/nurikk/zigbee2mqtt-frontend
