### ISSUE TITLE
Error: SRSP - SYS - ping after 6000ms with ZBDongle-E

### ISSUE THREAD

**Issue by whiteveon** [zigbee2mqtt/hassio-zigbee2mqtt#619]
### Description of the issue

I used ZBDongle-E on rasbberypi 4 
I tride:
 diferent firmware versions
 ZHA is disabled
adding to configurattion.yaml adapter: ezsp

nothing is working pleas help someone

### Addon version

v1.38.0-1

### Platform

Core 2024.6.0
Supervisor 2024.06.0
Operating System

20240605.0

### Logs of the issue (if applicable)

error: 	z2m: Error while starting zigbee-herdsman
[2024-06-08 15:50:51] error: 	z2m: Failed to start zigbee
[2024-06-08 15:50:51] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-06-08 15:50:51] error: 	z2m: Exiting...
[2024-06-08 15:50:51] error: 	z2m: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:101:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:127:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)

**Comment by whiteveon** [comment]
w***n@A***y:~ $ sudo ls -l /dev/serial/by-id
total 0
lrwxrwxrwx 1 root root 13 Jun  8 15:50 usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20240123210538-if00 -> ../../ttyACM0
w***n@A***y:~ $ test -w /dev/ttyACM0 && echo success || echo failure
success

**Comment by whiteveon** [comment]
data_path: /homeassistant/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: *****
  password: *****
serial:
  port: /dev/ttyACM0
permit_join: true
advanced:
  network_key:
    - 173
    - 105
    - 7
    - 9
    - 163
    - 47
    - 34
    - 94
    - 116
    - 27
    - 135
    - 140
    - 203
    - 191
    - 1
    - 50
  pan_id: 0903
  ext_pan_id:
    - 209
    - 19
    - 198
    - 189
    - 159
    - 29
    - 132
    - 84

**Comment by smint85** [comment]
Same issue, different dongle (skyconnect).

**Comment by Koenkk** [comment]
You need to add adapter: ember in the z2m addon config page, not the configuration.yaml

**Comment by smint85** [comment]
It worked. It is now up and running. Thank you!

**Comment by whiteveon** [comment]
> adapter: ember

didn't work for me
z2m: Error: NCP EZSP protocol version of 8 does not match Host version 13
    at EmberAdapter.emberVersion (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1674:19)

**Comment by whiteveon** [comment]
> > adapter: ember
> 
> didn't work for me z2m: Error: NCP EZSP protocol version of 8 does not match Host version 13 at EmberAdapter.emberVersion (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1674:19)

<img width="1021" alt="Знімок екрана 2024-06-09 о 22 39 42" src="https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/49923098/fcb4836f-9f1f-4af9-8a66-ac0830cf484a">

**Comment by Koenkk** [comment]
Make sure you are using the correct firmware, see https://github.com/Koenkk/zigbee2mqtt/discussions/21462
