### ISSUE TITLE
Backup of Zigbee2mqtt addon does not contain eg. friendly names of devices

### ISSUE THREAD

**Issue by heikkis** [zigbee2mqtt/hassio-zigbee2mqtt#627]
### Description of the issue

- full HA backup and restore -> no devices
- partial backup of zigbee2mqtt addon with one device, restored from backup -> no devices.

### Addon version

1.39.0-1

### Platform

All latest
Core 2024.7.2
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240710.0

**Comment by heikkis** [comment]
Same result for 1.35.1-1 version backup. Now I'm wondering where the device data should be if it is not in the addon's backup file.

Only these files are in the backup:
```
./addon.json
data/
data/options.json
```

**Comment by BobMac57** [comment]
Same as above, just the options.json file..

**Comment by heikkis** [comment]
I have found out that Zigbee2Mqtt addon provides backup functionality itself (basically it will make zip file of /data folder) which include all device settings, eg. friendly names and so on. Mind blowing, it seems not to be integrated to native addon backup feature.

Any ideas what that would mean in implementation? People are expecting that backup of addon would include all needed data to restore the addon. Clearly that is not the case currently.

**Comment by BobMac57** [comment]
> I have found out that Zigbee2Mqtt addon provides backup functionality itself (basically it will make zip file of /data folder) which include all device settings, eg. friendly names and so on. Mind blowing, it seems not to be integrated to native addon backup feature.
> 
> Any ideas what that would mean in implementation? People are expecting that backup of addon would include all needed data to restore the addon. Clearly that is not the case currently.

I saw that earlier and as far as I'm aware, this is the only addon that does this... doesn't make me a happy camper having to run a 2 step process to get a zip backup when IMO , should be in the HA backup strategy...

**Comment by FrankGiesecke** [comment]
This is very bad, as some of use use backup plans and make regular automated backups of HA.
In my case, I use the „Home Assistant Google Drive Backup“ to do this.
So the resulting Backup is worth than nothing

**Comment by Koenkk** [comment]
I checked a bit why this happens but cannot spot the error yet. The [HA addon backup code](https://github.com/home-assistant/supervisor/blob/aa7f4aafeb76252b9b53989bfbce23b10f217f8f/supervisor/addons/addon.py#L11970) creates a backup of the config which the addon defines [here](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/0727647607c952b88eb96b1e2304fabffd47ff77/zigbee2mqtt/config.json#L26). Would be greatly appreciated if someone with more knowledge about HA addons could investigate this (I don't have a HASS setup myself)

**Comment by FrankGiesecke** [comment]
Is there anyone working on this issue?

**Comment by FrankGiesecke** [comment]
This issue still exists

**Comment by ptfuzi** [comment]
This is still an issue, how to backup?

**Comment by BigBoot** [comment]
The problem is that the addon is mounting the general homeassistant config rather than the addon_specific one, i.e. 

```json
  "map": [
    "share:rw",
    "config:rw"
  ],
```

should be

```json
  "map": [
    "share:rw",
    "addon_config:rw"
  ],
```

But changing this now means existing users will need to manually migrate their config files to the new location.

A less invasive approach would be to just mount the `addon_config` in addition to the current `config` and update the default for `data_path` so new users would automatically get the `addon_config` and existing setups would continue to work with the option for manual migration.

@Koenkk Please let me know if you'd like to see a PR for one of those

**Comment by Koenkk** [comment]
@BigBoot I would love a PR, seems the second approach is the best
