### ISSUE TITLE
BLE-YL01  Invalid value for ec_max: 20000 (range 0.0 - 100.0)

### ISSUE THREAD

**Issue by xabix** [zigbee2mqtt/hassio-zigbee2mqtt#630]
### Description of the issue

Hi All,

Any idea of the issue? if it s withint HA or Zigbee2MQTT?

2024-07-29 13:42:35.998 ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.sonde_piscine_ec_max: 20000 (range 0.0 - 100.0)

Some info on the product: [Aliexpress](https://fr.aliexpress.com/item/1005005872455136.html?spm=a2g0o.productlist.main.17.61976Zi76Zi7l2&algo_pvid=12a2bb8d-79c9-4531-afd4-1f5a88022588&algo_exp_id=12a2bb8d-79c9-4531-afd4-1f5a88022588-8&pdp_npi=4%40dis%21CAD%21139.73%21139.73%21%21%2199.42%2199.42%21%402101e83017185475247844813efda4%2112000034652328250%21sea%21CA%21124843284%21&curPageLogUid=Y4CA21spsALk&utparam-url=scene%3Asearch%7Cquery_from%3A&gatewayAdapt=glo2fra#nav-specification)

Version Zigbee2MQTT [1.39.0]

Merci

### Addon version

19.62.0

### Platform

HA Core 2024.7.3, Supervisor 2024.06.2, Operating System 12.4, Interface utilisateur 20240710.0

### Logs of the issue (if applicable)

2024-07-29 13:42:35.998 ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.sonde_piscine_ec_max: 20000 (range 0.0 - 100.0)

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
