### ISSUE TITLE
z2m: Error: Error while opening socket

### ISSUE THREAD

**Issue by magiva** [zigbee2mqtt/hassio-zigbee2mqtt#644]
### Description of the issue

addon wont start
it Was running, i added the first device and now it wont start

### Addon version

1.40.2-1

### Platform

 Core 2024.10.1
Supervisor 2024.10.0
Operating System 13.1
Frontend 20241002.2

### Logs of the issue (if applicable)

[16:39:59] INFO: Preparing to start...
[16:40:00] INFO: Socat not enabled
[16:40:00] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-10-09 16:40:02] info: 	z2m: Logging to console, file (filename: log.log)
[2024-10-09 16:40:02] info: 	z2m: Starting Zigbee2MQTT version 1.40.2 (commit #unknown)
[2024-10-09 16:40:02] info: 	z2m: Starting zigbee-herdsman (2.1.3)
[2024-10-09 16:40:02] info: 	zh:zstack:znp: Opening TCP socket with slzb-06.local:6638
[2024-10-09 16:40:02] info: 	zh:zstack:znp: Socket connected
[2024-10-09 16:40:02] info: 	zh:zstack:znp: Socket ready
[2024-10-09 16:40:02] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
[2024-10-09 16:40:02] info: 	zh:zstack:znp: Socket error
[2024-10-09 16:40:02] error: 	z2m: Error while starting zigbee-herdsman
[2024-10-09 16:40:02] error: 	z2m: Failed to start zigbee
[2024-10-09 16:40:02] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-10-09 16:40:02] error: 	z2m: Exiting...
[2024-10-09 16:40:02] error: 	z2m: Error: Error while opening socket
    at Socket.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:166:24)
    at Socket.emit (node:events:529:35)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

/app/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:264
  var er = new ERR_STREAM_WRITE_AFTER_END();
           ^
Error: write after end
    at writeAfterEnd (/app/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:264:12)
    at DerivedLogger.Writable.write (/app/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:300:21)
    at DerivedLogger.log (/app/node_modules/winston/lib/winston/logger.js:231:12)
    at Logger.log (/app/lib/util/logger.ts:198:25)
    at Logger.info (/app/lib/util/logger.ts:211:14)
    at Znp.onPortClose (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:96:16)
    at Object.onceWrapper (node:events:632:26)
    at Socket.emit (node:events:517:28)
    at TCP.<anonymous> (node:net:350:12)

**Comment by indexample** [comment]
having the same issue, 

technically, the error message seems like an issue with async in NodeJS 
https://stackoverflow.com/questions/27769842/write-after-end-error-in-node-js-webserver

i have a similar issue running here, maybe i chose the wrong repo (zigbee2mqtt vs hassio-zigbee2mqtt):
https://github.com/Koenkk/zigbee2mqtt/issues/24154#issuecomment-2416654070

**Comment by Koenkk** [comment]
The real error is `[2024-10-09 16:40:02] info: zh:zstack:znp: Socket error`, meaning it cannot connect to the dongle, I've extended the error logging a bit, can you see what is logged now?

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by indexample** [comment]
i have tried with the de branch


[2024-10-23 08:59:55] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Kantoorlamp1', payload '{"backlight_mode":"inverted","linkquality":167,"power_on_behavior":"previous","state":"ON"}'
[2024-10-23 09:04:02] error: 	zh:zstack:znp: Socket error Error: read ECONNRESET
[2024-10-23 09:04:02] info: 	zh:zstack:znp: Port closed
[2024-10-23 09:04:02] info: 	zh:zstack:znp: closing
[2024-10-23 09:04:02] error: 	z2m: Adapter disconnected, stopping
[2024-10-23 09:04:02] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"offline"}'
[2024-10-23 09:04:02] info: 	z2m: Disconnecting from MQTT server
[2024-10-23 09:04:02] info: 	z2m: Stopping zigbee-herdsman...
[2024-10-23 09:04:02] info: 	z2m: Stopped zigbee-herdsman
[2024-10-23 09:04:02] info: 	z2m: Stopped Zigbee2MQTT

**Comment by Koenkk** [comment]
That indicates your network connection is not stable

**Comment by indexample** [comment]
Any test you recommend that would convince you the network is stable? 

Im running quite a large setup and this is the only one with issues

**Comment by Koenkk** [comment]
It could also be an issue of the coordinator itself, in the past I read people having these issues when opening the web page of the coordinator.

**Comment by indexample** [comment]
i think i worked it out

after diving into it more, there was a warning in my unify switch portal:
Multiple devices are using the same IP address: 192.168.2.X. Please check each device's configuration to ensure none are communicating with a rogue DHCP server.

the coordinator had hardcoded ip/dhcp settings, and the same static lease from router, but with different MAC address. For some reason the coordinator had gotten a different mac address over time(?!), which i believe would be the cause for this issue (in combination with the settings). 

now, after changing the coordinator to dhcp settings, the addon has been running well for over 1hr.

**Comment by lhw** [comment]
I suddenly ran into the same issue today. For me it definitely wasn't network related. Restarting the device did not fix the issue. What did solve it was setting the device to usb mode and back to network. Afterwards z2m was able to connect again. So it's  definitely an issue with the slzb6 firmware getting stuck.

**Comment by andlinux007** [comment]
I reverted back to V2.6.8.dev26 in the slzb6. 
Since I had done an update of the slzb6 firmware nothing worked in my Home Assistant.

**Comment by Tomasz720** [comment]
Today after the update errors appeared:

> ```
> [17:26:18]`` INFO: Preparing to start...
> [17:26:18] INFO: Socat not enabled
> [17:26:18] INFO: Starting Zigbee2MQTT...
> Starting Zigbee2MQTT without watchdog.
> [2025-01-21 17:26:22] info: 	z2m: Logging to console, file (filename: log.log)
> [2025-01-21 17:26:22] info: 	z2m: Starting Zigbee2MQTT version 2.0.0 (commit #unknown)
> [2025-01-21 17:26:22] info: 	z2m: Starting zigbee-herdsman (3.2.1)
> [2025-01-21 17:26:23] info: 	zh:zstack:znp: Opening TCP socket with 192.168.0.13:6638
> [2025-01-21 17:26:23] info: 	zh:zstack:znp: Socket connected
> [2025-01-21 17:26:23] info: 	zh:zstack:znp: Socket ready
> [2025-01-21 17:26:23] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
> [2025-01-21 17:26:23] error: 	zh:zstack:znp: Socket error Error: read ECONNRESET
> [2025-01-21 17:26:23] error: 	z2m: Error while starting zigbee-herdsman
> [2025-01-21 17:26:23] error: 	z2m: Failed to start zigbee-herdsman
> [2025-01-21 17:26:23] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start_crashes-runtime.html for possible solutions
> [2025-01-21 17:26:23] error: 	z2m: Exiting...
> [2025-01-21 17:26:23] error: 	z2m: Error: Error while opening socket
>  at Socket.<anonymous> (/app/node_modules/.pnpm/zigbee-herdsman@3.2.1/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:158:24)
>  at Socket.emit (node:events:530:35)
>  at emitErrorNT (node:internal/streams/destroy:170:8)
> at emitErrorCloseNT (node:internal/streams/destroy:129:3)
> at processTicksAndRejections (node:internal/process/task_queues:90:21)
> /app/node_modules/.pnpm/readable-stream@3.6.2/node_modules/readable-stream/lib/_stream_writable.js:264
>  var er = new ERR_STREAM_WRITE_AFTER_END();
> Error: write after end
>   at writeAfterEnd (/app/node_modules/.pnpm/readable-stream@3.6.2/node_modules/readable-stream/lib/_stream_writable.js:264:12)
>  at DerivedLogger.Writable.write (/app/node_modules/.pnpm/readable-stream@3.6.2/node_modules/readable-stream/lib/_stream_writable.js:300:21)
>  at DerivedLogger.log (/app/node_modules/.pnpm/winston@3.17.0/node_modules/winston/lib/winston/logger.js:231:12)
>   at Logger.log (/app/lib/util/logger.ts:198:25)
>  at Logger.info (/app/lib/util/logger.ts:211:14)
>   at Znp.onPortClose (/app/node_modules/.pnpm/zigbee-herdsman@3.2.1/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:88:16)  
>  at Object.onceWrapper (node:events:633:26)
>  at Socket.emit (node:events:518:28)
>   at TCP.<anonymous> (node:net:343:12)
> ```

No changes helped, only this advice helped, I sincerely thank the author.

> I suddenly ran into the same issue today. For me it definitely wasn't network related. Restarting the device did not fix the issue. What did solve it was setting the device to usb mode and back to network. Afterwards z2m was able to connect again. So it's  definitely an issue with the slzb6 firmware getting stuck.  

 _Originally posted by @lhw in [#644](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/644#issuecomment-2597038328)_

**Comment by subseatech** [comment]
For what it's worth, I ran into this issue after updating to firmware 2.7.0.
The fix for me after much time digging was to change the ip address of the SLZB. Increased it by one, edited it in Z2M and all is well.

**Comment by tempomode** [comment]
Same issue here with SLZB-06 on 2.7.0 - switching to USB mode and back didn't work for me (if you do this and don't have easy access to use USB with your SLZB, make sure you enable "Keep ON Wi-Fi/Ethernet network & web server in USB mode"!) but **removing the static address I had and setting a new one solved the problem**. Thanks @subseatech and others here!

**Comment by cabooseau** [comment]
> Today after the update errors appeared:
> 
> > ```
> > [17:26:18]`` INFO: Preparing to start...
> > [17:26:18] INFO: Socat not enabled
> > [17:26:18] INFO: Starting Zigbee2MQTT...
> > Starting Zigbee2MQTT without watchdog.
> > [2025-01-21 17:26:22] info: 	z2m: Logging to console, file (filename: log.log)
> > [2025-01-21 17:26:22] info: 	z2m: Starting Zigbee2MQTT version 2.0.0 (commit #unknown)
> > [2025-01-21 17:26:22] info: 	z2m: Starting zigbee-herdsman (3.2.1)
> > [2025-01-21 17:26:23] info: 	zh:zstack:znp: Opening TCP socket with 192.168.0.13:6638
> > [2025-01-21 17:26:23] info: 	zh:zstack:znp: Socket connected
> > [2025-01-21 17:26:23] info: 	zh:zstack:znp: Socket ready
> > [2025-01-21 17:26:23] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
> > [2025-01-21 17:26:23] error: 	zh:zstack:znp: Socket error Error: read ECONNRESET
> > [2025-01-21 17:26:23] error: 	z2m: Error while starting zigbee-herdsman
> > [2025-01-21 17:26:23] error: 	z2m: Failed to start zigbee-herdsman
> > [2025-01-21 17:26:23] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start_crashes-runtime.html for possible solutions
> > [2025-01-21 17:26:23] error: 	z2m: Exiting...
> > [2025-01-21 17:26:23] error: 	z2m: Error: Error while opening socket
> >  at Socket.<anonymous> (/app/node_modules/.pnpm/zigbee-herdsman@3.2.1/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:158:24)
> >  at Socket.emit (node:events:530:35)
> >  at emitErrorNT (node:internal/streams/destroy:170:8)
> > at emitErrorCloseNT (node:internal/streams/destroy:129:3)
> > at processTicksAndRejections (node:internal/process/task_queues:90:21)
> > /app/node_modules/.pnpm/readable-stream@3.6.2/node_modules/readable-stream/lib/_stream_writable.js:264
> >  var er = new ERR_STREAM_WRITE_AFTER_END();
> > Error: write after end
> >   at writeAfterEnd (/app/node_modules/.pnpm/readable-stream@3.6.2/node_modules/readable-stream/lib/_stream_writable.js:264:12)
> >  at DerivedLogger.Writable.write (/app/node_modules/.pnpm/readable-stream@3.6.2/node_modules/readable-stream/lib/_stream_writable.js:300:21)
> >  at DerivedLogger.log (/app/node_modules/.pnpm/winston@3.17.0/node_modules/winston/lib/winston/logger.js:231:12)
> >   at Logger.log (/app/lib/util/logger.ts:198:25)
> >  at Logger.info (/app/lib/util/logger.ts:211:14)
> >   at Znp.onPortClose (/app/node_modules/.pnpm/zigbee-herdsman@3.2.1/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:88:16)  
> >  at Object.onceWrapper (node:events:633:26)
> >  at Socket.emit (node:events:518:28)
> >   at TCP.<anonymous> (node:net:343:12)
> > ```
> 
> No changes helped, only this advice helped, I sincerely thank the author.
> 
> > I suddenly ran into the same issue today. For me it definitely wasn't network related. Restarting the device did not fix the issue. What did solve it was setting the device to usb mode and back to network. Afterwards z2m was able to connect again. So it's  definitely an issue with the slzb6 firmware getting stuck.
> 
> _Originally posted by [@lhw](https://github.com/lhw) in [#644](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/644#issuecomment-2597038328)_

Dude. Been hammering away at a similar issue for the better part of the day, your response prompted me to check and iI was set to usb connection. Back up and running. cant thank you enough.

**Comment by olekgo** [comment]
Switching from DHCP to static and back resolved the issue. Fwiw, during the process, I also changed the IP to a better one.

**Comment by bapesupreme** [comment]
Nothing works for me. I tried changing from usb to ethernet, dhcp to static, downgrading firmware.

v2.7.0 and 2.8.2dev3

**Comment by andlinux007** [comment]
> Nothing works for me. I tried changing from usb to ethernet, dhcp to static, downgrading firmware.
> 
> v2.7.0 and 2.8.2dev3

I'm still on v2.6.8.dev26, if I update it I have the same problem and I tried the things people mention here and on other websites.

**Comment by bapesupreme** [comment]
v2.6.8.dev26 worked for me

**Comment by mattmoo** [comment]
For me I tried upgrading/downgrading firmware, but that didn't work.

It seems to have been resolved by reassigning the IP in my router to another, and then back to the original. Maybe some network issue that zigbee2mqtt could tolerate better?

**Comment by lenusch** [comment]
THANK YOU! Indeed it seems that my tidy up end with hitting some button, it was suddently on USB Mode. I switched it to Ethernet again over GUI. Now Works. 

THANK YOU !!!!!!! <3

**Comment by Radieserlbrot** [comment]
I had the same issue and none of the above helped. Then I found the following entry in my SLZB's log: "taskZB | [SOCK IP WHITELIST] Rejected connection from unknown IP". That made me wonder and the I found the cause. I had changed the IP of my Home Assistant OS and forgot that there is the option to only allow a certain IP in the safety settings of SLZB. After I changed that IP to the new HAOS IP, everything worked as it should. 

Hopefully that may someday help anyone else, too.

**Comment by Camo1000** [comment]
Hello, I had same problem and tested all tips above (and others) without any success.
  I'd like to share what worked for me.
 I did a factory reset and did not configure a static ip. I let DHCP activated and  a made an ip reservation on the main router instead. 
  My SLZB-06 is now running for 2 days without any error :)
I hope my experience can help.
Greetings from Belgium.
Camomille
