### ISSUE TITLE
My Home Assistant is not showing new version available, even though there are

### ISSUE THREAD

**Issue by marcgarciamarti** [zigbee2mqtt/hassio-zigbee2mqtt#65]
**Description of problem:**
Hello,

I'm running version 1.16.1 and dev version (edge) is 1.16.2 but I've just browsed the repository and there I saw that version 1.18 is out. Why is that the case? How do I force an upgrade making sure I don't break anything. I have like 30 devices running just fine.

![Screen Shot 2021-03-14 at 11 40 41](https://user-images.githubusercontent.com/12695572/111065526-8a0fb200-84ba-11eb-8e26-a9a18eae8161.png)

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
"permit_join":false,"version":"1.16.1"}'
```

**Running platform (details from Suypervisor > System)**
```
  OS Version:               Debian GNU/Linux 10 (buster)
  Home Assistant Core:      2021.2.1
```

**Comment by DanielPiccoli** [comment]
click add-on store, upper right hand side, 3dot icon, hit RELOAD.

**Comment by marcgarciamarti** [comment]
> click add-on store, upper right hand side, 3dot icon, hit RELOAD.

Nothing :(

**Comment by DanielPiccoli** [comment]
did you follow these instructions ?

Updating the Edge add-on
To update the edge version of the add-on, you will need to uninstall and re-install the add-on.

⚠️ Make sure to backup your config as the procedure will not save this for you.

Steps

Backup config from: Supervisor → Dashboard → Zigbee2mqtt Edge → Configuration
Uninstall: Supervisor → Dashboard → Zigbee2mqtt Edge → Uninstall
Refresh repo: Supervisor → Add-on store → ⋮ → Reload
Re-install: Supervisor → Add-on store → Zigbee2mqtt Edge → Install
Restore config to: Supervisor → Dashboard → Zigbee2mqtt Edge → Configuration

**Comment by marcgarciamarti** [comment]
> did you follow these instructions ?
> 
> 
> 
> Updating the Edge add-on
> 
> To update the edge version of the add-on, you will need to uninstall and re-install the add-on.
> 
> 
> 
> ⚠️ Make sure to backup your config as the procedure will not save this for you.
> 
> 
> 
> Steps
> 
> 
> 
> Backup config from: Supervisor → Dashboard → Zigbee2mqtt Edge → Configuration
> 
> Uninstall: Supervisor → Dashboard → Zigbee2mqtt Edge → Uninstall
> 
> Refresh repo: Supervisor → Add-on store → ⋮ → Reload
> 
> Re-install: Supervisor → Add-on store → Zigbee2mqtt Edge → Install
> 
> Restore config to: Supervisor → Dashboard → Zigbee2mqtt Edge → Configuration

Thanks for that info. I certainly didn't know. I thought that the Edge version would stick to the normal update process. 
But that does not explain why the stable version is not displaying any pending update. For me the most pressing issue now is updating the stable version of the add-on.
Thanks a million anyway!

**Comment by marcgarciamarti** [comment]
Mystery solved. For some reason, the repo link had gone lost. I have no idea when that happened. Now I'm on 1.18!
