### ISSUE TITLE
IKEA E2206 : incorrect display of the mains voltage

### ISSUE THREAD

**Issue by PNenin** [zigbee2mqtt/hassio-zigbee2mqtt#655]
### Description of the issue

the mains voltage is 240 V while the display in the system shows 24.10 V

![Ikea INSPELNING Tension](https://github.com/user-attachments/assets/7f8a9668-743b-44f5-90d8-fb8cb2a55ed1)

### Addon version

v1.41.0-1

### Platform

Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2

**Comment by Argentino84** [comment]
Same problem here.
