### ISSUE TITLE
_TZ3000_qlmnxmac Tuya Power Outlet not showing power entity 

### ISSUE THREAD

**Issue by trehan86** [zigbee2mqtt/hassio-zigbee2mqtt#658]
### Description of the issue

I see that there are multiple threads on very similar issue. I am facing the same problem with Tuya Zigbee 2 gang power outlet. It operates okay but does not show power. I tried copying external converter but could not make it work, may be I am not setting up the external converter properly (I have no experience in this).

Device: https://vi.aliexpress.com/item/1005005857666258.html?spm=a2g0o.order_list.order_list_main.41.30421802vmzC2q&gatewayAdapt=glo2vnm

database.db:

{"id":5,"type":"Router","ieeeAddr":"0xa4c1383d06f6f017","nwkAddr":51409,"manufId":4417,"manufName":"_TZ3000_qlmnxmac","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"���.\u0013���.\u0012���.\u0016","65506":56,"65508":0,"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZ3000_qlmnxmac","zclVersion":3,"appVersion":78,"modelId":"TS011F","powerSource":1}},"seMetering":{"attributes":{"currentSummDelivered":0}},"haElectricalMeasurement":{"attributes":{"rmsVoltage":222,"rmsCurrent":0,"activePower":0}},"genOnOff":{"attributes":{"32768":0,"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":2,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"53248":0,"53249":0,"53250":2619665,"53251":123,"53252":11944,"53253":1374,"powerOnBehavior":2,"switchType":0}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":266,"inClusterList":[4,5,6,57345],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":78,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1731150671553}

any support would be greatly appreciated.

### Addon version

V1.41.0-1

### Platform

Core 2024.11.1
Supervisor 2024.11.2
Operating System 13.2
Frontend 20241106.2

**Comment by MakorKa** [comment]
Has same issue with latest version - no power info:(

**Comment by MakorKa** [comment]
@trehan86 hi. Can you try this converter? 

add file config/zigbee2mqtt/external_converters/ext_converter.js with this code and reboot zigbee2mqtt

```js
const m = require('zigbee-herdsman-converters/lib/modernExtend');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const ota = require('zigbee-herdsman-converters/lib/ota');
const reporting = require('zigbee-herdsman-converters/lib/reporting');

const NS = 'zhc:tuya';
const { tuyaMagicPacket } = tuya.modernExtend;
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [{ modelID: 'TS011F', manufacturerName: '_TZ3000_qlmnxmac' }],
    model: 'TS011F_2_gang_wall',
    vendor: 'Tuya',
    ota: true, //ota.zigbeeOTA,
    description: '2 gang socket with power monitoring',
    configure: async (device, coordinatorEndpoint) => {
        await tuya.configureMagicPacket(device, coordinatorEndpoint);
        const endpoint = device.getEndpoint(1);
        endpoint.saveClusterAttributeKeyValue('haElectricalMeasurement', {acCurrentDivisor: 1000, acCurrentMultiplier: 1, acPowerDivisor: 1, acPowerMultiplier: 1});
        endpoint.saveClusterAttributeKeyValue('seMetering', {divisor: 100, multiplier: 1});
        
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement', 'seMetering']);
        await reporting.rmsVoltage(endpoint, {change: 1});
        await reporting.rmsCurrent(endpoint, {change: 50});
        await reporting.activePower(endpoint, {change: 10});
        await reporting.currentSummDelivered(endpoint);
        
        device.save();
    },
    extend: [
        tuyaMagicPacket(),
        /*m.deviceEndpoints({
            endpoints: { 'l1': 1, 'l2': 2 },
            multiEndpointSkip: ['current', 'voltage', 'power', 'energy'],
        }),*/
        tuya.modernExtend.tuyaOnOff({
            backlightModeLowMediumHigh: true, 
            childLock: true, 
            endpoints: ['l1', 'l2'], 
            electricalMeasurements: true
        }),
        //m.electricityMeter(),
        //m.identify(),
    ],
    endpoint: (device) => {
        return {l1: 1, l2: 2};
    },
};

module.exports = definition;
```
