### ISSUE TITLE
Zigbee Actors slow response

### ISSUE THREAD

**Issue by ibaxx** [zigbee2mqtt/hassio-zigbee2mqtt#74]
Hi,

I had a great running Setup with hass on synology.
Now i have switched to hass os on raspi 3 with the same devices as before.

On hass os the is a significant delay when press a button and the lights recting.
In the Home Assistant forums is a thread with other Users witht his problem:
https://community.home-assistant.io/t/automations-slow-response-lights/221496

**Comment by drbugfinder** [comment]
Hi! I have a similar issue #76 

Do you see the same "idle behavior"?

**Comment by ibaxx** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Yes it looks like the same issue!                                                                                                                                                                                                                                                                                                                        Von: ***@***.***Gesendet: 27. März 2021 00:02An: ***@***.***Antworten: ***@***.***Cc: ***@***.***; ***@***.***Betreff: Re: [zigbee2mqtt/hassio-zigbee2mqtt] Zigbee Actors slow response (#74)  
Hi! I have a similar issue #76
Do you see the same "idle behavior"?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by pavelaizen** [comment]
I have the same issue, looks like C2531 fall a sleep, after clicking for the first time on my wireless switch it takes up to 4 seconds to run automation, other clothes cks response almost instantly.

**Comment by YuriyDY** [comment]
Same issue. Do someone have a solution for that?

**Comment by smithdo** [comment]
having the same issue

**Comment by YuriyDY** [comment]
I found this trouble and it was worked for me:
https://github.com/Koenkk/zigbee2mqtt/issues/8663
