### ISSUE TITLE
High latency for automation - almost unusable

### ISSUE THREAD

**Issue by drbugfinder** [zigbee2mqtt/hassio-zigbee2mqtt#76]
Hi all!

I've set up (multiple times and on x86 machine, as well as on RPi3) Homeassistant (core-2021.3.4) with zigbee2mqtt (1.18.1-2). Unfortunately I get a high latency between a button press and a actor response. I use Homeassistant automations (not NodeRED) and IKEA tradfri devices with a CC2531 dongle.

The behavior is like the following: 
When the system was idling for some minutes and a button gets pressed, it takes between 2-20 seconds until the light turns on. 
iff the light turned on (or off) and I toggle the button again, the light response is immediate (few milliseconds, as expected). This works as long as I don't let the system idle for some minutes (<5 min). If I wait longer, it will take again 2-20 seconds.

It gets even worse if I control a room with multiple lights in the automation. Then it can take up to a minute for the initial response. Same here, if I then press the button again within a few minutes, all lights in the same room respond almost immediately, as expected (<1 sec).

It is the same for all different rooms/automations. So if I go within some seconds/minutes after an initial button press to another room and press another button, the lights there need long time to respond as well. 

There must be some kind of idle timeout. I've repaired all devices multiple times and it does NOT depend on LQI or distance to the base station. The behavior is the same for Alexa control (via Emulated Hue).

Please see the attached logs.

Thank you!

```
Zigbee2MQTT:info  2021-03-26 10:23:26: MQTT publish: topic 'zigbee2mqtt/Schalter Bad', payload '{"action":"on","battery":70,"click":"on","linkquality":66,"update":{"state":"idle"},"update_available":false}'
Zigbee2MQTT:info  2021-03-26 10:23:26: MQTT publish: topic 'zigbee2mqtt/Schalter Bad', payload '{"action":"","battery":70,"linkquality":66,"update":{"state":"idle"},"update_available":false}'
Zigbee2MQTT:info  2021-03-26 10:23:26: MQTT publish: topic 'zigbee2mqtt/Schalter Bad', payload '{"battery":70,"click":"","linkquality":66,"update":{"state":"idle"},"update_available":false}'
Zigbee2MQTT:info  2021-03-26 10:23:26: MQTT publish: topic 'zigbee2mqtt/Schalter Bad/action', payload 'on'
Zigbee2MQTT:info  2021-03-26 10:23:26: MQTT publish: topic 'zigbee2mqtt/Schalter Bad/click', payload 'on'
Zigbee2MQTT:info  2021-03-26 10:23:37: MQTT publish: topic 'zigbee2mqtt/Deckenlampe Bad', payload '{"brightness":254,"color_temp":370,"color_temp_startup":65535,"linkquality":60,"state":"ON","update":{"state":"idle"},"update_available":false}'
```

**Comment by ibaxx** [comment]
Same issue here!
Raspi 3 x64 hass os... Two motion sensors one remote on zigbee2mqtt... Lights on hue bridge...

**Comment by drbugfinder** [comment]
After browsing the debug logs, it seems that MQTT is the bottleneck. At least it takes seconds, after a PUBLISH is sent until it is received from the zigbee2mqtt component. @ibaxx Can you verify this?

Add in config:
logger:
   default: debug
and have a look on home-assistant.log

**Comment by tasmatto** [comment]
Salve,ho lo stesso problema con pulsanti xiaomi ,ma da quello che noto nel comportamento, sembrerebbe una sleep mode del pulsante, in quanto il ritardo nell' attivazione dell' automazione avviene solo dopo il primo click, nei click successivi avviene in modo rapido. Dopo 10-15 minuti il problema ovviamente si ripete allo stesso modo.

Hi, I have the same problem with xiaomi buttons, but from what I notice in the behavior, it would seem a sleep mode of the button, as the delay in the activation of the automation happens only after the first click, in the following clicks it happens quickly.  After 10-15 minutes the problem obviously repeats itself in the same way.

**Comment by drbugfinder** [comment]
Do you see similar messages in your logs?

Logger: homeassistant.components.mqtt
Source: components/mqtt/__init__.py:932 
Integration: MQTT (documentation, issues) 
First occurred: 2. April 2021, 0:25:01 (3 occurrences) 
Last logged: 2. April 2021, 0:25:01

No ACK from MQTT server in 10 seconds (mid: 1)
No ACK from MQTT server in 10 seconds (mid: 2)
No ACK from MQTT server in 10 seconds (mid: 3)

**Comment by drbugfinder** [comment]
> > After browsing the debug logs, it seems that MQTT is the bottleneck. At least it takes seconds, after a PUBLISH is sent until it is received from the zigbee2mqtt component. Of course it could also be the zigbee2mqtt component, that is reacting very laggy. @ibaxx Can you verify this?
> 
> > 
> 
> > Add in config:
> 
> > 
> 
> > ```
> 
> > logger:
> 
> >    default: debug
> 
> > ```
> 
> > 
> 
> > and have a look on home-assistant.log
> 
> 
> 
> I've noticed the same behaviour, I've done this test: I pushed from dashboard (or any other software command) a switch of sonoff mini (I've 58 devices with several routers) a lot of time subsequently (each 0,5 sec more or less) after 10 or 20 push the system went on frozen, but only for the pubblish; I mean that when I've reached the frozen command status, I push the hardware command from my switch sonoff mini and the system received the status. So for 10 seconds the system was frozen on for sending command but was able to receive all the status. On my opinion this evidence 2 thing, first the delay and frozen is not from Mqtt broker that works normally (I've also other no ZigBee devices on Mqtt and every thing works good) second probably the z2m needs a sort of cache to route a command data train when the size of data (number of command message) is huge. This behaviour don't produce any logs error and it's tested on several switch (sonoff, tuya, lonshono switch and dimmer) and coordinator ( cc2531, cc2530+cc2592, ezsp WiFi, ezsp usb dongle, cc2530)

I agree - my observation is also, that receiving seems to be more reliable and without delay.

However I notice strange behavior on MQTT. I am not sure about the loggers output stream flush, but in the logs I see the z2m component receiving the MQTT message already seconds delayed - could also be the z2m MQTT input side which is processing slowly.

**Comment by tasmatto** [comment]
> Do you see similar messages in your logs?
> 
> Logger: homeassistant.components.mqtt
> Source: components/mqtt/**init**.py:932
> Integration: MQTT (documentation, issues)
> First occurred: 2. April 2021, 0:25:01 (3 occurrences)
> Last logged: 2. April 2021, 0:25:01
> 
> No ACK from MQTT server in 10 seconds (mid: 1)
> No ACK from MQTT server in 10 seconds (mid: 2)
> No ACK from MQTT server in 10 seconds (mid: 3)




i have:
Logger: homeassistant.components.mqtt
Source: components/mqtt/__init__.py:932
Integration: MQTT (documentation, issues)
First occurred: 4 aprile 2021, 15:35:44 (1 occurrences)
Last logged: 4 aprile 2021, 15:35:44

No ACK from MQTT server in 10 seconds (mid: 2)

**Comment by ibaxx** [comment]
Hi,

i had tried this morning to get the logging working...
I dont know... I have not found anything like your logs...

Mayby cause i was on beta channel since a few days...

Today i have looked through the integrations and found the "Zigbee home automation".
No delay but also without mqtt...

for me its the solution.

**Comment by fabricepipart** [comment]
Finally! I am not the only one experiencing this issue!

I have been struggling for weeks on this one. It appeared probably two month ago without any change of my setup I think. I tried countless things without success: moving the coordinator to the center of my flat, updating to this new repository, re-pairing all devices, changing channel...

I wonder what we all have in common (I don't think everyone using Z2M suffers from it).
On my side I have:
- Raspberry Pi 3B
- CC2531
- Xiaomi switch
- OSRAM plugs acting as routers
- Sonoff mini relay

And my typical automation looks like
`  - alias: Light A
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_xxx_action
        to: "single"
    action:
      - service: light.toggle
        entity_id: light.sonoff_xxx`

**Comment by ZzetT** [comment]
Could also be related to https://github.com/home-assistant/core/issues/48040 and https://github.com/home-assistant/addons/issues/1887.

You could try to switch back to Mosquitto 5.1 (in case you updated to 5.1.1.)

**Comment by drbugfinder** [comment]
> Could also be related to https://github.com/home-assistant/core/issues/48040 and https://github.com/home-assistant/addons/issues/1887.
> 
> 
> 
> You could try to switch back to Mosquitto 5.1 (in case you updated to 5.1.1.)

Thanks. I will try that and report.

**Comment by fabricepipart** [comment]
I can try that too. Any hint how to change the version of mosquitto that is installed? I am using the regular Add On

**Comment by drbugfinder** [comment]
I can confirm. This issue seems to be related to Mosquitto 5.1.1.
I downgraded to 5.1 and the issue is solved. However, this is a quick & dirty solution. 

> I can try that too. Any hint how to change the version of mosquitto that is installed? I am using the regular Add On
Try https://github.com/home-assistant/addons/issues/1887#issuecomment-802234693
Use 5.1 (not 5.1.0) in your own config. Don't forget to create a repository.json in the root folder of the forked repo (or use mine in your custom repo list: https://github.com/drbugfinder/addons)

**Comment by fabricepipart** [comment]
I also have a WAF problem ... I truly understand the pain @drbugfinder !
I ll try both methods (re-save conf and revert to 5.1 using a fork) this week end probably. After that, I will have to try ZHA

**Comment by KoenHaemels** [comment]
I must say that stopping to use zigbee2mqtt & homeassistant was a big improvement. I'm running the mosquitto-broker & zigbee2mqtt in a seperate docker container and started using node-red. I use the plugins of zigbee2mqtt in node-red with custom flows and after 2-3 months i noticed 1 delay yesterday.

Definitely try this :)

**Comment by fabricepipart** [comment]
First try to uninstall / install the addon failed for me. Plus I lost an hour trying to figure out why it broke all my setup (if you want to know that was because my configuration.yaml actually did not correspond to the Integration config I had before ...)

**Comment by fabricepipart** [comment]
Going back to Mosquitto 5.1 seems to work... Let's follow https://github.com/home-assistant/addons/issues/1887 now...

**Comment by attkri** [comment]
I had the same problems with zigbee2mqtt. At first I blamed it on the line quality since there are many wireless networks in the area. But every effort to increase the quality did nothing to the terrible latency. One day the whole Raspberry failed and could not access the SDCard anymore. Access was possible via Windows. So I took a new SDCard. Installed HA OS on it and restored the last backup. AND ALL PROBLEMS regarding latency were gone. The only difference I can name now is that my old SDCard was a 256GB card and the new one a 32GB.

**Comment by overas** [comment]
> Logger: homeassistant.components.mqtt
Source: components/mqtt/init.py:932
Integration: MQTT (documentation, issues)
First occurred: 2. April 2021, 0:25:01 (3 occurrences)
Last logged: 2. April 2021, 0:25:01
No ACK from MQTT server in 10 seconds (mid: 1)
No ACK from MQTT server in 10 seconds (mid: 2)
No ACK from MQTT server in 10 seconds (mid: 3)

The problem with high latency has been solved in Mosquitto broker 6.0.0. The authentication was to slow and dropped connections. https://github.com/home-assistant/core/issues/48040

![image](https://user-images.githubusercontent.com/37910044/120229893-71f43700-c24e-11eb-8695-e50ba5dc82d8.png)

**Comment by ciotlosm** [comment]
Can I close this issue? Or is it still relevant?

**Comment by kricha** [comment]
close
thanks
