### ISSUE TITLE
Devices->Setting(specific) not creating entries in devices.yaml

### ISSUE THREAD

**Issue by Masterz69** [zigbee2mqtt/hassio-zigbee2mqtt#80]
**Description of problem:**

Add-on UI Devices->Setting(specific) not creating entries in devices.yaml, despite popup declares 'Changed config...'.
As well not providing list of possible device specific parameters.

But, if parameters added manually in config/zigbee2mqtt/devices.yaml - UI show them & update if/when changed.

F.e. for
'0x00158d0006a0cc1b':
  friendly_name: BedRoom sTH
  pressure_precision: 2
  pressure_calibration: 7

it show and subsequently update (but only manually added to devices.yaml entries !):
![image](https://user-images.githubusercontent.com/15225823/113479388-77741180-9497-11eb-97bc-ea4c746e0b8e.png)

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
info  2021-04-03 13:47:31: Logging to console and directory: '/config/zigbee2mqtt/log' filename: log_2021-04-03.13-47-30_.txt
info  2021-04-03 13:47:31: Starting Zigbee2MQTT version 1.18.2 (commit #1.18.2)
info  2021-04-03 13:47:31: Starting zigbee-herdsman (0.13.88)
info  2021-04-03 13:47:34: zigbee-herdsman started
info  2021-04-03 13:47:34: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20200921,"transportrev":2},"type":"zStack3x0"}'
info  2021-04-03 13:47:34: Currently 11 devices are joined:
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
// replace this line with your pasted configuration
```

**Running platform (details from Suypervisor > System)**
```
Version	core-2021.3.4
Installation Type	Home Assistant OS
Host Operating System	Home Assistant OS 5.12
Update Channel	stable
Supervisor Version	supervisor-2021.03.6
```

**Your logs from Home Assistant Supervisor**
```
// Your logs here
```

**Comment by ciotlosm** [comment]
This is probably for the UI which should be tracked under: https://github.com/Koenkk/zigbee2mqtt/issues
