### ISSUE TITLE
Zigbee2MQTT not updating HA Entities

### ISSUE THREAD

**Issue by colinghart** [zigbee2mqtt/hassio-zigbee2mqtt#83]
When adding devices to zigbee2mqtt the devices appear after pairing and can be controlled, however zigbee2mqtt is not updating Home Assistant with the new entities, thus they are not visible in the developer list, nor in Node Red.

If I rename the device and mark it to update Home Assistant this also does not work.

version: 1.18.1-1
```
CONFIGURATION

data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CCC7177-if00
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false

```
// replace this line with your pasted configuration
```

**Running platform (details from Suypervisor > System)**
```

Core: core-2021.3.4
Supervisor: supervisor-2021.03.9
Operating System: Home Assistant OS 5.12
```

**Your logs from Home Assistant Supervisor**
```
1-04-07 09:28:01 INFO (MainThread) [supervisor.host.network] Updating local network information
21-04-07 09:28:02 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-04-07 09:28:02 INFO (MainThread) [supervisor.host] Host information reload completed
21-04-07 09:28:02 INFO (MainThread) [supervisor.host.apparmor] Loading AppArmor Profiles: {'hassio-supervisor'}
21-04-07 09:28:02 INFO (MainThread) [supervisor.host.services] Reloading local service hassos-apparmor.service
21-04-07 09:28:02 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-dns with version 2021.01.0
21-04-07 09:28:02 INFO (MainThread) [supervisor.plugins.dns] Starting CoreDNS plugin
21-04-07 09:28:03 INFO (SyncWorker_1) [supervisor.docker.dns] Starting DNS homeassistant/aarch64-hassio-dns with version 2021.01.0 - 172.30.32.3
21-04-07 09:28:03 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
21-04-07 09:28:03 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-audio with version 2021.02.1
21-04-07 09:28:03 INFO (MainThread) [supervisor.plugins.audio] Starting Audio plugin
21-04-07 09:28:04 INFO (SyncWorker_0) [supervisor.docker.audio] Starting Audio homeassistant/aarch64-hassio-audio with version 2021.02.1 - 172.30.32.4
21-04-07 09:28:04 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-cli with version 2021.03.1
21-04-07 09:28:04 INFO (MainThread) [supervisor.plugins.cli] Starting CLI plugin
21-04-07 09:28:05 INFO (SyncWorker_0) [supervisor.docker.cli] Starting CLI homeassistant/aarch64-hassio-cli with version 2021.03.1 - 172.30.32.5
21-04-07 09:28:05 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-observer with version 2020.10.1
21-04-07 09:28:05 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-multicast with version 2021.04.0
21-04-07 09:28:05 INFO (MainThread) [supervisor.plugins.multicast] Starting Multicast plugin
21-04-07 09:28:05 INFO (SyncWorker_1) [supervisor.docker.multicast] Starting Multicast homeassistant/aarch64-hassio-multicast with version 2021.04.0 - Host
21-04-07 09:28:05 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-04-07 09:28:08 INFO (MainThread) [supervisor.homeassistant.secrets] Loaded 1 Home Assistant secrets
21-04-07 09:28:08 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/raspberrypi4-64-homeassistant with version 2021.3.4
21-04-07 09:28:08 INFO (MainThread) [supervisor.hassos] Detect Home Assistant Operating System 5.12 / BootSlot A
21-04-07 09:28:08 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/15d21743 repository
21-04-07 09:28:08 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
21-04-07 09:28:08 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
21-04-07 09:28:08 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/cebe7a76 repository
21-04-07 09:28:08 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/7ad98f9c repository
21-04-07 09:28:09 INFO (MainThread) [supervisor.store] Loading add-ons from store: 69 all - 69 new - 0 remove
21-04-07 09:28:09 INFO (MainThread) [supervisor.addons] Found 12 installed add-ons
21-04-07 09:28:09 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/unifi/aarch64 with version 0.21.0
21-04-07 09:28:09 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-mosquitto with version 5.1.1
21-04-07 09:28:09 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to thomasmauerer/samba-backup-aarch64 with version 4.4
21-04-07 09:28:09 INFO (SyncWorker_5) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/adguard/aarch64 with version 4.0.0
21-04-07 09:28:09 INFO (SyncWorker_3) [supervisor.docker.interface] Attaching to zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.18.1-1
21-04-07 09:28:09 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/bitwarden/aarch64 with version 0.9.0
21-04-07 09:28:09 INFO (SyncWorker_6) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/vscode/aarch64 with version 3.1.0
21-04-07 09:28:09 INFO (SyncWorker_7) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-letsencrypt with version 4.11.0
21-04-07 09:28:09 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/node-red/aarch64 with version 8.2.1
21-04-07 09:28:09 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-duckdns with version 1.12.5
21-04-07 09:28:09 INFO (SyncWorker_5) [supervisor.docker.interface] Attaching to esphome/esphome-hassio-aarch64 with version 1.16.2
21-04-07 09:28:09 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/ssh/aarch64 with version 8.0.3
21-04-07 09:28:09 INFO (MainThread) [supervisor.snapshots] Found 7 snapshot files
21-04-07 09:28:09 INFO (MainThread) [supervisor.discovery] Loaded 2 messages
21-04-07 09:28:09 INFO (MainThread) [supervisor.ingress] Loaded 63 ingress sessions
21-04-07 09:28:09 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
21-04-07 09:28:09 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-04-07 09:28:09 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-04-07 09:28:09 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-04-07 09:28:09 INFO (MainThread) [__main__] Running Supervisor
21-04-07 09:28:10 INFO (MainThread) [supervisor.hassos] Rauc: A - marked slot kernel.0 as good
21-04-07 09:28:10 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' starting 0 add-ons
21-04-07 09:28:10 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SYSTEM' starting 1 add-ons
21-04-07 09:28:11 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mosquitto with version 5.1.1
21-04-07 09:28:13 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
21-04-07 09:28:16 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SERVICES' starting 6 add-ons
21-04-07 09:28:16 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/vscode/aarch64 with version 3.1.0
21-04-07 09:28:18 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/unifi/aarch64 with version 0.21.0
21-04-07 09:28:18 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/ssh/aarch64 with version 8.0.3
21-04-07 09:28:19 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/bitwarden/aarch64 with version 0.9.0
21-04-07 09:28:21 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-duckdns with version 1.12.5
21-04-07 09:28:21 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/adguard/aarch64 with version 4.0.0
21-04-07 09:28:27 INFO (MainThread) [supervisor.core] Start Home Assistant Core
21-04-07 09:28:27 INFO (SyncWorker_6) [supervisor.docker.interface] Starting homeassistant
21-04-07 09:28:27 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-04-07 09:28:30 INFO (MainThread) [supervisor.api.security] /network/interface/default/info access from a0d7b954_adguard
21-04-07 09:28:49 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.STARTUP
21-04-07 09:28:49 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-04-07 09:28:55 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-04-07 09:29:06 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-04-07 09:29:06 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' starting 4 add-ons
21-04-07 09:29:07 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/node-red/aarch64 with version 8.2.1
21-04-07 09:29:07 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on esphome/esphome-hassio-aarch64 with version 1.16.2
21-04-07 09:29:09 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on thomasmauerer/samba-backup-aarch64 with version 4.4
21-04-07 09:29:10 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_esphome
21-04-07 09:29:11 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.18.1-1
21-04-07 09:29:16 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
21-04-07 09:29:16 INFO (MainThread) [supervisor.core] Supervisor is up and running
21-04-07 09:29:16 INFO (MainThread) [supervisor.host.info] Updating local host information
21-04-07 09:29:16 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-04-07 09:29:16 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-04-07 09:29:16 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-04-07 09:29:16 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-04-07 09:29:17 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-04-07 09:29:17 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-04-07 09:29:17 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-04-07 09:29:17 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-04-07 09:29:17 INFO (MainThread) [supervisor.host.services] Updating service information
21-04-07 09:29:17 INFO (MainThread) [supervisor.host.network] Updating local network information
21-04-07 09:29:27 WARNING (MainThread) [supervisor.dbus.network] Can't process /org/freedesktop/NetworkManager/Devices/30: Error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/NetworkManager/Devices/30
21-04-07 09:29:27 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-04-07 09:29:28 INFO (MainThread) [supervisor.host] Host information reload completed
21-04-07 09:29:56 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqtt'
21-04-07 09:29:57 INFO (MainThread) [supervisor.auth] Successful login for 'mqtt'
21-04-07 09:29:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-04-07 09:29:59 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-04-07 09:29:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
```

**Comment by jantielens** [comment]
Same issue here. Brand new install of HA and Zigbee2MQTT (after upgrading from a Pi3 to a Pi4). I can pair Zigbee devices, they do show up in the Zigbee2Mqtt web ui, but I can't find them in Home Assistant.

**Comment by jantielens** [comment]
Small update here, I think I managed to get it back to work. I had to enable auto discovery for the MQTT integration. Now the Zigbee devices are added again.

**Comment by idefix38** [comment]
Same issue !

**Comment by ciotlosm** [comment]
If your devices are properly showing in the zigbee2mqtt UI but not in home assistant even after restart, the problem is with your MQTT integration. Either wrong authentication or some connectivity errors. 

I recommend you use the built in authentication discovery with the built in mosquitto add-on. 

Can you post the add-on logs as well?
