### ISSUE TITLE
Can I install this without supervisor?

### ISSUE THREAD

**Issue by the3future** [zigbee2mqtt/hassio-zigbee2mqtt#89]
Hi, I am new to HA. The latest synology docker is not supporting supervisor, so I am not sure how to install zigber2mqtt? Is there a way to install this to HA? 

And I have the cc2531 along with my synology

Thank you

**Comment by actuallymentor** [comment]
I think you need to use the [zigbee2mqtt docker](https://www.zigbee2mqtt.io/information/docker.html) option.

It doesn't install the HA addon though and works through the MQTT integration. I'd love to know how to install the add-on with HA and zigbee2mqtt both in docker.

**Comment by the3future** [comment]
Thanks. Installed the zigbee2mqtt docker
