### ISSUE TITLE
Documentation issues - Cannot find the correct configuration to get the web interface to start

### ISSUE THREAD

**Issue by larray** [zigbee2mqtt/hassio-zigbee2mqtt#90]
**Description of problem:**
I've been struggling for 4 days now trying to get zibee2mqtt to work.

Part of the issues lay in the fact that the version that got pulled down from was 1.18-1 and it didn't seem to support he adapter: ezsp option - it kept erasing it.   I had literally pulled it Sunday night and thought I had the latest.  Even went to the DEV branch thinking I could get bleeding edge latest. 

Now I have the adapter getting recognized and I can't get the front end / webpage to appear.  The "Open Web UI" button and the "Show in Sidebar" options result in a 502 Bad Gateway.  I've found one other issue that another user has reported  and commented there as well. 
Zigbee2MQTT Information:
```
Zigbee2MQTT:info  2021-04-12 23:00:45: Starting Zigbee2MQTT version 1.18.2 (commit #1.18.2)
Zigbee2MQTT:info  2021-04-12 23:00:45: Starting zigbee-herdsman (0.13.88)```
```
**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
base_topic: zigbee2mqtt
serial:
port: >-
/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300027-if01-port0
adapter: ezsp
advanced:
log_level: debug
pan_id: 6754
channel: 11
network_key:
availability_blocklist: []
availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
port: 8099
experimental: {}
socat:
enabled: false
master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
options: '-d -d'
log: false
zigbee_herdsman_debug: true
```

**Running platform (details from Suypervisor > System)**
```
// Example
Core Version: core-2021.4.3
Supervisor: supervisor-2021.03.9
Operating System: Home Assistant OS 5.13
```

**Your logs from Home Assistant Supervisor**
```
I don't know what expanded logs you are looking for but ever attempt to access results in this the Supervisor log:
21-04-13 03:00:57 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.6:8099 ssl:default [Connect call failed ('172.30.33.6', 8099)]
```

Here is where the documentation is really off - it still references on the zigbee2mqtt add-on "Documentation" page:
```
Enabling the built-in Frontend
Make sure your add-on options have the right settings. If you already had experimental options, you might now automatically get new_api set properly on update.

frontend:
  port: 8099
experimental:
  new_api: true
Enable ingress to have the frontend available in your UI: Supervisor → Dashboard → Zigbee2mqtt → Show in sidebar. You can find more details about the feature on the Zigbee2mqtt documentation.
```

However, when I put new_api: true into the configuration I get this in the logs:
```
21-04-13 02:54:02 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (45df7312_zigbee2mqtt)
```

More googling... and low and behold it looks like the option was removed! [https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/55](url) - so the docs tell me to put it in, the early release info from the main zigbee2mqtt project say to use it, and it has been deprecated and removed.. and I still can't get past the 502 Bad Gateway and have no idea where to go from here...

Help?

(Post updated to clean up markup language that threw everything off)

**Comment by Supreme-Bob** [comment]
this is wrong port: >-
/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300027-if01-port0

you're getting bad gateway cause z2m isn't starting as its not finding your zigbee controller

**Comment by larray** [comment]
@Supreme-Bob  -  That was the first part of the issue - one that required mulitple uninstall and re-installs of the hassio-zigbee2mqtt add-on - the version I pulled 4/4/21 didn't have the option for adapter: ezsp - which would not stick in the config. 

Once that was resolved I was able to get zigbee-herdsman to start - granted I don't know much about this add-on - I had some of the kind folks on the zigbee2mqtt github issues list confirm my work and it may be possible I got false information there that it had started.  Here is my add-on log:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[08:04:34] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[08:04:34] INFO: MQTT available, fetching server detail ...
[08:04:34] INFO: MQTT server settings not configured, trying to auto-discovering ...
[08:04:34] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[08:04:34] INFO: MQTT credentials not configured, trying to auto-discovering ...
[08:04:35] INFO: Configuring'addons' mqtt user
[08:04:35] INFO: Previous config file found, checking backup
[08:04:35] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[08:04:35] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:04:35] INFO: Zigbee Herdsman debug logging enabled
[08:04:35] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.2 start /app
> node index.js
Zigbee2MQTT:debug 2021-04-14 08:04:37: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2021-04-14 08:04:37: Logging to console and directory: '/config/zigbee2mqtt/log/2021-04-14.08-04-37' filename: log.txt
Zigbee2MQTT:debug 2021-04-14 08:04:37: Removing old log directory '/config/zigbee2mqtt/log/2021-04-12.14-35-06'
Zigbee2MQTT:info  2021-04-14 08:04:38: Starting Zigbee2MQTT version 1.18.2 (commit #1.18.2)
Zigbee2MQTT:info  2021-04-14 08:04:38: Starting zigbee-herdsman (0.13.88)
Zigbee2MQTT:debug 2021-04-14 08:04:38: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ezsp","path":"/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300027-if01-port0"}}'
2021-04-14T12:04:38.285Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300027-if01-port0","adapter":"ezsp"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"concurrent":null,"delay":null}}'
2021-04-14T12:04:38.288Z zigbee-herdsman:adapter:ezsp:uart Opening SerialPort with /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300027-if01-port0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2021-04-14T12:04:38.305Z zigbee-herdsman:adapter:ezsp:uart Serialport opened
2021-04-14T12:04:38.305Z zigbee-herdsman:adapter:ezsp:uart uart reseting
2021-04-14T12:04:38.306Z zigbee-herdsman:adapter:ezsp:uart Write reset
2021-04-14T12:04:38.307Z zigbee-herdsman:adapter:ezsp:uart --> [1ac038bc7e] [26,192,56,188,126]
Zigbee2MQTT:debug 2021-04-14 08:09:38: Saving state to file /config/zigbee2mqtt/state.json
```

I'm pretty sure the port is correct I used /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300027-if00-port0 (if00) for the Zwave radio.  I've also read that the HomeAssistant team is driving folks to use the /dev/serial/by-id reference and NOT the /dev/ttyUSB1 reference. 

Either way the result appears to be the same:

```
Zigbee2MQTT:info  2021-04-14 08:11:34: Starting Zigbee2MQTT version 1.18.2 (commit #1.18.2)
Zigbee2MQTT:info  2021-04-14 08:11:34: Starting zigbee-herdsman (0.13.88)
Zigbee2MQTT:debug 2021-04-14 08:11:34: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ezsp","path":"/dev/ttyUSB1"}}'
2021-04-14T12:11:34.834Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/ttyUSB1","adapter":"ezsp"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"concurrent":null,"delay":null}}'
2021-04-14T12:11:34.837Z zigbee-herdsman:adapter:ezsp:uart Opening SerialPort with /dev/ttyUSB1 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2021-04-14T12:11:34.854Z zigbee-herdsman:adapter:ezsp:uart Serialport opened
2021-04-14T12:11:34.854Z zigbee-herdsman:adapter:ezsp:uart uart reseting
2021-04-14T12:11:34.855Z zigbee-herdsman:adapter:ezsp:uart Write reset
2021-04-14T12:11:34.856Z zigbee-herdsman:adapter:ezsp:uart --> [1ac038bc7e] [26,192,56,188,126]
```

When I look for the devices/ports using:
ls -l /dev/serial/by-id
I get back:
```
lrwxrwxrwx 1 root root 13 Apr 11 23:29 usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300027-if00-port0 -> ../../ttyUSB0
lrwxrwxrwx 1 root root 13 Apr 11 23:29 usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300027-if01-port0 -> ../../ttyUSB1
```
The if00 / ttyUSB0 is my zwave adapter (and is completely  functional in ZWAVE2mqtt).

Way before I tried to get zigbee2mqtt working (because I needed the extended toolset in zigbee2mqtt) I did have Zigbee Home Automation working with the usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300027-if01-port0 reference. 

You may be thoroughly right in that zigbee isn't fully "up", but what I am missing is what the final lines in the log should look like if the Zigbee controller is properly initialized.   When I get time today I guess I'll rip zigbee2mqtt out (now that I'm nearly a professional at installing it) and put ZHA back in and validate my assumption that it is still working correctly.

**Comment by larray** [comment]
UPDATE - ZHA tested - Ripped zwave2mqtt out and put Zwave Home Assistant integration back in and selected /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300027-if01-port0 during setup.  BAM - all the Zigbee devices that were in the console previously came into Home Assistant and are visible and manageable.  Still doesn't get me to being able to alter the device template and add capabilities to a device that isn't being picked up - but does validate that the radio is functional at the if01 device.

**Comment by larray** [comment]
**FOR THOSE THAT FOLLOW:**
Nortek HUSBZB-1 using ```ncp-uart-sw-6.7.8.ebl``` firmware the magic command in the configuration file is:
```
advanced:
  baudrate: 57600
```

The ```502 BAD GATEWAY``` is gone and the logs are full of 2 way communications and the web interface is up.
