### ISSUE TITLE
Philips Hue Ensis not supported, is available in devices.js

### ISSUE THREAD

**Issue by stefanschoemaker** [zigbee2mqtt/hassio-zigbee2mqtt#92]
I get the following message in the log file: "Device '0x001788010924d127' with Zigbee model '4090330P9_02' and manufacturer name 'Philips' is NOT supported." but when I check the devices.js I do see the following entry:
```
    {
        zigbeeModel: ['LCP001', 'LCP002', '4090331P9_01', '4090331P9_02'],
        model: '4090331P9',
        vendor: 'Philips',
        description: 'Hue Ensis',
        meta: {turnsOffAtBrightness1: true},
        extend: preset.hue.light_onoff_brightness_colortemp_color(),
        ota: ota.zigbeeOTA,
    },
```

**Comment by wersim** [comment]
Hi @stefanschoemaker,
please note that your actual zigbee model 4090330P9_02 does not match any of the zigbee models in [philips.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/philips.js) (409033**0*** vs 409033**1***). You could follow the guide [How to support new devices](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html) to add it to your z2m instance.

**Comment by ciotlosm** [comment]
Please open device specific issues here: https://github.com/Koenkk/zigbee2mqtt/issues
