### ISSUE TITLE
Tuya switch TS0011

### ISSUE THREAD

**Issue by LaurentMicrotec** [zigbee2mqtt/hassio-zigbee2mqtt#94]
First of all, thank you very much for your work, thank you for allowing individuals to improve the comfort of our home. 
Well

Problem:
 I use Tuya TS0011 switches, one switch was recognized by the system, the second one was not! In the logs I have a message telling me that the equipment is unknown. I assure you that it is the same model.
What can I do to add it without problems?

I use: Zigbee2mqtt Edge, I don't what is the commit hash

// Configuration System:
core-2021.3.4
supervisor-2021.04.0
Home Assistant OS 5.13

Log from Zigbee2mqtt Edge:
Zigbee2MQTT:error 2021-04-18 16:36:21: Failed to interview '0xec1bbdfffe7bd3c0', device has not successfully been paired
Zigbee2MQTT:info  2021-04-18 16:36:21: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xec1bbdfffe7bd3c0","ieee_address":"0xec1bbdfffe7bd3c0","status":"failed"},"type":"device_interview"}'
Zigbee2MQTT:info  2021-04-18 16:36:21: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_failed","meta":{"friendly_name":"0xec1bbdfffe7bd3c0"},"type":"pairing"}'
Zigbee2MQTT:info  2021-04-18 16:36:21: Starting interview of '0xec1bbdfffe7bd3c0'
Zigbee2MQTT:info  2021-04-18 16:36:21: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xec1bbdfffe7bd3c0","ieee_address":"0xec1bbdfffe7bd3c0","status":"started"},"type":"device_interview"}'
Zigbee2MQTT:info  2021-04-18 16:36:21: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0xec1bbdfffe7bd3c0"},"type":"pairing"}'
Zigbee2MQTT:error 2021-04-18 16:36:21: Failed to interview '0xec1bbdfffe7bd3c0', device has not successfully been paired
Zigbee2MQTT:info  2021-04-18 16:36:21: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xec1bbdfffe7bd3c0","ieee_address":"0xec1bbdfffe7bd3c0","status":"failed"},"type":"device_interview"}'
Zigbee2MQTT:info  2021-04-18 16:36:21: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_failed","meta":{"friendly_name":"0xec1bbdfffe7bd3c0"},"type":"pairing"}'
Zigbee2MQTT:info  2021-04-18 16:36:21: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xec1bbdfffe7bd3c0","ieee_address":"0xec1bbdfffe7bd3c0"},"type":"device_announce"}'
Zigbee2MQTT:info  2021-04-18 16:36:21: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0xec1bbdfffe7bd3c0"},"type":"device_announced"}'
Zigbee2MQTT:info  2021-04-18 16:36:23: Finished Touchlink scan
Zigbee2MQTT:info  2021-04-18 16:36:23: MQTT publish: topic 'zigbee2mqtt/bridge/response/touchlink/scan', payload '{"data":{"found":[]},"status":"ok","transaction":"dvaj2-4"}'
Zigbee2MQTT:warn  2021-04-18 16:36:25: Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'undefined'
Zigbee2MQTT:warn  2021-04-18 16:36:25: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Zigbee2MQTT:warn  2021-04-18 16:36:32: Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'undefined'
Zigbee2MQTT:warn  2021-04-18 16:36:32: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Zigbee2MQTT:info  2021-04-18 16:39:55: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"0xec1bbdfffe7bd3c0"},"error":"Device '0xec1bbdfffe7bd3c0' cannot be configured","status":"error","transaction":"dvaj2-5"}'

**Your logs from Home Assistant Supervisor**
Nothing Wrong
![2021-04-18 16_40_03-Zigbee2mqtt Edge - Home Assistant - Brave](https://user-images.githubusercontent.com/50947256/115150267-ec367680-a067-11eb-8b87-1081fc5306e9.png)

```

**Comment by ciotlosm** [comment]
Please open device specific requests here: https://github.com/Koenkk/zigbee2mqtt/issues
