### ISSUE TITLE
Please report this to the maintainer of Zigbee2mqtt

### ISSUE THREAD

**Issue by jorojoro66** [zigbee2mqtt/hassio-zigbee2mqtt#95]
21-04-25 23:55:54 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Zigbee2mqtt
21-04-25 23:55:54 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Zigbee2mqtt Edge

Zigbee2mqtt
Current version: 1.16.1

Core
Version
core-2021.4.6

Supervisor
Version
supervisor-2021.04.0

Operating System
Home Assistant OS 5.13

21-04-25 23:55:54 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Zigbee2mqtt
21-04-25 23:55:54 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Zigbee2mqtt Edge

**Comment by ciotlosm** [comment]
This was fixed in newer versions.
