### ISSUE TITLE
Support for additional manufacturer TS0014

### ISSUE THREAD

**Issue by Petervanoos** [zigbee2mqtt/hassio-zigbee2mqtt#98]
Message in the log:

"Received message from unsupported device with Zigbee model 'TS0014' and manufacturer name '_TZ3000_r0pmi2p3'_"

Is it possible to add support fot this new manufacturer?

Thanks in advance.

**Comment by ciotlosm** [comment]
Please report this to https://github.com/Koenkk/zigbee2mqtt/issues not in the add-on repo.
